### ISSUE TITLE
files.sharedPublicURL get error 'not_allowed_token_type'

### ISSUE THREAD

**Issue by ledamint** [slackapi/node-slack-sdk#1000]
### Description

Hi, when I use `this.client.files.sharedPublicURL({ file: fileId })` I get the error  `Error: An API error occurred: not_allowed_token_type`

Other methods, for example `this.client.files.upload` and `this.client.chat.postMessage`, work well. I called this method through postman and got the same error. Maybe I forgot to specify something?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
The error code indicates that the API method call requires a user token, not a bot token. The compatible token types are available in API method documents (the part starting with `Works with:`): https://api.slack.com/methods/files.sharedPublicURL

**Comment by ledamint** [comment]
That helped, thank you. Could you suggest which URL from `files.sharedPublicURL` I could use for [image block](https://api.slack.com/reference/block-kit/blocks#image)?
```javascript
{
    type: 'image',
    title: {
        type: 'plain_text',
        text: 'text',
    },
    image_url: ???,
    alt_text: 'alt_text',
},
```

**Comment by ledamint** [comment]
I found a solution, I hope there is the better way.

```javascript
const uploadRes = await this.client.files.upload({
    file: message.data.image, // Buffer | Stream
});
const sharedPublicURLRes = await this.client.files.sharedPublicURL({
    file: uploadRes.file.id,
});

const parsedPermalink = sharedPublicURLRes.file.permalink_public.split('-');
const pubSecret = parsedPermalink[parsedPermalink.length - 1];

const imageBlock = {
    type: 'image',
    title: {
        type: 'plain_text',
        text: 'text',
    },
    image_url: sharedPublicURLRes.file.url_private + `?pub_secret=${pubSecret}`,
    alt_text: 'alt_text',
},
```

**Comment by cristiancardosodexcom** [comment]
> I found a solution, I hope there is the better way.
> 
> ```js
> const uploadRes = await this.client.files.upload({
>     file: message.data.image, // Buffer | Stream
> });
> const sharedPublicURLRes = await this.client.files.sharedPublicURL({
>     file: uploadRes.file.id,
> });
> 
> const parsedPermalink = sharedPublicURLRes.file.permalink_public.split('-');
> const pubSecret = parsedPermalink[parsedPermalink.length - 1];
> 
> const imageBlock = {
>     type: 'image',
>     title: {
>         type: 'plain_text',
>         text: 'text',
>     },
>     image_url: sharedPublicURLRes.file.url_private + `?pub_secret=${pubSecret}`,
>     alt_text: 'alt_text',
> },
> ```

This option won't work 2022, need a pro version to share link

**Comment by digglife** [comment]
sharedPublicURL is for user token only, so used with bot token will cause invalid token error.
Workaround: create a public trash channel for image uploading. This is not natural but I guess from permission perspective it's not a problem that can be fixed easily.

**Comment by zimeg** [comment]
The fix with a user token remains correct, but I also want to share updates since this issue was created:

- File uploads should use [`filesUploadV2`](https://slack.dev/node-slack-sdk/web-api#upload-a-file) instead of the now deprecated `files.upload`.
- After the file is uploaded, the **File ID** can be used for `slack_file` within [`image`](https://api.slack.com/reference/block-kit/blocks#image) blocks.

If the file is used just within Slack, the `permalink` from `files.sharedPublicURL` might not be needed either! As long as the same user token is used in both the file upload and posted message, uploads should be shared alright 🙏
