### ISSUE TITLE
`invalid_service` error in slack slash commands 

### ISSUE THREAD

**Issue by AHMED3T** [slackapi/node-slack-sdk#1001]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] I don't know

#### Reproducible in:

package version: Not Applicable

node version: 12.x

OS version(s): Windows 10

#### Steps to reproduce:

1. Create a slack app and create a new slash command, add url, details, etc.
2. Reinstall the app on development workspace
3. Open slack client, type the slack command (which is visible in the popup meaning it has synced)

#### Expected result:

Slack accepts the command and hits my provided url using HTTP POST verb along with payload

#### Actual result:

Slackbot returns a silly error "failed with the error `invalid_service`". My endpoint doesn;t receive any hit from slack.

P.S. Sometimes the command is there in the popup but its details like description, etc are gone as shown in screenshot # 2. Then, I reinstall the app and it comes back as shown in screenshot # 3.

I've googled a lot about this problem searched YouTube but didn't find any clue about whats wrong with it. Please help me I'm working on a project and deadline is really near 😞 I've spent a whole day meddling with it but to no avail.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.
![image](https://user-images.githubusercontent.com/55442279/80239946-8264d600-867a-11ea-8550-2548204421af.png)
![image](https://user-images.githubusercontent.com/55442279/80239996-9ad4f080-867a-11ea-9ce0-6f48e01b46ba.png)
![image](https://user-images.githubusercontent.com/55442279/80240142-d4a5f700-867a-11ea-9897-f6871708caa8.png)

**Comment by AHMED3T** [comment]
Hi @seratch ,

Isn't there any solution for my problem? I've been waiting for a couple of days. I'm working on a project and I need your guidance urgently

**Comment by seratch** [comment]
@AHMED3T Thank you for writing in here and following up. I've internally reported your requestion/feedback here with the server-side team. I haven't got any information to share with you yet. If you're urgent, you can contact Slack's support team. They can do an investigation more deeply by accessing your app/workspace information.

**Comment by AHMED3T** [comment]
Hi @seratch,

Thank you for guiding me. Meanwhile, waiting for response of your server-side team, I'll be contacting Slack's support team because it's urgent for me!

Regards

**Comment by seratch** [comment]
@AHMED3T This seems to be caused by a rare condition on the server-side and unfortunately there is no simple way to fix the state. I have to say this but could you reinstall your Slack app to the workspace that is having the issue? Revoking all the tokens generated for the workspace and doing the OAuth flow again should work for you. I'm sorry for the inconvenience and my unclear answer here. I would appreciate it if you could understand this.

**Comment by AHMED3T** [comment]
Thank you @seratch, revoking all tokens and reinstalling the app has solved my problem 😄. I'm closing this issue now. Thanks once again. 👍

**Comment by goldeneggg** [comment]
> Revoking all the tokens generated for the workspace and doing the OAuth flow again should work for you. 

Our team got the same issue and we resolved by the same method above.

**Comment by rnaimi** [comment]
Is there a fix for this issue? We keep running into this every so often and it's very frustrating to revoke and reissue tokens and redeploy the app
