### ISSUE TITLE
views.update method doesn't accept only external_id

### ISSUE THREAD

**Issue by suyashgulati** [slackapi/node-slack-sdk#1002]
### Description

The views.update method does not accept object with only external_id, as the [documentation](https://api.slack.com/methods/views.update#arg_external_id) says it should accept but the typings don't allow it without view_id [code reference](https://github.com/slackapi/node-slack-sdk/blob/a4f3d5044ef66ee35b446f083ff0495f2560d477/packages/web-api/src/methods.ts#L942).

![Screen Shot 2020-04-27 at 3 06 56 AM](https://user-images.githubusercontent.com/20201768/80320762-f697a900-8835-11ea-9d46-4d82861f2306.png)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 2.0.0

node version: 12.13.1

OS version(s): MacOS 10.13.6

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

Should allow ViewsUpdateArguments with only external_id or view_id

#### Actual result:

Currently view_id is required argument which should not be the case

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
As #1003 has been reverted, this issue is not yet fixed. https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%405.10.0/packages/web-api/src/methods.ts#L991-L996

We should fix this issue in the next version - https://github.com/slackapi/node-slack-sdk/pull/1003#discussion_r437157719
