### ISSUE TITLE
Reply_broadcast removes custom image_url

### ISSUE THREAD

**Issue by fstojanac** [slackapi/node-slack-sdk#1016]
### Description

When using `reply_broadcast = true` in combination with an `image_url`, a message is posted with a default bot image. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: `5.8.1`

node version: `>=12`

OS version(s):

#### Steps to reproduce:
1. Send a message with `image_url` and `reply_broadcast = false` => message is posted to a thread and image is set to whatever URL point to
2. Send a message with `image_url` and `reply_broadcast = true` => message is posted to a thread and channel (expected), but the image is now a default bot avatar

#### Expected result:

The message should have a custom image.

**Comment by seratch** [comment]
👋 Thanks for taking the time to report this! 

>image_url

Did you mean `icon_url`, right? If so, I've reproduced the issue. This is not specific to node-slack-sdk but a server-side issue. I will share this issue with the teams concerned.

<img width="300" src="https://user-images.githubusercontent.com/19658/82287758-ea89ac00-99db-11ea-84f4-fce172affdc8.png">


### Repro steps

1) the first message to start a thread
```
POST https://slack.com/api/chat.postMessage

channel=C111111
&text=Hi%21
```

2) reply_broadcast=false in thread

```
POST https://slack.com/api/chat.postMessage

channel=C111111
&thread_ts=1589864780.000500
&icon_url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1107799663720071168%2FZ-Zob5pS_400x400.jpg
&reply_broadcast=0
&blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Hi%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22image%22%2C%22image_url%22%3A%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1107799663720071168%2FZ-Zob5pS_400x400.jpg%22%2C%22alt_text%22%3A%22foo%22%7D%7D%5D
```
3) reply_broadcast=true in thread
```
POST https://slack.com/api/chat.postMessage

channel=C111111
&thread_ts=1589864780.000500
&icon_url=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1107799663720071168%2FZ-Zob5pS_400x400.jpg
&reply_broadcast=1
&blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Hi%22%7D%2C%22accessory%22%3A%7B%22type%22%3A%22image%22%2C%22image_url%22%3A%22https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1107799663720071168%2FZ-Zob5pS_400x400.jpg%22%2C%22alt_text%22%3A%22foo%22%7D%7D%5D
```

### References:

#### blocks in the above replies

```json
"blocks": [
  {
    "type": "section",
    "text": {
      "type": "plain_text",
      "text": "Hi"
    },
    "accessory": {
      "type": "image",
      "image_url": "https://pbs.twimg.com/profile_images/1107799663720071168/Z-Zob5pS_400x400.jpg",
      "alt_text": "foo"
    }
  }
]
```

**Comment by fstojanac** [comment]
> Did you mean icon_url, right? If so, I've reproduced the issue. This is not specific to node-slack-sdk but a server-side issue. I will share this issue with the teams concerned.

Oh, yes I meant `icon_url`. 😅 

Thanks for sharing this with the server team! 🙂

**Comment by solb** [comment]
Any update on this?

**Comment by seratch** [comment]
I've confirmed that this issue is not yet fixed on the server-side. 

I'm sorry to say this but, as we are unable to share the progress in a timely manner here(= in this SDK's issue tracker), please let us close this issue now. 

If this unexpected behavior still affects your Slack app experience even in the future, please ask our support agents to provide the latest information around the issue. We'd appreciate it if you could understand this.
