### ISSUE TITLE
Message subtype is undefined on thread replies

### ISSUE THREAD

**Issue by brennop** [slackapi/node-slack-sdk#1019]
### Description

I'm not sure if I misundertood the slack event api documentation, but I when replying to threads, the message event type is `undefined` instead of `message_replied`

https://api.slack.com/events/message/message_replied

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 2.3.2

node version: 14.2.0

OS version(s):

#### Steps to reproduce:

1. Reply to a thread
2. Verify message subtype

#### Expected result:

Thread replies event having a subtype `message_replied`

#### Actual result:

Thread replies event have no subtype

#### Attachments:

![A console.log of event.subtype on message](https://user-images.githubusercontent.com/38540987/82133915-c8b7db80-97c7-11ea-8eda-ab4116e4e802.png)

A console.log of event.subtype on "message" event

**Comment by seratch** [comment]
👋 Thanks for taking the time to report this. 

I reproduced this behavior and found this has been an issue on the server-side. I cannot tell when this issue will be resolved (it may take a bit long). So, I'm sorry for the confusion and I hate to say this but please just ignore the subtype. Your app can receive message events without subtype for this use case. 

Also, you can test if a message is a reply in a thread by checking the existence of `thread_ts` in an event payload.

**Comment by seratch** [comment]
The situation around this issue is still the same as of today. You can expect that your app receives only messages without subtype when a user posts a message in a thread. 

We will continue working with the teams concerned for the documentation improvement but I think there is nothing else we, as the SDK maintainers, can do here. For this reason, let us close this issue now.
