### ISSUE TITLE
Support 'style' on Confirm object

### ISSUE THREAD

**Issue by EddieCameron** [slackapi/node-slack-sdk#1022]
### Description

The 'style' field is missing on the Confirm object interface in Typescript.

![image](https://user-images.githubusercontent.com/1468286/82576190-83910200-9b57-11ea-87ea-7a8e45085edd.png)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
My understanding is `confirm` doesn't have a `style` field. Can you share the JSON payload you want to use?

**Comment by EddieCameron** [comment]
I was going off 
![image](https://user-images.githubusercontent.com/1468286/82578189-0dda6580-9b5a-11ea-8bb8-de6bf4f3fe9f.png)

**Comment by EddieCameron** [comment]
```                accessory: {
                    type: "button",
                    text: {
                        type: "plain_text",
                        text: "Skip their turn"
                    },
                    style: "danger",
                    value: JSON.stringify(metadata),
                    action_id: PlayerChoose.MAIN_PLAYER_PASS_ACTION_ID,
                    confirm: {
                        title: {
                            type: "plain_text",
                            text: "Are you sure?"
                        },
                        text: {
                            type: "mrkdwn",
                            text: `Are you sure you want to skip <@${mainPlayerSlackId}>'s turn?`
                        },
                        confirm: {
                            type: "plain_text",
                            text: "Skip"
                        },
                        deny: {
                            type: "plain_text",
                            text: "Don't skip"
                        },
                        style: "danger"
                    }```

**Comment by seratch** [comment]
Ah, it seems the field has been added very recently. 
https://api.slack.com/reference/block-kit/composition-objects#confirm

Thank you very much for pointing out this 🙇
