### ISSUE TITLE
I keep getting invalid_block_format error

### ISSUE THREAD

**Issue by jvkumar** [slackapi/node-slack-sdk#1027]
### I keep getting invalid_block_format

I have the following block

```
{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Docs Team Calendar brought to you by your friendly birdie Raven*"}},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"*Today Wed May 27 2020*"}},{"type":"context","elements":[{"type":"mrkdwn","text":"*Everyone is available today*"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"*Tomorrow Thu May 28 2020*"}},{"type":"context","elements":[{"type":"mrkdwn","text":"*Everyone is available tomorrow*"}]},{"type":"divider"},{"type":"section","text":{"type":"mrkdwn","text":"*Onward till Thu Jun 11 2020*"}},{"type":"context","elements":[{"type":"mrkdwn","text":"*Everyone is available onward till Thu Jun 11 2020*"}]}]}
```
That I am trying to send using node-slack-sdk

My code snippet is as follows:
`res = await web.chat.postMessage({ channel: conversationId, text: "", blocks: message });`
 
When I try to test it through web console https://app.slack.com/block-kit-builder/ it works fine. But when I try to test it through my above code or the API tester https://api.slack.com/methods/chat.postMessage/test it throws an error message

```
{
    "ok": false,
    "error": "invalid_blocks_format"
}
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [X ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 5.9.0

node version: 12.16.1

OS version(s): OSX 10.14.6 (Mojave)

#### Steps to reproduce:

1. I have explained above

#### Expected result:

Success message on API call through SDK

#### Actual result:

throws error

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by jvkumar** [comment]
I figured out the issue, so closing it.

**Comment by seratch** [comment]
Good to know you've figured out the cause!

**Comment by jbucci1990** [comment]
@jvkumar  What was the problem? I'm having the same issue and can't figure out for the life of me what's causing the invalid_block_format error.

**Comment by jvkumar** [comment]
> @jvkumar What was the problem? I'm having the same issue and can't figure out for the life of me what's causing the invalid_block_format error.

I was passing the payload as `{"blocks":[{....}]}` which is wrong. No need to put the `block` key there, just passing as `{[{...}]}` fixed the issue. HTH.

**Comment by bastienboutonnet** [comment]
@jvkumar Do you know if there is there a reason why the Block Kit Builder shows the payload with the `"blocks": [{...}]` key then? I just got tripped by it as well 🤦

**Comment by jvkumar** [comment]
@bastienboutonnet remove `blocks` key and just pass `[{...}]`

**Comment by bastienboutonnet** [comment]
@jvkumar yeah I did that and it worked. But that wasn't my question. I was wondering if there is a reading for the discrepancy...

**Comment by clicktechnology** [comment]
Just had this problem.  Here's a valid block from the Block Builder Kit : https://app.slack.com/block-kit-builder/ 
```
{
	"blocks": [
		{
			"type": "divider"
		},
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "I like chocolate.",
				"emoji": true
			}
		}
	]
}
```
The working JavaScript string would be this..
```
const messsage = '[{"type": "divider"},{"type": "section","text": {"type": "plain_text","text": "I like chocolate.","emoji": true}}]';
```
So, from @jvkumar's post, for `{"blocks":[{....}]}`, use `[{....}]`

HTH

**Comment by ViniciusPaldes** [comment]
Thanks for sharing your fix @jvkumar !

**Comment by dmakanadci** [comment]
Thank you for the information @jvkumar

**Comment by shahkali** [comment]
I'm still encountering issues with the SlackAskV2 feature. Although I managed to resolve the previous problem by implementing your suggestion, a new issue has arisen. Now, when a user clicks on a button(Approve or deny) to perform an action, no response is being sent back from slack 
![ASD](https://github.com/user-attachments/assets/4413d6b0-f579-43a6-8e7b-2ed5065c9f1c)
