### ISSUE TITLE
Test kit (mainly for e2e tests) and mocking Slack signature and requests

### ISSUE THREAD

**Issue by Akrabut** [slackapi/node-slack-sdk#1031]
### Description

My app is a backend app that uses Slack's Express middleware.
My app takes `reaction_added` events, and then does stuff based on their context.
I want to write an e2e test that generates a mock event, sends it to my `/slack/events` endpoint and tests whether said stuff happens.

As far as I understand given the lack of test kits, I have to understand how Slack signs the even on their end, implement the signing and then go on with the test.

Are there any tools that allow me to mock a request, or any information about how I can mock the signing?

Thanks.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Hey @Akrabut,

You are right in that in regards to e2e tests, you would need to implement slacks signing. I'll chat with the team to see if this is something we can release as a small package in the future to help folks such as yourself implement e2e tests.

Usually we recommend to just test your application logic by sending fake input to your handler directly. But this isn't really an end to end test.

Question for you, what e2e testing tool are you currently using?

**Comment by Akrabut** [comment]
In my job - Puppeteer with Jest and Cypress in my personal projects.

I was wondering if there's some documentation on how to mock Slack's signing rather than just verifying it?

**Comment by Akrabut** [comment]
More specifically, I'm trying to do like:

```
const generateSlackSignature = (timestamp: any, body: any) => {
  const slackSecret = 'top secret 1';
  const basestring = `v0:${timestamp}:${JSON.stringify(body)}`;
  const hmac = crypto.createHmac('sha256', slackSecret);
  hmac.update(basestring);
  return hmac;
};
```

with the body parameter an event object, something like:
```
const event = {
    type: 'reaction_added',
    user: 'U024BE7LH',
    reaction: 'thumbsup',
    item_user: 'U0G9QF9C6',
    item: {
      type: 'message',
      channel: 'C0G9QF9GZ',
      ts: '1360782400.498405',
    },
    event_ts: '1360782804.083113',
  };
```

I understand this is not the right format for the object and it has to be something with '=', but how do I properly format the event?

**Comment by Akrabut** [comment]
For the sake of humanity, this is sample code of how to do it:
Hard code an event:

```
export const generateQuery = () => {
  return {
    event: {
      type: 'reaction_added',
      user: 'U012X8BTJFP',
      reaction: 'sled_issue',
      item_user: 'U012X8BTJFP',
      item: {
        type: 'message',
        channel: 'G0142DYRMUL',
        ts: '1360782400.498405',
      },
      event_ts: '1360782804.083113',
    },
  };
};
```

Generate a slack signature:

```
import crypto from 'crypto';
const generateSlackSignature = (timestamp: any, body: any) => {
  const slackSecret = 'top secret 1';
  const hmac = crypto.createHmac('sha256', slackSecret);
  // @ts-ignore
  hmac.update(`v0:${timestamp}:${body}`);
  return `v0=${hmac.digest('hex')}`;
};
```

Generate the headers:

```
export const generateHeaders = (timestamp, stringifiedBody) => {
  return {
    'x-slack-request-timestamp': timestamp,
    'x-slack-signature': generateSlackSignature(timestamp, stringifiedBody),
  };
};
```

Send the request:

```
timestamp = Math.floor(Date.now() / 1000);
stringifiedBody = JSON.stringify(generateQuery());
headers = generateHeaders(timestamp, stringifiedBody);
await axios.post(`${url}/slack/events`, stringifiedBody, {
      headers: { ...headers },
    });
```
