### ISSUE TITLE
Default Content-Type rule is being deleted from Axios config globally

### ISSUE THREAD

**Issue by notable-marcelo** [slackapi/node-slack-sdk#1037]
### Description

[This piece of code](https://github.com/slackapi/node-slack-sdk/blob/766851cb0db3822cda471dfbb8aaf59581846267/packages/web-api/src/WebClient.ts#L129) seems to be removing the Axios default Content-Type config for POST requests at a global level.

So, a system using `node-slack-sdk` could get very odd side effect if it also relies on Axios.

Note how the `post` default config is removed globally.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Example, an axios default config on a random application would look something like:
```
> axios.defaults
{
  adapter: [Function: httpAdapter],
  transformRequest: [ [Function: transformRequest] ],
  transformResponse: [ [Function: transformResponse] ],
  timeout: 0,
  xsrfCookieName: 'XSRF-TOKEN',
  xsrfHeaderName: 'X-XSRF-TOKEN',
  maxContentLength: -1,
  validateStatus: [Function: validateStatus],
  headers: {
    common: { Accept: 'application/json, text/plain, */*' },
    delete: {},
    get: {},
    head: {},
    post: { 'Content-Type': 'application/x-www-form-urlencoded' },
    put: { 'Content-Type': 'application/x-www-form-urlencoded' },
    patch: { 'Content-Type': 'application/x-www-form-urlencoded' }
  }
}
```
However, after sending a slack message using `node-slack-sdk`, it would be:
```
> axios.defaults
{
  adapter: [Function: httpAdapter],
  transformRequest: [ [Function: transformRequest] ],
  transformResponse: [ [Function: transformResponse] ],
  timeout: 0,
  xsrfCookieName: 'XSRF-TOKEN',
  xsrfHeaderName: 'X-XSRF-TOKEN',
  maxContentLength: -1,
  validateStatus: [Function: validateStatus],
  headers: {
    common: { Accept: 'application/json, text/plain, */*' },
    delete: {},
    get: {},
    head: {},
    post: {},
    put: { 'Content-Type': 'application/x-www-form-urlencoded' },
    patch: { 'Content-Type': 'application/x-www-form-urlencoded' }
  }
}
```

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 5.2.0

node version: 12.15.0

OS version(s): MacOS

#### Expected result:

Not to modify Axios global config

#### Actual result:

Does modifies it.

**Comment by seratch** [comment]
Hi @notable-marcelo, I'm sorry for our slow response here. I tried to resolve this issue but if I understand the issue correctly, it seems the issue no longer exists as long as we use WebClient along with the latest version of axios. 

I've submitted a pull request adding a unit test that verifies if `WebClient` constructor never modifies the global defaults value: https://github.com/slackapi/node-slack-sdk/pull/1204

It'd be greatly appreciated if you could check the tests are valid. I will merge the PR and close this issue soon if my verification here is relevant.

**Comment by seratch** [comment]
As I've verified in the pull request #1204, it seems that this is no longer an issue as long as you use the latest versions of `@slack/web-api` and its underlying axios.

Let me close this issue now but please feel free to write in if there is still anything to consider regarding this topic.
