### ISSUE TITLE
Please fix this line. This doesn't work anymore: $ ./node_modules/.bin/slack-verify --secret <signing_secret> [--path=/slack/events] [--port=3000]

### ISSUE THREAD

**Issue by shwethashyam1** [slackapi/node-slack-sdk#1038]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ X] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [X ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.$ ./node_modules/.bin/slack-verify --secret <signing_secret> [--path=/slack/events] [--port=3000]

2.
3.

#### Expected result: The verification server is now listening at the URL: http://:::3000/slack/events

What you expected to happen

#### Actual result:No such file or directory

I managed to fix it by changing the command to ./node_modules/.bin/slack-verify --secret=ENTERSECRET --path=/slack/events --port=3000
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by shwethashyam1** [comment]
Please fix the documentation accordingly

**Comment by seratch** [comment]
@shwethashyam1 
Indeed, as it may be a bit confusing for others, I've updated the part on README by https://github.com/slackapi/node-slack-sdk/commit/89f39c4cd498913e946946fb20a8d1e5c1f30f97

Thank you for taking the time to report this!
