### ISSUE TITLE
Types - ViewsUpdateArguments cannot use externalId instead of viewId

### ISSUE THREAD

**Issue by oakgary** [slackapi/node-slack-sdk#1039]
### Description

Types for https://github.com/slackapi/node-slack-sdk/blob/master/packages/web-api/src/methods.ts#L1350 are missing the option to use the externalId instead of the viewId. - viewId is not required
See: https://api.slack.com/methods/views.update

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: "@slack/web-api": "^5.8.1"

**Comment by seratch** [comment]
Thanks for taking the time to report this. This issue is duplicated with https://github.com/slackapi/node-slack-sdk/issues/1002#issuecomment-641051407 and the team will be fixing it soon.
