### ISSUE TITLE
Header Signature verifications

### ISSUE THREAD

**Issue by B0ER** [slackapi/node-slack-sdk#1041]
### Description

Please don't use Date.now() when to check headers signature, it throws error on local development pc.
You should use DateTime.utc().toJsDate() (luxon) or moment.utc().toDate() (momentjs)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by stevengill** [comment]
Hey @B0ER

Can you provide more details about how `Date.now()` doesn't work on your PC. I haven't heard about this issue before.

**Comment by B0ER** [comment]
I needed interactive-messages, more precisely the processing of their events.

At first, I've used boltjs, and events weren't be delivered. Then I've used the interactive-messages package by redefining receiver (I've added adapter.requestListener() here), but events still weren't be delivered.

While exploring this issue, I've noticed that the boltjs source code has its own request handlers, and the interactive-messages package own request handlers too.

I've added the express and written a separate endpoint for interactive-messages. Then I've made debagging and discovered from the header of signature checking line that the validity condition doesn't work.

In my saved package I've changed the signature checking,  which uses tsscmp, to my signature checking, which uses crypto. As well, I've made the checking of the time stamp by using the UTC time. The program on the local machine (mac os catalina) works properly in this case.

But after the publishing my bot on production server I've noticed that my solution doesn't work, but yours works.

**Comment by seratch** [comment]
[These two packages are now deprecated](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6#deprecating-slackevents-api--slackinteractive-messages). Please consider switching to bolt-js and we are happy to answer your questions in the project's issue tracker.
