### ISSUE TITLE
@slack/interactive-messages: view_submission  longer than 3 sec 

### ISSUE THREAD

**Issue by mogadanez** [slackapi/node-slack-sdk#1044]
### Description

My Modal works like Search form, so after  view_submission in normal flow I respond with new Modal with results or with "Nothing found"
But sometimes search takes longer than 3 secs. And error shown in Dialog.
If I respond with empty result - dialog is closed. More one there is no response_url in view_submission event
Is it possible to respond with something to force Modal "continue" waiting with Circular progress? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

**Comment by seratch** [comment]
I think [this app](https://github.com/seratch/deepl-for-slack/blob/master/README.md#shortcut-to-run-deepl-translate-api) does something similar you'd like to implement. It's possible to dynamically transform your modal by the following steps:

* respond to a `view_submission` request with `response_action` + `view` (including loading indicator) in its HTTP response
* update the modal using `views.update` API method

[These lines of code](https://github.com/seratch/deepl-for-slack/blob/5929cbeef857490f10ce95ad31f431bc1f2f7c11/src/index.ts#L39-L54) does the above. Although the app is built with [Bolt for JS](https://github.com/slackapi/bolt-js), checking the code may be helpful.

**Comment by arpit-digi** [comment]
hhh

**Comment by misscoded** [comment]
We are going to close this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
