### ISSUE TITLE
invalid_cursor error when paginating using slack/web-api 

### ISSUE THREAD

**Issue by alete89** [slackapi/node-slack-sdk#1051]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] enhancement (feature request)
- [x] bug
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 5.10

node version: 12.13

OS version(s): ubuntu 20.04

#### Steps to reproduce:

1. have a function like this one:

```
const getReactions = async (user) => {
  const result = [];

  try {
    for await (const page of web.paginate("reactions.list", { user })) {
      result.push(page.items);
    }
    return result;
  } catch (error) {
    console.log(error);
  }
};
```
2. consume it with an user id like: `UJUGTADBZ`
3. get this kind of logs on your terminal:

```
Error: An API error occurred: invalid_cursor
    at Object.platformErrorFromResult (/home/myuser/git/reactions/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/home/myuser/git/reactions/node_modules/@slack/web-api/dist/WebClient.js:503:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_cursor',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

#### Expected result:

no errors on terminal

#### Actual result:

errors on terminal.

I checked both bug and question because I might be doing something wrong, but I'm kinda copy-pasting an example from the docs.
I read about this API error in the docs for pagination, but I'm not manually paginating, but `@slack/web-api` is...

EDIT:

further looking into this, it seems like this error is raised everytime, since it always try to loop one extra time. It seems to me like it  should be catched by the package before or not being raised at all if it's because there are no more pages.

**Comment by tmakuch** [comment]
Hey @alete89, did you come to any conclusion on your own? It hit us as well and we have it already on production, so I'm looking for anything, a hotfix as well, to minimize the impact on our customers.

In terms of our reproduction - the code below shows how we create a cache of public channels and users which we reuse for any user on the workspace. We have had it for more than a week now and we had a minor release today adding additional pagination for private channels, which we paginate per user (no caching). We saw this error today for the very first time.

Code in question:
```
const p = require("bluebird");
const { WebClient, WebClientEvent, retryPolicies } = require("@slack/web-api");

//from db
const unifiedUserAuth = {/*...*/};
//constants from our config, resolves to this:
const webClientOptions = { retryConfig: retryPolicies.fiveRetriesInFiveMinutes };
const paginateOptions = { exclude_archived: 1, limit: 250 };

//web client instances
const botClient = new WebClient(
    unifiedUserAuth.slackBotAccessToken,
    webClientOptions
);
const userClient = new WebClient(
    unifiedUserAuth.slackUserAccessToken,
    webClientOptions
);

return p.all([
    userClient.paginate(
        "channels.list",
        paginateOptions,
        () => false, 
        (acc, page, index) => {
            logger.info("Pagination for channels", index);
            if (page.ok) {
                return [...(acc || []), ...page.channels];
            } else {
                handleSlackResponse(page, logger);
            }
            return [];
        }
    ),
    botClient.paginate(
        "users.list",
        paginateOptions,
        () => false,
        (acc, page, index) => {
            logger.info("Pagination for members", index);
            if (page.ok) {
                return [...(acc || []), ...page.members];
            } else {
                handleSlackResponse(page, logger);
            }
            return [];
        }
    )
])
.then(/* ... (mapping mostly) */)
.catch(/* ... */);
```

Additionally we see an strange behavior in logs. We do get an error logged from `p.all(...).catch` (as the very first log after executing pagination), which means the whole promise fails, but we see a constant stream of logs `Pagination for channels X`, which means the reducer is constantly being fired up for `channels.list`. Even above the point that would be explained by the number of users on the workspace. And we see no `Pagination for members Y`. The error is thrown from the `userClient` (base on the scopes from the error we get). Additionally function `handleSlackResponse` would log and throw an error if there would be `page.error`, this does not happen as well.

The error we get looks the same as in original post:
```
{"code":"slack_webapi_platform_error","data":{"ok":false,"error":"invalid_cursor","response_metadata":{"scopes":["links:read","links:write","commands","users:read","team:read"],"acceptedScopes":["users:read"]}}}
Error: An API error occurred: invalid_cursor
    at Object.platformErrorFromResult (/code/node_modules/@slack/web-api/dist/errors.js:50:33)
    at WebClient.apiCall (/code/node_modules/@slack/web-api/dist/WebClient.js:503:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Our assumption for third argument shouldStop: PaginatePredicate being () => false, was that we want to download full set of channels and users. During writing the code promises did stop iterating through the lists and get resolved. we assumed this works ok.

**Comment by seratch** [comment]
I tried to reproduce this issue but I'm not able to see the same situation yet. Here is a simple script I used for it.

```js
const { WebClient } = require('@slack/web-api');
const client = new WebClient(process.env.SLACK_BOT_TOKEN);
const parameters = { limit: 1, user: 'your-user-id-here' };
(async () => {
  // https://api.slack.com/methods/reactions.list
  for await (const page of client.paginate('reactions.list', parameters)) {
    console.log(JSON.stringify(page, null, 2));
  }
})();
```

As long as the server-side returns either a valid cursor or "" (the empty string indicates the end of the pagination), this package works as expected. If there is a rare pattern this package is missing, sharing the payload from the server-side in the scenario would be greatly appreciated.

**Comment by seratch** [comment]
Let me close this issue due to inactivity. If anyone encounters the same situation, please let us know the steps to reproduce the error with detailed information such as package version.
