### ISSUE TITLE
@slack/webhook `socket hang up` error on GCP 

### ISSUE THREAD

**Issue by MakeYuan-Driver** [slackapi/node-slack-sdk#1053]
### Description

Describe your issue here.

code
```
const { IncomingWebhook } = require('@slack/webhook');

const url=process.env.SLACK_URL. 

const webhook = new IncomingWebhook(url);  

(async()=>{await webhook.send({text:" Autoscale allowed "});})();  
```

```
Error: A request error occurred: socket hang up
    at Object.requestErrorWithOriginal (/workspace/node_modules/@slack/webhook/dist/errors.js:25:33)
    at IncomingWebhook.send (/workspace/node_modules/@slack/webhook/dist/IncomingWebhook.js:54:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: ~5

node version: 10

OS version(s): CloudFunction

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by clavin** [comment]
It sounds like you're using Google Cloud's "Cloud Functions". A quick google search tells me that [you need to return the Promise](https://stackoverflow.com/a/50630868). Does that fix your issue?

**Comment by MakeYuan-Driver** [comment]
Thanks,I Will Try it
