### ISSUE TITLE
Add custom API URL support @slack/oauth

### ISSUE THREAD

**Issue by karenfann** [slackapi/node-slack-sdk#1055]
### Description

Custom API URL via `slackApiUrl` option is supported in @slack/web-api but not in @slack/oauth

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Thanks @karenfann!

Relevant custom api url docs: https://slack.dev/node-slack-sdk/web-api#custom-api-url

@seratch mentioned one way to handle this would be to allow developers to pass in their own instance `WebClient` via method args. Also, `getBotId` can reuse the instance. 

`getBotId` needs to the token that was issued during the OAuth flow, so this [initialize without a token section](https://slack.dev/node-slack-sdk/web-api#initialize-the-client) seems relevant. 

We also need to update the hardcoded url in `generateInstallUrl`. So maybe accepting `slackApiUrl` would be the easiest

**Comment by stevengill** [comment]
This has been merged and will be released later today!
