### ISSUE TITLE
web-api gets status 401 errors with proxy agent settings

### ISSUE THREAD

**Issue by MonikaDadhich** [slackapi/node-slack-sdk#1058]
Hi Team,

 I'm using 

```js
const web = new WebClient('xoxb-bot token', { agent : proxy, logLevel: LogLevel.DEBUG });

(async () => {
  try {
    // Use the `chat.postMessage` method to send a message from this app
    await web.chat.postMessage({
      channel: '#general',
      text: "Hello everyone, this is Monika"
    });
  } catch (error) {
    console.log("Error is :");
    console.log(error.stack);
  }
  console.log('Message posted!');
})();
```
But i'm getting following error in loop:
```
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 401
[DEBUG]  web-api:WebClient:0 will perform http request
```

- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:12.16.1

OS version(s):MAC Mojave 10.14.6

#### Steps to reproduce:

1.First of all I am behind corporate proxy hence in order to replicate you should have similar environment.
2. I've already verified  https-proxy-agent with https package and it worked for me by using https.get method for path : https://slack.com/api
3. But when i'm trying to send message through my code attached then its throwing this error.
[index4.txt](https://github.com/slackapi/node-slack-sdk/files/4950091/index4.txt)

#### Expected result:

Message "Hello everyone" posted to channel #general

#### Actual result:

It gave error in loop:
attempting to GET "https://slack.com/api"
```
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('chat.postMessage') start
[DEBUG]  web-api:WebClient:0 will perform http request
Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
[DEBUG]  web-api:WebClient:0 http response received
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 401
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
👋  @MonikaDadhich thanks for writing in!

I'm happy to be of any help but I'm not able to verify how things go with your proxy server. Could you verify how [`https-proxy-agent` with `https` package](https://github.com/TooTallNate/node-https-proxy-agent#https-module-example) works in your environment, first? If you detect something specific to node-slack-sdk, please let us know.

**Comment by MonikaDadhich** [comment]
@seratch Here is the code and it works in my corporate environment.

**Comment by MonikaDadhich** [comment]
@seratch Here is the code and it works in my corporate environment.
[y.txt](https://github.com/slackapi/node-slack-sdk/files/4951435/y.txt)

**Comment by MonikaDadhich** [comment]
@seratch Yes, I've verified connection  https-proxy-agent with https package and it works in my corporate environment.
Here is the attached code to verify as well https://slack.com/api
[y.txt](https://github.com/slackapi/node-slack-sdk/files/4951443/y.txt)

**Comment by seratch** [comment]
I'm sorry for a very late response here! I revisited this and tried to reproduce your situation with the following script. However, I was not able to see the error you've shared.

```js
const { HttpsProxyAgent } = require('https-proxy-agent');
const { WebClient, LogLevel } = require("@slack/web-api");

const clientOptions = {
  agent: new HttpsProxyAgent('http://user:pass@localhost:9000'),
  logLevel: LogLevel.DEBUG,
}
const client = new WebClient(process.env.SLACK_BOT_TOKEN, clientOptions);

(async () => {
  try {
    await client.chat.postMessage({
      channel: '#general',
      text: "Hello everyone, this is Monika"
    });
  } catch (error) {
    console.log(error.stack);
  }
})();
```

I think there might be something specific to your proxy. If you're still struggling with this issue, please let us know (I'm not sure if I can easily help you out though). Otherwise, please let us close this issue after waiting for your response for a while.
