### ISSUE TITLE
Suddenly getting not_allowed_token_type

### ISSUE THREAD

**Issue by f8k8** [slackapi/node-slack-sdk#1060]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 5.10.0

node version: v12.14.1

OS version(s): Ubuntu LTS 16

#### Steps to reproduce:

1. Authorize a user with https://slack.com/oauth/authorize?scope=client+rtm:stream & https://slack.com/api/oauth.access
2. Create a Slack client using the bot token
3. Attempt to create a new conversation

#### Expected result:

A new conversation is created

#### Actual result:

The API returns an error: `Error: An API error occurred: not_allowed_token_type`. This used to work and I'm assuming it's something to do with the recent changes to the scopes, as it no longer works. We haven't changed anything in this code or with the setup of the app scopes in Slack, and we haven't upgraded to the new scopes as we still require access to RTM. Our plan is to migrate the part of our product which uses RTM over to the Events / Webhooks APIs, at which point we can switch to the new scopes. But for now, is there a reason that we're getting this error, and is there a way to work around it? Our app is set up for the `bot`, `channels:read` and `channels:write` OAuth scopes.

#### Attachments:

Sample code: 
```
const SlackWebClient = require("@slack/web-api").WebClient;
const client = new SlackWebClient(<Bot Token>);
client.conversations.create({ name: "test_conversation", is_private: false }).then(result => {
	console.log(result);
});
```

**Comment by seratch** [comment]
Thanks for writing in. I've verified the situation arises with my classic app. I'll update you once I get more information on this.

**Comment by seratch** [comment]
@f8k8 For channel creation using a classic app, please use a user token, not a bot token. For classic apps, this hasn't been changed from the beginning (while you can create a channel with a bot token in the new permission model).

**Comment by seratch** [comment]
As I've provided an answer here, let me close this issue now. Please feel free to write in if you have more to ask/discuss here.
