### ISSUE TITLE
chat.update: text is a required argument, but optional in the docs

### ISSUE THREAD

**Issue by dginovker** [slackapi/node-slack-sdk#1061]
### Description

chat.update has an [optional text](https://api.slack.com/methods/chat.update#arg_text) parameter (which should be used if you're not using blocks), but [in the code](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/methods.ts#L820) it's marked as required through Typescript.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: Slack bolt 2.1.1

node version: 12.18.1

OS version(s): Ubuntu 18.04.4

#### Steps to reproduce:

```
const app = new bolt.App({
  token: process.env.SLACK_BOT_TOKEN,
  signingSecret: process.env.SLACK_SIGNING_SECRET
});

app.client.chat.update({
  token: "token",
  channel: "channel",
  ts: "timestamp",
  blocks: {},
});
```

This breaks at compiler stage ^

#### Expected result:

Passing "token", "channel", "ts" and "blocks" as the only arguments to app.client.chat.update should be valid

#### Actual result:

Typescript compiler catches the error of "text" missing, although it should be optional if "blocks" is present

#### Attachments:

![image](https://user-images.githubusercontent.com/32943174/88560293-f1482700-cffb-11ea-8e9d-6f062f3506eb.png)

**Comment by seratch** [comment]
This seems to be related to this discussion: https://github.com/slackapi/node-slack-sdk/pull/853#issuecomment-641909673
@aoberoi @stevengill I leave it up to your judgment.
