### ISSUE TITLE
Any plan to support Koajs apps?

### ISSUE THREAD

**Issue by chenzhutian** [slackapi/node-slack-sdk#1064]
### Description

Are there any plans to support KoaJs apps?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

**Comment by stevengill** [comment]
Hey @chenzhutian

We don't currently have any plans to support koa out of the box. I believe you should be able to add these libraries to your koa apps still. Checkout the section `Using an existing HTTP server` at https://github.com/slackapi/node-slack-sdk/tree/main/packages/events-api#user-content-start-a-server for some guidance. I haven't tested it myself though. 

If you checkout [bolt-js](https://slack.dev/bolt-js/concepts), I know a community developed koa receiver exists over at https://github.com/IBM/slack-wrench/tree/master/packages/koa-bolt. Give it a try and let us know how it goes!

**Comment by chenzhutian** [comment]
Hi @stevengill ,

I have tried to wrap the `slackEvents.requestListener()` into a koa middleware, but it seems it cannot support async / await feature, which is a key feature of Koajs. Once I tried to await something in the middleware (i.e., use the options provided by slack/interactive-message 
```js
slackOptions.options({ within: 'block_actions'}, async (payload) => { await fetch('something') }
```
), then the whole koa app is stuck in this middleware.

I would like to provide a minimal reproduce repo but it is a bit difficult to separate the code, since it involves many signingSecrete and internal APIs...

**Comment by chenzhutian** [comment]
Oh when I use `.expressMiddleware()` instead of `.requestListener()` it works...
I think this is because `expressMiddleware` return a middleware with three params (req, res, _next).

I think this issue can be closed

**Comment by stevengill** [comment]
@chenzhutian thanks for the update on how you got it working!
