### ISSUE TITLE
@slack/web-api pachage not found when installing via npm or yarn

### ISSUE THREAD

**Issue by hildebert** [slackapi/node-slack-sdk#1071]
Node 12.10.0
Npm 6.10.3
Yarn 1.16.0

(also tested on Node 13x and 14x, several colleagues tested)

`yarn add @slack/web-api`, response:

`An unexpected error occurred: "https://registry.yarnpkg.com/@slack%2fweb-api: Not found".`

`npm install @slack/web-api`, response:

`npm ERR! 404 Not Found - GET https://registry.npmjs.org/@slack%2fweb-api - Not found`

It was working yesterday, so I don't know exact time when this began. Can you please look into this?

**Comment by uptown** [comment]
👍

**Comment by Darksole** [comment]
Getting the same issue with:

`npm i @slack/webhook`

node v14.7.0
npm v6.14.7

```
npm i @slack/webhook@5.0.3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@slack%2fwebhook - Not found
npm ERR! 404
npm ERR! 404  '@slack/webhook@5.0.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by uptown** [comment]
@hildebert @Darksole 
According to npmjs.org ( https://status.npmjs.org/ )
![image](https://user-images.githubusercontent.com/3631891/89519723-c8077200-d817-11ea-8be7-50ac421e3f4a.png)

**Comment by uptown** [comment]
currently scoped packages have an accessing problem

**Comment by montacerdk** [comment]
Same problem

**Comment by seratch** [comment]
According to their incident report, the situation is getting better. I myself no longer have the download issue with `@slack` packages. I hope it recovers for all as early as possible.

>Errors are decreasing while we re-populate a faulty cache. We are working to speed up that process to fully resolve the remaining issues quickly.
Posted 14 minutes ago. Aug 06, 2020 - 10:22 UTC

https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by seratch** [comment]
The npm registry is now operating normally. Let me close this issue now.

>The incident has been resolved and we see no errors with installing packages anymore. Posted 1 hour ago. Aug 06, 2020 - 12:01 UTC
https://status.npmjs.org/incidents/cksjqc1w11v5
