### ISSUE TITLE
Where to store user's tokens

### ISSUE THREAD

**Issue by Qwoxa** [slackapi/node-slack-sdk#1079]
### Description

I'm currently working on integration with Slack. The goal is to give a user the ability to share information using own Slack account right from our platform.

We gain the access token on the backend (because of the app secret) and use it on the frontend. The access token is stored in local storage; all the requests (`chat.postMessage`, `conversations.list`, `users.list`) are made on the frontend.

Is it okay to store tokens in local storage? Or it is better to move the logic (as well as access token) to the backend?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
In general, it is less secure to store tokens on the frontend and it is recommend to do it on the backend. Checkout https://auth0.com/docs/tokens/token-storage#don-t-store-tokens-in-local-storage to learn more about why.
