### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jbartadev** [slackapi/node-slack-sdk#1088]
### Description

Trying to initialize the client and got the`TypeError: Cannot convert undefined or null to object`
` at new WebClient (.../node_modules/@slack/web-api/dist/WebClient.js:444:44)`

The token is 100% valid, same code works with older versions of client.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

happens only from `5.8.0` and higher

node version: `v13.10.1`

OS version(s): `Mojave 10.14.6 `

#### Steps to reproduce:

```
const { WebClient } = require('@slack/web-api');
const slackToken = process.env.SLACK_BOT_TOKEN;
const slackClient = new WebClient(slackToken);  //<-- throws the error
```

#### Expected result:

The web client should be created.

#### Actual result:

Throws strange error.

**Comment by misscoded** [comment]
Hey @jbartadev, I'm trying to reproduce your issue but no luck on either side of `5.8.0`. 

Could you let us know exactly what package version you're using that causes the error, as well as the pre-`5.8.0` version that doesn't?

**Comment by jbartadev** [comment]
Hi @misscoded ,

Thanks for the quick reaction. 

This is a version where the provided code works:

```
	"@slack/web-api": {
			"version": "5.7.0",
			"resolved": "https://registry.npmjs.org/@slack/web-api/-/web-api-5.7.0.tgz",
			"integrity": "sha512-n3c2S5+fvRJV/FYhdZXPuMrRhnEdF5yPhSXK9ph4xJezNzMbb4OWymrMz7+XVf4qOz30HxN9A6ktV98stOBrhw==",
			"requires": {
				"@slack/logger": ">=1.0.0 <3.0.0",
				"@slack/types": "^1.2.1",
				"@types/is-stream": "^1.1.0",
				"@types/node": ">=8.9.0",
				"@types/p-queue": "^2.3.2",
				"axios": "^0.18.0",
				"eventemitter3": "^3.1.0",
				"form-data": "^2.5.0",
				"is-stream": "^1.1.0",
				"p-queue": "^2.4.2",
				"p-retry": "^4.0.0"
			},
```
--> Everything is fine.


And then when I update for example to the newest version of the package:
```
"@slack/web-api": {
			"version": "5.11.0",
			"resolved": "https://registry.npmjs.org/@slack/web-api/-/web-api-5.11.0.tgz",
			"integrity": "sha512-4a/uj7IZjFLu7Qmq0nH74ecLqk1iI/9x3yRS/v6M5vXDyc5lEruRFp4d5/bz4eN5Bathlq4Bws0wioY516fPag==",
			"requires": {
				"@slack/logger": ">=1.0.0 <3.0.0",
				"@slack/types": "^1.7.0",
				"@types/is-stream": "^1.1.0",
				"@types/node": ">=8.9.0",
				"@types/p-queue": "^2.3.2",
				"axios": "^0.19.0",
				"eventemitter3": "^3.1.0",
				"form-data": "^2.5.0",
				"is-stream": "^1.1.0",
				"p-queue": "^2.4.2",
				"p-retry": "^4.0.0"
			},

```

--> `TypeError: Cannot convert undefined or null to object`

same with a version just above the 5.7.0 -> 5.8.0 as I posted earlier:

```
"@slack/web-api": {
			"version": "5.8.0",
			"resolved": "https://registry.npmjs.org/@slack/web-api/-/web-api-5.8.0.tgz",
			"integrity": "sha512-lUMFM9jtdn+9Q0kHLegf5RjIgQlmb1PGWwWdTsc9mQ8PJu2BogI5ZttG8/tA6r2bX/C4bgXhd0JJ4syUR0AAhQ==",
			"requires": {
				"@slack/logger": ">=1.0.0 <3.0.0",
				"@slack/types": "^1.2.1",
				"@types/is-stream": "^1.1.0",
				"@types/node": ">=8.9.0",
				"@types/p-queue": "^2.3.2",
				"axios": "^0.19.0",
				"eventemitter3": "^3.1.0",
				"form-data": "^2.5.0",
				"is-stream": "^1.1.0",
				"p-queue": "^2.4.2",
				"p-retry": "^4.0.0"
			},
```

--> `TypeError: Cannot convert undefined or null to object`

**Comment by aoberoi** [comment]
just adding some info to the investigation. i downloaded v5.8.0 (`npm pack @slack/web-api@5.8.0`) of the package to find the line where the error is produced.

```js
        this.axios = axios_1.default.create({
            baseURL: slackApiUrl,
            headers: Object.assign({
                'User-Agent': instrument_1.getUserAgent(),
            }, headers),
            httpAgent: agent,
            httpsAgent: agent,
            transformRequest: [this.serializeApiCallOptions.bind(this)],
            validateStatus: () => true,
            maxRedirects: 0,
            // disabling axios' automatic proxy support:
            // axios would read from envvars to configure a proxy automatically, but it doesn't support TLS destinations.
            // for compatibility with https://api.slack.com, and for a larger set of possible proxies (SOCKS or other
            // protocols), users of this package should use the `agent` option to configure a proxy.
            proxy: false,
        });
        // serializeApiCallOptions will always determine the appropriate content-type
        delete this.axios.defaults.headers.post['Content-Type'];
        this.logger.debug('initialized');
```

Line 444 specifically refers to `delete this.axios.defaults.headers.post['Content-Type'];`, where column 44 is the "p" in `post`.

**Comment by aoberoi** [comment]
It seems like `this.axios.defaults.headers` is no longer an object, but instead `null` or `undefined`. I think the next place to look would be at recent changes in `axios` that would have caused this. If that's the case, let's figure out whether or not they intend to revert this breaking change before we add any sort of workaround in our code.

**Comment by aoberoi** [comment]
@jbartadev would you mind sharing the output of `npm ls axios` in both the working and non-working scenarios?

**Comment by jbartadev** [comment]
@aoberoi sure I can:

This one works (5.7.0)
```
├─┬ @slack/web-api@5.7.0
│ └── axios@0.18.1 
├─┬ apify-client@1.0.0-beta.0
│ └── axios@0.19.2 
└─┬ apify-shared@0.4.3
  └── axios@0.19.2  deduped
```
And this one not (5.8.0)

```
├─┬ @slack/web-api@5.8.0
│ └── axios@0.19.2 
├─┬ apify-client@1.0.0-beta.0
│ └── axios@0.19.2  deduped
└─┬ apify-shared@0.4.3
  └── axios@0.19.2  deduped
```

**Comment by aoberoi** [comment]
Thanks, it's helpful to know that the issue seems to correlate to `axios@0.19.x` as the resolved dependency for `@slack/web-api`.

I tried to reproduce the issue but I haven't been able to. I created this sample project, and ran it with node v13.10.1 on macOS Catalina (I don't have a system with Sierra on it, but I'd be really surprised if that had anything to do with this).

Here is [a sample project](https://github.com/slackapi/node-slack-sdk/files/5147462/node-sdk-playground.zip).  @jbartadev Would you mind downloading it and running it on your system? You should be able to unzip and run `node issue-1088.js` (don't reinstall dependencies). Maybe this will help eliminate some possible causes.

If the project above works, then the next place to look is to see if `apify-client` or `apify-shared` are unintentionally mutating some global state within axios, such that by the time `@slack/web-api` tries to use it, the failure is caused.

If it doesn't work, it would be helpful to start adding log statements within the `./node-modules/@slack/web-api/dist/WebClient.js` file on you machine and for you to share the output.

**Comment by aoberoi** [comment]
Here's some code from `apify-client@1.0.0-beta.0` that is destructively modifying global state: 

https://github.com/apify/apify-client-js/blob/ad8027c678c0c14805f6920e9800f736fce2c57e/src/http-client.js#L38-L40

In my humble opinion, I think that's a bug in that dependency. @jbartadev would you be able to help land a change in that project?

**Comment by aoberoi** [comment]
@jbartadev any updates here? If you've figured this out or moved on, we'd love to close out the issue.

**Comment by misscoded** [comment]
Hi @jbartadev, hopefully you've been able to resolve the issue above. If you need any further help, please feel free to comment and we can revisit.

**Comment by pablopaul** [comment]
I had the same exact issue, caused by CodeceptJS overriding the global axios instance, see [here](https://github.com/codeceptjs/CodeceptJS/blob/10e86bebfd731817e2f2cbe12d5184224c6f818d/lib/helper/REST.js#L53).

@aoberoi @misscoded do you have any advice how the CodeceptJS project should handle this instead, so the global axios instance stays untouched? 

Thanks!
