### ISSUE TITLE
@slack/events-api can't verify URL with ngrok

### ISSUE THREAD

**Issue by Baksha2008** [slackapi/node-slack-sdk#1090]
### Description

I tried to verify the address with ngrok and followed this tutorial https://slack.dev/node-slack-sdk/events-api#verify-tool, but always getting error.  Could you please tell me where I am making a mistake?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: 2.3.4

node version: 12.17.0

OS version(s): macos 10.15.6 

#### Expected result:
address verify

#### Actual result:
Can't verify address  

#### Attachments:
<img width="689" alt="Screenshot 2020-09-01 at 14 05 04" src="https://user-images.githubusercontent.com/22969597/91842145-24fe1880-ec5c-11ea-9750-84a5b8d1b940.png">
<img width="698" alt="Screenshot 2020-09-01 at 14 03 43" src="https://user-images.githubusercontent.com/22969597/91842147-27f90900-ec5c-11ea-8720-f9a9c5afc0df.png">
<img width="569" alt="Screenshot 2020-09-01 at 14 03 16" src="https://user-images.githubusercontent.com/22969597/91842150-2a5b6300-ec5c-11ea-993c-a57609e059ea.png">

**Comment by stevengill** [comment]
Hey @Baksha2008,

You need to append `/slack/events` to your ngrok url when adding it to slack. 

You can see the little note at the bottom of the section you [linked to in the docs](https://slack.dev/node-slack-sdk/events-api#verify-tool) mentioning it. 

> Note: If you’re using a tunneling tool like ngrok, the Request URL you save in Slack would be the tunnel URL, such as https://abcdef.ngrok.io, appended with the path. In other words, it should look like https://abcdef.ngrok.io/slack/events

Please close this issue if this solves your problem. Thanks!

**Comment by Baksha2008** [comment]
> Hey @Baksha2008,
> 
> You need to append `/slack/events` to your ngrok url when adding it to slack.
> 
> You can see the little note at the bottom of the section you [linked to in the docs](https://slack.dev/node-slack-sdk/events-api#verify-tool) mentioning it.
> 
> > Note: If you’re using a tunneling tool like ngrok, the Request URL you save in Slack would be the tunnel URL, such as https://abcdef.ngrok.io, appended with the path. In other words, it should look like https://abcdef.ngrok.io/slack/events
> 
> Please close this issue if this solves your problem. Thanks!

Thank you for your answer!  I tried, of course, the result was the same

<img width="631" alt="Screenshot 2020-09-02 at 10 03 54" src="https://user-images.githubusercontent.com/22969597/91942434-9e9d1180-ed03-11ea-8c8e-4b9662c5f561.png">

**Comment by Baksha2008** [comment]
Thanks again, I just tried one more time and everything works. 
<img width="689" alt="Screenshot 2020-09-02 at 10 23 20" src="https://user-images.githubusercontent.com/22969597/91944173-54695f80-ed06-11ea-8caf-08b6a16f3572.png">

**Comment by varundroid** [comment]
Hi, I am facing the same issue. I can't seem to get it work. Tried with and without `/slack/events`. Any idea how do I solve this?

**Comment by CatsNipYummy** [comment]
Same issue for me as well. It used to work fine before with `/slack/events` . Not any more.

**Comment by srajiang** [comment]
@CatsNipYummy The API has not changed to my knowledge. Are you using a static domain with ngrok? This has tripped up some people before when they have a dynamic ngrok provided domain (https://4cce13c5234c.ngrok.io vs https://sjiang.ngrok.io/), where once they have restarted ngrok they haven't updated their URL in App Config.

If that doesn't apply to you, I recommend opening a new issue and providing more detail on the behavior you're seeing, including screenshots, your current version of @slack/events-api etc. since we don't actively monitor closed messages.

**Comment by CatsNipYummy** [comment]
@srajiang I am using the dynamic one. So I have been updating the url on my end. I see the event coming through on my end as well. So the routing seems to be working. I'm using the python sdk. I'll open an issue on that github with all the information.

**Comment by laroza13465** [comment]
ngrok                                                           
                                                                                
Join us in the ngrok community @ https://ngrok.com/slack                        
Session Status                online                                            
Account                       ffdddfffggg (Plan: Free)                          
Version                       3.0.6                                             
Region                        Europe (eu)                                       
Latency                       68ms                                              
Web Interface                 http://127.0.0.1:4740                             
Forwarding                    tcp://0.tcp.eu.ngrok.io:1xxxxxx -> localhost:4444   
                                                                                
Connections                   
                            وجهتني مشكلة هل من حل ؟
 I'm having a problem with ngrok
solution of solution?
