### ISSUE TITLE
User ID missing in OAuth v1 callback

### ISSUE THREAD

**Issue by lasseschou** [slackapi/node-slack-sdk#1103]
### Description

When using the v1 OAuth method, the result from the underlying call to /oauth.access contains the user ID of the installing user, but the code does not at it to the `Installation` object - see here:

https://github.com/slackapi/node-slack-sdk/blob/4bb46750a994bb72a6cbbb0ee196d9e8b8f406e1/packages/oauth/src/index.ts#L222

It's an easy fix. Simply use `resp.user_id` instead of `''`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version: latest

node version: latest

OS version(s): Shouldn't matter

#### Steps to reproduce:

1. Create a classic Slack bot (which uses OAuth v1) and use either node-slack-sdk or bolt-js to create an oauth-based app
2. This bug (or missing feature) was found in relation to building a bolt-js based app, but the bug was tracked down to this package. The success function called when the oauth.access method returns does not include the user ID of the installing user.
3. The Installation object contains team.id, team.name, user.token, bot.token, but user.id is undefined.

#### Expected result:

Since the user ID of the installing user is returned in the oauth.access call to Slack, I would expect this ID to be passed on to the client using the library.

#### Actual result:

Undefined

#### Proposed fix:

https://github.com/slackapi/node-slack-sdk/blob/4bb46750a994bb72a6cbbb0ee196d9e8b8f406e1/packages/oauth/src/index.ts#L222

Replace `id: '', // Todo: no value for this` with `id: resp.user_id,`

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hey @lasseschou 👋🏻 Thanks for reaching out with this enhancement! The original motivation behind `@slack/oauth` was for `bolt-js`, so I imagine v2 OAuth 2.0 was the main focus.

Thanks for tracking down the solution! @stevengill are there any reasons that come to mind on why we can't move forward with adding User ID for v1 OAuth?

**Comment by stevengill** [comment]
During my initial tests, I didn't notice a `user_id` part of the `oauth.access` response payload. It isn't [documented](https://api.slack.com/methods/oauth.access#response) either. I'll have to run a test to see if I see it in the response payload.

**Comment by lasseschou** [comment]
Thanks @mwbrooks and @stevengill. I also noticed it was undocumented, but the `user_id` variable works fine for me. I hope you are able to move forward with this.

**Comment by stevengill** [comment]
Sent a PR #1105. Thanks again for reporting this @lasseschou!

**Comment by praveen-raghav-ns** [comment]
Will we get user_id of installing user in the response here ? If so, should user_id be added to the response in below page ?
https://api.slack.com/legacy/oauth#authenticating-users-with-oauth__the-oauth-flow__step-3---exchanging-a-verification-code-for-an-access-token__bot-user-access-tokens
