### ISSUE TITLE
Question: a mechanism to regularly send messages to all users in a remote workspace?

### ISSUE THREAD

**Issue by mihristov** [slackapi/node-slack-sdk#1106]
### Description

Hi. Not sure whether this is the right place to ask, so excuse me if not. I have a distributed app (bolt-js, multi-workspace, but not in the app store for now) which need a new feature: regularly (via cronjob) sending private DMs to all the users in the workspace (once a week, like a reminder). Ideally the messages have to be in the bot Messages (home) tab. I've looked for different solutions but nothing seems to work so far.
1. Workflow steps - this needs to be setup manually on the client workspace so this is a deal breaker. Clients need to be able to install my app without my help or any additional work done.
2. Webhooks - this kind of only works for public channels so again not what I need.

Let me know if you have any ideas, thanks.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/events-api`
- [] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] I don't know

#### Expected result:

A mechanism to regularly send messages to all users in a remote workspace.

#### Actual result:

Cannot find a way.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mihristov** [comment]
I solved my problem. I was trying to run my cronjob in the bolt-js app which was the mistake. Since I have the workspace token and the team id in the database I could send the messages using the web api in a separate lambda. Closing the ticket...

**Comment by aoberoi** [comment]
@mihristov hey there, while this isn't directly relevant to the SDK, it's no problem to ask for some help here.

i think you've mostly figured this out already. you already understand the idea of a cron job and that's probably the biggest leap to make. i'm going to make a couple of assumptions:
1. you have a Bolt for JS app, and the majority of your code lives in some file (such as `app.js`) (if not, the [Getting Started tutorial](https://slack.dev/bolt-js/tutorial/getting-started) is a good place to catch up).
2. you've already gotten your app installed in at least one workspace (for development) and you understand [how to set up OAuth](https://slack.dev/bolt-js/concepts#authenticating-oauth) to support making it distributed.
3. you have some cron service that just needs a command to execute each time it triggers.
4. you have a database (or some other storage) where you store installations. this is necessary to implemnt OAuth as described above. in addition to the `fetchInstallation()` and `storeInstallation()` functions, you also implemented a `fetchAllInstallations()` function which returns a Promise of an array of installation objects (the same shape as the single installation returned by `fetchInstallation()`). you wrote these three functions in a separate file called `db.js`. that file exports all three functions.

some words of caution: users don't like being spammed. DMing every user in the workspace, without them explicitly opting into some notification, is likely to be seen as spam. this will likely result in people quickly removing your app. you should only be DMing users in response to some activity OR if they've explicitly asked your app to do so. in the latter case, you should also give them a way to opt our and turn off the notifications. in the following code example, i will show you how to send the DM to all users, and afterwards i'll tell you more about how you might change this to allow users to opt-in.

one way to do this is to give your cron service a command like `node notify-users.js`. in your project, run `npm install @slack/web-api` to add a direct dependency on this package. then in the `notify-users.js` file (which is different from your `app.js` file), you use the following code:

```javascript
const { WebClient } = require('@slack/web-api');
const { fetchAllInstallations } = require('./db');

(async () => {
  const installations = fetchAllInstallations();
  for (const installation of installations) {
    const client = new WebClient(installation.bot.token);
    for await (const page of web.paginate('users.list')) {
      for (const member of page.members) {
        const openResult = await client.conversations.open({ users: member.id });
        await client.chat.postMessage({
          channel: openResult.channel.id,
          text: 'MY NOTIFICATION TEXT HERE',
        });
      }
  	}
  }
})().catch(console.error);
```

this code will iterate over all installations, and use the bot token in each installation to make a few API calls. the first is a call to `users.list`, which is paginated automatically, and returns all members of the workspace. then for each member in the workspace, there's a call to `conversations.open` and `chat.postMessage` to open a DM and send a message.

as i mentioned earlier, this could seem spammy. the next step would be to store a separate table or list in your database that represents each of the users who have opted into this notification. then you can simply replace the logic for iterating over all installations and calling `users.list`, which logic that iterates over those users, with some reference to their associated installation (to retrieve the appropriate bot token).

**Comment by aoberoi** [comment]
glad that you figured this out! i saw that you closed the ticket while i was still typing my response. i decided to still post it because it might help someone else with a similar question.

**Comment by mihristov** [comment]
Thanks for the answer @aoberoi The implementation you posted came in handy as well :1st_place_medal:
