### ISSUE TITLE
How do I properly identify modal block_actions?

### ISSUE THREAD

**Issue by ArjenStens** [slackapi/node-slack-sdk#1107]
### Description

I am working on upgrading from dialogs to modals. I have an application where I define different kinds of modals by use-case. For example I have a modal for creating a database and one for creating a new git repository. The submission/closing events work well but i have a question specifically about `block_actions`.

When creating a modal, I can subscribe to `viewSubmission` and `viewClosed` events using a `callback_id` as a `matchingConstraint` and process that event knowing that it came from the specific type of modal I just defined because of the `callback_id`. This works the way I expect and is similar to how it worked with dialogs.

When I try to subscribe to action events for that same modal, things get tricky. I want to subscribe to an `action_id` of an input block in this modal. For that I use an `ActionContraints` object as the `matchingConstraint`, where I can constrain to `callback_id`, `action_id`, `block_id` and `type`.

But the problem is that when I pass the `callback_id` there, it will not match properly like the `viewSubmission/viewClosed` do. I can’t match on `block_id` since those are required to be always unique [(blocks documentation)](https://api.slack.com/reference/block-kit/blocks#input_fields) So then I’m left with `action_id` which does indeed work. The problem with that however, is that it will conflict with other kinds of modals that I (or someone else working on the application) may create later that contain the same `action_id`.

So to get to my question: How do I subscribe to an action_id of a modal without risking conflicts/overrides because other parts of the application may also subscribe to the same action_id?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Hey @ArjenStens!

Two possible thoughts on how to move forward.

1) Use a combination of `block_id` and `action_id` when making the constraint. Something like:
```
slackInteractions.action({'block_id':'some_block_id', 'action_id': 'some_action_id'}, (payload, response) => {
...
})
```

2) Make `action_id` unique for every block element. 

Let me know if that helps
