### ISSUE TITLE
2.0.0: one datastore for all teams

### ISSUE THREAD

**Issue by acemtp** [slackapi/node-slack-sdk#111]
In the memory datastore of the 2.0.0, it has an object teams so does you plan to be able to put more than one team in the same datastore?

If yes, it works fine except that some links are missing; For example, in a channel model, there's no way to know in which team it is. And in team, we don't have a list of channel for in the end, we cannot know which channels are for which teams.

Any idea on how to fix that?

**Comment by l12s** [comment]
The intention was to support multiple teams on a single datastore. I'm not sure that I'm going to get to the work that's required to make that happen for the 2.0.0 release though. I'm going to put a milestone in for a 2.1.0 release and add this to it.

**Comment by acemtp** [comment]
Perfect

**Comment by peernohell** [comment]
Hi,

Is there some news about this issue?
Does the current version support multiple teams on a single datastore?

thanks

**Comment by DEGoodmanWilson** [comment]
We're in the process of revisiting how the datastore works, just to keep y'all abreast. Using a single datastore for each team is something that is on the table, as it should make implementing Events API easier.

**Comment by aoberoi** [comment]
there's currently a larger discussion going on around the future of the datastore API. i'd like to consolidate that discussion into #330. specifically, i think the problems stated here are covered by the point about Enterprise Grid and not having knowledge of the entire team.
