### ISSUE TITLE
Slack API returns 400 when attachment has footer and blocks

### ISSUE THREAD

**Issue by Ponjimon** [slackapi/node-slack-sdk#1112]
### Description

I'm trying to send a webhook but the API returns a 400 error when using `blocks` instead of `fields` and when trying to use fields like `ts` or `footer`.

I can't find anything in the documentation that says you cannot use certain fields when using blocks, maybe I overlooked it, if so, please tell me where I can find that information.

Otherwise, that information should either be added or this issue fixed? The TypeScript types also indicate that I'm allowed to use it like that.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

Not applicable since it's a Slack API issue potentially.

#### Expected result:

It should allow the use of those fields.

#### Actual result:

Slack API returns 400.

**Comment by seratch** [comment]
Hi @Ponjimon, I'm sorry for our very slow response here. 

If you're still interested in this issue, can you elaborate a bit more about the situation you faced at that time? Particularly,

>I'm trying to send a webhook but the API returns a 400 error when using blocks instead of fields and when trying to use fields like ts or footer.

I am not sure what the payload you used looks like.

**Comment by seratch** [comment]
Let me close this due to inactivity
