### ISSUE TITLE
Improvements for the Releasing portion of Maintainers Guide

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#1117]
### Description

While performing a release, I found a couple issues that I think could be addressed to make releasing a tiny bit easier.

* need to run `npm install` before step 0. if that's true, might as well do this first and not use `npx` for the lerna related commands.

* `npx lerna clean && npx lerna bootstrap` doesn't remove all the `package-lock.json` files. this caused an issue for me. `typescript@3.9.3` was stored in a `package-lock.json` and had a bug. it cost me a bunch of time to figure out, but could have been prevented if the latest version was fetched. i thought that's what clean and bootstrap would do for me, and it didn't.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
As we've updated the maintainers guide in the way of request https://github.com/slackapi/node-slack-sdk/pull/1265 , this issue is no longer relevant. Let me close this task now.
