### ISSUE TITLE
Using files.upload API with the browser file object

### ISSUE THREAD

**Issue by flickz** [slackapi/node-slack-sdk#1118]
### Description
I'm trying to use `files.upload` API within the browser but passing the web API `new File()` object or `Blob` stream API to `file` option would result in `no_file_data`. Take for example the code below:

```js

web.files.upload({
    file: new File(['foo'], 'foo.txt', {
      type: 'text/plain',
    }),
    channels: ``,
    initial_comment:  '',
  });

```

Why can't we make this work? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
Hey @flickz this is a great question. It looks like you're working with [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and [File](https://developer.mozilla.org/en-US/docs/Web/API/File) from the Web API that are not implemented in Node.js. While this package doesn't specifically aim to support usage from a browser, we're not opposed to making the package compatible for use cases where it makes sense.

So let's start by understanding your use case. Are you building a Slack app that solely runs inside a browser? If so, how are you planning on keeping your tokens safe? Given that anything in a browser is user-inspectable, this is usually a blocker for people who start down this path. Often times, people with this idea will pivot to using a server for all communication with the Slack API, and then make their own API for fetching and sending data to that server from the browser.

**Comment by flickz** [comment]
> Are you building a Slack app that solely runs inside a browser? 

Right now, I'm just experimenting with the APIs and most of the API calls I've used so far worked without the need for server setup, I was kind of hoping `files.upload` would offer the same compatibility experience. I'd definitely use a serverless function to handle this in the future. 

Thanks, @aoberoi Feel free to close the issue.
