### ISSUE TITLE
`missing_scope` error when using `conversation.info` Slack API call

### ISSUE THREAD

**Issue by jerrytohvan** [slackapi/node-slack-sdk#1124]
I am trying to retrieve slack channel name via slack bot token with channel id as a parameter.

The tester call works fine:`https://slack.com/api/conversations.info?token=<TOKEN>&channel=C0000000000&pretty=1`(open raw response)

However, when trying from webhook script it returns the following error only when accessing channel:
```
"err":{
"message":"An API error occurred: missing_scope",
"name":"Error",
"stack":"Error: An API error occurred: missing_scope\n
    at Object.platformErrorFromResult (/usr/src/app/node_modules/@slack/web-api/dist/errors.js:50:33)\n
    at WebClient.apiCall (/usr/src/app/node_modules/@slack/web-api/dist/WebClient.js:485:28)\n
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
...
```
I believe that channels:read permission have been granted.

**Comment by seratch** [comment]
@jerrytohvan Does the `curl` command work for you?

```bash
export CHANNEL_ID=C1111  # your channel ID
export SLACK_BOT_TOKEN=xoxb- # your token
curl -X GET "https://slack.com/api/conversations.info?pretty=1&channel=${CHANNEL_ID}" -H "Authorization: Bearer ${SLACK_BOT_TOKEN}"
```

If the above works with the same token, your JS code may be using another token.

If the `curl` does not work as with your JS code, tester may behave a bit different for some reason (I've never encountered this though). In this case, can you try re-installing the Slack app with `channels:read` to surely add the scope to the token?

**Comment by jerrytohvan** [comment]
Hi @seratch , thanks for your prompt response! ◡̈ 

Just tried and it works and confirmed that we are using the same token for our WebClient

**Comment by stevengill** [comment]
Hey @jerrytohvan,

Still having this issue or can we mark it as closed?

**Comment by jerrytohvan** [comment]
@seratch you're right! The problem with running multiple tokens 😅 Thank you! 


@stevengill - all good ◡̈

**Comment by muzamilar** [comment]
I am getting this issue,  need help


index.js:1 Error: An API error occurred: missing_scope
    at Object.platformErrorFromResult (errors.ts:93)
    at WebClient.apiCall (WebClient.ts:198)
    at async handleMessageSubmit (chat.js:32)
