### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by jeemyeong** [slackapi/node-slack-sdk#1125]
https://github.com/slackapi/node-slack-sdk/blob/333d5e674026c140dcd7d0171a3df001862eefe7/packages/interactive-messages/src/adapter.ts#L418

message
```
TypeError: Cannot read property 'then' of undefined
  File "/workspace/node_modules/@slack/interactive-messages/src/adapter.ts", line 419, col 35, in respond
  File "internal/process/next_tick.js", line 68, col 7, in process._tickCallback
```

dependencies:
```
"@slack/interactive-messages@^1.7.0":
  version "1.7.0"
  resolved "https://registry.yarnpkg.com/@slack/interactive-messages/-/interactive-messages-1.7.0.tgz#eff17dcacb7c40caf0d9e1a641ebc6c304502c36"
  integrity sha512-GDhlanY0hHJnKrVKCi9Xtda974NHsFXTlExH+7HyNS7bOMGKp8BdqQTVVMijQnBm+sJn2y2z5j3icl1GtHf8Lw==
  dependencies:
    "@types/debug" "^4.1.4"
    "@types/express" "^4.17.0"
    "@types/lodash.isfunction" "^3.0.6"
    "@types/lodash.isregexp" "^4.0.6"
    "@types/lodash.isstring" "^4.0.6"
    "@types/node" ">=4.2.0"
    axios "^0.19.0"
    debug "^3.1.0"
    lodash.isfunction "^3.0.9"
    lodash.isplainobject "^4.0.6"
    lodash.isregexp "^4.0.1"
    lodash.isstring "^4.0.1"
    raw-body "^2.3.3"
    tsscmp "^1.0.6"
```

**Comment by stevengill** [comment]
Hey @jeemyeong do you know what slack event/action triggered this error? Would help with reproducing this. Regardless, adding a check for message to not be undefined before the check you highlighted would solve this bug.

**Comment by akateliev** [comment]
I've got this error as well.

`2020-12-07 12:15:26.179 EET(node:33) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
Default
2020-12-07 12:15:26.179 EET at respond (/app/node_modules/@slack/interactive-messages/dist/adapter.js:399:32)
Default
2020-12-07 12:15:26.179 EET at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by akateliev** [comment]
We are basically doing that in our codebase and we got the above error not every time but is happening quite often.
We've got 3 static_selects with a submit button. We got the error on submit. It is express app.
slackInteractions is the createAdapter from @slack/interactive-messages:

`app.post('/interact', slackInteractions.requestListener(), (req: any, res: any) => {
  if (req.body && req.body.challenge) {
    return res.status(200).json(req.body.challenge)
  }

  res.status(200)
})

slackInteractions.action({
  type: 'button',
  actionId: ActionIds.SomeID
}, async (payload, respond) {
  const someValue1 = await someFunction1() // gets values from payload and get request to api
  const someValue2 = await someFunction2() // gets other values from payload and get request to api

  if (!someValue1 || !someValue2) {
    await respond({ text:"message" })
    return
  }

  const someValue3  = await someFunction3() // keeps some params to redis/db
  const blocks = buildBlocksFrom({ someValue1, someValue2, someValue3 })

  respond({ blocks })
})`

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
