### ISSUE TITLE
Typing indicator in Events API?

### ISSUE THREAD

**Issue by rogueDev9** [slackapi/node-slack-sdk#1130]
### Description

Is there any functional equivalent of the `sendTyping` function in RTM for Events API?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

**Comment by stevengill** [comment]
hey @rogueDev9,

There is no equivalent functionality in events-api and we don't plan on introducing it. 

We know from our user research that people prefer interactive apps most of the time over conversational bots. so we've been building features like App Home, Block Kit, and Modals to make bring those interactions to life. Ultimately, if you want to pretend your bot is typing, you can do it by sending a "@my_fun_bot is typing" message from the app, and then removing it after you send your actual message. Better yet, you can send a spinner or other animation in an image.

**Comment by rogueDev9** [comment]
Got it thanks for the clarification

**Comment by migsterrrrr** [comment]
> hey @rogueDev9,
> 
> There is no equivalent functionality in events-api and we don't plan on introducing it.
> 
> We know from our user research that people prefer interactive apps most of the time over conversational bots. so we've been building features like App Home, Block Kit, and Modals to make bring those interactions to life. Ultimately, if you want to pretend your bot is typing, you can do it by sending a "@my_fun_bot is typing" message from the app, and then removing it after you send your actual message. Better yet, you can send a spinner or other animation in an image.

You still stand by this? 😇

**Comment by gusman80** [comment]
with all the chatgpts  around , their streaming api and their latency on longer threads i think you should overthink this ...

**Comment by boutcher** [comment]
Totally agree with @gusman80 ... Have Slack front-ending an OpenAI Assistant, sometimes there's 20-30 seconds to get a response. Not seeing any indication of work being done ("bot is typing") makes for a really awkward experience.

**Comment by zimeg** [comment]
@boutcher still no update on introducing a typing indicator, but you could consider using the  🤔 emoji with [`reactions.add`](https://api.slack.com/methods/reactions.add) then [`reactions.remove`](https://api.slack.com/methods/reactions.remove) to signal your app is thinking? I might've seen @seratch use this before!

**Comment by seratch** [comment]
Yet another approach for this is to repeatedly call chat.update with chunk of gen AI response text. [My example app]*https://github.com/seratch/ChatGPT-in-Slack/) utilizes the technique.

**Comment by dkarlovi** [comment]
@seratch how are the rate limits here, do you do batching or do you just stream the LLM responses as they come in?

**Comment by seratch** [comment]
@dkarlovi chat.update's rate limit is Tier 3, which means you can call it 50+ times per minute (per app and per workspace). In most cases, you won't receive an error, but if you're building an app for a busy workspace/org with a large user base, adjusting the frequency of repeated updates may be worth considering.
