### ISSUE TITLE
`trigger_id` expired

### ISSUE THREAD

**Issue by xiuleiyy** [slackapi/node-slack-sdk#1131]
### Description

I got the below errors intermittently in my code:
```
[ERROR] web-api:WebClient:1 `trigger_id` expired [json-pointer:/trigger_id]
{ Error: An API error occurred: invalid_arguments
at Object.platformErrorFromResult (/Users/acostry/Box Sync/Workspace/Git-Dev/avm-bot/node_modules/@slack/web-api/dist/errors.js:51:33)
at WebClient.apiCall (/Users/acostry/Box Sync/Workspace/Git-Dev/avm-bot/node_modules/@slack/web-api/dist/WebClient.js:156:28)
at process._tickCallback (internal/process/next_tick.js:68:7)
code: 'slack_webapi_platform_error',
data:
{ ok: false,
error: 'invalid_arguments',
response_metadata: { messages: [Array], scopes: [Array] } } }
```

My code looks like:

```
app.action('ng_select_block', async ({ ack, action, context, message, body, client, say }) => {
    await ack();

    Doing some search action and this will take some time. 

    const result = await client.views.open({
        trigger_id: body.trigger_id,
        view: composeNotificationView
    });
});
```
1. I ack() in the first line, why still got the timeout error?
2. Do you have any best practice on the coding to avoid this timeout error?
Thanks much.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Hey @xiuleiyy,

`trigger_id` [expires after 3 seconds](https://api.slack.com/surfaces/modals/using#opening_modals). That means you need to open the modal within that timeframe.

In general, if a user initiates a modal (maybe a shortcut or a button click), it is bad UX to make them wait longer than three seconds to pop that modal up.

Some suggestions to your problem
- make the work you do after ack but before opening the modal less than 3 seconds. Possibly do this work early if possible
- publish a modal right away and save the `view_id`. Then you can update the contents of the modal once you have the data you want to publish.

**Comment by xiuleiyy** [comment]
Thanks @stevengill 
I got your point.
One more question: Is it possible in my code to change the 3 seconds limitation? is supported by the SDK?

**Comment by xiuleiyy** [comment]
@stevengill 
I tested base on your 2nd suggestion to update with the view_id. The log returns me an OK, but the modal wasn't updated with the new contents. Is there a known issue here?

My code looks like:

```
app.action('ng_select_block', async ({ ack, action, context, message, body, client, say }) => {
    await ack();

    const result = await client.views.open({
        trigger_id: body.trigger_id,
        view: composeNotificationView
    });

    Doing some search action and this will take some time. 
    Update the composeNotificationView with new content.

    const result = await client.views.open({
      view_id: result.view.id,
      hash: result.view.hash,
      view: composeNotificationView
    });
});```

**Comment by seratch** [comment]
Hello @xiuleiyy, I'm in a similar timezone 👋 

>One more question: Is it possible in my code to change the 3 seconds limitation? is supported by the SDK?

Unfortunately, there is no way to change the time period.

>publish a modal right away and save the view_id. Then you can update the contents of the modal once you have the data you want to publish.

If you go with the approach, you can construct the complete version of the modal after 3 seconds. Here is a simple example demonstrating how it works.

<img src="https://user-images.githubusercontent.com/19658/101609824-c6122180-3a4a-11eb-905c-aa945a94a5fa.gif" width=500 />

```js
app.command("/workplace-checkin", async ({ logger, client, ack, body }) => {
  await ack();
  const res = await client.views.open({
    trigger_id: body.trigger_id,
    view: {
      "type": "modal",
      "title": {
        "type": "plain_text",
        "text": "Workplace check-in"
      },
      "close": {
        "type": "plain_text",
        "text": "Cancel"
      },
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "text": ":man-biking: Now loading..."
          }
        }
      ]
    }
  });
  const viewId = res.view.id;
  await new Promise(r => setTimeout(r, 4000));
  await client.views.update({
    view_id: viewId,
    view: {
      "type": "modal",
      "callback_id": "your-callback-id",
      "submit": {
        "type": "plain_text",
        "text": "Submit"
      },
      "close": {
        "type": "plain_text",
        "text": "Cancel"
      },
      "title": {
        "type": "plain_text",
        "text": "Workplace check-in"
      },
      "blocks": [
        {
          "type": "input",
          "element": {
            "type": "plain_text_input",
            "action_id": "plain_text_input-action"
          },
          "label": {
            "type": "plain_text",
            "text": "Let us know your thoughts!",
            "emoji": true
          }
        }
      ]    
    }
  })
});
````

**Comment by xiuleiyy** [comment]
@seratch
Could you check out my last comments? ^^^
When I tried to update my modal, some block was updated as expected, some not. Is there a known issue here? Thanks.

**Comment by xiuleiyy** [comment]
@seratch Your sample is awesome. Let me refine my code to see if this will help. Thanks much.

**Comment by seratch** [comment]
Oops, I’m sorry. Somehow I overlooked your next comment. Yeah, there is a known limitation where views.update API does not update a modal if the structure of blocks in the modal is not changed.

**Comment by xiuleiyy** [comment]
OK. Gotcha @seratch 
With your sample, I didn't see a timeout anymore. Thanks a lot.

**Comment by stevengill** [comment]
Sweet! Thanks @seratch for jumping in and providing an awesome sample. I'm going to close this issue as it seems resolved.

**Comment by Spoonrad** [comment]
Hi there, I'm not sure where to give feedback on the general REST API (rather than the Node SDK specifically) so I'll post this here because it's the same issue. I'm a little bit confused by what's happening to be honest. We use Flask in our back-end and make API requests using the REST API.

The opening of the modal has been failing often lately, but when I take a look at the request time, as logged by Flask, I always find results under 1000ms, that is 1000ms to reply with a 500 error to the service that forwards Slack's HTTP request to the service that handles it. If the trigger expires after 3 seconds, how is this possible?

Do the 3 seconds include the time it takes Slack to process the request and send it to our servers? What if we respond with a 500 error, will Slack retry using the same (now expired) trigger id? What if Slack's servers are slow or unresponsive, which has happened several times, sometimes for the span of entire days, in the past 3 months? What if something fails internally and we want to retry?

The implementation doesn't feel like it has many pros, but it has cons: 
- We have to carry around a trigger_id internally. Not a big deal.
- It seems like opening the modal might fail even if the request is sent before the 3000ms expiration 
- Instead of taking > 3 seconds for the modal to open, the modal does not open at all! What's better for the user's experience, something slow or something that doesn't work?

**Comment by bingwu-chime** [comment]
> Hello @xiuleiyy, I'm in a similar timezone 👋
> 
> > One more question: Is it possible in my code to change the 3 seconds limitation? is supported by the SDK?
> 
> Unfortunately, there is no way to change the time period.
> 
> > publish a modal right away and save the view_id. Then you can update the contents of the modal once you have the data you want to publish.
> 
> If you go with the approach, you can construct the complete version of the modal after 3 seconds. Here is a simple example demonstrating how it works.
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/19658/101609824-c6122180-3a4a-11eb-905c-aa945a94a5fa.gif">
> 
> ```js
> app.command("/workplace-checkin", async ({ logger, client, ack, body }) => {
>   await ack();
>   const res = await client.views.open({
>     trigger_id: body.trigger_id,
>     view: {
>       "type": "modal",
>       "title": {
>         "type": "plain_text",
>         "text": "Workplace check-in"
>       },
>       "close": {
>         "type": "plain_text",
>         "text": "Cancel"
>       },
>       "blocks": [
>         {
>           "type": "section",
>           "text": {
>             "type": "plain_text",
>             "text": ":man-biking: Now loading..."
>           }
>         }
>       ]
>     }
>   });
>   const viewId = res.view.id;
>   await new Promise(r => setTimeout(r, 4000));
>   await client.views.update({
>     view_id: viewId,
>     view: {
>       "type": "modal",
>       "callback_id": "your-callback-id",
>       "submit": {
>         "type": "plain_text",
>         "text": "Submit"
>       },
>       "close": {
>         "type": "plain_text",
>         "text": "Cancel"
>       },
>       "title": {
>         "type": "plain_text",
>         "text": "Workplace check-in"
>       },
>       "blocks": [
>         {
>           "type": "input",
>           "element": {
>             "type": "plain_text_input",
>             "action_id": "plain_text_input-action"
>           },
>           "label": {
>             "type": "plain_text",
>             "text": "Let us know your thoughts!",
>             "emoji": true
>           }
>         }
>       ]    
>     }
>   })
> });
> ```

@seratch this has been a very helpful post. I have a follow up question -- how does Bolt (or any Python client) proactively close the intermediate screen? 

For example, I launched a thread that carries the `view_id` of the intermediate modal view (`":man-biking: Now loading..."`). The thread failed and now I want to close all the views and print error in text/DM. Is there a way to achieve this? Or we always need user interaction to close views? Thanks

**Comment by srajiang** [comment]
Hi @bingwu-chime - hope you don't mind me chiming in here, as @seratch is OOO currently!

There isn't currently a way to close views via API without user interaction. You could use `views.update` however to prompt the user to close the modal in the event of an error however, in the same way that you display the application state when loading. 

For the full list of methods available, here's the [reference page](https://api.slack.com/methods), in case that's useful to you as well.

**Comment by pnedelko** [comment]
I faced the same problem in AWS lambda environment, lambda logs showed ~200ms request time (I just open a modal immediately, no DB requests, etc.) and I was wondering WTF?!?!

The problem was, that I'm giving the `processBeforeResponse: true` param to the `app` instance, and not to the `ExpressReceiver` instance. When you are using a non-default receiver this param on the `app` instance is ignored.

Hope this will save you time, my dear comment reader.
