### ISSUE TITLE
web-api token should be passed in header instead of body param

### ISSUE THREAD

**Issue by stevengill** [slackapi/node-slack-sdk#1132]
### Description

Slack's api is dropping support in Feb 2021 for `token` to be passed in as a body param. We should update web-api to always pass in token via header

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`

**Comment by seratch** [comment]
@stevengill I think it's great to always use Authorization header (Python & Java SDKs do so). But, just to clarify here, it's fine to use POST body params. The only thing we no longer recommend is to use querystrings.

> Instead, apps must send tokens in the Authorization HTTP header or alternatively as a URL-encoded POST body parameter.
https://api.slack.com/changelog/2020-11-no-more-tokens-in-querystrings-for-newly-created-apps

**Comment by stevengill** [comment]
ooo thanks @seratch! good to know. Still worth moving to using Authorization Header since it is needed for other token types (app Token)

**Comment by danhsiung** [comment]
I'm having an issue with this for `apps.event.authorizations.list`.  I haven't been able to get a successful response unless the token is in the authorization header.

In my sample code:

const { WebClient } = require("@slack/web-api");
const web = new WebClient();
async function get_auths(token, event_context) {
  try {
    return await web.apps.event.authorizations.list({ token, event_context });
  } catch (err) {
    console.log(err);
  }
}
Calling get_auths("MY_APP_TOKEN", "EVENT_CONTEXT") always returns an error for me:
{ Error: An API error occurred: invalid_auth at Object.platformErrorFromResult (/Users/dan/tmp/slack/node_modules/@slack/web-api/dist/errors.js:51:33) at WebClient.apiCall (/Users/dan/tmp/slack/node_modules/@slack/web-api/dist/WebClient.js:156:28) at process._tickCallback (internal/process/next_tick.js:68:7) code: 'slack_webapi_platform_error', data: { ok: false, error: 'invalid_auth', response_metadata: {} } }

I'm able to get it working with curl:
curl 'https://slack.com/api/apps.event.authorizations.list' -H 'authorization: Bearer MY_APP_TOKEN' -H 'content-type: application/json; charset=UTF-8' -H 'accept: application/json' --data-raw '{"event_context":"EVENT_CONTEXT"}'

The curl doesn't work if I add the token to the JSON payload, but don't pass the authorization header.

Looking through the source code, I don't see the authorization header getting added anywhere in WebClient, but the API seems to require it, even though the documentation states "Tokens should be passed as an HTTP Authorization header or alternatively, as a POST parameter".

I can assemble my own HTTP calls to get this working in my code, but it would be nice to just use this SDK.

**Comment by filmaj** [comment]
Talking with @stevengill, need to make sure [this code in socket mode client](https://github.com/slackapi/node-slack-sdk/blob/main/packages/socket-mode/src/SocketModeClient.ts#L359-L364) continue to work
