### ISSUE TITLE
web-api is missing auth.teams.list

### ISSUE THREAD

**Issue by daveagill** [slackapi/node-slack-sdk#1137]
### Description

The web-api package is missing a binding for https://api.slack.com/methods/auth.teams.list

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

- [x] `@slack/web-api`

**Comment by seratch** [comment]
Thanks for taking the time to report this. You're right. The endpoint is not yet supported in the package. We need to add the method to https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%405.14.0/packages/web-api/src/methods.ts#L180-L183

**Comment by stevengill** [comment]
Thanks for reporting @daveagill. This will be in the next release!
