### ISSUE TITLE
GitHub Actions CI is missing Node 10

### ISSUE THREAD

**Issue by stevengill** [slackapi/node-slack-sdk#1138]
### Description

We are having an issue with `rewiremock` and Node 10. We need to investigate and fix this issue so we can add Node v10 back to the testing matrix. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] testing related

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
We dropped Node 10 support since v6.x. Let close this issue.

>To migrate to the latest packages, updating your minimum Node.js to 12.13.0 is all that is required
https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6

Also, the requirements part in the top page is outdated. I will send a pull request fixing the error in documents.

>Requirements
>This package supports Node v8 LTS and higher. It’s highly recommended to use the latest LTS version of node, and the documentation is written using syntax and features from that version.
https://slack.dev/node-slack-sdk/
