### ISSUE TITLE
publish Axios version update

### ISSUE THREAD

**Issue by jassdv** [slackapi/node-slack-sdk#1142]
### Description
I noticed you updated axios version in web-api package.json. When would that be published?
It is currently blocking our security audit and we were hoping to know the timeframe for this update.
reference:
https://github.com/slackapi/node-slack-sdk/commit/2e9ad5804709c9548342d0da967b4ef706994729

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by sjbeatle** [comment]
This at least affects `@slack/webhooks`, as well.
<img src='https://user-images.githubusercontent.com/7853451/103678961-3761c900-4f52-11eb-83f3-161c987a4374.png' width='500' />

**Comment by stevengill** [comment]
Going out today!

**Comment by sjbeatle** [comment]
@stevengill Now that the latest `@slack/webhook` and `@slack/web-api` are published... looks like other packages that depend on them, such as `@slack/client` also need to be updates and published.

**Comment by stevengill** [comment]
@sjbeatle `@slack/client` doesn't need a new version published as it specifies a range for both `@slack/webhook` and `@slack/web-api`. You would just need to delete your local `package-lock.json` and `node_modules` directory and run `npm install` to get the latest versions. 

Ranges specified in `@slack/client`:
```
    "@slack/web-api": "^5.3.0",
    "@slack/webhook": "^5.0.2"
```

Closing this issue since the releases are live now
