### ISSUE TITLE
invalid_auth error for apps.event.authorizations.list using an appToken with correct scope

### ISSUE THREAD

**Issue by nivo33** [slackapi/node-slack-sdk#1149]
### Description

When making a call like so: 
```
import { WebClient } from '@slack/web-api';

const token = process.env.SLACK_APP_TOKEN;
const appLevelToken = process.env.SLACK_APP_LEVEL_TOKEN

const client = new WebClient(token, {
      logLevel: IS_LOCAL && LogLevel.DEBUG,
    });

    const authorizations = await client.apps.event.authorizations.list({
      token: appLevelToken,
      event_context: someEventContextId,
    })
```

I receive the following error:

```
{
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'invalid_auth', response_metadata: {} }
}
```

I have tried creating a new token twice, and reinstalling my app in the workspace, yet the error keeps returning, the token is generated as described here:
https://api.slack.com/methods/apps.event.authorizations.list

Any idea why this is happening?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---
#### Packages:

- [X] `@slack/web-api`

**Comment by stevengill** [comment]
Hey @nivo33,

Pretty sure this is related to https://github.com/slackapi/node-slack-sdk/issues/1132. Until that is resolved, you need to pass appToken in the header. Example:

```
    const client = new WebClient('', {
      logLevel: LogLevel.DEBUG,
      headers: { Authorization: `Bearer ${appLevelToken}` },
    });
```

Let me know if that works for you

**Comment by nivo33** [comment]
@stevengill Works, perfect! Thanks
