### ISSUE TITLE
Socket mode is slower than RTM API

### ISSUE THREAD

**Issue by KhushrajRathod** [slackapi/node-slack-sdk#1159]
### Description

I was eagerly awaiting socket mode since I need the speed of WebSockets and I wanted to migrate my RTM API apps over. However, it seems the RTM API is much faster than socket mode and that socket mode is almost as slow as the HTTP events API. Is this intended behaviour? Am I missing something? Thanks

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 1.0.0

node version: 15.0.1

OS version(s): macOS 11.1

#### Steps to reproduce:

1. Test speed of message event with RTM API
2. Test speed of message event with Socket Mode
3. See difference

#### Expected result:

Socket mode is as fast as the RTM API since it uses WebSockets

#### Actual result:

Socket mode is much slower than RTM API and almost as slow as the HTTP Events API

**Comment by seratch** [comment]
Unlike RTM, Socket Mode uses the same processing pipelines as our HTTP events such as the Events API and App Interactivity features. This means that events through Socket Mode will be more consistent with the rest of our platform in terms of delivery rules and payload shapes. Also, they will be processed at the same speed as what you expect from our HTTP features.

**Comment by yardensachs** [comment]
This is the only reason we can't leave RTM. Instead of instant response - we get a 1 - 3+ second delay.

I am sure there must be a way to solve for this.

**Comment by binwiederhier** [comment]
Same here. There is a significant delay in delivery of events in socketmode.

**Comment by MrHamel** [comment]
I am also experiencing this issue as well, when comparing RTM and socket mode side by side with nearly the same code behind it.

**Comment by ankur-doshi** [comment]
@seratch is this resolved? We are also facing similar issue in our slackbot while using socket mode. Or are there any parameters that can be adjust to reduce this delay?

**Comment by sonnd08** [comment]
I'm working to write a chat bot and yes, sometime socket event is very slow. Any news on this?
