### ISSUE TITLE
How do use @slack/oauth without a bot?

### ISSUE THREAD

**Issue by MoSattler** [slackapi/node-slack-sdk#1166]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Generating an url like this
```typescript
  const url = await installer.generateInstallUrl({
    redirectUri,
    scopes: ["users:read", "users:read.email"],
  });
```
results in an URL that only works, if the app has a bot - even if a bot is not required for the use case.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 2.0.1

node version: 15.7.0

#### Steps to reproduce:

Try executing oauth with a non-bot slack app.

#### Expected result:

Be able to execute the oauth flow without a bot

#### Actual result:

Error message:
```
my_org doesn’t have a bot user to install

This app is requesting permission to install a bot on your workspace, but it’s not currently configured with a bot. Please contact the developer to resolve this issue.
```

#### Attachments:
![Screenshot from 2021-01-30 18-17-27](https://user-images.githubusercontent.com/64152453/106363193-6be55c80-6327-11eb-855f-dfd9c4fd62ac.png)

**Comment by marks** [comment]
It sounds like your app has no **bot** token scopes and only **user** token scopes. Try switching `scopes: ` to `user_scopes`.

Typically its best to use bot token scopes instead of user token scopes, as mentioned in the docs [here](https://api.slack.com/authentication/basics#scopes) but you might have good reason not to, too :) 

Hope this helps!

**Comment by MoSattler** [comment]
@marks sure enough, that was it! Thanks a bunch!
