### ISSUE TITLE
callback_id constraint does not work with block_actions requests in modals

### ISSUE THREAD

**Issue by davidalpert** [slackapi/node-slack-sdk#1170]
### Description

Handler constraints don't seem to match properly in the options callbacks.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

When I try to register an options call with constraints:

```js
slackInteractions.options({ within: 'dialog', callbackId: 'model_name', actionId: 'person_selected' }, (payload) => { /* ... */ });
```

I get a dispatch error logged as:
```
 2021-02-03T19:58:00.903Z @slack/interactive-messages:http-handler Parsing raw request
 2021-02-03T19:58:00.904Z @slack/interactive-messages:http-handler request signing verification success
 2021-02-03T19:58:00.906Z @slack/interactive-messages:adapter dispatch could not find a handler
 ```
 
This appears to come from [this line of code](https://github.com/slackapi/node-slack-sdk/blob/%40slack%2Finteractive-messages%401.7.1/packages/interactive-messages/src/adapter.ts#L489-L492) as in an `options` callback the type I'm getting is `block_suggestion` and the `callback_id` is under `payload.view.callback_id` not directly on the `payload` so I suspect that my configured `callbackId` constraint is failing as it's not being read properly from the options callback payload.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: `1.7.1` (though this code doesn't seem to have changed between `1.7.1` and latest `2.0.0`)

node version: `14.15`

OS version(s): `node:14.15-alpine`

#### Steps to reproduce:

1. as above, register an options handler with `callbackId` constraint
2. open a dialog and generate an options callback

#### Expected result:

- expect the constraints to match and my callback handler to fire

#### Actual result:

```
@slack/interactive-messages:adapter dispatch could not find a handler
 2021-02-03T19:58:00.906Z @slack/interactive-messages:adapter dispatch could not find a handler
 2021-02-03T19:58:00.907Z @slack/interactive-messages:adapter {
   payload: {
     type: 'block_suggestion',
     user: { ...  },
     container: { type: 'view', view_id: '...' },
     api_app_id: '...',
     token: '...',
     action_id: 'person_selected',
     block_id: 'person',
     value: 'chr',
     team: { ... },
     enterprise: null,
     is_enterprise_install: false,
     view: {
       id: '...',
       team_id: '...',
       type: 'modal',
       blocks: [Array],
       callback_id: 'model_name',
       state: [Object],
       hash: ' .... ',
       title: [Object],
       clear_on_close: false,
       notify_on_close: false,
       close: [Object],
       submit: [Object],
       previous_view_id: null,
       root_view_id: '...',
       app_id: '...',
       external_id: '',
       app_installed_team_id: '...',
       bot_id: '...'
     }
   }
 }
```

**Comment by seratch** [comment]
Hi @davidalpert , thanks for asking the question!

For handling events in a modal, you can use `within: 'block_actions'` as the interaction is happening in a [block](https://api.slack.com/block-kit). `within: 'dialog'` is supposed to be used for another (old) feature - dialogs https://api.slack.com/dialogs

**Comment by davidalpert** [comment]
I probably copy/pasta'd that code sample off the docs. in my code I have used `within: 'block_actions'` but seen the same behaviour.

when I add a `callbackId` constraint it doesn't match.

**Comment by seratch** [comment]
@davidalpert The callback_id constraint is available only for view_submission / view_closed requests in this package. https://github.com/slackapi/node-slack-sdk/blob/%40slack/interactive-messages%402.0.0/packages/interactive-messages/src/adapter.ts#L485-L500

Please consider using a unique identifier for the action_id for each modal.

**Comment by davidalpert** [comment]
is the documentation wrong?
![image](https://user-images.githubusercontent.com/43332/107164175-78933180-6973-11eb-8c6a-b3917b063901.png)

**Comment by davidalpert** [comment]
in fact, the code suggests that it attempts to validate `callback_id` on all callbacks, as per the documentation, but only looks for it as a `view` property on `viewSubmission()` and `viewClosed()` hence why I suspect this is a bug.

**Comment by seratch** [comment]
Oh, thanks for pointing this out (sorry for overlooking your comment before my comment - somehow the comment was not loaded for me). As long as the document says so, I call it an obvious bug.

**Comment by misscoded** [comment]
Hi @davidalpert! Thanks once again for bringing this to our attention! Community involvement is incredibly important to us and our tools only become better with input and insight like that of which you've provided here. 🙂 

Unfortunately, a fix will not be introduced for this issue. `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
