### ISSUE TITLE
type definition of ChatPostMessageArguments has incorrect property

### ISSUE THREAD

**Issue by kentac55** [slackapi/node-slack-sdk#1172]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Type definition of [ChatPostMessageArguments](https://github.com/slackapi/node-slack-sdk/blob/a90787ea80185d198e7b508e20ce69ccefc34033/packages/web-api/src/methods.ts#L964) has `message` as required property but in [slack api doc](https://api.slack.com/methods/chat.postMessage#arg_text),  as optional property.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.0.0

node version: 14.15.4

OS version(s): Linux 5.10.14-arch1-1 SMP PREEMPT Sun, 07 Feb 2021 22:42:17 +0000 x86_64 GNU/Linux

#### Steps to reproduce:

1. write code as below

    ```typescript
    webClient.chat.postMessage({
      channel: 'C0BQ8GW78',
      blocks: [
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text:
              "Hello, Assistant to the Regional Manager Dwight! *Michael Scott* wants to know where you'd like to take the Paper Company investors to dinner tonight.\n\n *Please select a restaurant:*",
          },
        },
      ],
    })
    ```

2. run tsc
3. got error

    ```
    src/index.ts:105:28 - error TS2345: Argument of type '{ channel: string; blocks: { type: "section"; text: { type: "mrkdwn"; text: string; }; }[]; }' is not assignable to parameter of type 'ChatPostMessageArguments'.
      Property 'text' is missing in type '{ channel: string; blocks: { type: "section"; text: { type: "mrkdwn"; text: string; }; }[]; }' but required in type 'ChatPostMessageArguments'.
    ```

#### Expected result:

No error occured.

#### Actual result:

Compile failed.

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by Stono** [comment]
+1 to this, getting hit by it now!

**Comment by seratch** [comment]
Thanks for taking the time to write in and we are sorry for our slow response here.

We had a discussion on this issue in the past: https://github.com/slackapi/node-slack-sdk/pull/853

The outcome of the discussion in the issue was that we can loosen the limit (in this library) if we add warning log output for the missing text field: https://github.com/slackapi/node-slack-sdk/issues/1128

We've already implemented the warning message in Python SDK and Java SDK:
* https://github.com/slackapi/python-slack-sdk/pull/910
* https://github.com/slackapi/java-slack-sdk/pull/657

We would like to have a similar one in this Node SDK too. If you are interested in implementing the warning, it'd be greatly appreciated.

**Comment by kentac55** [comment]
I'm sorry for my poor search skills. :bow:
I see. I'll work on its implementation 💪
