### ISSUE TITLE
Reading changelog for one package is hard

### ISSUE THREAD

**Issue by IchordeDionysos** [slackapi/node-slack-sdk#1179]
### Description

When faced with updates from one version to the next it’s important to look at the changes between the version and as I see you are treating this with the proper care.

However, the Github UI does not help here a lot to understand the changes for one package like `@slack/web-api` as there are 7 other package changelogs mixed up with the change for the package you currently care about.

This is the UI one has to go through to see the changes to the packages:
<img width="645" alt="Screenshot 2021-02-15 at 19 07 18" src="https://user-images.githubusercontent.com/10195482/107980806-2da39a80-6fc1-11eb-95ac-42b251ef4ea1.png">

It would be easier to have one list where you can see all the changes for one package.

### What type of issue is this?
- [x] documentation related

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Thanks for taking the time to send this feedback! I agree that it's not so easy to scan releases with the GitHub UI. We can easily get the list of releases by utilizing https://api.github.com/repos/slackapi/node-slack-sdk/releases 

This is just my two cents but building a nice web page that enables visitors to filter by modules and/or major/minor versions in https://slack.dev/node-slack-sdk/ should be useful. What do you think? > other maintainers

**Comment by mksmzpsv** [comment]
Hello, @seratch!
If this improvement is still actual, I can work on it.
I played around on my local, and I think I can add a simple filter (by package and version) on the Changelog page at [https://slack.dev/node-slack-sdk/](https://slack.dev/node-slack-sdk/).
Could you please assign it to me?

**Comment by filmaj** [comment]
I do not think this is a problem anymore, I changed the release note generation documentation to scope changes to a single package (see [this commit](https://github.com/slackapi/node-slack-sdk/commit/c32414cadd3804cfaa53338737af2edffcb53704)). Closing this.

**Comment by mksmzpsv** [comment]
Okay, I see. 
I implemented a filter for the Changelog page (see attached image), and if this filter is needed in the future, I have a branch with implementation in my fork.
Thank you for the updates!
<img width="1436" alt="Screenshot 2024-01-15 at 19 22 44" src="https://github.com/slackapi/node-slack-sdk/assets/13748477/8824d4e5-0dae-45a4-84ab-b7fc0dba7904">

**Comment by IchordeDionysos** [comment]
@mksmzpsv that would be amazing 😍

**Comment by zimeg** [comment]
👋 We've started appending to a `CHANGELOG.md` for each package to help with updates across multiple releases!

📚 https://github.com/slackapi/node-slack-sdk/blob/d5fc19063358f51b1bbb7f5dae3155e72c14f694/packages/web-api/CHANGELOG.md

**Comment by IchordeDionysos** [comment]
So nice thanks! 😍
