### ISSUE TITLE
404 when receiving workflow_step_edit payload

### ISSUE THREAD

**Issue by priyankakodali19** [slackapi/node-slack-sdk#1182]
### Description

We are trying to create our own custom workflow step for our app. We get a 404 when trying to receive the `workflow_step_edit` payload. 
This seems to be because of a bug on this [line](https://github.com/slackapi/node-slack-sdk/blob/2e5705f4bf36f08eea8bec601d78657d25e227c2/packages/interactive-messages/src/adapter.ts#L505) where there is a check to see if the payload contains `actions` or `submission` or `message` object. But the workflow payload contains neither of them and instead contains `workflow_step` object. As a result we get 404 because of this bug. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: "2.0.0"

node version: 14.15.0

OS version(s): macos 10.15.7

#### Steps to reproduce:

1. Created a custom workflow step in our app 
![image](https://user-images.githubusercontent.com/22124247/109672929-22ad4600-7b3b-11eb-9991-6dbd2ea77214.png)

2. Try to add this step to your workflow

#### Expected result:

App receives the `workflow_step_edit` payload with a 200. This is our

#### Actual result:

The app receives a 404 for the payload of type `workflow_step_edit`. 

By changing this [line](https://github.com/slackapi/node-slack-sdk/blob/2e5705f4bf36f08eea8bec601d78657d25e227c2/packages/interactive-messages/src/adapter.ts#L505) to include a check for `workflow_step` object we were able to get the right response without 404
![image](https://user-images.githubusercontent.com/22124247/109672680-de21aa80-7b3a-11eb-9602-aa75a7de34cc.png)

**Comment by stevengill** [comment]
Hey @priyankakodali19,

@slack/interactive-messages doesn't currently support `workflow_step_edit` and we don't plan on adding support for it. We officially deprecated this package on January 12th. We are encouraging developers to migrate over to Bolt-Js. See our [migration guide](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6#deprecating-slackevents-api--slackinteractive-messages) for more information.

**Comment by misscoded** [comment]
We are going to close this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
