### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by onedebos** [slackapi/node-slack-sdk#1183]
### Description

I keep getting a syntax error when following the `@slack/events-api` example. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 3.0.0

node version: 14.5.1

OS version(s): macOS

#### Steps to reproduce:

1. Call a registered slash command from inside a Slack channel in development mode using ngrok as proxy to a registered request URL. 
2. I've verified my request URL using my signing secret
3.

#### Expected result:

What you expected to happen
Log out a value to my console.

#### Actual result:
I keep getting this error from slackEvents.on('error)
```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at /Users/adebola/Documents/aeeiee-bot/node_modules/@slack/events-api/dist/http-handler.js:180:33
```
What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
Hi @onedebos! Can you provide us with a bit more information -- do you mean [this](https://github.com/slackapi/node-slack-sdk#listening-for-an-event-with-the-events-api) example? Is the code you're trying to run exactly as written, or have you altered it at all? If so, can you also provide that?

**Comment by onedebos** [comment]
I eventually ended up using the Bolt library. That solved my problem.
