### ISSUE TITLE
[oauth] Add "installOptions" as argument to "storeInstallation" call?

### ISSUE THREAD

**Issue by Bazze** [slackapi/node-slack-sdk#1185]
### Description

I'm currently facing difficulties storing the token from the oauth process using the @slack/oauth "installationStore" functionality. The problem is that when saving the `installation` in our db (using `storeInstallation`) we want to properly relate this data to a specific customer account. We pass the customer account info in the "metadata" and it's available in the `installOptions` which is currently NOT being passed into the [`storeInstallation` call](https://github.com/slackapi/node-slack-sdk/blob/main/packages/oauth/src/index.ts#L341). Why is that and would you consider a PR for changing this and also passing the `installOptions`? 

(In the [success callback](https://github.com/slackapi/node-slack-sdk/blob/main/packages/oauth/src/index.ts#L347) it is supplied as an argument, so I'm thinking I'll try as a workaround to just set `storeInstallation` to a function that returns a resolved promise and then do my storing in the success callback instead.)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Hey @Bazze,

This is a very reasonable request. I agree we should add `metadata` to installation, or offer a different way to extend the installation object. I've marked this as a enhancement for now.

**Comment by seratch** [comment]
`team_id`, `scopes`, and `user_scopes` in `InstallURLOptions` are already in the installation data too. I don't think there are possible use cases where developers need to know `redirect_uri` when storing an installation. 

For this reason, I think we can simply have metadata as an optional value in Installation interface data. Here is a pull request resolving this issue: https://github.com/slackapi/node-slack-sdk/pull/1187
