### ISSUE TITLE
Improve error messaging of OAuth flow when user cancels

### ISSUE THREAD

**Issue by misscoded** [slackapi/node-slack-sdk#1186]
### Description

Brought to our attention in [#824](https://github.com/slackapi/bolt-js/issues/824) of the `bolt-js` repo, the error message surfaced when a user selects **Cancel** during the OAuth flow does not adequately indicate what has occurred and instead cites `redirect url is missing state or code query parameters` with an error code of `slack_oauth_missing_state`.

The [logic](https://github.com/slackapi/node-slack-sdk/blob/%40slack/oauth%402.0.1/packages/oauth/src/index.ts#L217) in the `@slack/oauth` package should be adjusted to accommodate, as the `MissingStateError` is not reflective of this use case. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
@misscoded how do you envision a proper solution to this issue to look like? Perhaps explicitly catching the `error=access_denied` querystring parameter and throwing a different error (and if so, which error should it throw)?

**Comment by misscoded** [comment]
> how do you envision a proper solution to this issue to look like? Perhaps explicitly catching the error=access_denied querystring parameter and throwing a different error (and if so, which error should it throw)?

@filmaj That's what I was also thinking. Without looking at the errors currently at our disposal, either reaching for one that suits this case or creating a new one specific to this.
