### ISSUE TITLE
Add `admin.analytics.getFile` API support

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#1191]
### Description

https://api.slack.com/methods/admin.analytics.getFile is not yet supported in this SDK. 

For the implementation, we should be aware that this endpoint is a bit different from others. The response body can be gzipped binary data for successful response. If the response has an error code, the server-side returns text JSON data instead.

See also:
* https://github.com/slackapi/java-slack-sdk/pull/602
* https://github.com/slackapi/python-slack-sdk/pull/865

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AdriannaBeck** [comment]
Hello, is there any estimate of when this feature may be available?

**Comment by seratch** [comment]
Fixed by #1515
