### ISSUE TITLE
Update issue templates under .github

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#1199]
### Description

Like other projects such as python-slack-sdk, bolt-python, and java-slack-sdk, we may want to have multiple issue templates per category

Example: https://github.com/slackapi/python-slack-sdk/tree/main/.github/ISSUE_TEMPLATE

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by srajiang** [comment]
@seratch - I see the `discussion` tag on here, but I don't see any reason why we shouldn't set this up, since it is the recommended format now for issues.

**Comment by seratch** [comment]
> I see the discussion tag on here, but I don't see any reason why we shouldn't set this up

@srajiang The only reason I set the tag was that I wanted to have inputs from others if there are any. Thanks for working on this! will check the PR now
