### ISSUE TITLE
Are slash commands currently supported by the SDK?

### ISSUE THREAD

**Issue by MartinListwan** [slackapi/node-slack-sdk#1201]
### Description
Is there documentation on the correct way of supporting slash commands with the slack SDK? I've read the bug from 2017 that says it's not supported but I wanted to know if anything has changed.

I mainly want to avoid having to do the message verification myself.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] I don't know

**Comment by seratch** [comment]
Hi @MartinListwan, thanks for asking the question!

The currently recommended way for handling slash command requests is to use [the Bolt for JS library](https://github.com/slackapi/bolt-js). Refer to https://slack.dev/bolt-js/concepts#commands for details.

**Comment by seratch** [comment]
Hi @MartinListwan, let us know if you need further help 👋 I will close this issue after waiting for your response for a few more business days.
