### ISSUE TITLE
Angular App will not build after installing @slack/web-api@6.1.0

### ISSUE THREAD

**Issue by patrickriles** [slackapi/node-slack-sdk#1207]
### Description

Hi guys, I'm attempting to use @slack/web-api in an Angular 9.0.0 project but am getting the follow error upon running npm run build for the project:

`
ERROR in ./node_modules/@slack/web-api/dist/instrument.js
Module not found: Error: Can't resolve 'os' in '/Users/priles/IdeaProjects/gns-howser-sos-assistant/node_modules/@slack/web-api/dist'
`

I've looked everywhere for a solution to this but nothing has worked and there has been very limited related issues either.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: @slack/web-api@6.1.0

node version: v14.12.0

OS version(s): macOS Big Sur 11.2.3

#### Steps to reproduce:

1. Install @slack/web-api using steps found here https://slack.dev/node-slack-sdk/web-api
2. Run npm run build
3. Build fails with error above

#### Expected result:

The build to complete and my Angular App to run successfully

#### Actual result:

The App does not build correctly I am unable to load anything

**Comment by mwbrooks** [comment]
Hey @patrickriles, 👋🏻 Sorry to hear that you're running into an issue with the Angular 9.0.0 and `@slack/web-api@6.1.0`.

Thanks for the steps to reproduce your issue. I installed node `v14.12.0` and ran a few of my example apps. I wasn't able to reproduce your issue. So, maybe it's something more specific to your Angular project.

**A few questions that might help us think through the problem:**
1. When did the error occur? When you upgraded Angular, `@slack/web-api@6.1.0`, or made some build-chain changes?
1. What were the previous versions the worked correctly?
1. A quick Google around shows that ["Can't resolve 'os'"](https://stackoverflow.com/questions/60767615/cant-resolve-os) in Angular projects is often related to Webpack not using the appropriate shim
    * I checked and the [`os` module in `instrument.ts` has been used for over 2 years now](https://github.com/slackapi/node-slack-sdk/blame/67a2a5feaf25b6ebbf1b30ba36655a0185d5f144/packages/webhook/src/instrument.ts)
1. Super silly, but some people have solved this by deleting their `node_modules/` directory

**Comment by patrickriles** [comment]
Thanks for the quick response @mwbrooks! The application was just created a couple days ago and this is my first attempt at installing the web-api or any other slack packages. I tried the quick and easy delete node_modules and npm install but had no luck. Is there anything I can show you to help figure out why it wouldn't be working?

**Comment by mwbrooks** [comment]
> Thanks for the quick response @mwbrooks! The application was just created a couple days ago and this is my first attempt at installing the web-api or any other slack packages. I tried the quick and easy delete node_modules and npm install but had no luck. Is there anything I can show you to help figure out why it wouldn't be working?

Thanks for the response! Well, it makes life easier to recreate the issue if it's a brand new project :)

Our team isn't as familiar with Angular (especially the latest and greatest version). Any chance that you could provide some high-level steps to reproduce how you set up your project? I'll try to follow them to recreate the issue!

**Comment by patrickriles** [comment]
Yeah I can try to do that, my company actually has a sort of build framework that creates new projects off of a template. I can send you a repo for the template to give it a try.

Template repo: https://github.com/patrickriles/angular-template/tree/master

**Comment by patrickriles** [comment]
Then once you get it running you can try to install the web-api and see if npm run build returns you the same error.

**Comment by patrickriles** [comment]
@mwbrooks You also have to import it to the project for the error to appear.

**Comment by patrickriles** [comment]
@mwbrooks 

By removing this line from instrument.ts:

![image](https://user-images.githubusercontent.com/32268343/114919128-3f0cf580-9dfe-11eb-9631-412ad5ee14bb.png)


and adding this to package.json:

![image](https://user-images.githubusercontent.com/32268343/114919186-4e8c3e80-9dfe-11eb-810d-6b4299046cde.png)


I was able to make it work. Obviously this is not a proper solution to the problem but is there anything you take from that involving the origin of the issue?

**Comment by seratch** [comment]
@patrickriles We rely on [the standard Node module](https://nodejs.org/api/os.html) to learn what operating system the user agent uses. For your use case (perhaps, running in a web browser?), I would recommend adding the `os` npm package as a workaround. As this is a Node SDK, we don't try to stop depending on the standard Node modules including this one.

It seems that everything is now clear. Would you mind closing this issue?
