### ISSUE TITLE
RTM API returns missing_scope

### ISSUE THREAD

**Issue by dnlmzw** [slackapi/node-slack-sdk#1211]
### Description

I want to retrieve every users online status. It's not available through the Events API so I'm using RTM, with a classic Slack app (since granular bot permissions doesn't allow for this).

However, even when trying to start my client, I get an error: `[INFO]  rtm-api:RTMClient:119 unable to RTM start: An API error occurred: missing_scope`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Not able to start RTMClient

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:
@slack/rtm-api": "^6.0.0"

node version:
v12.16.3

OS version(s):
MacOS Catalina 10.15.7

#### Steps to reproduce:
```
const app = require('express')()

app.get('/slack', (req, res) => {
  console.log('Slack API endpoint hit')

  const { RTMClient } = require('@slack/rtm-api')
  const token =
    'xoxp-[token-secret-here]'
  const rtm = new RTMClient(token)

  ;(async () => {
    await rtm.start()
  })()
})

module.exports = app
```
#### Expected result:

Ability to start up the server.

#### Actual result:

It returns an error.

#### Attachments:
![Skærmbillede 2021-04-19 kl  12 27 49](https://user-images.githubusercontent.com/960055/115222851-771c7d00-a10b-11eb-9ff5-ec137c2b3aff.png)

**Comment by seratch** [comment]
Hi @dnlmzw, thanks for asking the question!

I know this is a bit confusing but adding a bot user for your classic app is the way to enable your bot token. Then, use the bot token starting with `xoxb-`, not a user token, which starts with `xoxp-`.

To do this, go to "App Home" page, click "Add Legacy Bot User" button,

<img width="500" src="https://user-images.githubusercontent.com/19658/115233287-aa362f00-a152-11eb-8bd2-14551b7774f1.png"><img width="500" src="https://user-images.githubusercontent.com/19658/115233295-ad311f80-a152-11eb-89b9-a058a3e6042b.png">

and then, reinstall your app. You will get two types of tokens. Use the one starting with `xoxb-`.

**Comment by dnlmzw** [comment]
I had already added the bot, but I was missing the re-install. This helped — Thanks :)
