### ISSUE TITLE
6.2.0-rc.0 is published under `latest` tag

### ISSUE THREAD

**Issue by Hypnosphi** [slackapi/node-slack-sdk#1212]
That's probably a mistake

```
% npm info @slack/web-api version  
6.2.0-rc.0
```

It means that `npm install @slack/web-api` will install the unstable version

**Comment by mwbrooks** [comment]
Hey @Hypnosphi 🙇🏻 Thank you for reporting this!

I think it was a mistake as well. I'm checking with our maintainers and then we'll update `latest › 6.1.0`.

**Comment by mwbrooks** [comment]
Alright, I've confirmed that this was our mistake. We've now updated `latest › 6.1.0` so that no one downloads the release candidate. Anyone who wants to opt-in to using the latest and greatest can directly install `6.2.0-rc.0`.

Thanks for the quick catch @Hypnosphi! 🙇🏻

**Comment by seratch** [comment]
@Hypnosphi This is my bad. Thanks a lot for reporting this!
