### ISSUE TITLE
Webhook.send not sending messages

### ISSUE THREAD

**Issue by yiranzhan9** [slackapi/node-slack-sdk#1218]
### Description

I'm using the Incoming Webhooks api to post messages to a Slack channel via an AWS Lambda function. It works fine in local environment as in the unit test, but not with the lambda. Like when the lambda function is triggered, it gets to `await webhook.send()` but doesn't send the message. There's never been an error. It just doesn't post to the slack channel. Maybe something related to being in a Lambda function or being in a loop? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.0.0

node version: v12.13

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

Messages get sent.

#### Actual result:

Messages don't get sent but no errors whatsoever.

#### Attachments:

The code looks something like
```
const sendSlackMessages = (events, webhookUrl) => {
	for (let i = 0; i < events.length; i++) {
		const event = events[i];
		const skuString = event.skus.join();
		const startDate = new Date(event.start);

		(async () => {
			await webhook.send({
				text: `*Event ID:* ${event.id}\n*Live Date:* ${startDate}\n*Last Updated By:* ${event.user.id}\n*SKUs:* ${skuString}`,
			});
		})();
	}
};
```

**Comment by seratch** [comment]
Hi @yiranzhan9, 
The AWS Lambda runtime may terminate once your main function returns a response to its trigger event. For this reason, `(async () => {  await ... })();` does not work as you expect. 

Instead, you can use an async function as a lambda handler and the function can call `await webhook.send()` this way:

```js
const webhook = ...;
exports.handler =  async function(event, context) {
  await webhook.send({text: "your message"});
  return {}
}
```
Refer to AWS's official documents like https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html for details.

If you have further general questions about AWS Lambda, I'd recommend asking in the AWS community / forum. More experts can help you out there. If you don't mind, may I ask you to close this issue?

**Comment by seratch** [comment]
Let us close this issue due to inactivity. If you have something further to discuss here, please feel free to write in at any time!
