### ISSUE TITLE
Slack App open modal with trigger_id

### ISSUE THREAD

**Issue by penguinsource** [slackapi/node-slack-sdk#1219]
### Description

Hello!

I have a Slack application which is using the trigger_id to open a modal after the user interacts with a button.

- In order to actually open the modal though, I need the trigger_id and the user's access token. Can i find the access token of the user in the same payload response as the trigger_id? If that is so, where is it? I currently lookup the user by their user id in my database in order to get their access token, but too many times, the trigger_id expires by the time the database lookup operation is complete.

- I have used 2 solutions..
1. query my database using the slack user id coming from the event payload in order to get the access token. trigger_id often times expires before i can make the call to open a modal
2. encrypt access token onto the block id and decrypt it when it comes back. This has much smaller trigger_id expiry rates but I'm not sure how recommended it is and would love if there was a better way
3. The third option would be to keep a hashtable on my services of { slackUserId: slackAuthData } and update this list upon any user authenticating or un-authenticating.

Please let me know your thoughts on the best practice for this.

Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

**Comment by seratch** [comment]
Hi @penguinsource, thanks for asking the question!
 
>In order to actually open the modal though, I need the trigger_id and the user's access token.

Is there any specific reason to use a user token over a bot token here? As far as I know, I can't think of such situations. You can open a modal with a bot token, which should be already resolved before running the listener function. The `client` argument already holds the token. Also, you can access the value by `context.bot_token`.

>Can i find the access token of the user in the same payload response as the trigger_id? 
>If that is so, where is it? I currently lookup the user by their user id in my database in order to get their access token

As you may know, no tokens would be included in payloads. The right way to access tokens is, as you are already doing, to lookup the stored values in either your database or env variables.

>too many times, the trigger_id expires by the time the database lookup operation is complete.

The trigger_id expires in 3.x seconds. I think the period should be long enough even for the situations like having to run multiple queries that may take hundreds of milliseconds for each. 

How many queries are you running in a single listener execution? You can have a short-time cache layer for reducing the number of queries. However, I wonder if there may be other major contributing factors than the spent time by database interactions.

We are unsure about the details of your listener function but, if the function does other things before calling `views.open` API method, I would recommend `views.open` API before doing anything else. If you want more help from us, sharing minimum working example code demonstrating your situation is helpful.

**Comment by seratch** [comment]
Sorry, in the above response, I was assuming you are using Bolt for JavaScript although this is an issue in the node-slack-sdk repository. We've announced the deprecation of interactivity modules in this repository: https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6#deprecating-slackevents-api--slackinteractive-messages Please consider using bolt-js for new projects (and migrating existing ones if possible).

**Comment by seratch** [comment]
👋 Hi @penguinsource, let us know what you think about my above response. Also, could you write in if you have something further to ask/discuss here? I will close this issue after waiting for your response for a few more days.

**Comment by seratch** [comment]
Let me close this issue now but please feel free to write in at any time!

**Comment by penguinsource** [comment]
@seratch sorry things got a little bit busy! I really appreciate the response. 

- I am using the web API and a bot token
- The issue is on my end it seems on the db connection
- I have moved over to using views.open and then views.update - now encountering a worse issue where the views.update API response comes back as successful but the modal does not actually update in Slack - **NOT all the time** but often enough that it creates a big/noticeable problem for users. Is this the place to post this issue or somewhere else? Is there a workaround?

![image](https://user-images.githubusercontent.com/2596623/118324480-1bf26600-b4d0-11eb-9518-06198d5e7b4e.png)
![image](https://user-images.githubusercontent.com/2596623/118324492-21e84700-b4d0-11eb-8ebc-a8b80172ab7d.png)
![image](https://user-images.githubusercontent.com/2596623/118324535-2f9dcc80-b4d0-11eb-9caf-026b888dc0a9.png)
