### ISSUE TITLE
`ViewsOpenResponse` type is incorrect

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1235]
### Description

the type is defined as 

```ts
export declare type ViewsOpenResponse = WebAPICallResult & {
    ok?: boolean;
    error?: string;
    response_metadata?: ResponseMetadata;
    needed?: string;
    provided?: string;
};
```

however in actuality, it has an additional `view` property. Here is an example opened view response:

```json
{
   "ok":true,
   "view":{
      "id":"V021U522M6G",
      "team_id":"OMITTED",
      "type":"modal",
      "blocks":[
         {
            "type":"section",
            "block_id":"JtAZ+",
            "text":{
               "type":"mrkdwn",
               "text":"Loading...",
               "verbatim":false
            }
         }
      ],
      "private_metadata":"",
      "callback_id":"CONFIRM_MESSAGE_SELECTION",
      "state":{
         "values":{
            
         }
      },
      "hash":"1620800476.cy2CiRSe",
      "title":{
         "type":"plain_text",
         "text":"Create a new issue",
         "emoji":true
      },
      "clear_on_close":false,
      "notify_on_close":false,
      "close":{
         "type":"plain_text",
         "text":"Cancel",
         "emoji":true
      },
      "submit":null,
      "previous_view_id":null,
      "root_view_id":"V021U522M6G",
      "app_id":"OMITTED",
      "external_id":"",
      "app_installed_team_id":"OMITTED",
      "bot_id":"OMITTED"
   },
   "response_metadata":{
      "scopes":[
      ]
   }
}
```

I suspect the same bug is present in other view related response types.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.2.3

node version: 12.19.0

OS version(s): N/A

#### Steps to reproduce:

1. Invoke `client.views.open(options)`

#### Expected result:

The response type corresponds to what properties actually exist. As far as I can tell, it is just missing the `view` property, which is quite important.

#### Actual result:

There is no such property defined on the interface.

**Comment by rr-codes** [comment]
Note: the `view` property is a superset of the existing `View` interface

**Comment by rr-codes** [comment]
actually, all the types are actually present in Bolt already https://github.com/slackapi/bolt-js/blob/b0d733a5721d6acf0333abab3d82d95385314edb/src/types/view/index.ts#L140

**Comment by seratch** [comment]
@rr-codes Thanks for reporting this and you're right. As all the response data types are auto-generated, we cannot reuse the hand-written one. I will look into this.
