### ISSUE TITLE
post_at as option in schedule message has the wrong type

### ISSUE THREAD

**Issue by Zummek** [slackapi/node-slack-sdk#1240]
### Description
I think `ChatScheduleMessageArguments` interface has wrong type for `post_at` property. In my opinion, it should be `number` instead of `string`.

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

As in [documentation in "code"](https://api.slack.com/methods/chat.scheduleMessage/code) section we see `post_at` as number. While `@slack/web-api` package tells me that property should be a string.
As I try to call `webClient.chat.scheduleMessage({..., post_at: <Unix Epoch timestamp as string>})` I encountered a problem in response:
```
[ERROR]  web-api:WebClient:0 must provide a number [json-pointer:/post_at]
error Error: An API error occurred: invalid_arguments
    at Object.platformErrorFromResult (C:\<project-path>\node_modules\@slack\web-api\src\errors.ts:94:5)
    at WebClient.apiCall (C:\<project-path>\node_modules\@slack\web-api\src\WebClient.ts:196:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
{
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_arguments',
    response_metadata: { messages: [Array], scopes: [Array], acceptedScopes: [Array] }
  }
}
```

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.2.3

node version: 12.18.3

OS version(s): Windows 10

**Comment by seratch** [comment]
Hi @Zummek, thanks a lot for taking the time to point the issue out. You're right that the recommended data type for `post_at` is `number`, not `string`. I just submitted a pull request #1242  fixing the issue. The fix will be included in the next release.

One thing I noticed is that actually `string` also works for `post_at` argument as long as the value is a valid integer value. I'm wondering if your input value might not be an integer value. Can you check your input data again?

```js
// This value '1621497501.644' will be rejected by the Slack server-side.
// {"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] must provide a number [json-pointer:/post_at]"]}}
const postAt = "" + (Date.now() / 1000) + 60 * 15;

// This value  '1621497501' will be accepted by the Slack server-side.
const postAt = "" + Number.parseInt((Date.now() / 1000) + 60 * 15);
```

**Comment by Zummek** [comment]
You're right, I didn't note that number should be integer. I tried to run your suggestion to round the number and of course it works fine. Thanks
