### ISSUE TITLE
Socket mode: Bolt doesn't handle WebSocket disconnections gracefully

### ISSUE THREAD

**Issue by Zenexer** [slackapi/node-slack-sdk#1243]
### Description

Bolt crashes when it loses its WebSocket connection in socket mode, and there doesn't seem to be a great way for the calling code to handle the situation.  Disconnections from an EC2 instance in us-east-1 are happening frequently enough for this to be a significant issue.  This happens even when a bot is idle.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 3.3.0

node version: 16.1.0

OS version(s): Ubuntu 20.04.2 LTS (focal)

#### Steps to reproduce:

I have a fairly simple bot in the following form:

```typescript
const app = new App({
	token: "...",
	appToken: "...",
	socketMode: true,
});

app.message(/^foobar$/, async ({ message, say, client }) => {
	// Doesn't matter what's here; it doesn't need to ever trigger for the bug to manifest
});

await app.start();
```

The crash happens if I:

1. Start the bot on an EC2 us-east-1 instance.
2. Leave it running for an arbitrary period of time--sometimes it takes an hour, sometimes a few days.
3. At some point, the WebSocket will close.  I'm not sure why, but I assume it's something on Slack's end, as the EC2 instance is left untouched.

#### Expected result:

The bot will either:

* Handle connectivity interruptions gracefully, without the need for the programmer to manually reconnect or instantiate a new `App`.
* Throw an exception or trigger an event that can be handled by the calling code in a trivial manner--one that doesn't require instantiating a new `App`.  This would probably need to be documented and demonstrated in the examples, since a socket mode Bolt bot isn't really viable without some mechanism for handling connectivity interruptions.

#### Actual result:

```
[ERROR]  socket-mode:SocketModeClient:0 failed to send message on websocket: WebSocket is not open: readyState 3 (CLOSED)
/git/slackbot/node_modules/@slack/socket-mode/dist/errors.js:29
    const error = errorWithCode(new Error(`Failed to send message on websocket: ${original.message}`), ErrorCode.WebsocketError);
                                ^

Error: Failed to send message on websocket: WebSocket is not open: readyState 3 (CLOSED)
    at Object.websocketErrorWithOriginal (/git/slackbot/node_modules/@slack/socket-mode/dist/errors.js:29:33)
    at /git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:347:48
    at sendAfterClose (/git/slackbot/node_modules/ws/lib/websocket.js:758:5)
    at WebSocket.send (/git/slackbot/node_modules/ws/lib/websocket.js:345:7)
    at /git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:344:32
    at new Promise (<anonymous>)
    at SocketModeClient.send (/git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:329:16)
    at ack (/git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:469:24)
    at App.processEvent (/git/slackbot/node_modules/@slack/bolt/dist/App.js:428:19)
    at runMicrotasks (<anonymous>) {
  code: 'slack_socket_mode_websocket_error',
  original: Error: WebSocket is not open: readyState 3 (CLOSED)
      at sendAfterClose (/git/slackbot/node_modules/ws/lib/websocket.js:754:17)
      at WebSocket.send (/git/slackbot/node_modules/ws/lib/websocket.js:345:7)
      at /git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:344:32
      at new Promise (<anonymous>)
      at SocketModeClient.send (/git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:329:16)
      at ack (/git/slackbot/node_modules/@slack/socket-mode/dist/SocketModeClient.js:469:24)
      at App.processEvent (/git/slackbot/node_modules/@slack/bolt/dist/App.js:428:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async SocketModeClient.<anonymous> (/git/slackbot/node_modules/@slack/bolt/dist/receivers/SocketModeReceiver.js:88:13)
}
```

**Comment by Zenexer** [comment]
@seratch Actually, I think this is probably both a Bolt issue and a SocketModeClient issue.

It appears to throw an error that can't be caught in a reasonable manner, since the Promise is never awaited.  Take the following code:

```typescript
try {
    await app.start();
} catch (e) {
    // ...
}
```

There's a problem with that design.  Once the client has authenticated, the Promise returned by `SocketModeClient#start` will resolve.  From that point forward, no errors can be caught, and any errors not caught by Bolt or SocketModeClient will tear down the whole Node instance.  That's what's happening here.

**Comment by seratch** [comment]
@Zenexer Thanks for your reply. 

>May I ask you to elaborate a bit more about the "crash"? Does it mean that the Node.js app process terminates? Or, while the process is still running, the app process no longer has an active Socket Mode connection plus it does not automatically recover?

So, the situation you faced is the latter one, right? It seems that `SocketModeClient` does not properly maintain its underlying WebSocket connections for some reason and it does not automatically recover. 

If my understanding is correctly, this is 100% `SocketModeClient`'s issue. The low-level module should handle the state of connections and should throw an exception if the situation is unrecoverable (say, app-level token is revoked).

**Comment by seratch** [comment]
@Zenexer Thanks, this is helpful. We'll start writing a unit test reproducing the situation.

**Comment by usubram** [comment]
I also notice connection failures lately. Here are the debug logs. App is stuck at this state until i manually intervene and do an app restart. Though stuck at this state, it is still able to receive events but eventually it errors before it reaches the code `app.event('app_mention', handler)`

```
[DEBUG]  socket-mode:SocketModeClient:0 calling ack events_api
[DEBUG]  socket-mode:SocketModeClient:0 send() in state: connected,ready
[DEBUG]  socket-mode:SocketModeClient:0 sending message on websocket: {"envelope_id":"xxx","payload":{}}
[ERROR]  socket-mode:SocketModeClient:0 failed to send message on websocket: WebSocket is not open: readyState 3 (CLOSED)
(node:18) UnhandledPromiseRejectionWarning: Error: Failed to send message on websocket: WebSocket is not open: readyState 3 (CLOSED)
    at Object.websocketErrorWithOriginal (/opt/app/node_modules/@slack/socket-mode/dist/errors.js:29:33)
    at /opt/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:347:48
    at sendAfterClose (/opt/app/node_modules/@slack/socket-mode/node_modules/ws/lib/websocket.js:768:5)
    at WebSocket.send (/opt/app/node_modules/@slack/socket-mode/node_modules/ws/lib/websocket.js:345:7)
    at /opt/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:344:32
    at new Promise (<anonymous>)
    at SocketModeClient.send (/opt/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:329:16)
    at ack (/opt/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:469:24)
    at App.processEvent (/opt/app/node_modules/@slack/bolt/dist/App.js:428:19)
    at runMicrotasks (<anonymous>)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 122)
```

**Comment by cjbrunner** [comment]
Just wanted to mention that this is a problem for my team as well, if there's some kind of voting mechanism here.

**Comment by usubram** [comment]
Meanwhile, i did this as a workaround. Not sure if it is the right approach to depend on `app.receiver.client.badConnection`, but based on my testing seems to works well. Alternatively, would be great for the library to support a health check ability for the bot. My deploy setup would restart the bot if  `/health` fails with `500`

```
  httpApp.get('/health', (req, res) => {
    if (app.receiver.client.badConnection) {
      res.status(500).send('Internal Server Error');
      return;
    }

    res.status(200).send(app.receiver.client.badConnection);
  });
```

**Comment by cjbrunner** [comment]
Has this issue been prioritized?

**Comment by ojaha065** [comment]
We recently started using HTTP instead of Socket Mode, so this is no longer an issue for us. However, before migrating to HTTP, I witnessed this happening in three different environments:

* Node.js 16.x running in Heroku dyno (using [Heroku-20 stack](https://devcenter.heroku.com/articles/stack) so basically Ubuntu 20.04)
* Node.js 14.17.x running on Windows Server 2019
* Even in my dev machine when I left a socket mode bot running overnight. I'm running Node.js 14.17.3 on Win10

As an interesting observation, the WebSocket disconnection and subsequently this issue seemed to always happen in the middle of the night (1 am to 6 am, UTC+03:00), when the bot spent a lot of time idling without getting any requests. This could be a total coincidence tho.

**Comment by danilooliveira88** [comment]
We encountered a very similar problem. But WebSocket disconnections occur constantly.

```
[ERROR]  socket-mode:SocketModeClient:0 A websocket error occurred: Client network socket disconnected before secure TLS connection was established
[INFO]  socket-mode:SocketModeClient:0 A ping wasn't received from the server before the timeout of 30000ms!
[ERROR]  socket-mode:SocketModeClient:0 cannot send message when client is not ready
/usr/src/app/node_modules/@slack/socket-mode/dist/errors.js:63
    return errorWithCode(new Error('Cannot send message when client is not ready'), ErrorCode.NoReplyReceivedError);
                         ^

Error: Cannot send message when client is not ready
    at sendWhileNotReadyError (/usr/src/app/node_modules/@slack/socket-mode/dist/errors.js:63:26)
    at /usr/src/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:343:60
    at new Promise (<anonymous>)
    at SocketModeClient.send (/usr/src/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:334:16)
    at ack (/usr/src/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:473:24)
    at App.processEvent (/usr/src/app/node_modules/@slack/bolt/dist/App.js:531:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SocketModeClient.<anonymous> (/usr/src/app/node_modules/@slack/bolt/dist/receivers/SocketModeReceiver.js:142:13) {
  code: 'slack_socket_mode_no_reply_received_error'
}
```

**Comment by levenleven** [comment]
We've also seen:
```
[INFO]  A ping wasn't received from the server before the timeout of 30000ms!
[ERROR] A websocket error occurred: connect ETIMEDOUT ...
```
On multiple hosts around the same time, and connection wasn't recovered until app restart.

**Comment by seratch** [comment]
https://github.com/slackapi/node-slack-sdk/pull/1465 will resolve this issue. We are going to release an RC version soon. Please try the RC version out and let us know if you find something wrong with it.

**Comment by seratch** [comment]
👋 Hi, all the developers watching this thread! 

We've improved the `SocketModeClient` internals a lot to be more robust. You can try the updated one by installing the RC version by running the following command:
```bash
npm i @slack/socket-mode@next
# or npm i @slack/socket-mode@1.3.0-rc.0
```

If you are interested in all the changes included in the release, refer to https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fsocket-mode%401.3.0-rc.0 for the details.

If everything goes well, we will release v1.3.0 next week!

**Comment by balpha** [comment]
Anyone trying this, note my mistake in the first commit :arrow_up: -- if you're using bolt, then socket-mode is a transitive dependency.

**Comment by seratch** [comment]
[version 1.3.0](https://www.npmjs.com/package/@slack/socket-mode/v/1.3.0) is now available. Please upgrade to the latest version 👋
