### ISSUE TITLE
How do I subscribe to the presence_change event if RTM is deprecated?

### ISSUE THREAD

**Issue by CodeBradley** [slackapi/node-slack-sdk#1245]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Steps to reproduce:

I keep getting this missing_scope error when I try and run `rtm.start()` in my app

<img width="400" alt="Screen Shot 2021-05-22 at 5 50 15 PM" src="https://user-images.githubusercontent.com/3913066/119242750-36f35480-bb26-11eb-9527-1ea52eb98085.png">

Here's the scopes I have set in both my old and new apps (I'm switching tokens out trying both apps, both both and user tokens for each app)

<img width="400" alt="Screen Shot 2021-05-22 at 5 51 30 PM" src="https://user-images.githubusercontent.com/3913066/119242777-6efa9780-bb26-11eb-931c-2af8bb7264de.png">
<img width="400" alt="Screen Shot 2021-05-22 at 5 51 13 PM" src="https://user-images.githubusercontent.com/3913066/119242778-70c45b00-bb26-11eb-895e-f072e0fee6ac.png">

How do I access presence_change events from a new or old app in Slack? I've tried both new and old and can't get this to work. There is nothing in the documentation stating if `presence_change` is going to be deprecated, but I did find this notice saying you can't access RTM from a new app.

<img width="400" alt="Screen Shot 2021-05-22 at 5 30 37 PM" src="https://user-images.githubusercontent.com/3913066/119242703-d401bd80-bb25-11eb-887c-61f31d7d410f.png">

It looks like I can't use it with the event api according to the image below.

<img width="400" alt="Screen Shot 2021-05-22 at 5 43 40 PM" src="https://user-images.githubusercontent.com/3913066/119242726-00b5d500-bb26-11eb-8cbf-f9a39ab11c95.png">

How do I access obtain the data from this event now? I can't figure it out.

Edit: If I switch to the bot token btw, I get this error instead:

```rtm-api:RTMClient:1 unable to RTM start: An API error occurred: not_allowed_token_type```

#### Expected result:

What you expected to happen

To get the presence_change data

#### Actual result:

What actually happened

missing_scope

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by CodeBradley** [comment]
I said screw it and decided to try and add all scopes to see if it would work, then it tells me that I've added invalid_scopes/permissions. Unrelated, but how is that even possible? Figured I would point this out too.

<img width="572" alt="Screen Shot 2021-05-22 at 6 10 42 PM" src="https://user-images.githubusercontent.com/3913066/119243094-65befa00-bb29-11eb-9817-16db6c7a4324.png">

![screencapture-api-slack-apps-A022485MC8N-oauth-2021-05-22-18_05_51 (1)](https://user-images.githubusercontent.com/3913066/119243092-622b7300-bb29-11eb-8e33-33994783acf1.png)

This stuff all seems really unorganized

**Comment by seratch** [comment]
Hi @CodeBradley, thanks for asking the question!

As you've noticed, the default way to create a new Slack app no longer supports the RTM feature. With that being said, you can still use it if you create a new "classic" Slack app. See **How do I create a classic Slack app?** at https://api.slack.com/authentication/migration

Here are the steps to make your classic app functional with RTM API and its presence change events.

* Create a new classic app from Create a new classic app from　https://api.slack.com/apps?new_classic_app=1
* Go to Features > App Home
  * Click "Add Legacy Bot User"
  * Save the bot with its name
* Go to Settings > Install App
  * Click "Install to Workspace"
  * Complete the installation flow
* Create a new project
  * Follow the instructions at https://slack.dev/node-slack-sdk/rtm-api

The following example code demonstrates how the presence change subscription works.

```js
const { RTMClient } = require('@slack/rtm-api');
const { WebClient } = require('@slack/web-api');

// Read a token from the environment variables
const token = process.env.SLACK_BOT_TOKEN;

// Initialize
const client = new WebClient(token, { logLevel: 'debug' });
const rtm = new RTMClient(token, { logLevel: 'debug' });

// For those user's whose presence was subscribed, log the updates to the console.
rtm.on('presence_change', (event) => {
  console.log(`User: ${event.user} Presence: ${event.presence}`);
});

// Presence subscription state, and helper
const trackedUserIds = [];
async function addPresenceSubscriptions(userIds) {
  await rtm.subscribePresence(trackedUserIds.concat(userIds));
  trackedUserIds.push(...userIds);
}

(async () => {
  const intialTrackUserIds = (await client.users.list({ limit: 10 })).members.map((m) => m.id);
  console.log(`trackedUserIds: ${trackedUserIds}`);
  addPresenceSubscriptions(intialTrackUserIds);

  // Connect to Slack
  const { self, team } = await rtm.start();
})();
```

I hope this was helpful to you. If everything is clear now, would you mind closing this issue?

**Comment by CodeBradley** [comment]
Yeah, I'll try this out and close when I confirm its working. One other thing though, is this being deprecated completely or will it be reintroduced in the events api? Thanks for the guidance.

**Comment by seratch** [comment]
> is this being deprecated completely or will it be reintroduced in the events api?

@CodeBradley Unfortunately, we don't have any plans to add the event to Events API as of today.

**Comment by CodeBradley** [comment]
@seratch So it looks like I can't get a list of user IDs from a user group using this type of app? I'm trying to get a list of users within a specific user group and then get notified when they log out so the next guy so I can be notified if no one is monitoring slack which tells me to jump in. Here's what I have so far.

`require('dotenv').config();
const { WebClient, ErrorCode } = require('@slack/web-api');
const { RTMClient } = require('@slack/rtm-api');

const botToken = process.env.SLACK_BOT_TOKEN;
const userGroupName = "Team TX";

const web = new WebClient(botToken);
let rtm = new RTMClient(botToken);

const getUserGroupId = async (userGroupName) => {
    const userGroups = await web.usergroups.list();
    const userGroup = userGroups.usergroups.find((userGroup) => {
        return userGroup.name === userGroupName;
    });
    if(!userGroup) {
        console.log("\nFatal Error:", "UserGroup was not found\n");
        process.exit(0);
    }
    const userGroupId = userGroup.id;
    console.debug("Monitoring UserGroup ID:", userGroupId);
    return userGroupId;
}

getUserGroupMemberIds = async (userGroupId) => {
    const groupMembers = await web.usergroups.users.list({usergroup: userGroupId});
    if(!groupMembers) {
        console.log("Fatal Error:", "No users in group?");
        process.exit(0);
     }
     let groupMemberIds = groupMembers.users;
     console.debug(groupMemberIds);
     return groupMemberIds;
}
//Currently connects to Slack, Pulls User Groups and Get Members Id's. Need to pull user data and stats now and create db
(async () => {
    const userGroupId = await getUserGroupId(userGroupName);
    const userGroupMemberIds = await getUserGroupMemberIds(userGroupId);
    rtm.subscribePresence(userGroupMemberIds);
    await rtm.start()
})();`

**Comment by CodeBradley** [comment]
I tried your code also btw, and it says `not_authed`

**Comment by CodeBradley** [comment]
I just made another app and am using a mixture of user and bot tokens. I'm assuming this is the only solution when working with usergroups, or are there older methods I can use?

**Comment by seratch** [comment]
@CodeBradley 
> So it looks like I can't get a list of user IDs from a user group using this type of app?

Yes. Unfortunately, `usergroups.users.list` is not available for classic bot tokens. If an API method document does not have "classic bot", the token for RTM connections are not usable for the API calls.

<img width="300" src="https://user-images.githubusercontent.com/19658/119417654-4abed680-bd31-11eb-9a25-8302910aa9e8.png"><img width="300" src="https://user-images.githubusercontent.com/19658/119417659-4c889a00-bd31-11eb-815d-e5ec3ad975f9.png">
^ usergroups.user.list does not have "classic bot" in its list of token types while chat.postMessage has

>I just made another app and am using a mixture of user and bot tokens. I'm assuming this is the only solution when working with usergroups, or are there older methods I can use?

This is the only workaround I can think of.

**Comment by seratch** [comment]
@CodeBradley When you have `identity.*`scopes, you cannot have non-`indentity.*` scopes at the same time. Refer to the document for more details: https://api.slack.com/docs/sign-in-with-slack

**Comment by seratch** [comment]
As we've provided answers to all the questions here, let us close this issue now.
