### ISSUE TITLE
Expose axios timeout parameter

### ISSUE THREAD

**Issue by Sytten** [slackapi/node-slack-sdk#1250]
### Description

By default axios has no timeout, this is a bad default for production systems and currently there is no way to override it.
You can override the socket timeout with the agent but it's not the same thing.
I would like to be able to change that via the WebClient options.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

**Comment by misscoded** [comment]
Hey @Sytten, thanks for suggesting this enhancement! We're in total agreement and will work on getting a PR out to introduce a customizable `timeout` to the `WebClient` options. 

In the event that you're interested in tackling this enhancement yourself, just let us know. 🙂

**Comment by misscoded** [comment]
Just merged this fix. It will be out and available for use once we release v6.3. Thanks again for making the suggestion/request! 🙂

**Comment by Sytten** [comment]
Thanks for the quick resolution :)
