### ISSUE TITLE
How to list only users inside Multi-select menu element (with user list)

### ISSUE THREAD

**Issue by DevShashi1993** [slackapi/node-slack-sdk#1253]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Question
I need to list only users inside the Multi-select menu element. So how can I list only users inside Multi-select menu element (with user list) in my slack app? Generally, it lists outs all the users including the bots installed.

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
Hi @DevShashi1993! This is a feature request that we've seen many developers raise, but unfortunately **the ability to filter bots out of the `multi_users_select` has not yet been introduced**.

One workaround is to use the multi-select menu with a [static](https://api.slack.com/reference/block-kit/block-elements#static_multi_select) or [external data source](https://api.slack.com/reference/block-kit/block-elements#external_multi_select) along with `users.list` to query for the users and populate the available options. Alternatively, you could also use the `multi_users_select` as is and validate the user's selection on submission.

Let us know if either workaround provided above resolves the issue for the time being. In the meantime, we'll pass on the additional request for filterability on the `multi_users_select` menu. 🙂

**Comment by DevShashi1993** [comment]
Hi, @misscoded  Thanks a lot for providing the workaround!
Yes, the provided workaround does the job by adding the static data source along with `users.list` and populate the available users. It would be much better if you can roll out this new feature request asap.

**Comment by misscoded** [comment]
Fantastic -- really happy to hear that the workaround resolved the issue in lieu of filterability. As such, I'll close this issue, but we're in total agreement with you about having the ability to filter being a better solution. This feature isn't to do with the SDKs, so it's out of the maintainers' purview, but we'll be sure to pass on the feedback to the appropriate team!

**Comment by LipatovAlexander** [comment]
Had the same question, here is the answer of Slack support about this. For me it solves the issue completely.

> Thank you for following up! If using Block Kit to display a drop-down list, I believe you should be able to use the conversations multi-select menu and define a filter for the list. If you're looking to display a list of users, you can include only im conversations and then exclude bot users by setting the exclude_bot_users field to true. There is some more information on this here: https://api.slack.com/reference/block-kit/composition-objects#filter_conversations.
