### ISSUE TITLE
@slack/oauth has unpublished updates

### ISSUE THREAD

**Issue by nikglavin** [slackapi/node-slack-sdk#1256]
### Description

@slack/oauth 2.0.1 package was last published to NPM on January 26 since then 2 pull request have been merged. One being adding metadata to the installation object which is a very useful enhancement.

Are you able cut a version and publish the changes to NPM 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @nikglavin, thanks for flagging this! Indeed, it's about time to release a new version. We'll ship it shortly.

**Comment by seratch** [comment]
v2.1.0 is now available. Thanks for taking the time to report this! 
https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Foauth%402.1.0
