### ISSUE TITLE
Support "timepicker" element

### ISSUE THREAD

**Issue by 80rian** [slackapi/node-slack-sdk#1259]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

I have built a slack bot in Javascript and I just started porting it to Typescript(&nestjs).
I didn't have any problem working with timepicker element in js but it seems like timepicker is not yet implemented to types.
I am not sure if it's just adding another interface to a union type or not.
If it's just that simple, I can definitely work on it and PR. If not, please consider implementing timepicker type.
I know timepicker is still in beta, but something that works with js should work with ts, right?
Let me know!

**Comment by seratch** [comment]
Hi @80rian, thanks for taking the time to report this! 

We recently added `timepicker` to the package: https://github.com/slackapi/node-slack-sdk/pull/1226 but haven't yet released a new version. As we don't have anything further for the next release, we can release a new version shortly.

**Comment by 80rian** [comment]
@seratch Thanks for a quick reply!
Sorry for missing that pr and it looks exactly like what I did!
I can close this issue.

**Comment by seratch** [comment]
FYI, the interface is now available in `@slack/types@2.1.0`.
