### ISSUE TITLE
web-api chat.postMessage post duplicated message to App home

### ISSUE THREAD

**Issue by sunxivincent** [slackapi/node-slack-sdk#1261]
### Description

I am using `chat.postMessage` in my node service to post message to app home. However, I saw duplicated message for same user even if I was only calling this API once. Do I miss something here? Sample code as below shown: 
```
const { WebClient } = require('@slack/web-api');
const dao = require('./dao');
const client = new WebClient(process.env.SLACK_BOT_TOKEN);

(async () => {
    const userInfos = await dao.getUserInfoFromDB();   // some logic to fetch userId from database
    for (const userInfo of userInfos) {
        const result = await client.chat.postMessage({
          channel: userInfo.userId,
          text: "Hello world"
      } 
    }
})();
```
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: ^6.2.3

node version: 14.17.0

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

see message once
#### Actual result:

see message multiple times

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
Hi @sunxivincent! With the sample you've provided, the only reason I can see that a duplicate message might occur is if `userInfos` contained more than one record for a given user. 

Can you log out `userInfos` for the user you're seeing a duplicate message for and verify there aren't two records in the collection?

**Comment by sunxivincent** [comment]
> Hi @sunxivincent! With the sample you've provided, the only reason I can see that a duplicate message might occur is if `userInfos` contained more than one record for a given user.
> 
> Can you log out `userInfos` for the user you're seeing a duplicate message for and verify there aren't two records in the collection?

Thanks. Just want to confirm I don't have to do other things such as `ack()` if I want to post message to Slack via web api. I am suspecting that Heroku will initiate service + schedule call since I am using built-in Heroku scheduler to send notifications to user via bot, which leads to this code block is executed twice

**Comment by misscoded** [comment]
Nope, when posting messages via the WebAPI no other things are required.

If you've already ruled out the scenario of a duplicate record being present, we recommend the following at this point:

- Check the Heroku logs for duplicate scheduled executions to verify your suspicion
- Manually run the script outside of the scheduler to see if the duplicate messages occur

Let us know how you go with the above 🙂

**Comment by sunxivincent** [comment]
Thanks for confirmation. I have figured out the root cause, basically I am putting my scheduler script in same entry point of `npm start`, it's somehow getting triggered twice when deploying the node by heroku scheduler. I am moving it to separate file and using an empty script for `npm start` solves the issue.
