### ISSUE TITLE
How send shared message via API ?

### ISSUE THREAD

**Issue by brunoosilva** [slackapi/node-slack-sdk#1266]
### Description

How send shared message via API ?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

How send shared message via API ? 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.2.4

node version: 12.20.0

OS version(s): MacOS 10.15

#### Attachments:

![image](https://user-images.githubusercontent.com/3465257/121744288-0e34fe00-cad9-11eb-96b1-e043c94452bb.png)

**Comment by mwbrooks** [comment]
Hey @brunoosilva 👋🏻 

I spent some time looking into this and asked around internally at Slack. Unfortunately, there's no public API to share messages. It may come in the future, but it's not available today.

**The recommended approach is to share the link using `chat.postMessage` with `unfurl_link: true` and `unfurl_media: true`.** It's not as rich of an experience, but it's the recommended approach.

There's also an [example by @colmdoyle that shows this approach in action](https://github.com/slackapi/template-message-linking).

Hope that helps!
Michael

**Comment by brunoosilva** [comment]
@mwbrooks thank's, work fine!
