### ISSUE TITLE
Better developer experience with `blocks` in code editor (VS Code etc.)

### ISSUE THREAD

**Issue by adelin-b** [slackapi/node-slack-sdk#1267]
### Description

Block typings lead to unprecise usage

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

they key `type` in `Block` is of type `string` instead of being constants of the multiple type possible
#### Expected result:

What you expected to happen
`type` is a union of possible string

I fixed this by overriding the `Block` interface and removing the `type: string` but it is more valuable to provide it by default
![image](https://user-images.githubusercontent.com/23508913/121685770-a4105f00-cac0-11eb-8fac-3295e8ce7d2e.png)

#### Actual result:
`type` is just string

**Comment by filmaj** [comment]
I believe the latest `web-api` 7.0 or newer should have you covered! We have extensive JSDocs in place for blocks, so your IDE should be able to give you many hints along the way. For example, here is my attempt at writing the first block, the JSDocs can start giving you hints as to the various available types:

<img width="777" alt="Screenshot 2024-01-25 at 5 09 14 PM" src="https://github.com/slackapi/node-slack-sdk/assets/52645/65ccba9a-2738-472c-938a-a6901ec55fd1">

Once you start typing out the actual `type` property, the options narrow down:

<img width="719" alt="Screenshot 2024-01-25 at 5 11 34 PM" src="https://github.com/slackapi/node-slack-sdk/assets/52645/fc10e90b-22dc-49f4-bd92-58a6fb49206c">

Closing this.
