### ISSUE TITLE
Incorrect type: `StaticSelect['options']` erroneously allows `MrkdwnElement`

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1268]
### Description

Describe your issue here.

The following input block has no compile-time type errors, but leads to a Slack BlockKit validation error:

```json
{
   "type":"input",
   "element":{
      "type":"static_select",
      "action_id":"id",
      "options":[
         {
            "text":{
               "type":"mrkdwn",
               "text":"hello"
            },
            "value":"a"
         }
      ]
   }
}
```

This is because the `Option['text']` type is `MrkdwnElement | PlainTextElement`, when in reality, the payload only supports `PlainTextInput`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @rr-codes, thanks for taking the time to report this (as always)! Indeed, this can be improved in the next release. Perhaps, we can have a new `PlainTextOption` interface and use it for static_select and others that have the same restriction. https://github.com/slackapi/node-slack-sdk/blob/%40slack/types%402.1.0/packages/types/src/index.ts#L70-L75

**Comment by rr-codes** [comment]
@seratch awesome! I can implement the change if that works for you?

**Comment by seratch** [comment]
@rr-codes Yes, we are so glad to have your contribution on this!
