### ISSUE TITLE
Incorrect type: `PinsAddArguments['timestamp']` is optional, but should be required

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1275]
### Description

Describe your issue here.

In the `PinsAddArguments` interface, the `timestamp` property is defined as being optional. This is incorrect as noted in the method description [here](https://api.slack.com/methods/pins.add), and should be changed to be non-optional.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1. Use the WebClient `pins.add` method with no `timestamp` argument
2. Notice no type errors
3.

#### Expected result:

A type error saying the property is required

#### Actual result:

No such error

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
Hey @rr-codes! Thanks for bringing this to our attention. You're absolutely right -- both the documentation and the interface need to be corrected. If you're interested in making the correction to the interface, please feel free to open up a PR with the fix, else we'll aim to address it shortly. 🙂

**Comment by rr-codes** [comment]
yup, on it!
