### ISSUE TITLE
Bug: get "ok" instead of passed metadata

### ISSUE THREAD

**Issue by SweetSheldon** [slackapi/node-slack-sdk#1282]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

When i pass metadata to installer.generateUrl, i become just ok in installer.handleCallback instead of it. Also if i don't pass anything i receive same in installer.handleCallback. I try to send string, object, stringify object. But everytime receive just ok.
<img width="570" alt="Снимок экрана 2021-07-06 в 20 57 38" src="https://user-images.githubusercontent.com/48868754/124646050-d7b28f00-de9c-11eb-84e0-aa3db9c512c9.png">
<img width="726" alt="Снимок экрана 2021-07-06 в 20 49 19" src="https://user-images.githubusercontent.com/48868754/124645896-a6d25a00-de9c-11eb-9e52-0bb8c008b029.png">

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ x ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 2.1.0

node version: 14.16.0

OS version(s): macOS Big Sur 11.2.3

#### Steps to reproduce:

1. Pass metadata to installer.generateUrl
2. Check it in installer.handeCallback

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment]
Hey @SweetSheldon, good to hear from you again 🙂 Your code sample looks correct for storing and retrieving the metadata. 

If possible, can you tell us what output you get from `logger.info(metadata, 'metadata')`.

In the meantime, I'll try to put together an example to reproduce your issue and get back to you!

**Comment by SweetSheldon** [comment]
Here is output from logger.info(metadata, 'metadata').
<img width="150" alt="Снимок экрана 2021-07-06 в 22 08 28" src="https://user-images.githubusercontent.com/48868754/124654124-d38b6f00-dea6-11eb-94a2-86f6910a846f.png">

**Comment by srajiang** [comment]
Hey @SweetSheldon Can you try adjusting the success callback to accept an options object to get the `metadata`?

```javascript
const success = async (installation, options, req, res) => {
   console.log('metadata: ', options.metadata);
   // other stuff here
}, 
```
The when custom callbackOptions are supplied, the handler [will pass a installOptions](https://github.com/slackapi/node-slack-sdk/blob/0487cb23c799ae6764fddb6bfc03ef15dc7460e1/packages/oauth/src/index.ts#L514) object to the `success` and `failure` callbacks as a second argument. If you initially provided `metadata` as part of the installerOptions, it should exist in that object.
