### ISSUE TITLE
Not receiving events for workflow_step_execute

### ISSUE THREAD

**Issue by zac-metin** [slackapi/node-slack-sdk#1292]
### Description

Unlike other events, the client.on('workflow_step_execute' never triggers or receives an event

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ x ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 1.1.0

node version: 14

OS version(s): mac OS X 11.1

#### Steps to reproduce:

1. Create socket mode connection
2. All other tested events seem to work
3. Workflow step is executed but no workflow_step_execute event is acted on by the client

#### Expected result:

workflow_step_execute event is received and acted on by the client

#### Actual result:

no workflow_step_execute event is acted on by the client

**Comment by stevengill** [comment]
Hey @zac-metin,

I just tested this and it worked fine. 

```
socketModeClient.on('workflow_step_execute', async ({event, body, ack}) => {
  console.log('made it');
});
```

My theory is that maybe the workflow step isn't setup correctly for you? Want to share more info/code?

Also, I'd highly recommend using bolt-js to work with workflow steps. See https://slack.dev/bolt-js/concepts#steps

**Comment by zac-metin** [comment]
Hi Steven,

We have the scopes `workflow.steps:execute `under our Bot Token Scopes in Oauth & Permissions section as well as `workflow_step_execute` under the Subscribe to Bot Events section of the Events Subscription menu

The App is using socket mode

When we fire a workflow no event is received using the code above

We haven't used Bolt as it seems to be running an express server app for each Slack App/Bot -we are building a company-wide code solution within AWS Lambda which can react and respond on behalf of a range of different Slack Apps, so bolt didn't seem that suitable for event driven architecture unless we used ECS instead - in which case we would have needed a unique container for each new bot/app context

Thanks for your help on this

**Comment by seratch** [comment]
@zac-metin 

>When we fire a workflow no event is received using the code above

I would recommend checking the "Activity" tab in your workflow admin pages. You can see how your workflow executions failed there.

**Comment by seratch** [comment]
@zac-metin Let us know if you need more help here 👋

**Comment by seratch** [comment]
Let us close this issue now but please feel free to write in whenever you have anything further to ask regarding this topic!
