### ISSUE TITLE
implement private shares property on FileUploadResponse

### ISSUE THREAD

**Issue by JeanBarriere** [slackapi/node-slack-sdk#1294]
### Description

The type definition appearing in the Shares of the FileUploadResponse is not valid, according to the doc.

https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/response/FilesUploadResponse.ts#L58-L60

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: @slack/web-api@6.2.4

node version: 16.4.2

OS version(s): MacOS 11.4

#### Steps to reproduce:

1. npm install @slack/web-api
2. use `webapi.files.upload` result
3. try and access `result.file.shares.private`

#### Expected result:

I'd expect the Shares type to something close to this:
```ts
export interface SharesPublic {
  public: Record<string, Public[]>
}
interface SharesPrivate {
  private: Record<string, Public[]>
}
type Shares = SharesPublic | SharesPrivate
```
So that it matches what appears in the API: https://api.slack.com/methods/files.upload

#### Actual result:
Shares type is:
```ts
export interface Shares {
  public?: { [key: string]: Public[] };
}
```

**Comment by seratch** [comment]
HI @JeanBarriere, thanks for taking the time to report this issue! 

You are right that not only `public` but also `private` should exist there. As the API responses are auto-generated, we will update the source data to fix this issue.

**Comment by JeanBarriere** [comment]
@seratch Thanks, it will be useful
