### ISSUE TITLE
Invalid JSON string causing "Cannot create property 'response_metadata' on string" error

### ISSUE THREAD

**Issue by wizar** [slackapi/node-slack-sdk#1302]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have made my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 6.1.0

node version: v12.22.4

OS version(s):

#### Steps to reproduce:
I'm facing quite a weird issue from time to time while trying to fetch the complete list of workspace members:
```
const limitedConcurrencySlackClient = new WebClient({ maxRequestConcurrency: 3 });
const accumulator = [];

for await (const page of limitedConcurrencySlackClient.paginate('users.list', { limit: 999, token: 'XXXX' })) {
  accumulator.push(...page.members);
}
```

After successfully processing some pages, it fails with error:
```
TypeError: Cannot create property 'response_metadata' on string '{"ok":true,"offset":"XXXX","members":[<actual users array, but incomplete>'
    at WebClient.buildResult (/opt/services/dbss/node_modules/@slack/web-api/dist/WebClient.js:369:36)
    at WebClient.apiCall (/opt/services/dbss/node_modules/@slack/web-api/dist/WebClient.js:130:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It looks like `response.data` is actually a string with an incomplete JSON payload, which is causing errors in the WebClient:

```
if (data.response_metadata === undefined) {
  data.response_metadata = {};
}
```

This issue isn't reproducible every time, and I suspect what the key condition is to fetch data from a really bit workspace (which I'm not sure how to simulate)

#### Expected result:

The pagination method goes through the complete dataset w/o errors.

**Comment by srajiang** [comment]
@wizar - Thanks for writing in. I agree, that's pretty weird sounding behavior for sure. Let me look into this a little bit further to see whether I can reproduce at all, and will get back to you.

**Comment by wizar** [comment]
@srajiang Sorry for confusion, but turns out the actual error now is:
```
An API error occurred: internal_error
    at Object.platformErrorFromResult (/opt/services/dbss/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/opt/services/dbss/node_modules/@slack/web-api/dist/WebClient.js:156:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'internal_error',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

It happens everytime after rougly same amount of processed items (around 80k) irregarding of page size. It looks to me like there could be some user object causing this failure

**Comment by seratch** [comment]
Thanks for flagging this!

>TypeError: Cannot create property 'response_metadata' on string

This `TypeError` should be thrown here: https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%406.3.0/packages/web-api/src/WebClient.ts#L464-L466

It's not possible to continue the pagination in the case where an internal server error is returned from the server side but we should definitely improve the developer facing exception here.

**Comment by wizar** [comment]
@seratch Is there any good way to repeat request or at least skip current page and continue with another one?

**Comment by seratch** [comment]
There is no good way to do so at this moment. The web-api package can be improved to better support the use case (e.g., including some useful info in the exception thrown in the scenario)

**Comment by wizar** [comment]
I see, ok, thanks anyway!
