### ISSUE TITLE
zoom/crop feature for images

### ISSUE THREAD

**Issue by lapaz17** [slackapi/node-slack-sdk#1304]
### Description

Is there a way to create modal body with zoom feature for images?
I can only see [image block](https://api.slack.com/reference/block-kit/blocks#image) at API. That prevents me from creating an app for this feature. The primary use case for this hypothetical app is for developers who have multiple monitors in their work and they want to highlight(by cropping) problematic part of their screen (after taking screenshot) to their colleagues. See gif below.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Attachments:

![GIF](https://github.com/lapaz17/Gif/raw/main/output.gif)

**Comment by misscoded** [comment]
Hi @lapaz17! Very interesting use case! Unfortunately, this feature doesn't exist. As such, I'm going to close this issue but I'll also escalate the feedback/request to the responsible team(s) on your behalf. 🙂

**Comment by lapaz17** [comment]
@misscoded could you inform me when it is decided to be implemented?

**Comment by misscoded** [comment]
Though we forward on feedback and feature requests, there's no guarantee they will be introduced. In cases such as these, we recommend keeping an eye out on the [Changelog](https://api.slack.com/changelog).
