### ISSUE TITLE
scheduleMessage api returns internal error

### ISSUE THREAD

**Issue by chuanAlloy** [slackapi/node-slack-sdk#1305]
### Description

posting  https://slack.com/api/chat.scheduleMessage returns internal_error when all details are correct

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1. post POST
 https://slack.com/api/chat.scheduleMessage

with simple body:
```js
{
    "channel": "#deployments-nonprod",
    "text": "this is from postman",
    "post_at": "1628876830" //tomorrow's epoch timestamp
}
```
2. returns 
```js
{
    "ok": false,
    "error": "internal_error"
}
```
3. using the same authorization and postMessage api works fine

#### Expected result:

I should be able to schedule a message via the api when I can post the message

#### Actual result:

```js
{
    "ok": false,
    "error": "internal_error"
}
```

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @chuanAlloy, thanks for asking the question! 

I tried to reproduce your situation as much as possible but I'm still unsure what the conditions causing it are. Obviously, the `internal_error` does not provide sufficient information for you and the Slack server-side can be improve much more.

The following code example using this SDK should work for you. Can you try it out? 

```js
const { WebClient } = require('@slack/web-api');
const token = process.env.SLACK_BOT_TOKEN;
const client = new WebClient(token);
(async () => {
  const postAt = Math.floor(new Date().getTime() / 1000) + 600; // 10 minutes later
  const response = await client.chat.scheduleMessage({
    channel: '#random', // your own channel here
    text: 'Hi there!',
    post_at: postAt,
  });
  console.log(response);
})();
```

If you still see the same situation with the script, we would like you to contact our platform support agents (from `/feedback` in your Slack workspace or https://my.slack.com/help/requests/new). They can investigate the situation with your workspace / app information. As this issue tracker is a public place, we are unable to help you that way.

I hope this was helpful to you. Let us know if you have anything further to ask here!

**Comment by chuanAlloy** [comment]
Hi @seratch ,

Thank you for your response. My issue has been solved. I was using the legacy bot token. I created a new bot app and now it is working.
