### ISSUE TITLE
feat(webhook): Add method to validate Slack Incoming Webhook URL?

### ISSUE THREAD

**Issue by kunalnagar** [slackapi/node-slack-sdk#1311]
### Description

Is it possible to add a method to validate a Slack Webhook URL from the `@slack/webhook` package? The following RegEx seems to do the trick:

```
https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}
```

**Context:** When talking with the awesome Slack Support folks, they mentioned that this might seem like a viable option. I already have a slightly different version of this [here](https://github.com/kunalnagarco/action-cve/blob/main/src/destinations/slack.ts#L52-L57).

I'd be happy to whip up a Draft PR and contribute 🙂 

---

### What type of issue is this?
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @kunalnagar, thanks for taking the time to write in!

Although your validation code is quite simple, we hesitate to add it to the module that we maintain at least in the short term. The main reason is that there are more edge-case patterns among hooks.slack.com URLs and we are not planning to provide and maintain a complete module for validation.

For instance, the part `/services/` in a URL can be others like `/commands/` (response_url in a slash command payload) and `/workflows/` for webhook triggers in workflows. In addition to these, the platform may add more in the future. 

If we have the module as part of this SDK, we should cover all the possible patterns. So, keep your simple validation rule in your applications. Thanks again for sharing the feedback and offering the help!

**Comment by kunalnagar** [comment]
@seratch - Thanks for the update! This should be good to close.

**Comment by seratch** [comment]
Thank you for your prompt response! Let us close this issue now.
