### ISSUE TITLE
Add Support for apps.manifest.* Endpoints

### ISSUE THREAD

**Issue by misscoded** [slackapi/node-slack-sdk#1340]
### Description

Add support for the following `apps.manifest.*` methods:

`apps.manifest.create`
`apps.manifest.validate`
`apps.manifest.update`
`apps.manifest.delete`
`apps.manifest.export`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by filmaj** [comment]
Bumping this to 6.7, and FYI support for this exists on the `feat-app-manifests` branch.

**Comment by wcauchois** [comment]
Any update on support for these endpoints? 🙏
