### ISSUE TITLE
`InstallProvider#handleCallback` fails with `userScopes` 

### ISSUE THREAD

**Issue by mmyoji** [slackapi/node-slack-sdk#1342]
### Description

Our Slack app uses `Sign in with Slack`. It requires `userScopes: ["identity.basic", "identity.team"]`.
After upgrading `@slack/oauth@2.2.0`, Slack app installation fails.

It fails in https://github.com/slackapi/node-slack-sdk/commit/130da70cc43f5ec6216bec3f32bd957b23f55dc1#diff-eddef2341a2b17e36f1498c83b7eb8b1835d58bccd8c3c4ecbc479fd075d2f0dR408.

This was `if ~ else if ~` in the former version (`<=@2.1.0`), but has changed this commit: 130da70cc43f5ec6216bec3f32bd957b23f55dc1. 
Was this change intensional?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: `@slack/oauth@2.2.0` 

node version: v12, v14, v16

OS version(s):

#### Steps to reproduce:

1. Use the example app: https://github.com/slackapi/node-slack-sdk/tree/main/examples/oauth-v2 
2. Upgrade `@slack/oauth` to `2.2.0`
2. Add `userScopes: ["identity.basic", "identity.team"]` in https://github.com/slackapi/node-slack-sdk/blob/e771849f4d5a92e26f412db0b051edacdd2c6ea8/examples/oauth-v2/app.js#L77-L80  
3. Go to `http://localhost:3000/slack/install` and follow the Slack app installation step.

#### Expected result:

Installation succeeds.

#### Actual result:

Installation fails.

#### Attachments:

When passing `logLevel: LogLevel.DEBUG` to `new InstallProvider()`

```
$ node example/app.js
Example app listening on port 3000! Go to http://localhost:3000/slack/install to initiate oauth flow
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  web-api:WebClient:0 apiCall('oauth.v2.access') start
[DEBUG]  web-api:WebClient:0 will perform http request
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:1 initialized
[DEBUG]  web-api:WebClient:1 apiCall('auth.test') start
[DEBUG]  web-api:WebClient:1 will perform http request
[DEBUG]  web-api:WebClient:1 http response received
[DEBUG]  web-api:WebClient:2 initialized
[DEBUG]  web-api:WebClient:2 apiCall('auth.test') start
[DEBUG]  web-api:WebClient:2 will perform http request
[DEBUG]  web-api:WebClient:2 http response received
[ERROR]  OAuth:InstallProvider:0 Error: An API error occurred: invalid_auth
    at Object.platformErrorFromResult (/home/mmyoji/dev/slack-oauth-app/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/home/mmyoji/dev/slack-oauth-app/node_modules/@slack/web-api/dist/WebClient.js:158:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'invalid_auth',
    response_metadata: { scopes: [Array] }
  }
}
[DEBUG]  OAuth:InstallProvider:0 run built-in failure function
```

**Comment by seratch** [comment]
Hi @mmyoji, thanks for taking the time to write in!

As far as I know, even before v2.2.0, `@slack/oauth` package has never been properly supporting the "Sign In With Slack" (SIWS) flow (from the beginning if I understand correctly). I tried to find the versions that can function for the SIWS scenario but I was not able to. If you have a minimum working example **with a specific version of `@slack/oauth`**, sharing it with us would be appreciated.

Regarding a better solution for SIWS going forward, indeed it's possible to improve the `@slack/oauth` package not to call the `auth.test` API in this scenario. One downside of it would be the logic inside the package can be unnecessarily complicated.

However, even with the change, the package is not so useful for SIWS yet. The reason why I think so is that there are not so many customizable parts for `@slack/oauth` users. For this reason, I would recommend using `@slack/web-api` with your web application framework. This approach brings more flexibility plus the simplicity of the code. The following code uses Koa but it should be easy to migrate to Expess.js or whatever.

* `identity.*` compatible example: https://github.com/slackapi/node-slack-sdk/tree/main/examples/legacy-sign-in-with-slack
* OpenID Connect compatible example: https://github.com/slackapi/node-slack-sdk/tree/main/examples/openid-connect (We recently released a new generation of SIWS, which is compatible with OpenID Connect. If you don't have a strong reason to continue using the `identity.*` scopes, we recommend switching to this new flow.)

Ultimately, `@slack/oauth` package should be improved to cover more use cases. But in the short term, our recommendation is to keep your code simple by using only `@slack/web-api`.

I hope this helps!

**Comment by mmyoji** [comment]
Thank you for you quick reply and additional info! 

> One downside of it would be the logic inside the package can be unnecessarily complicated.

totally agree.

Changing our impl to OIDC w/ `@slack/web-api` sounds great :)
We'd go with the plan, thanks 😄
