### ISSUE TITLE
Checking for Slack team id before installation?

### ISSUE THREAD

**Issue by JLDCodes** [slackapi/node-slack-sdk#1344]
### Description

Is it possible to check the slack installation team id before connecting an app with Slack? 

Use case: I'd like to check if a team on the app I am working on has already connected to the slack workspace in an OAuth callback. 

Code:
Using just handleCallback 
https://gist.github.com/JLDCodes/74e48dcf7080ba984886fb6310aa8e41

Modified to use installationStore inside of InstallProvider to grab the slack team id so that I can check the database for its  presence
https://gist.github.com/JLDCodes/079c981139aa4ae1f3e19e3ff2d3d64d

Is it possible to get the installation.team.id before installing?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by seratch** [comment]
Hi @JLDCodes, thanks for asking the question and also sharing the details of your code (that's so helpful for us to understand your question more clearly)!

>Is it possible to get the installation.team.id before installing?

Unfortunately, this is not possible before the redirect_uri callback. Our recommendation is to do everything in the success listener in your use case. Refer to https://slack.dev/node-slack-sdk/oauth for more details.

<img width="600" src="https://user-images.githubusercontent.com/19658/134429953-1adeeda6-de3c-4f00-917e-cdbebed5baaf.png">

I hope this helps!

**Comment by viperfx** [comment]
@seratch this would still cause the app to be "installed" in the workspace right? We are looking for a way to check the slack workspace ID before Slack actually installs it.

**Comment by seratch** [comment]
@viperfx For your use case, I would suggest calling [auth.revoke](https://api.slack.com/methods/auth.revoke) API method with the tokens that are just issued if the team_id in `oauth.v2.access` response (=`installation` argument of the callbacks) is not in your allowlist. You can do this revocation and build a web page telling the end-user what just happened in the success callback function.

**Comment by seratch** [comment]
@JLDCodes Thanks for your reaction to my answer comment! Let us close this issue now but please feel free to write in whenever you have anything further to ask/discuss regarding this topic.
