### ISSUE TITLE
Best way to maintain users/channels cache + search?

### ISSUE THREAD

**Issue by wizar** [slackapi/node-slack-sdk#1345]
### Description

We need to provide some slack-api related features like:
- Showing suggestions based on typed user (or channel) name, in other words - search user/channel by name
- Looking up actual name by user slack ID
- In extreme case we might need to have the complete set of public channels

Nowadays we're using just `conversations.list` and `users.list` method + Nginx cache. But it's sttill not 100% reliable solution because of either hitting rate limits or encountering slack internal errors.

Initially I thought it's relatively trivial problem and there should be some off-shelf solutions, but didn't find any. So, I want to ask some advice of how to approach it in a best way. My current thinking is to "mirror" channels/users to the local DB and keep it up-to-date with Slack Events API.

Thanks!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @wizar, thanks for writing in!

To build quickly searchable database of the users / channels in a Slack workspace, as you already mentioned, creating a cache data of them is a common practice. However, with this approach, the cached data can be easily outdated. As you mentioned, utilizing the Events API to detect data changes of users / channels will help your system maintain the data in real time. But maintaining the data by an hour job / daily job would be acceptable in most cases.

Another approach I wanted to mention is that, in the case where you just would like to show select menus to select users / channels / conversations, the built-in Block Kit elements would be the easiest and the most robust way. Searching by keyword also works in these select menus.

* https://api.slack.com/reference/block-kit/block-elements#users_select
* https://api.slack.com/reference/block-kit/block-elements#conversation_select
* https://api.slack.com/reference/block-kit/block-elements#channel_select

Lastly, let me share my suggestions to the purposes you mentioned in the description:

>Showing suggestions based on typed user (or channel) name, in other words - search user/channel by name

This can be done by the above built-in elements in the Slack UI.

>Looking up actual name by user slack ID

If your app already knows a user ID, [users.info API method](https://api.slack.com/methods/users.info) is available for this.

>In extreme case we might need to have the complete set of public channels

This would be useful for other purposes but for the above two, this is not always necessary.

I hope this was helpful to you!

**Comment by wizar** [comment]
Hey @seratch , thanks for a fast reply!

Block-kit actually looks interesting, but I need to show these select menus in another web-app, not as message from bot. And thanks for the rest answers, it's really helpful!

**Comment by jaapdeheer** [comment]
Friendly word of warning from a fellow Slack app developer: if you subscribe to `user_change` with the Events API, and your app is installed in a sizable number of teams, you can get an absolute barrage of events.

When we tried it we saw unexplained, large `user_change` bursts at minutes :15, :30, :45 and mostly :00 of each hour, at one point approaching 1000 events per second (total, across some 15k teams). With other events (`team_join`, `app_home_opened`, etc) we rarely see more than 10 events per second, so we weren't quite expecting this.

Seems like maybe Slack internally does some kind of user profile maintenance that generates a bunch of `user_change` events every 15 minutes.
FYI :)

**Comment by wizar** [comment]
Oh, wow, thanks @jaapdeheer! I think you just saved me some nerves and hours of debugging 🤣

**Comment by seratch** [comment]
@jaapdeheer Thanks for sharing your knowledge 👍 I am sure that the event bursts would be due to user status updates by calendar integration apps (e.g., Google Calendar, Outlook Calendar, Clockwise, and more). Updating users' Slack status to "in meeting" is a very common functionality among those apps.

@wizar Thanks for your prompt reply. It seems that everything is clear now. Let me close this issue now. Good luck for your work on building local cache of user/channel metadata!
