### ISSUE TITLE
@slack/type View changes cause compile errors 

### ISSUE THREAD

**Issue by amphro** [slackapi/node-slack-sdk#1349]
In `@slack/type@2.2.0`, the `View` type was broken into multiple types and `View` was changed to a union type. See [here](https://github.com/slackapi/node-slack-sdk/blob/%40slack/types%402.2.0/packages/types/src/index.ts#L63). This causes a TON of compile errors in our bolt app where we return a `View` in a lot of methods.

For example, 

```
const result = cleanseViewData(view); // cleanseViewData -> View
const closeText = result?.close?.text;
```
This will result in `Property 'close' does not exist on type 'View'.  Property 'close' does not exist on type 'HomeView'.`.

Although I like this change in general, it is a little disruptive in a minor patch.

I did attempt to refactor our code since these types are more robust. At the very least, export HomeView, ModalView, and WorkflowStepView to prevent something like `View & { type: 'modal' }` on our end.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```bash
"slack/bolt": "^3.7.0",
"slack/logger": "^3.0.0",
"slack/oauth": "^2.3.0",
"slack/socket-mode": "^1.1.0",
"slack/types": "^2.2.0",
"slack/web-api": "^6.4.0",
```

"typescript": "^4.4.3"

#### Node runtime version

```
v14.15.5
```

#### OS info

```
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

Try to compile the following on `@slack/types@2.2.0`.

```
function getView(): View { 
  return {
    type: 'modal',
    title: { type: 'plain_text', text: '' },
    blocks: []
  };
}
const view = getView();
console.log(view.title);
```

### Expected result:

It compiles.

If the change doesn't want to be reverted, at least expose the types so the code can be changed to:

```
function getView(): ModalView { 
```

instead if:

```
function getView(): View & { type: 'modal' } { 
```

### Actual result:

Compile error.

![image](https://user-images.githubusercontent.com/918434/134994155-04ee1b2d-c841-4898-a770-30df12601fa9.png)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by misscoded** [comment]
Hi @amphro! Thanks for bringing this to our attention: we clearly overlooked the implications of this seemingly minor change. We'll get a fix up and out in the next release, specifically by way of exporting the individual types as you've suggested. Following the release, you should be able to use `ModalView` for the case you've shared above.
