### ISSUE TITLE
Auth test is failing when used with v2 oauth user token that also has a bot token.

### ISSUE THREAD

**Issue by thomsong** [slackapi/node-slack-sdk#1354]
This auth test is failing when i use the v2 oauth for a bot and user token in a non-enterprise workspace. Not sure if this is a slack API error, but either way, it should only be run inside the if statement since it's only used inside that one if.

In prior releases, the major block was an else, and now they are two if statements, which is maybe why the code is being executed now, where it wasn't before.

Suggested change is:

```typescript
 if (v2Resp.is_enterprise_install && v2Installation.enterpriseUrl === undefined) {
    const authResult = await runAuthTest(v2Resp.authed_user.access_token, this.clientOptions);
    v2Installation.enterpriseUrl = authResult.url;
}
```

https://github.com/slackapi/node-slack-sdk/blob/ff19f55540ab00c6fb7f3f3871d1a57b517c8ab8/packages/oauth/src/index.ts#L472

**Comment by mwbrooks** [comment]
@thomsong thanks for taking the time to report this issue! 🙇🏻 

I may be understanding the logic incorrectly, but should the suggested change be (`!== undefined`)?
```javascript
if (v2Resp.is_enterprise_install && v2Installation.enterpriseUrl !== undefined) {
```

@misscoded I noticed that this logic was touched when the token rotation feature was added. Would you mind looking over the suggestion above to ensure it works with the upcoming auth changes?

**Comment by mwbrooks** [comment]
@thomsong I spoke with @misscoded offline - you may want to read through issue #1342. At the moment, `@slack/oauth` doesn't completely support the "Sign-in with Slack" flow and you may be running into that issue. There's a recommended workaround included in the issue.
