### ISSUE TITLE
Add "Sign in with Slack" document section

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#1356]
We don't have any document pages for "Sign in with Slack" feature while having an example app in the repo: https://github.com/slackapi/node-slack-sdk/tree/main/examples/openid-connect

### List any relevant URLs

- https://slack.dev/node-slack-sdk/oauth

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Looking into this a bit further, we probably want a web-api-specific version of [the Sign in with Slack doc available on api.slack.com](https://api.slack.com/authentication/sign-in-with-slack).

I will put together a PR with an outline for a potential new documentation section to add for this, and then we can refine during PR review or in the future.

**Comment by seratch** [comment]
@filmaj Having a section in the web-api package document at this moment does make sense! As we have been receiving questions like "How can I handle the SIWS flow using the oauth package?", having a short section on the oauth package document side, which mentions that SIWS is not yet supported by the oauth package, would be event better. We can have a link to the new web-api document section from there.

**Comment by filmaj** [comment]
Sounds good, I will add that to the oauth package docs and link it back to the new web-api doc.
