### ISSUE TITLE
Issues with websocket connection for @slack/socket-mode

### ISSUE THREAD

**Issue by anirudha-simha** [slackapi/node-slack-sdk#1357]
### Description

Hi team, 
I am reaching out per directions from Slack support.

#### Overview:
My team is having some interesting issues with socket-mode when we are running it using the node.js 12 "@slack/socket-mode" package (v1.1.0)
Per the DEBUG level logs we have enabled we do not see any disconnects, disconnect events sent, etc. The container that has this service is up and running the whole time so per the logs nothing is unusual. However we have noticed that randomly we will appear to have no events coming in. During this "down time" window we had sent multiple events to our app (e.g. slash commands, messages, etc) but nothing was received in our logs and we got dispatch failed errors.
I have attached our logic to see if there is anything that stands out but would appreciate some assistance in determining why these random disconnects appear to happen  

#### Deployment Info:
Using @slack/socket-mode v1.1.0 
Using node.js 12 
Running this in an ECS container running out of AWS
container is running behind a corporate proxy and so all calls to slack are made through our aws-proxy. 
socket-mode implementation simply receives events and then forwards events to a lambda for further processing

#### Code Sample
```javascript
// Imports
const {SocketModeClient, LogLevel} = require('@slack/socket-mode');
const ProxyAgent = require('proxy-agent');
const Index = require('./index')

// Exports
module.exports = {
    sendEvent,
    onEvent
}

console.log(`IS_ECS_CONTAINER = ${process.env.IS_ECS_CONTAINER}`)

// Setting up Socket Mode
const socketModeClient = new SocketModeClient({
    appToken: process.env.SOCKET_MODE_APP_TOKEN,
    socketMode: true,
    logLevel: LogLevel.DEBUG,
    autoReconnectEnabled: true,
    clientOptions: {agent: new ProxyAgent(process.env.HTTPS_PROXY)}
});

socketModeClient.on('message', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'event', 'message')
});

socketModeClient.on('reaction_added', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'event', 'reaction_added')
});

socketModeClient.on('interactive', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'interactive', 'interactive')
});

socketModeClient.on('slash_commands', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'command', 'slash_commands')
});

socketModeClient.on('app_home_opened', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'event', 'app_home_opened')
});

socketModeClient.on('member_joined_channel', async ({event, body, ack}) => {
    await onEvent(event, body, ack, 'event', 'member_joined_channel')
});

socketModeClient.on('disconnect', async ({event, body, ack}) => {
    try {
        console.log(JSON.stringify(body, null, 4))
        await ack();
        console.log('Got disconnect event, reconnecting to slack')
        await socketModeClient.disconnect()
        await socketModeClient.start();
        console.log('Socket Mode started')
    } catch (e) {
        console.error(e)
    }

});


(async () => {
    try {
        await socketModeClient.start();
        console.log('Socket Mode started')
    } catch (e) {
        console.error(e)
    }
})();


// Helper Functions

/**
 * Forwards event to another lambda or local code
 * @param body - json event to send
 */
async function sendEvent(body) {
    // send to lambda, this env var should not be on for local dev... unless you have a very specific use case
    if (process.env.IS_ECS_CONTAINER) {
        // awaited function that forwards the event to a lambda to be processed there (legacy code stuff)
    }
    // send to local index file
    else {
        await Index.handler({body})
    }
}

/**
 * handles what to do on an event, will print its details and then call sendEvent()
 * @param event - SocketModeClient param
 * @param body - SocketModeClient param, is json
 * @param ack - SocketModeClient param, is a function to ack event
 * @param resourceType - string which says the resource type Slackline classifies this as
 * @param eventType - string of the event type the SocketModeClient "on" func ran on
 */
async function onEvent(event, body, ack, resourceType, eventType) {
    try {
        console.log(`============= ${eventType} =================\n${JSON.stringify(body, null, 4)}\n==============================\n`)
        await ack();
        body.resource_type = resourceType
        await module.exports.sendEvent(body)
    } catch (e) {
        console.error(e)
    }
}
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:
@slack/socket-mode v1.1.0

node version:
12

#### Steps to reproduce:

1. `npm install` socket-mode and proxy libs 
2. npm run the code above
3. let it run for a while 

#### Expected result:

Connection should be up all the time except for when it gets the disconnect event

#### Actual result:

Connection is just not being reported as terminating but no events can be received and we get `dispatch_failed` errors

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
Hi @anirudha-simha, thanks for writing in!

One thing that we are aware is that the Slack server-side had some issues with Socket Mode event delivery yesterday:
* https://github.com/slackapi/bolt-js/issues/1151#issuecomment-940656436
* https://status.slack.com//2021-10/10375fe5eef22d73

Now that the issue should be resolved already, could you check the issue still arises in your ECS environment?

Also, the listener for `socketModeClient.on('disconnect'` pattern would be necessary as the `SocketModeClient` automatically does the same under the hood.

I hope this was helpful to you.

**Comment by seratch** [comment]
@anirbanmu I cannot tell anything further but I'm guessing that something wrong might be due to some connectivity issues in between the Slack server-side and your AWS infra. One suggestion that I can provide is that trying to reproduce the same situation in other hosts (say, your laptop) may be helpful to narrow the issue down.

**Comment by williammartin** [comment]
I just want to add that in the past 4 days since I started making use of bolt with the SocketMode receiver I have been intermittently not receiving events. For example, if I have created a handler for `app.message("test", ...` and I send 4 test messages, the `SocketModeReceiver` logs may get anywhere between 0 and 4 of the messages.

As I was working on this the first evening, I assumed I must be doing something wrong. When I came back the next morning and started the app to continue investigating and started receiving all events for the entire day. Now that I have come back to it again this morning I am again intermittently receiving events with no code changes.

It is of course possible (maybe likely!) that the problem exists on my end, but I am looking _extremely_ suspiciously at the SocketMode right now, and am standing up my app with the Events API to see if I experience the same behaviour.

**Comment by mattbillenstein** [comment]
FWIW, I'm seeing the same thing in Python using socket-mode...

**Comment by seratch** [comment]
@mattbillenstein Thanks for writing in. The only issue we are aware of with the Python SDK is this one: https://github.com/slackapi/python-slack-sdk/issues/1110 

If you are not using any of the aiohttp based implementations (meaning that you use either the default one or websocket_client based one), could you share a bit more details of your issue in either https://github.com/slackapi/bolt-python or https://github.com/slackapi/python-slack-sdk/?

**Comment by mattbillenstein** [comment]
Yeah, I mean, the point in my mind is that if the same issue is popping up across various client libs, perhaps it's a problem actually server-side?

In Python I've actually seen it with both the regular SocketModeClient as well as the websocket one -- so I guess two different python implementations as well.

**Comment by msw-psh** [comment]
I'm only seeing about 1/10 sockets mode events get received, also. python with aiohttp.

**Comment by valerybugakov** [comment]
I bumped into the same issue today. Some `app_mention` events are delivered, and some are not in a random manner. 
This happens only with the socket mode enabled in Python and JS SDKs (bolt-js and bolt-python). Switching to [events over HTTP](https://slack.dev/bolt-python/tutorial/getting-started-http) and ngrok for local development fixed the issue without changing any application code.

**Comment by seratch** [comment]
@valerybugakov The most common cause of your situation is another Socket Mode app process is still running somewhere you no longer manage. The forgotten/outdated process might be receiving some of the events you wanted to receive with your active app process. To deal with this situation, revoking the existing app-level tokens and creating a new one may be worth trying. Please refer to https://github.com/slackapi/java-slack-sdk/issues/803#issuecomment-895768180 for more details.
