### ISSUE TITLE
Using users.list with an orgwide app's bot token or workspace token returns null

### ISSUE THREAD

**Issue by dhpark** [slackapi/node-slack-sdk#1364]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [ x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
node --version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`

#### Python runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1. node searchDisplayNames.js
2.
3.
https://gist.github.com/dhpark/1fdc3cb967eb0b0dac9d8a4ed323dcbc
### Expected result:

(Tell what you expected to happen)
a payload of 950 users comes back, I see this properly happening in postman and the API tester at https://api.slack.com/methods/users.list/test
### Actual result:
Getting null each pagination:
![image](https://user-images.githubusercontent.com/3418781/139258238-4dd314b8-6ae5-4745-88a8-b53f3eed69d1.png)

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
My previous comment should be the answer for your question here. Let us close this issue but please feel free to write in if you have any follow-ups!
