### ISSUE TITLE
Expose axios timeout parameter for webhooks

### ISSUE THREAD

**Issue by tk26** [slackapi/node-slack-sdk#1378]
By default axios has no timeout, this is a bad default for production systems and currently there is no way to override it.
You can override the socket timeout with the agent but it's not the same thing.
I would like to be able to change that via the WebClient options.

Note: This was added for web-api in https://github.com/slackapi/node-slack-sdk/issues/1250
As a part of this issue, it'd be great if we could support webhooks.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @tk26, thanks for writing in! I agree that this should be a good addition.

**Comment by tk26** [comment]
that was an ultra-fast response! thanks @seratch - mind if I take a stab at it?

**Comment by seratch** [comment]
If you are fine to sign our CLA (https://cla-assistant.io/slackapi/node-slack-sdk), a fix with test code (like this way: https://github.com/slackapi/node-slack-sdk/pull/1264) would be appreciated!

**Comment by tk26** [comment]
Great! I just signed the CLA. Will create a fix soon. Thanks @seratch

**Comment by tk26** [comment]
I totally lost track of this issue. Thanks for fixing it and seeing it through @xuhas @filmaj
