### ISSUE TITLE
Snippet type?

### ISSUE THREAD

**Issue by owens-ben** [slackapi/node-slack-sdk#1379]
I am running into an issue where files are automatically assigned the "mode" snippet. This is causing issues as the size limit for snippets is 1 MB. Is it possible at all to specify the mode? 

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
node --version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`

#### Python runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Which package are you using, and what API? Can you share any more information about what you've tried thus far?

**Comment by owens-ben** [comment]
"@slack/web-api": "^6.5.0",

**Comment by filmaj** [comment]
And which API are you using? `files.upload`? What parameters are you providing to the API?

**Comment by owens-ben** [comment]
const result = await client.files.upload({
                // channels can be a list of one to many strings
                channels: channelId,
                initial_comment: "Here\'s my file :smile:",
                // Include your filename in a ReadStream here
                file:html
            });

html is a `fs.createReadStream()`

I am trying to upload an HTML file, which has images in it.

**Comment by owens-ben** [comment]
If I remove the images from the HTML file, it works fine so it's pretty clear its due to the 1 MB cap.

**Comment by filmaj** [comment]
Hmm, I don't understand how images can be "included" in the HTML file unless you are encoding them in some way (e.g. base64) and embedding in the HTML file? Typically, images are linked from HTML files, not necessary "included" in them. Can you expand on how your HTML differs when you include vs. not the images?

I am asking these questions to figure out how to reproduce your scenario so that I may test different approaches and understand what, if any, failure mechanism is at play.

**Comment by owens-ben** [comment]
Sure, and btw I very much appreciate the prompt response! I do believe it is being encoded as base64 is what's happening (I am using a report aggregator I didn't write). I would like to upload these reports as a single file which is why I chose this approach. 

Here is an example file
[master-report (5).html.zip](https://github.com/slackapi/node-slack-sdk/files/7582818/master-report.5.html.zip)

**Comment by filmaj** [comment]
Thanks for sharing! I Will experiment and report back.

**Comment by owens-ben** [comment]
Thanks!!! Let me know if you need any more info

**Comment by filmaj** [comment]
FYI the file you shared is 70kb unzipped, so it is definitely under 1MB. Is this intentional, or do you use a different HTML file that is more than 1MB in size?

**Comment by owens-ben** [comment]
Sorry that was a bad example, try this one instead.
[master-report.html.zip](https://github.com/slackapi/node-slack-sdk/files/7583334/master-report.html.zip)

**Comment by filmaj** [comment]
FWIW this is what your upload code looks like to me when using the 70kb HTML file:

<img width="525" alt="Screen Shot 2021-11-22 at 1 18 52 PM" src="https://user-images.githubusercontent.com/52645/142914426-ebad0dd8-27e7-4252-bde6-c2b91bc5d9d9.png">

I will now try with the larger one...

**Comment by filmaj** [comment]
And here's what it is with the larger file. Both look the same to me...

<img width="511" alt="Screen Shot 2021-11-22 at 1 21 54 PM" src="https://user-images.githubusercontent.com/52645/142914819-c9c7ed53-3b9f-48c3-9077-596ebb1cf2ac.png">

This looks like the same, and correct, behaviour to me. What would be your expectation, here, @owens-ben ?

**Comment by owens-ben** [comment]
When I try it with the 2MB file, nothing happens. No error response but it never gets uploaded.

**Comment by owens-ben** [comment]
Basically it gets to this line, and just does nothing. I have put in various log lines to try and debug it but everything looks normal. https://github.com/slackapi/node-slack-sdk/blob/8b3fb8d584623b12d24ca1453b14353c80456427/packages/web-api/src/WebClient.ts#L388

**Comment by filmaj** [comment]
Hmmm, in my app, the upload of the larger file takes about a second, and I get a standard, expected response in my `result` variable, as described in the [API methods page for `files.upload`](https://api.slack.com/methods/files.upload#responses).

Are you sure no errors are raised? Does execution continue after your call to `await client.files.upload`? Can you add some `console.log`s before and after the `files.upload` call to understand how execution flows through your code? Maybe wrap the `files.upload` call with a `try/catch` to see if an error is raised during the `upload` call, like this:

```
console.log('going to upload soon');
let result;
try {
  result = await client.files.upload({
                // channels can be a list of one to many strings
                channels: channelId,
                initial_comment: "Here\'s my file :smile:",
                // Include your filename in a ReadStream here
                file:html
            });
} catch (e) {
  console.log('OH NO! error!', e);
}
console.log('upload attempt done');
```

**Comment by filmaj** [comment]
> Basically it gets to this line, and just does nothing. I have put in various log lines to try and debug it but everything looks normal.

Oh interesting, so it gets stuck on issuing the HTTP POST, huh? What OS and node version is your bot running on? Are there any network restrictions in the environment where your bot is running (say, a corporate firewall, or is a proxy server required to be configured)?

**Comment by owens-ben** [comment]
Running on my local machine, macos 11.6. Node version 14.17.3.

Can't think of type of network restrictions or anything like that.

**Comment by filmaj** [comment]
Perhaps slow network? Depending on the size of the file, it may take a while, esp. off home broadband. Additionally, if you are executing this code directly inside of an event subscription handler, you may need to be cognizant of the maximum 3 seconds response time that the Slack backend expects to get an answer within.

Perhaps a decent way of narrowing down the problem space is to see if you can use `curl` to upload the file, using your app's bot token, directly (possibly consider using the `-v` verbose flag to see how the request is issued from your machine and what the response looks like as it comes back from the Slack backend). In the [Examples section of the `files.upload` API docs](https://api.slack.com/methods/files.upload#examples), the first example shows how to use `curl` to upload a .gif file. Perhaps change this line to match your particular situation, something like:

```
curl -F file=@report.html -F "initial_comment=Heres my file" -F channels=C123456789 -H "Authorization: Bearer xoxb-xxxxxxxxx-xxxx" https://slack.com/api/files.upload
```

You'll need to use a proper channel ID relevant to the workspace you are testing this out in, as well as replace `xoxb-xxxxxx-xxxx` in my above example with your actual bot token.

**Comment by owens-ben** [comment]
Thanks for that tip, and the result is kinda interesting. Here is the output of that commant with -v: 

```curl -v -F file=@master-report.html -F "initial_comment=Heres my file" -F channels=Cxxxxxxx -H "Authorization: Bearer xoxb-xxxxxx" https://slack.com/api/files.upload

*   Trying 34.225.62.185...
* TCP_NODELAY set
* Connected to slack.com (34.225.62.185) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Slack Technologies, Inc.; CN=slack.com
*  start date: Apr 13 00:00:00 2021 GMT
*  expire date: Apr 18 23:59:59 2022 GMT
*  subjectAltName: host "slack.com" matched cert's "slack.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fa18a008200)
> POST /api/files.upload HTTP/2
> Host: slack.com
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer xoxb-xxxxxxxxxxx
> Content-Length: 2374210
> Content-Type: multipart/form-data; boundary=------------------------de0b5b68812dbea5
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
* We are completely uploaded and fine
```

But it doesn't exit!!! Could that be the issue?

**Comment by owens-ben** [comment]
aha..... if i wait longer, eventually it returns a 408!

```
< HTTP/2 408
< x-backend: files_normal files_bedrock_normal_with_overflow files_canary_with_overflow files_bedrock_canary_with_overflow files_control_with_overflow files_bedrock_control_with_overflow
< x-server: slack-www-hhvm-files-iad-o7no
< content-length: 14
< content-type: text/plain
< x-slack-shared-secret-outcome: no-match
< date: Mon, 22 Nov 2021 19:08:27 GMT
< server: envoy
< via: envoy-www-iad-2cng, envoy-edge-iad-cur8
< x-edge-backend: envoy-www
< x-slack-edge-shared-secret-outcome: no-match
<
* Connection #0 to host slack.com left intact
stream timeout* Closing connection 0
```

**Comment by filmaj** [comment]
Does the `curl` command exit on its own after "* We are completely uploaded and fine" - or does it sit stuck there? Did you have to `CTRL+C` to exit the `curl` command? This is bizarre... rather quickly the Slack API should respond back to you - my `curl` execution (logs below) took about 6 seconds total, with file upload and response back from Slack.

Every line prefixed with `>` from `curl`'s output is what your outgoing HTTP request to the Slack API contains. Afterwards, we expect to see a series of lines prefixed with `<` that show the HTTP response back from the Slack API. I see your outgoing POST request details - but see no response from Slack. This is definitely not expected!

For comparison, here is what mine looks like (minus redacted tokens / channel / user / team identifiers):

```
*   Trying 34.225.62.185...
* TCP_NODELAY set
* Connected to slack.com (34.225.62.185) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Slack Technologies, Inc.; CN=slack.com
*  start date: Apr 13 00:00:00 2021 GMT
*  expire date: Apr 18 23:59:59 2022 GMT
*  subjectAltName: host "slack.com" matched cert's "slack.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f826f00d600)
> POST /api/files.upload HTTP/2
> Host: slack.com
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer xoxb-xxxxxxxxx
> Content-Length: 2374203
> Content-Type: multipart/form-data; boundary=------------------------ef0eb72d7fc91be9
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
* We are completely uploaded and fine
< HTTP/2 200
< date: Mon, 22 Nov 2021 19:02:25 GMT
< server: Apache
< access-control-allow-origin: *
< referrer-policy: no-referrer
< x-slack-backend: r
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< access-control-allow-headers: slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags
< access-control-expose-headers: x-slack-req-id, retry-after
< x-oauth-scopes: chat:write,app_mentions:read,channels:history,calls:read,calls:write,channels:join,channels:manage,channels:read,chat:write.customize,chat:write.public,commands,conversations.connect:manage,conversations.connect:read,conversations.connect:write,dnd:read,emoji:read,files:read,files:write,groups:history,groups:read,groups:write,im:history,im:read,im:write,incoming-webhook,links:read,links:write,mpim:history,mpim:read,reactions:write,reminders:read,reminders:write,mpim:write,remote_files:share,remote_files:read,reactions:read,pins:read,pins:write,remote_files:write,team:read,users:read.email,users:read,workflow.steps:execute,users:write,usergroups:read,usergroups:write,users.profile:read
< x-accepted-oauth-scopes: files:write
< expires: Mon, 26 Jul 1997 05:00:00 GMT
< cache-control: private, no-cache, no-store, must-revalidate
< pragma: no-cache
< x-xss-protection: 0
< x-content-type-options: nosniff
< x-slack-req-id: f67cee0399e2297d6122be5ef3ec56c1
< vary: Accept-Encoding
< content-type: application/json; charset=utf-8
< x-envoy-upstream-service-time: 567
< x-backend: files_normal files_bedrock_normal_with_overflow files_canary_with_overflow files_bedrock_canary_with_overflow files_control_with_overflow files_bedrock_control_with_overflow
< x-server: slack-www-hhvm-files-iad-zrny
< x-slack-shared-secret-outcome: no-match
< via: envoy-www-iad-ie8r, envoy-edge-iad-wzg4
< x-edge-backend: envoy-www
< x-slack-edge-shared-secret-outcome: no-match
<
* Connection #0 to host slack.com left intact
{"ok":true,"file":{"id":"REDACTED","created":1637607745,"timestamp":1637607745,"name":"report.html","title":"report","mimetype":"text\/plain","filetype":"html","pretty_type":"HTML","user":"REDACTED","editable":false,"size":2373790,"mode":"hosted","is_external":false,"external_type":"","is_public":true,"public_url_shared":false,"display_as_bot":false,"username":"","url_private":"REDACTED","url_private_download":"REDACTED","media_display_type":"unknown","permalink":"REDACTED","permalink_public":"REDACTED","comments_count":0,"is_starred":false,"shares":{"public":{"REDACTED":[{"reply_users":[],"reply_users_count":0,"reply_count":0,"ts":"1637607746.002500","channel_name":"general","team_id":"REDACTED","share_user_id":"REDACTED"}]}},"channels":["REDACTED"],"groups":[],"ims":[],"has_rich_preview":false}}* Closing connection 0
```

**Comment by owens-ben** [comment]
see my comment that i posted right before yours ^^

**Comment by owens-ben** [comment]
tried bumping the timeout with the -m flag, fails the same way

**Comment by filmaj** [comment]
> aha..... if i wait longer, eventually it returns a 408!

Aha, indeed, HTTP 408 means "request timed out". Meaning, your machine is taking too long to upload the file and Slack is cutting the connection off! Out of curiosity, how long does the `curl` command execute before you receive the HTTP 408 response? You can add the `--trace-time` flag to your `curl` command to get timestamps for each line of the verbose output (but you must keep the `-v` flag to use `--trace-time`).

**Comment by filmaj** [comment]
For the record, on my machine it takes about a half second to complete the outgoing request (the difference between the "we are completely uploaded and fine" verbose log and the previous log), and then an additional half second before I start seeing the Slack HTTP response come back.

**Comment by owens-ben** [comment]
looks like 3 minutes 

```14:27:07.424411 >
14:27:07.448620 * Connection state changed (MAX_CONCURRENT_STREAMS == 2147483647)!
14:27:08.881383 * We are completely uploaded and fine
14:30:10.118527 < HTTP/2 408```

**Comment by owens-ben** [comment]
So this must be something unique to my org's Slack config? Is there some setting in the slack app we aren't thinking of?

**Comment by owens-ben** [comment]
Tried using ```mkfile``` to generate generic files of certain size.

1 MB works fine, anything even 1 KB more than that times out.

**Comment by filmaj** [comment]
Wow, I am at a loss! 3 minutes isn't even how long it took your machine to upload (it looks like the uploading took about ~1.4 seconds) - 3 minutes is how long Slack took to respond after your upload was complete. Truly bizarre!

I will speak to my team about this to see what else I can glean... sorry about that! Appreciate your patience while I try to find other possible causes.

**Comment by owens-ben** [comment]
Thanks!

**Comment by filmaj** [comment]
Can you tell me what kind of Slack plan the workspace you are running this against is on? Free, Pro, Enterprise, etc.?

**Comment by owens-ben** [comment]
Enterprise Select

**Comment by filmaj** [comment]
It doesn't look like there is an admin setting to limit the file upload sizes. There is the standard 1GB file size limit but we are not hitting that.

It sounds related to https://github.com/slackapi/python-slack-sdk/issues/858 and https://github.com/slackapi/python-slack-sdk/issues/880. [One person recommended, as a workaround, trying to use an external third party storage service and feeding URLs for shareable links to those resources into the `files.remote.add` API](https://github.com/slackapi/python-slack-sdk/issues/880#issuecomment-733584495).

This sounds like "weird networking stuff" (very scientific, I know) and I'm tempted to suggest things like reboot your machine? If possible, maybe you could try running this from a different machine, or hosting your bot code on some server or hosting platform and seeing if you experience the same issues?

**Comment by owens-ben** [comment]
Alas, it's definitely something with my network. Just ran it on an AWS instance and it worked fine :D 

But what in the world could be causing this problem? Are <1MB and >1MB files handled differently at all on your end?

**Comment by seratch** [comment]
Great to hear that your code works in an AWS host!

>Are <1MB and >1MB files handled differently at all on your end?

No, this is not the case. Apart from 1G size limit, there is nothing specific to the Slack platform.

> what in the world could be causing this problem?

I think that we cannot mention a single answer to this question. My understanding is just uploading a larger file can more often trigger the issue you've faced. There could be a few factors causing the issues like this. The common patterns that I've observed in the past are network connection instability between your app and Slack, proxy server limitation (proxy on the developer's app side, not Slack's proxy), weird connection issues from Docker container apps, Slack server-side's outage/instability, and so on.

I hope this helps.
