### ISSUE TITLE
WorkflowStepView doesn't work if there are multiple `views.update` API calls

### ISSUE THREAD

**Issue by bkeung** [slackapi/node-slack-sdk#1391]
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

### Reproducible in:
```
"slack/bolt": "^3.8.1",
"slack/logger": "^3.0.0",
"slack/socket-mode": "^1.2.0",
"slack/web-api": "^6.5.1",
"slack/oauth": "^2.3.0",
"slack/types": "^2.3.0",
v14.17.6
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
```

#### Steps to reproduce:
1. Make an API call to `views.update` using the new `WorkflowStepView` object. The first view update will be successful.
2. Make another API call to `views.update` to update the same view. This time the call will return an error `not_found`.

The reason is because `external_id` is not a property in `WorkflowStepView`.

### Expected result:
`views.update` API call should be successful and the view should continue to expand with new fields.
![Screen Shot 2021-12-02 at 12 30 04 PM](https://user-images.githubusercontent.com/95444954/144498215-71c66e8f-311d-46a1-b7d7-9218bb9862ef.png)

### Actual result:
An error occurred and the view doesn't get updated.
![Screen Shot 2021-12-02 at 10 55 06 AM](https://user-images.githubusercontent.com/95444954/144497290-32921b5e-475f-4798-a6a2-0f6b495a3988.png)
```
{"level":"ERROR","msg":"An API error occurred: not_found","line_number":23,"function":null,"file":"src/libs/logging/mw-bolt-ctx-logger.ts","error_name":"Error","error_msg":"An API error occurred: not_found"}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Hey @bkeung! Thanks for filing this issue.

My colleague @srajiang and I did some sleuthing and, we think, the issue of missing `external_id` on this type was introduced in this PR: https://github.com/slackapi/node-slack-sdk/pull/1276

As can be seen in that PR, the contributor based their refactoring of the three different view types based on two public docs:

1. https://api.slack.com/reference/workflows/configuration-view
2. https://api.slack.com/reference/surfaces/views

The first document doesn't mention either of `view_id` or `external_id` - so I think resolving this issue also may require some documentation updates.

Additionally, based on the [API docs for `views.update`](https://api.slack.com/methods/views.update), it looks like one of `view_id` or `external_id` is necessary for this method - so perhaps this issue bleeds into some of the other packages as well (i.e. perhaps we could ensure the `@slack/web-api` package revised in this repo checks for that, or perhaps we can reflect this either-or relationship in the type? not sure).

@srajiang was thinking that maybe `WorkflowStepView` should extend from `ModalView`.

What do others from the team think? Pinging @misscoded @stevengill @seratch

**Comment by srajiang** [comment]
Update: `WorkflowStepView` cannot extend `ModalView` because of existing required fields in `ModalView` that aren't in the former, so the initial thought I had is not the right direction.

The api docs say the workflow modal configuration object should be able to be used with views.update. Currently, without `external_id` that does not seem to be true. Seems we can `external_id` as a field to `WorkflowStepView` and then make sure that the api docs are corrected.
