### ISSUE TITLE
Some fields of the type definition of conversations.list are missing.

### ISSUE THREAD

**Issue by ryokohbato** [slackapi/node-slack-sdk#1397]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

I noticed that the type definition of `conversations.list API` is partly missing.
This may be a problem with java-slack-sdk, but I will write it here.

In [ConversationsListResponse.ts](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/response/ConversationsListResponse.ts), this may not be all, but some fields are missing, like `user`, `is_user_deleted`, and `priority`. As far as I can see from the [docs](https://api.slack.com/methods/conversations.list), it seems that if `is_im` is `true`, i.e. in the case of direct message, these fields are included in the response.

**Comment by seratch** [comment]
Hi @ryokohbato, thanks for taking the time to report this issue! And you're right that the generated source data is not complete due to the issue on the Java SDK side. We'll resolve this issue in the next release.
