### ISSUE TITLE
content-type of interactive-messages response needed as application/json

### ISSUE THREAD

**Issue by sonal-chauhan** [slackapi/node-slack-sdk#1407]
Currently , interactive messages buttons are calling interactive-response-url with content-type = application/x-www-form-urlencoded

can it be passed as application/json. This is needed to call jenkins generic-webhook-plugin url directly from action interaction but problem is  jenkins generic-webhook-plugin does not parse requestBody if content-type is other than application/json.

**Comment by seratch** [comment]
Hi @sonal-chauhan, thanks for writing in!

As you mentioned, any interactivity-related payloads are "application/x-www-form-urlencoded" content-type data (=`payload={url encoded JSON data here}` in its request body). Also, unfortunately, there is no way to customize this server-side behavior as of today.

The only thing that I can suggest is to have a kind of proxy between Slack and your Jenkins server, which converts the payload to "application/json" content-type data.

I know that this is not an ideal answer for you but I hope this helps.
