### ISSUE TITLE
Repeated view submissions

### ISSUE THREAD

**Issue by sukdeesh** [slackapi/node-slack-sdk#1408]
Days of frustration/searching has lead me to post a question here. 

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

node v14.16.0

#### The Slack SDK version
@slack/bolt": "^3.8.1

#### Python runtime version

(Paste the output of `node --version`)

#### OS info

Windows: Version	10.0.19043 Build 19043

#### Steps to reproduce:

Simple interactive bot implementation. It listens for messages and responds by opening a modal view with checkbox options. 1st time round, selecting and submitting works fine (bot responds with a single message). However, if I invoke the bot again, make a selection,  I am seeing a repeated message for that selection. Upon each invocation, it repeats again (2 messages, 3 messages, 4 messages etc). Here is what Bolt debug is showing (when invoking the bot twice):

![image](https://user-images.githubusercontent.com/61004690/147750041-ff5a65f8-620b-4f5e-bf8d-a5b260c08b7a.png)

Here is the code for the action:

```javascript
app.action("mor_actionId-1", async ({ body, ack, say }) => {
  var requestIds = [];
  var selections = [];

  await ack();

  const channel = body.user.id;

  const userInfo = await app.client.users.info({
    user: body.user.id,
  });
  const userInet = userInfo.user.profile.email;

  if (body.actions[0].selected_option.value === "notify_slack") {
    /*  1. get user's records  */
    
    const setSlackNotify = async () => {
      let request = {};
    
      const results = await axios.get("calls end point");
      if (!results) {
        console.log("Whoops! no requests");
        return;
      } else {
        const records = results.data;
        var myRequests = [];
    
    /* Build object array of requests to select from */
        records.forEach((record) => {
          request = {
            text: {
              type: "plain_text",
              text: record.requestid,
            },
            value: record.requestid,
          };
          myRequests.push(request);
        });
      }

      app.client.views.open({
        trigger_id: body.trigger_id,

        view: {
          type: "modal",
          clear_on_close: true,
          title: {
            type: "plain_text",
            text: "Select your request(s)",
          },
          submit: {
            type: "plain_text",
            text: "Submit",
          },
          close: {
            type: "plain_text",
            text: "Cancel",
          },
          blocks: [
            {
              type: "input",
              block_id: "b_001",
              element: {
                type: "checkboxes",
                action_id: "a_001",
                options: myRequests,
              },
              label: {
                type: "plain_text",
                text: "Please select request(s) to be notified on status change:",
                emoji: true,
              },
            },
          ],
        },
      });

/* THIS IS WHAT IS BEING REPEATED EACH TIME A SELECTION/SUBMISSION TAKES PLACE */

      app.view("", async ({ ack, body, view, client }) => {
        await ack();

        requestIds = [];
        selections = [];

        selections = view.state.values["b_001"]["a_001"]["selected_options"];

        selections.forEach((option) => requestIds.push(option.value));
console.log("submitted update for request: ", requestIds);
/* **After 1st selection/submission**, the console statement shows: 
submitted update for request:  [ '1099183' ]
**After the 2nd selection/submission**, the console statement shows: 
submitted update for request:  [ '1099184' ]
submitted update for request:  [ '1099184' ]
*/
        const results = await axios.put("calls end point");
        if (results) {
          msg = `*Done!* You are now set up to receive slack notifications for the following requests(s): *${requestIds}*`;
        } else {
          msg = `Whoops! There was a database update error for your request(s). Please contact your local support.`;
        }

        try {
          await client.chat.postMessage({
            channel: body.user.id,
            type: "mrkdwn",
            text: msg,
          });
        } catch (error) {
          console.error(error);
        }
      });
    };

    setSlackNotify();
  }
```

### Expected result:

one message per modal view submission:
![image](https://user-images.githubusercontent.com/61004690/147750285-80240b83-cbc1-41fa-9664-98112c57a028.png)

### Actual result:
![image](https://user-images.githubusercontent.com/61004690/147750218-03a3428b-e0f2-43ab-9580-95e6df63c47a.png)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @sukdeesh, thanks for asking the question!

It seems that your modal view does not have its `callback_id` and that's why your view submission handling times out. Can you add `callback_id` in your view and set the same string to `app.view` method call?

```javascript
client.views.open({
  trigger_id: body.trigger_id,

  view: {
    type: "modal",
    "callback_id": "your-own-modal-callback-id", // CHANGED 
```

```javascript
app.view("your-own-modal-callback-id", // CHANGED 
  async ({ ack, body, view, client }) => {
```

I hope this helps.

**Comment by sukdeesh** [comment]
Hi Kazuhiro,

thanks for the response! I implemented as you suggested but still face the same issue:

app.client.views.open({
     trigger_id: body.trigger_id,
        view: {
          type: "modal",
         callback_id:  "view_cb_id",

 app.view("view_cb_id", async ({ ack, body, view, client }) => {

I noticed in the documentation that the callback_id is optional?

I have attached an image of what is happening each time I make a selection from the view modal and submit. As you can see, the options in the modal are displaying correctly (once an option is selected and submitted, it is removed from the list). So the view is correctly showing the options available after each submission.

Thanks & regards,

Sukdeesh
________________________________

**Comment by seratch** [comment]
Do you have the app.view listener registration inside an app.action listener? If so, the situation that you describe may arise.

**Comment by sukdeesh** [comment]
Yes, I do....that would make sense and indeed it was the case! You live & learn. Thank you so much for pointing this out. If this is documented, I must have missed it (or misunderstood!).

Happy New Year!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
