### ISSUE TITLE
installerOptions.failure() options can be undefined

### ISSUE THREAD

**Issue by Gregoor** [slackapi/node-slack-sdk#1409]
### Description

As the title says and contrary to the type definitions, the `failure()` callback within `installerOptions` can receive `undefined`. Specifically I got that when aborting the OAuth flow.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 3.8.1

node version: 16.8

OS version(s): MacOS

#### Steps to reproduce:

1. Set-up `installerOptions.failure(error, options) { console.log({ options }); }`
2. Use the associated `installer.generateInstallUrl()` to go to the oauth flow
3. Click "Cancel"

#### Expected result:

Receive an `options` object with metadata etc.

#### Actual result:

Received `undefined`

**Comment by seratch** [comment]
@Gregoor Thanks for reporting this issue. The latest revision no longer has this issue. After merging other changes for the next release, we'll ship a new version shortly (perhaps, within a few business days).
