### ISSUE TITLE
manifest update always gives 'not_allowed_token_type' error

### ISSUE THREAD

**Issue by culli** [slackapi/node-slack-sdk#1412]
#### Packages:

Select all that apply:

- [x] `@slack/web-api` sort of
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

```
"slack/bolt": "^3.8.1",
"slack/logger": "^3.0.0",
"slack/oauth": "^2.3.0",
"slack/socket-mode": "^1.2.0",
"slack/types": "^2.4.0",
"slack/web-api": "^6.5.1",
```

#### Node version

v14.18.2

#### OS info

```
ProductName:    macOS
ProductVersion: 12.1
BuildVersion:   21C52
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64
```
#### Steps to reproduce:

Create the app from a manifest.

Run the following code.  I am using Bolt, and I would use the WebClient exposed by Bolt, but until branch `feat_app_manifest` gets merged manifest operations aren't available that way.

```javascript
import axios from 'axios';

export async function updateDeployment() {
  try {
    const TOKEN = '';
    const api = axios.create({
      baseURL: 'https://slack.com/api/',
      headers: {
        Authorization: `Bearer ${TOKEN}`,
        'Content-Type': 'application/json; charset=utf-8',
      },
    });

    const appId = '';

    const manifest = generate();
    const data = {
      app_id: appId,
      manifest,
    };
    const result = await api.post('apps.manifest.update', data);
    console.log('result', result.data);
  } catch (err) {
    console.error('error deploying manifest', err);
  }
}
```

### Expected result:

200 ok, and updating the manifest

### Actual result:

No matter which token I use in TOKEN, it gives the same error `not_allowed_token_type`.  Which token should be used?  Understand this api is marked Beta.

**Comment by seratch** [comment]
Hi @culli, thanks for writing in!

To perform the App Manifest APIs, you need to use an App Configuration Token. You can generate the token [from here](https://api.slack.com/authentication/config-tokens). Visit the page and click the "Generate Token" button:

<img width="600" src="https://user-images.githubusercontent.com/19658/149049481-a654978b-90dd-49f8-92ec-c03448c4f83f.png">

Also, to learn more details of App Manifest APIs, refer to the following documents for details:
* https://api.slack.com/reference/manifests#manifest_apis
* https://api.slack.com/authentication/config-tokens

I hope this helps!

**Comment by culli** [comment]
Yes it does help!

**Comment by culli** [comment]
That should be linked on pages like https://api.slack.com/methods/apps.manifest.create

And on this page https://api.slack.com/reference/manifests#manifest_apis
![image](https://user-images.githubusercontent.com/8321764/149183908-09801b7f-84bb-4c4f-8f63-87bd498ed0ba.png)
Those last two links both go to https://api.slack.com/authentication/config-tokens (maybe that's not intentional or necessary)

**Comment by culli** [comment]
Final question, when @slack/web-api supports this will it handle token rotation (and indirectly, will bolt work with token rotation)?

**Comment by mwbrooks** [comment]
Great to hear that @seratch was able to help you out @culli! 👏🏻 

> Final question, when @slack/web-api supports this will it handle token rotation (and indirectly, will bolt work with token rotation)?

Unfortunately, App Configuration/Tooling Token rotation is not currently built-in to `node-slack-sdk`. I'll raise this as a task for the maintainers to look at, but there may be complexities because each App Configuration Tokens is unique to the user and workspace (not app). Until there is built-in support, you'll need to [manually rotate the App Configuration Token](https://api.slack.com/authentication/config-tokens#rotating) (if you have chosen to enable token rotation). Sorry about that 🙁 

I'm going to close this issue since the original topic was handled. But feel free to respond or re-open if needed!
