### ISSUE TITLE
conversations.history call fails with missing field exception

### ISSUE THREAD

**Issue by NorbertHuethmayr** [slackapi/node-slack-sdk#1415]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`

#### The Slack SDK version

**@slack/web-api 6.5.1**

#### OS info

**Firebase Function on GCP** with **NodeJS 16**

#### Steps to reproduce:

```ts
const webClient = new WebClient()
const res = await webClient.conversations.history({
  token: team.accessToken,
  channel: item.channelId,
  latest: item.ts,
  limit: 1,
  inclusive: true
})
```

Also, the parameters fed into the method are valid. I built a request with Postman using the very same values and the result was OK.

### Expected result:

An OK result from the API along with the message history.

### Actual result:

```[ERROR]  web-api:WebClient:0 missing required field: channel ``` and 
```Error: An API error occurred: invalid_arguments at platformErrorFromResult (/workspace/node_modules/@slack/web-api/dist/errors.js:51:33) at WebClient.apiCall (/workspace/node_modules/@slack/web-api/dist/WebClient.js:167:56) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /workspace/lib/pubSub/item_threshold_processor.func.js:27:29```

![error logs](https://user-images.githubusercontent.com/26460692/149683400-544f1b4d-85b5-4da2-adbb-4d024a4f328e.png)

**Comment by seratch** [comment]
Hi @NorbertHuethmayr, thanks for asking the question!

The situation does not arise on my end.

> missing required field: channel

This error message indicates your `item.channelId` can be undefined/null for some reason. Could you check the data or the property name in the app again?

For your information, I used the following script to just in case verify the behavior of the package.

```javascript
const { WebClient } = require('@slack/web-api');

const item = {
  channelId: 'CHE2DUW5V',  // replace this with your own data
  ts: '1642161875.000700', // replace this with your own data
};

(async () => {
  const client = new WebClient(process.env.SLACK_BOT_TOKEN);
  const response = await client.conversations.history({
    channel: item.channelId,
    latest: item.ts,
    limit: 1,
    inclusive: true
  });
  console.log(response)
})();
```

I hope this helps!

**Comment by NorbertHuethmayr** [comment]
> Hi @NorbertHuethmayr, thanks for asking the question!
> 
> The situation does not arise on my end.
> 
> > missing required field: channel
> 
> This error message indicates your `item.channelId` can be undefined/null for some reason. Could you check the data or the property name in the app again?
> 
> For your information, I used the following script to just in case verify the behavior of the package.
> 
> ```js
> const { WebClient } = require('@slack/web-api');
> 
> const item = {
>   channelId: 'CHE2DUW5V',  // replace this with your own data
>   ts: '1642161875.000700', // replace this with your own data
> };
> 
> (async () => {
>   const client = new WebClient(process.env.SLACK_BOT_TOKEN);
>   const response = await client.conversations.history({
>     channel: item.channelId,
>     latest: item.ts,
>     limit: 1,
>     inclusive: true
>   });
>   console.log(response)
> })();
> ```
> 
> I hope this helps!

Hi Kazuhiro,

I've had a look and indeed you were right. I forgot to use a `converter` when writing my objects to the Firestore and hence got my **underscore** in `channelId` removed which then made that it was `null` upon reading again. Entirely my fault.

![image](https://user-images.githubusercontent.com/26460692/149779483-45978bec-1bda-4a8d-beec-4ae08f469676.png)

Thanks again for your help.
