### ISSUE TITLE
How to pass parameters in redirect_uri or install url?

### ISSUE THREAD

**Issue by Kunal951996** [slackapi/node-slack-sdk#1428]
Let's say I want to save the data received after redirect_url and I want to save it against specific user Id. For that how can I pass parameters in install url and maintain it when receiving request from redirect url?

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
node --version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

(Paste the output of 
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`)

#### Python runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hey @Kunal951996, thanks for taking the time to reach out 👋🏻 

Passing state data with the OAuth module is a little awkward and we're in the process of improving it (release coming soon).

For now, you will want to use the [OAuth metadata feature](https://slack.dev/node-slack-sdk/oauth#generating-an-installation-url) to pass data from the install URL to the success redirect_uri. For example:

1. Create a install route such as `/app/install` or `/slack/install` (but not the built-in version)
2. Inside the route, [generate a dynamic url](https://slack.dev/node-slack-sdk/oauth#generating-an-installation-url) with the user's metadata
3. Use a [custom success handler](https://slack.dev/node-slack-sdk/oauth#handling-the-oauth-redirect) to parse the metadata

A rough code sample may look like:

```javascript
app.get('/slack/install', async (req, res, next) => {
  try {
    const url = await installer.generateInstallUrl({
      scopes: ['channels:read', 'groups:read', 'channels:manage', 'chat:write', 'incoming-webhook'],
      metadata: 'some_metadata',
    });

    res.send(`<a href=${url}><img alt=""Add to Slack"" height="40" width="139" src="https://platform.slack-edge.com/img/add_to_slack.png" srcset="https://platform.slack-edge.com/img/add_to_slack.png 1x, https://platform.slack-edge.com/img/add_to_slack@2x.png 2x" /></a>`);
  } catch(error) {
    console.log(error);
  }
});

const callbackOptions = {
  success: (installation, metadata, req, res) => {
    res.send('successful!');
  },
  failure: (error, installOptions , req, res) => {
    res.send('failure');
  },
}

app.get('/slack/oauth_redirect', async (req, res) => {
  await installer.handleCallback(req, res, callbackOptions);
});
```

Hope that helps!

**Comment by filmaj** [comment]
FYI the release candidate for oauth@2.5.0-rc.1 is live on npm (you will need to install it referencing the version directly like so: `npm i @slack/oauth@2.5.0-rc.1`), but I will leave this issue open as I think we still need to add documentation for the new methods we have exposed in this release candidate. Once we have docs in place we will post here and close this issue.

**Comment by seratch** [comment]
The latest version v2.5.0 supports more callbacks to customize your OAuth flow. Refer to the "Persisting data during the OAuth flow" section in the updated document: https://slack.dev/node-slack-sdk/oauth
