### ISSUE TITLE
Catch SSL errors in a more transparent manner

### ISSUE THREAD

**Issue by jpmschuler** [slackapi/node-slack-sdk#1440]
Scenario:
We use @slack/bolt-js and had a hiccup with `chat.postMessage` in our CI after the CI runners where put behind a WAF, where each and every domain/URL needs whitelisting. The WAF will return a self-signed error page in the domain is not whitelisted. Slack wasn't whitelisted for that machine. As chat.postMessage is directly used from web-api, this issue is posted here.

What happened:
The call to https://slack.com/api was blocked by the WAF which resulted in multiple

```
[WARN]  web-api:WebClient:0 http request failed self signed certificate in certificate chain
Error: A request error occurred: self signed certificate in certificate chain
    at Object.requestErrorWithOriginal (/path/to/node_modules/@slack/web-api/dist/errors.js:28:33)
    at /path/to/node_modules/@slack/web-api/dist/WebClient.js:280:36
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/path/to/node_modules/p-queue/dist/index.js:163:29) {
  code: 'slack_webapi_request_error',
```

Annoyance:
The real thing with this problem was not that an exception occurred, however it retried a lot and finally had a timeout after about 23min (instead of failing directly), while retrying an SSL problem in general doesn't seem reasonable.

Solution/Question:
I know that this might be considered an edge case, but would it be possible to either fail this cleanly and directly with an exception or perhaps give options to set timeout or number of retries to reduce this >20min to something more reasonably?

Select all that apply:

- [X] `@slack/web-api`

**Comment by filmaj** [comment]
Hey @jpmschuler thanks for writing in.

Quick question to help me diagnose this better: What version of `@slack/web-api` or `@slack/bolt-js` are you using?

**Comment by filmaj** [comment]
Sorry, after reviewing this a bit deeper, the version you are using may not make much of a difference, ultimately.

I think your considerations on this topic are sound and worthy of discussion. First I will address the easier of your questions: can you customize the retry behaviour? Absolutely! I suggest checking out the documentation on [Automatic Retries](https://slack.dev/node-slack-sdk/web-api#automatic-retries) for this client. The default retry policy is [10 retries in about 30 minutes (randomized slightly, so the time frames are not exact)](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/retry-policies.ts#L10-L19), but there are other retry options you can try that we provide out of the box (see all the [various exports in this file](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/retry-policies.ts)), or even completely customize. Note, though, that the retry behaviour options for outgoing requests apply globally to all requests intended to hit Slack's backend. I think it is worth having that in mind, as in the case that you intend to customize retry behaviour to tweak this specific scenario around a request error during establishing a network connection with Slack's backend, this may also have unintended consequences in other functioning of your application.

However, you can customize the [`retryConfig` constructor parameter](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L157) as you desire. These options get passed directly to the [`p-retry` npm module as the `options` argument](https://github.com/sindresorhus/p-retry#options), so you can do some neat things in there to customize the retry behaviour as you see fit. In particular, in this case, perhaps you may want to add a [`onFailedAttempt` function](https://github.com/sindresorhus/p-retry#onfailedattempterror) to the `retryConfig` to further inspect the error and e.g. throw an error in this specific case that your application code can then more closely watch for and handle.

As for your other question, should these kinds of errors be retried, I think there is no right answer to that question. I can see both sides of this argument: I think retrying request errors makes sense for e.g. transient network hiccups (in fact, our [docs on Automatic Retries even specifically call this scenario out](https://slack.dev/node-slack-sdk/web-api#automatic-retries)), but may make less sense for e.g. SSL certificate issues. It's tough to make everyone happy - but hopefully the workaround I mentioned above and the ability to customize the retry behaviour is sufficient to unblock you in this situation.

Let me know what you think and how it goes!
