### ISSUE TITLE
 The Field in the 'users.profile.get' response does not seem to have a 'label' type.

### ISSUE THREAD

**Issue by 75asa** [slackapi/node-slack-sdk#1452]
(Describe your issue and goal here)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

### Reproducible in:

```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
node --version
sw_vers && uname -v # or `ver`
```

#### The Slack SDK version

6.7.0

#### Python runtime version

v17.0.0

#### OS info

macOS Monterey
Version 12.3

MacBook Pro (14-inch, 2021)
Chip Apple M1 Pro
Memory 32 GB
Startup Disk Macintosh HD
Serial Number R147VN4OXO

#### Steps to reproduce:

```ts
    const profileResponse = await app.client.users.profile.get({
      user: userId,
      include_labels: true,
    });
```

### Question
 The Field in the 'users.profile.get' response does not seem to have a 'label' type.

 There is a Field type in profile.fields in the 'users.profile.get' response, which is currently as follows in src

```ts
export interface Field {
    value?: string;
    alt?: string;
}
```

But actually, when you enable the option `include_labels: true` as shown below, you will get the following response.

```ts
    const profileResponse = await app.client.users.profile.get({
      user: userId,
      include_labels: true,
    });
```

```javascript
{
  // ...
  fields: {
    Xf09R6614KQS: { value: 'U012FEZ9BQ8', alt: '', label: 'Manager' }
    Xf0179U2GMGR: { value: 'Engineering', alt: '', label: 'Division' }
    Xf047M335YN4: { value: 'SlackApp Developer', alt: '', label: 'Title' }
  },
  // ...
}
````

I read the source below.

https://github.com/slackapi/node-slack-sdk/blob/8b6d3806166be139f72b2a8c765566f71d9f3c66/packages/web-api/src/response/UsersProfileGetResponse.ts#L52-L55

If it is listed elsewhere, we would like to know.

### Expected result:

```ts
export interface Field {
    value?: string;
    alt?: string;
    label?: string;
}
```

### Actual result:

```ts
export interface Field {
    value?: string;
    alt?: string;
}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @75asa, thanks for reporting this. This issue will be resolved in the next release.
