### ISSUE TITLE
Block Kit TextInput Interaction Behavior Does Not Work As Expected

### ISSUE THREAD

**Issue by inf3rnus** [slackapi/node-slack-sdk#1461]
#### Packages:

This is package agnostic, didn't know where else to submit the issue.

Select all that apply:

- [x ] Block Kit

### Reproducible in:

https://app.slack.com/block-kit-builder/T0339780GGJ#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22block_id%22:%22section678%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Pick%20items%20from%20the%20list%22%7D,%22accessory%22:%7B%22action_id%22:%22text1234%22,%22type%22:%22multi_static_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20items%22%7D,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22%7D,%22value%22:%22value-0%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22%7D,%22value%22:%22value-1%22%7D,%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22%7D,%22value%22:%22value-2%22%7D%5D%7D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D%5D%7D%5D%7D

#### The Slack SDK version

Not applicable

#### Node.js runtime version

Not applicable

#### OS info

Not applicable

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1. Visit the URL above.
2. Click on the Select Items button.
![image](https://user-images.githubusercontent.com/5959983/162051888-fe2277ff-6c09-4cf0-b8f8-f8b3d606c659.png)
3. Click on the text-input field.
4. Note how the options present themselves in the drop-down menu.
5. Backspace your input so it's empty.
6. Click away from the text input so it is no longer focused.
7. Refocus the text input by clicking it.
8. Note how options no longer present themselves.

### Expected result:
- When backspacing to an empty string, you are presented with the options drop-down again.
- When backspacing to an empty string and then clicking on some other part of the modal outside of the text-input field, and then clicking the text input field again, you are presented with the options drop-down.

### Actual result:

![image](https://user-images.githubusercontent.com/5959983/162052490-f104f7a8-10dd-4f43-a86d-02b237b1aa47.png)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

ADDITIONAL PROBLEM:

Similar problem, clicking away from a text input field that has the options drop-down rendered dismisses the drop-down, but does not remove focus from the text input field.

e.g.

1. First click (Clicked on the text-input field)
![image](https://user-images.githubusercontent.com/5959983/162052652-a7867c20-106b-4434-8ffb-2326e5fef9d5.png)
2. Second click (Clicked outside the text-input field on the background of the modal.)
![image](https://user-images.githubusercontent.com/5959983/162052707-3d4febb5-01f1-4d8a-91e9-bb474355994e.png)

The expectation is that anything that opened up as a result of the initial click that brought focus to the text-input field will be closed. e.g. If I click on the text-input field and it blue borders itself as being focused and opens a drop-down, it should close that drop-down and no longer show the blue border indicating it's focused if i click some other component component of the modal.

**Comment by misscoded** [comment]
Hi @inf3rnus! Thanks for raising this. It's actually the same issue that [another developer raised to us recently](https://github.com/slackapi/bolt-js/issues/1389#issuecomment-1078432180), so it's on our radar and has already been escalated to the responsible team.

As it's a server-side issue and out of the scope of the SDK, we're going to close this issue, but again, thank you for bringing it to our attention! 🙌🏼

**Comment by inf3rnus** [comment]
Thanks @misscoded sg2m!
