### ISSUE TITLE
ERROR: Cannot send message when client is not ready

### ISSUE THREAD

**Issue by kyman2001** [slackapi/node-slack-sdk#1464]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Received the following error while using the BOLT API. Process then terminates. This is happening intermittently (approximately once a week). The process will have been running for some days prior to the error, and operating normally without any errors of any description.

```
[ERROR]  socket-mode:SocketModeClient:0 cannot send message when client is not ready
/usr/local/www/apache24/data/slack/node_modules/@slack/socket-mode/dist/errors.js:63
    return errorWithCode(new Error('Cannot send message when client is not ready'), ErrorCode.NoReplyReceivedError);
                         ^

Error: Cannot send message when client is not ready
    at sendWhileNotReadyError (/usr/local/www/apache24/data/slack/node_modules/@slack/socket-mode/dist/errors.js:63:26)
    at /usr/local/www/apache24/data/slack/node_modules/@slack/socket-mode/dist/SocketModeClient.js:343:60
    at new Promise (<anonymous>)
    at SocketModeClient.send (/usr/local/www/apache24/data/slack/node_modules/@slack/socket-mode/dist/SocketModeClient.js:334:16)
    at ack (/usr/local/www/apache24/data/slack/node_modules/@slack/socket-mode/dist/SocketModeClient.js:473:24)
    at App.processEvent (/usr/local/www/apache24/data/slack/node_modules/@slack/bolt/dist/App.js:536:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SocketModeClient.<anonymous> (/usr/local/www/apache24/data/slack/node_modules/@slack/bolt/dist/receivers/SocketModeReceiver.js:146:13) {
  code: 'slack_socket_mode_no_reply_received_error'
}
```

#### Reproducible in:

package version: 0.24.10

node version:  16.13.0

OS version(s):  FreeBSD 13.0-RELEASE-p6 (GENERIC) #0: Mon Jan 10 06:28:50 UTC 2022

#### Steps to reproduce:

1. Unable to reproduce on demand. This error is intermittent.
2.
3.

#### Expected result:

failure has a documented response and/or allows the program to continue.

#### Actual result:

Error is output then the process stops.

#### Attachments:

No further information.

**Comment by seratch** [comment]
https://github.com/slackapi/node-slack-sdk/pull/1465 will resolve this issue. We are going to release an RC version soon. Please try the RC version out and let us know if you find something wrong with it.

**Comment by seratch** [comment]
👋 Hi, all the developers watching this thread! 

We've improved the `SocketModeClient` internals a lot to be more robust. You can try the updated one by installing the RC version by running the following command:
```bash
npm i @slack/socket-mode@next
# or npm i @slack/socket-mode@1.3.0-rc.0
```

If you are interested in all the changes included in the release, refer to https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fsocket-mode%401.3.0-rc.0 for the details.

If everything goes well, we will release v1.3.0 next week!

**Comment by kyman2001** [comment]
Thank you folks for attending to this issue. I will install the rc after the holiday weekend.

**Comment by seratch** [comment]
[version 1.3.0](https://www.npmjs.com/package/@slack/socket-mode/v/1.3.0) is now available. Please upgrade to the latest version 👋
