### ISSUE TITLE
Fallback argument missing: confusing error text

### ISSUE THREAD

**Issue by saveman71** [slackapi/node-slack-sdk#1476]
Opening a new issue after reading slackapi/bolt-js#1249 which is closed.

@seratch, what was confusing on my end is that the error explicitly refers to a "\`fallback\` argument", so it leads to believe that the missing argument name is `fallback`, whereas it's actually `text`.

Maybe the warning message could be improved?

Suggestion:

```
The `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message which acts as a fallback. It is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
```

**Comment by seratch** [comment]
@filmaj 

Attachments are indeed marked as legacy in the documents but they are used a lot in the real world especially for having a color bar in a message. Thus, just suggesting the top-level `text` or removing the validation for `fallback` in attachments may not be the best way to revise the warning. 

If we would like to improve the warning message to be clearer, the logic to check fallback existence can be:
* If the top-level `text` exists, we can skip warning for `fallback` in any of attachments
* If the top-level `text` does not exist and any of its attachments does not have `fallback` property, we still should warn it (w can say "You should have either top-level text or fallback in all the attachments" if we want to make it more accurate)
* No change to the use case where a message does not have attachments

Does this make sense to you? Also, if we do this, the same change should be done in other Python/Java SDKs.

**Comment by filmaj** [comment]
That makes a lot of sense! I think this is a great, small, but helpful improvement.
