### ISSUE TITLE
not_allowed_token_type upon client.files.sharedPublicURL

### ISSUE THREAD

**Issue by novellizator** [slackapi/node-slack-sdk#1480]
I tried using this package directly and then tried using it through bolt (which has a direct dependency here anyway) and I failed to get the needed response

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version
"slack/bolt": "^3.11.0",
"slack/web-api": "^6.7.1",

#### Node.js runtime version
v16.15.0

#### OS info
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

#### Steps to reproduce:

 ```
 const slackApp = new App({
    signingSecret: secret,
    token: bot,
  });
  
  slackApp.start(3000)
  await slackApp.client.chat.postMessage({text: 'test', channel}) // this works
  await slackApp.client.files.sharedPublicURL({ file: 'F03E6M2CQ02'})
```
Alternatively, using this api directly
 ```
const web = new WebClient(bot);
web.chat.postMessage({ channel, text: 'Hello there' });
web.files.sharedPublicURL({ file: 'F03E6M2CQ02'})
```
### Expected result:
It should make the file public, or get me an error that the file doesn't exist

### Actual result:

```
Error: An API error occurred: not_allowed_token_type
    at platformErrorFromResult (./simple-slack-server/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (./simple-slack-server/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (./simple-slack-server/index.js:62:3) {
  code: 'slack_webapi_platform_error',
  data: { ok: false, error: 'not_allowed_token_type', response_metadata: {} }
}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Hi @novellizator - You need a properly scoped user token to use this API method. You might be using a granular bot token here (should be prefaced with `xoxb-`) when instead you need a token prefaced with `xoxp-`

Here's the api documentation for the [method](https://api.slack.com/methods/files.sharedPublicURL) with the required scopes and more info on [user tokens](https://api.slack.com/authentication/token-types#user)

**Comment by srajiang** [comment]
Related: https://github.com/slackapi/bolt-js/issues/1331

**Comment by novellizator** [comment]
Thank you so much! So for reason I didn't read it out from the official slack documentation.
