### ISSUE TITLE
Downloading WebP image data in an image block fails

### ISSUE THREAD

**Issue by deathcoder** [slackapi/node-slack-sdk#1482]
#### Packages:

Select all that apply:

- [X] `@slack/web-api`

### Reproducible in:
https://app.slack.com/block-kit-builder/TDM8H9KF1#%7B%22blocks%22:%5B%7B%22type%22:%22image%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Please%20enjoy%20this%20photo%20of%20a%20kitten%22%7D,%22block_id%22:%22image4%22,%22image_url%22:%22https://firebasestorage.googleapis.com%252Fv0%252Fb%252Fcheckin-b7e8d.appspot.com%252Fo%252Fimages%252Fflow-Occhiobello-%2528Ro%2529-1651824183328.webp%253Falt%253Dmedia%2526token%253Dc58ee3bd-f900-446d-94e6-7cf1a02cf8c2%22,%22alt_text%22:%22An%20incredibly%20cute%20kitten.%22%7D%5D%7D

note the problem happens even if the image_url is correctly url encoded but when sharing the link doesn't handle url encoded urls well

#### The Slack SDK version

will skip these details since it the problem seems unrelated to the version used

#### Steps to reproduce:

post a message with an image block like the following:

```json
{
	"blocks": [
		{
			"type": "image",
			"title": {
				"type": "plain_text",
				"text": "Please enjoy this photo of a kitten"
			},
			"block_id": "image4",
			"image_url": "https://firebasestorage.googleapis.com%2Fv0%2Fb%2Fcheckin-b7e8d.appspot.com%2Fo%2Fimages%2Fflow-Occhiobello-%28Ro%29-1651824183328.webp%3Falt%3Dmedia%26token%3Dc58ee3bd-f900-446d-94e6-7cf1a02cf8c2",
			"alt_text": "An incredibly cute kitten."
		}
	]
}
```

### Expected result:

the api call works without errors

### Actual result:

```
Unhandled error { Error: An API error occurred: invalid_blocks
    at platformErrorFromResult (/workspace/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/workspace/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slack_webapi_platform_error',
  data:
   { ok: false,
     error: 'invalid_blocks',
     errors:
      [ 'downloading image failed [json-pointer:/blocks/6/image_url]' ],
     response_metadata:
      { messages: [Array], scopes: [Array], acceptedScopes: [Array] } } }
```

**Comment by seratch** [comment]
Hi @deathcoder, thanks for asking the question!

The URL in an image block must be publicly accessible. The URL that you passed returns 400 Bad Request. That's why the image loading fails.

```
$ curl -I 'https://firebasestorage.googleapis.com/v0/b/checkin-b7e8d.appspot.com/o/images/flow-Occhiobello-(Ro)-1651824183328.webp?alt=media&token=c58ee3bd-f900-446d-94e6-7cf1a02cf8c2'
HTTP/2 400
x-guploader-uploadid: ADPycdsa3sikGdoEdxQIolXMwCJytdlhpLlIrdBSxlKaYWM3rpSri34Aolb3P53zUM2YoHtbEggVL4LzW8BJQTFSy2ytKhGtGhHi
x-content-type-options: nosniff
content-type: application/json; charset=UTF-8
access-control-expose-headers: Content-Range, X-Firebase-Storage-XSRF
access-control-allow-origin: *
date: Mon, 09 May 2022 00:02:59 GMT
expires: Mon, 09 May 2022 00:02:59 GMT
cache-control: private, max-age=0
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

To make it functioning, you need to specify a publicly accessible URL in the block.

I hope this was helpful to you.

**Comment by deathcoder** [comment]
Hi @seratch thanks for looking into this, as i said before the website incorrectly handles urlencoded urls, the actual url we are using is this:

https://firebasestorage.googleapis.com/v0/b/checkin-b7e8d.appspot.com/o/images%2Fflow-Occhiobello-(Ro)-1651824183328.webp?alt=media&token=c58ee3bd-f900-446d-94e6-7cf1a02cf8c2

you can see that if you open it in the browser it is publicly available

also:

```
curl 'https://firebasestorage.googleapis.com/v0/b/checkin-b7e8d.appspot.com/o/images%2Fflow-Occhiobello-(Ro)-1651824183328.webp?alt=media&token=c58ee3bd-f900-446d-94e6-7cf1a02cf8c2'                                       ✔  09:38:52
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

what is interesting is that the HEAD method will return 400 as in your previous example:

```
curl -I 'https://firebasestorage.googleapis.com/v0/b/checkin-b7e8d.appspot.com/o/images%2Fflow-Occhiobello-(Ro)-1651824183328.webp?alt=media&token=c58ee3bd-f900-446d-94e6-7cf1a02cf8c2'                                    ✔  09:41:14
HTTP/2 400
x-guploader-uploadid: ADPycdt3TbyPLdgQFXWIFn4vpwdYS7VPhhAPkEW2OqflSwdmkzOlIWieMJO-4mC7a75lUIEYRaS_tNAqQYjcfEp7Y97hEw
x-content-type-options: nosniff
content-type: application/json; charset=UTF-8
access-control-expose-headers: Content-Range, X-Firebase-Storage-XSRF
access-control-allow-origin: *
date: Mon, 09 May 2022 07:41:49 GMT
expires: Mon, 09 May 2022 07:41:49 GMT
cache-control: private, max-age=0
server: UploadServer
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
```

is this the reason it is not working?

as a final example to showcase the url rewrite problem on the website, the image with the last forward-slash rewritten doesn't work either:

```
curl 'https://firebasestorage.googleapis.com/v0/b/checkin-b7e8d.appspot.com/o/images/flow-Occhiobello-(Ro)-1651824183328.webp?alt=media&token=c58ee3bd-f900-446d-94e6-7cf1a02cf8c2'                                         ✔  09:43:25
{
  "error": {
    "code": 400,
    "message": "Invalid HTTP method/URL pair."
  }
}
```

can this be considered a bug of slack or should just firebase allow HEAD methods?

**Comment by seratch** [comment]
@deathcoder Thanks for sharing the valid URL. I found that the endpoint returns WebP image data. Unfortunately, the Slack Block Kit server side does not support the format. To display an image as part of Slack message, your app needs to pass png, jpeg or other image format instead.

**Comment by nerder** [comment]
Hey @seratch, is there an ETA for when `webp` will be supported?

**Comment by seratch** [comment]
@nerder I cannot tell anything at this moment. I'll share this use case with the product/engineering teams but I don't think WebP support will be available in the short term.

**Comment by nerder** [comment]
Ok, no worries at all. If anything changes will be tracked in this issue? I'm asking just for our internal tracking of this.

**Comment by seratch** [comment]
Thanks again for writing in! Since we don't have any further actions for this issue in the short term, let us close this issue now.
