### ISSUE TITLE
What are the required request headers to send a request from postman to Slack/events endpoints

### ISSUE THREAD

**Issue by svasudevareddy-clgx** [slackapi/node-slack-sdk#1484]
I want to setup postman request to test slack/events API and needed what are the required setting, please explain

#### Packagpes:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

(Paste the output of 
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`)

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @svasudevareddy-clgx!

It's difficult to help you directly with Postman usage. In many ways, accessing the Slack API with Postman will be similar to other APIs. I'd recommend posting a question to the Postman support group.

As a starting place, you may find this [Slack Apps & Postman Tutorial](https://api.slack.com/tutorials/slack-apps-and-postman) helpful.

**Comment by svasudevareddy-clgx** [comment]
Thank you for the quick response, also the following link has helped https://api.slack.com/authentication/verifying-requests-from-slack
