### ISSUE TITLE
What URLs to use when passing custom parameters via Add to Slack button with directInstall enabled

### ISSUE THREAD

**Issue by rileysoward** [slackapi/node-slack-sdk#1487]
Hi there,

I am passing in a dynamic `userId` parameter in my app's installation URL and using that userId as a cookie during installation. Example URL: https://myapp/slack/install?userId=user12345 (and thanks @seratch for the recommendation to use cookies)

As expected, currently when I use the link https://myapp/slack/install?userId=user12345 I get the following flow:
1. See plain page with "add to slack" button
2. Click on that button and get sent to /oauth that includes the user12345 in the URL
3. You then confirm you want to install and proceed accordingly

From here, I want to switch to an Add to Slack Button that includes a dynamic parameter depending on UserId and also has directInstall enabled. My question is: what URL do I include in the Add to Slack button and what URL do I include in the Direct install URL in my Slack app config settings?

My understanding is that visiting myapp.com/slack/install?userId=user12345 is what triggers the encoding of userId, so I don't think I can use the URL recommended by: https://api.slack.com/docs/slack-button. I also am not sure what URL to use as the Direct install URL since the userId is dynamic based on user.

Thanks in advance for your help!

**Comment by seratch** [comment]
@rileysoward 

>what URL do I include in the Add to Slack button and what URL do I include in the Direct install URL in my Slack app config settings?

You can use `https://{your app public domain}/slack/install` even for the "Add to Slack" button. All the query string parameters in this URL needs to be converted to cookies before redirecting to slack.com authorize URL.

Does this make sense? If not, I may not fully understand your question. Please elaborate on your goal in a different way.

**Comment by rileysoward** [comment]
@seratch this makes sense. I figured it out! I realized that the URL in Slack app config settings doesn't need to include the dynamic parameters, so I can just use /slack/oauth_redirect there. Thanks, this issue is resolved!
