### ISSUE TITLE
Get useful JSDoc output generated from the code

### ISSUE THREAD

**Issue by l12s** [slackapi/node-slack-sdk#149]
Current JSDoc output isn't especially helpful.

Also would be good to add an npm scripts entry to generate JSDoc

**Comment by ekmartin** [comment]
A bit off-topic for the issue, but maybe it would be nice to move the [usage instructions](https://github.com/slackhq/node-slack-client#usage) and similar to a hosted doc-website, using something like https://readthedocs.org/ or similar?

**Comment by aoberoi** [comment]
i'm going to say this is a dup of #294 and close. If you disagree, please feel free to comment.
