### ISSUE TITLE
Add missing properties to UsersInfoResponse

### ISSUE THREAD

**Issue by AdriannaBeck** [slackapi/node-slack-sdk#1490]
#### Description:

As seen on Slack's documentation page for a [User object](https://api.slack.com/types/user), a user contains an `is_invited_user` property. However, this property is currently not present in the `User` interface in the [UsersInfoResponse](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/response/UsersInfoResponse.ts#L20-L45) file.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hey @AdriannaBeck 👋🏻 Thanks for the TypeScript suggestion!

I agree, I don't see a reason why we can't type `is_invited_user`. Sometimes types are difficult with Slack API responses that are fluid, but I don't believe that's the case here.

Feel free to follow-up with a pull request otherwise one of the maintainers will pick up this issue!

**Comment by neptunel** [comment]
Hello @AdriannaBeck, just wanted to double-check. How are you using the user object type? Do you receive a response including `is_invited_user ` when you make an API call? I wanted to confirm whether this field actually does get sent along with the response payloads, so we can either update the Slack documentation page or the type in the interface.

**Comment by seratch** [comment]
@AdriannaBeck Thanks for taking the time to report this issue. We've confirmed that the flag can exist under some conditions. My pull request https://github.com/slackapi/node-slack-sdk/pull/1491 will resolve this issue.
