### ISSUE TITLE
(Set a clear title describing your idea)

### ISSUE THREAD

**Issue by mutazawad991** [slackapi/node-slack-sdk#1494]
(Describe your issue and goal here)

### List any relevant URLs

- E.g. https://slack.dev/node-slack-sdk/

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
@mutazawad991 It looks like this was accidentally opened. I'm going to close this issue. Please leave a comment if you intentionally opened it and we can help you out.
