### ISSUE TITLE
SocketModeClient still fails to automatically reconnect when apps.connections.open API returns an error code

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#1495]
As reported at https://github.com/slackapi/bolt-js/issues/1428#issuecomment-1153495646, there is still a pattern that SocketModeClient's auto-reconnection does not work. See the repro steps below for details.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

any version including 1.3.0

#### Node.js runtime version

any version

#### OS info

any

#### Steps to reproduce:

Copied from https://github.com/slackapi/bolt-js/issues/1428#issuecomment-1153495646

```
[INFO] A pong wasn't received from the server before the timeout of 5000ms!
[INFO] Reconnecting to Slack ...
[INFO] Going to establish a new connection to Slack ...

[ERROR] Failed to send a message as the client is not ready
[ERROR] An unhandled error occurred while Bolt processed (type: event_callback, error: Error: Failed to send a WebSocket message as the client is not ready)
[ERROR] Failed to send a message as the client is not ready
[ERROR] An unhandled error occurred while Bolt processed (type: event_callback, error: Error: Failed to send a WebSocket message as the client is not ready)

[ERROR] Faled to retrieve a new WSS URL for reconnection (error: Error: An API error occurred: internal_error)
[WARNING] Failed to start a Socket Mode connection (error: An API error occurred: internal_error)
```

And then endless loop of:
```
[ERROR] Failed to send a message as the client is not ready
[ERROR] An unhandled error occurred while Bolt processed (type: event_callback, error: Error: Failed to send a WebSocket message as the client is not ready)
```

Looking into similar occurrences, it is usually able to reconnect, so I think what caused the problem is:
```
Faled to retrieve a new WSS URL for reconnection
Failed to start a Socket Mode connection
```

### Expected result:

The SocketModeClient automatically reconnects when the server-side started working again.

### Actual result:

The reconnection does not happen.

**Comment by levenleven** [comment]
👋 This happened again today https://github.com/slackapi/node-slack-sdk/issues/1500. This time with different error code **fatal_error** instead of **internal_error** (we're using latest `1.3.1` version)
