### ISSUE TITLE
A WebSocket error occurred: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by srigar** [slackapi/node-slack-sdk#1501]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [X] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

```
"slack/bolt": "^3.11.3",
"slack/logger": "^3.0.0",
"slack/oauth": "^2.5.3",
"slack/types": "^2.5.0",
"slack/socket-mode": "^1.3.1",
"slack/web-api": "^6.7.2",
```

#### Node.js runtime version

node 14.19.3

#### OS info

Docker node-alpine-14.19.3

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)
Im just trying to deploy the sample code in the server(GCP) via docker and it is failed to start. The same has been working in my local.

```javascript
const { SocketModeClient } = require("@slack/socket-mode");

const socketModeClient = new SocketModeClient({
  appToken: process.env.APP_TOKEN,
});

socketModeClient.on("message", async ({ event, body, ack }) => {
  await ack();
});

(async () => {
  // Connect to Slack
  await socketModeClient.start();
})();
```

Dockerfile for reference,

```Dockerfile
FROM node:14.19.3-alpine
ENV NODE_ENV production
ENV NODE_TLS_REJECT_UNAUTHORIZED='0'
WORKDIR /usr/local/test
COPY . .
RUN ls -lrt
EXPOSE 8080
CMD ["node", "."]
```

### Expected result:

```
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
```

### Actual result:

```
[ERROR]  socket-mode:SocketModeClient:0 A WebSocket error occurred: Client network socket disconnected before secure TLS connection was established
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ..
```

**Comment by WilliamBergamin** [comment]
Hi @srigar thanks for witting in!

Before I go ahead and try to reproduce this on my end I just want to confirm that the APP_TOKEN environment variable is set in your docker container. The referenced dockerfile does not seem to set this variable, I would enjoy more context as to how this value is passed to the container?

**Comment by seratch** [comment]
@WilliamBergamin Thanks for jumping in! If the tokens are not provided to the Docker containers, the error can be a bit different.

@srigar 
I've verified that your `Dockerfile` works for me in my local machine. Thus, this is obviously an issue specific to your GCP environment. Since we are not here as GCP experts, we are unable to help you out in details here. By googling the error message "Client network socket disconnected before secure TLS connection was established", you will see so many Q&A pages. I hope that you will figure the cause out soon!
