### ISSUE TITLE
Add timezone property to Timepicker block element

### ISSUE THREAD

**Issue by hello-ashleyintech** [slackapi/node-slack-sdk#1502]
### Description

For the [Timepicker block element](https://api.slack.com/reference/block-kit/block-elements#timepicker), we need to add a new optional String property, `timezone`. This needs to be added to the `@slack/types` package.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Fixed by #1503
