### ISSUE TITLE
deprecate `@slack/client` if it's flagged as legacy?

### ISSUE THREAD

**Issue by jimmywarting** [slackapi/node-slack-sdk#1508]
if `@slack/client` is marked as legacy, should you deprecate it then? 
See how: https://docs.npmjs.com/cli/v8/commands/npm-deprecate

**Comment by mwbrooks** [comment]
Hey @jimmywarting, that's a great suggestion and I'm a little surprised that we overlooked it! I'm going to loop in a few teammates/maintainers to double-check that there wasn't a reason why we didn't mark the npm package as deprecated.

@stevengill @seratch Do you know if there's a reason why we haven't marked this package as deprecated in `package.json`?

**Comment by seratch** [comment]
@mwbrooks I am sure that there is no blocker for marking the package deprecated.

**Comment by jimmywarting** [comment]
still not deprecated...

**Comment by hello-ashleyintech** [comment]
I have deprecated the `@slack/client` package and have a PR open to update the package's README to reflect its deprecation. I'll close this issue out once the PR to update the README is added in. 🙌  Thanks again for the awesome suggestion, @jimmywarting!
