### ISSUE TITLE
File Upload API succeeds despite 408 Request Timeout

### ISSUE THREAD

**Issue by edwmurph** [slackapi/node-slack-sdk#1516]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```
    "@slack/web-api": "6.5.1",
```

#### Node.js runtime version

```
16.14.2
```

#### OS info

running on this docker image `node:16.14.2-alpine3.15`

#### Steps to reproduce:

```
const { WebClient } = require('@slack/web-api');
const client = new WebClient( token );
await client.files.upload({ channels, title, initial_comment, content });
```

### Expected result:

i expect the file to be uploaded one

### Actual result:

the request received a 408 despite uploading successfully and then internally retried 6 more times

**Comment by edwmurph** [comment]
relevant: https://github.com/slackapi/python-slack-sdk/issues/1165

**Comment by edwmurph** [comment]
error being logged:
```
web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 408
```

**Comment by srajiang** [comment]
Thanks for posting this issue @edwmurph. This is definitely related to the same server-side issue here: https://github.com/slackapi/python-slack-sdk/issues/1165. At the moment we don't have a good workaround for you for this issue, as it's server-side

I am sorry for the poor experience here. I've marked this as a do not skip in our auto-triage process to make sure it stays open.

**Comment by edwmurph** [comment]
ok no problem thanks for the update and making sure this is getting attention

**Comment by srajiang** [comment]
@edwmurph - I have a bit more detail to share. Appears there's an active incident at the moment resulting in 408 timeouts in more situations than usual. Our backend teams are working on resolving this, and I'll post an update here when that's declared resolved. 

I'm not sure whether the the issue you're seeing at this moment will be resolved by the resolution of the incident, but I will post an update here!

**Comment by srajiang** [comment]
@edwmurph - The incident has an all clear now. Can you give it another try to see if any of the behavior you were seeing has resolved / changed?

**Comment by edwmurph** [comment]
i just tried it a few more times and am no longer seeing that same symptom so i think my issue is resolved thanks for following up!

**Comment by srajiang** [comment]
Oh hurray! I will close this up then :)
