### ISSUE TITLE
users.lookupByEmail not working with valid email

### ISSUE THREAD

**Issue by Bloopis** [slackapi/node-slack-sdk#1523]
### Description

When I'm trying to get user by giving the email, an error is returned saying user is not found even if the email is valid.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### Reproducible in:

package version: 6.7.2

node version: 10.24.1

OS version(s):

#### Steps to reproduce:

1.  Call `users.lookupByEmail` with a valid email
```
const web = new WebClient(tokenSlack);
user = await web.users.lookupByEmail({
        email: 'xx.yy@example.com'
      });
```

#### Expected result:

A valid response object :
```{
    "ok": true,
    "user": {
        "id": "W012A3CDE",
        "team_id": "T012AB3C4",
        "name": "yy",
        "deleted": false,
        "color": "9f69e7",
        "real_name": "xxyy",
        "tz": "America/Los_Angeles",
        "tz_label": "Pacific Daylight Time",
        "tz_offset": -25200,
        "profile": {
            "avatar_hash": "ge3b51ca72de",
            "status_text": "Print is dead",
            "status_emoji": ":books:",
            "real_name": "xx yy",
            "display_name": "yy",
            "real_name_normalized": "xx yy",
            "display_name_normalized": "yy",
            "email": "xx.yy@example.com",
            "image_24": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "image_32": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "image_48": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "image_72": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "image_192": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "image_512": "https://.../avatar/e3b51ca72dee4ef87916ae2b9240df50.jpg",
            "team": "T012AB3C4"
        },
        "is_admin": true,
        "is_owner": false,
        "is_primary_owner": false,
        "is_restricted": false,
        "is_ultra_restricted": false,
        "is_bot": false,
        "updated": 1502138686,
        "is_app_user": false,
        "has_2fa": false
    }
}
```

#### Actual result:

An error message is returned in logs :

```
"Error: An API error occurred: user_not_found
    at platformErrorFromResult (/workspace/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/workspace/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

#### Attachments:

I use the same client to access other slack api services (`users.info`, `conversations.open`) without any errors.

I can retrieve and check  the email if I use the `users.list` with the following code :
```
let list = await web.users.list({
    limit: 1000
});

for (const user of list.members) {
    if(user.profile.email === 'xx.yy@example.com'){
        userID = user.id;
        break;
    }
}
```

I have valid result when I send curl cmd : 
```
curl --data "token=xoxb-xxxxxxxxxxxxxxxxxxxx&email=xx.yy@example.com" https://slack.com/api/users.lookupByEmail
```

**Comment by WilliamBergamin** [comment]
Hi @Bloopis thanks for writing in!

I tried to reproduce this on my end but everything seems to work as intended.
This is the script I'm using
```javascript
const { WebClient } = require("@slack/web-api");

const web = new WebClient(
  "Bot User OAuth Token"
);

(async () => {
  user = await web.users.lookupByEmail({
    email: "my-email@slack.com",
  });

  console.log(user);
})();
```
Make sure you have [users:read](https://api.slack.com/scopes/users:read) a well as [users:read.email](https://api.slack.com/scopes/users:read.email) included in your `Bot Token Scopes` and the app is added to a workspace in which the user is present.

Unfortunately without more information I cannot reproduce your error on my end 💻

**Comment by Bloopis** [comment]
Hello @WilliamBergamin ,

Thanks for your response !

I have the exact same code struc as you. I have tested in local on my PC and it's works well.
My code is running in DialogFlow fulfillment as an Google Cloud function. I made it works 1 time and now every run throw me into `user_not_found` error.

I have changed nothing about rights. My bot already have [users:read](https://api.slack.com/scopes/users:read) a well as [users:read.email](https://api.slack.com/scopes/users:read.email). Moreover I couldn't get the email result for [users.list](https://api.slack.com/methods/users.list) if I haven't setted necessary rights but in fact I got one.

**Comment by WilliamBergamin** [comment]
There could be some sort of issue with DialogFlow fulfillment as a Google Cloud function, but it isn't something I would be able to diagnose.
On the other side of things would you be able to log the emails before executing `web.users.lookupByEmail` in order to  validate that they are the correct emails you want to look up?

**Comment by Bloopis** [comment]
Currently I have disabled the use of the variable.

I use brut string like in ur example but even with that the API return me user_not_found

Here the current code deployed :
```
 // Initialize Slack client
 const web = new WebClient(tokenSlack);
 let userID;

console.log("bubu " + inputID.toString());
let user = await web.users.lookupByEmail({
  email: "test.test@stack-labs.com",
});
console.log(JSON.stringify(user));
userID = user.id;
```

and logs : 
```
2022-08-17 23:17:08.066 CEST | dialogflowFirebaseFulfillment | 4b55d57jeeqg | bubu test.test@stack-labs.com
2022-08-17 23:17:12.943 CEST | dialogflowFirebaseFulfillment | 4b55d57jeeqg | Error: An API error occurred: user_not_found
    at platformErrorFromResult (/workspace/node_modules/@slack/web-api/dist/errors.js:51:33)
    at WebClient.apiCall (/workspace/node_modules/@slack/web-api/dist/WebClient.js:171:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

this is the only method from the API who have this strange behavior.

Other methods called after this one are working without any problem.
```

    //check if we need to get user name from the ID for personalized content
    if (getUserName) {
      let usr = await web.users.info({
        user: userID
      });
      //console.log('DEBUG USER : ' + JSON.stringify(usr));
      userName = usr.user.profile.display_name;

      // now we replace all %USER_NAME% occurences token in content object
      content = JSON.parse(JSON.stringify(content).replace(/%USER_NAME%/g, userName));
    }

    // Open or create a private channel conversation with the specific user.
    // Find more arguments and details of the response: https://api.slack.com/methods/conversations.open
    const privateConv = await web.conversations.open({
      users: userID
    });

    // we need to set the channel in the content
    content.channel = privateConv.channel.id;

    // Post a message to the channel, and await the result.
    // Find more arguments and details of the response: https://api.slack.com/methods/chat.postMessage
    const result = await web.chat.postMessage(content);

    // The result contains an identifier for the message, `ts`.
    console.log(`[SLACK API] Successfully send slack private message ${result.ts} in conversation ${privateConv.channel.id}`);
```

**Comment by Bloopis** [comment]
Hello,

I have made futher investiguations.
It appear that the method is working well now. In my example it was missing "user" object to get access to the rest of fields (`userID = user.user.id;`).

Moreover sometimes dialogflow sometimes not switching on the new cloud function version instantly that lead to more problems during the investiguation.

Conclusion : Method is working well, thanks again to @WilliamBergamin for your help.
