### ISSUE TITLE
`invalid_blocks` error when using type `rich_text`

### ISSUE THREAD

**Issue by marcopiii** [slackapi/node-slack-sdk#1527]
#### Packages:

- [x] `@slack/web-api`

#### The Slack SDK version
```
"slack/web-api": "^6.7.2",
"slack/logger": "^3.0.0",
"slack/types": "^2.7.0",
```

#### Node.js runtime version
```
v12.22.10
```
#### OS info

```
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
```

#### Steps to reproduce:
```
slackWebClient.chat.postMessage({
    channel: "ABC123",
    blocks: [{
        "type": "rich_text",
        "elements": [{
            "type": "rich_text_list",
            "elements": [{
                    "type": "rich_text_section",
                    "elements": [{
                        "type": "text",
                        "text": "First"
                    }]
                },
                {
                    "type": "rich_text_section",
                    "elements": [{
                        "type": "text",
                        "text": "Second"
                    }]
                }
            ],
            "style": "bullet",
            "indent": 0
        }]
    }],
});
```

### Expected result:

I would expect this to work since in the [Slack Block Kit Builder](https://app.slack.com/block-kit-builder/) it seems a legit block

### Actual result:

```
Error: An API error occurred: invalid_blocks
```

**Comment by srajiang** [comment]
Hey @marcopiii - When I put those blocks you supplied into block kit builder, I get a type error, so I'm curious whether there's a version of the sample you provided that block kit builder accepts, or what you're referencing that refers to `rich_text` and `rich_text_list`

Based on [this](https://api.slack.com/reference/block-kit/composition-objects#text) there is `plain_text` and `mrkdwn` as supported types for text.

**Comment by marcopiii** [comment]
I'm can't see any reference to a version of the tool. If it can be useful this is the exact fragment that should allow you to recreate the same block

```
#%7B"blocks":%5B%7B"type":"rich_text","elements":%5B%7B"type":"rich_text_list","elements":%5B%7B"type":"rich_text_section","elements":%5B%7B"type":"text","text":"First"%7D%5D%7D,%7B"type":"rich_text_section","elements":%5B%7B"type":"text","text":"Second"%7D%5D%7D%5D,"style":"bullet","indent":0%7D%5D%7D%5D%7D
```

and this is the preview

<img width="438" alt="Schermata 2022-08-31 alle 20 48 14" src="https://user-images.githubusercontent.com/34537387/187759096-601a1e3f-1d8d-41f2-bde7-5402c54ccd2f.png">

**Comment by seratch** [comment]
@marcopiii Unfortunately, "rich_text" blocks are unavailable for 3rd party Slack apps. Only Slack client apps (Desktop/Web/iOS/Android) can send those blocks to Slack API servers. Block Kit Builder may work with more blocks like you've observed because the tool can be used for crafting a human message too (You can find "Send to Slack" button).

Thus, please go with the blocks listed [here](https://api.slack.com/reference/block-kit/blocks) instead.

**Comment by marcopiii** [comment]
@seratch thank you for the clarification 🙏

A bit off-topic but, is there any other way to represent a real bullet point list for a 3rd part app (I mean, besides using some visual trick like `•` characters)? It looks like `-` doesn't work in the markdown block.

**Comment by seratch** [comment]
@marcopiii I see your point here very well ... but
>using some visual trick like • characters

this is the only way to list items in Slack text messages 🙇 

If everything is clear now, would you mind closing this issue?

**Comment by vvo** [comment]
@seratch
> Unfortunately, "rich_text" blocks are unavailable for 3rd party Slack apps.

Is that still true? I mean, I can definitely craft API requests to send rich_text blocks and it just works

**Comment by seratch** [comment]
@vvo Great question! Almost a month ago, the platform unlocked the feature to 3rd party apps, so as you've noticed, you can now use rich_text blocks in a message and modal inputs!

See also:
* https://github.com/slackapi/java-slack-sdk/pull/1215
* https://github.com/slackapi/python-slack-sdk/pull/1406
* https://github.com/slackapi/bolt-js/pull/1963
* https://github.com/slackapi/node-slack-sdk/pull/1643

**Comment by vvo** [comment]
Nice :)
