### ISSUE TITLE
fallback always renders even if attachments are included

### ISSUE THREAD

**Issue by edwmurph** [slackapi/node-slack-sdk#1528]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`

#### The Slack SDK version

`6.7.2`

#### Node.js runtime version

`16.16.0`

#### OS info

```
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83
Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101
```

#### Steps to reproduce:

<details>
<summary>run this snippet to repro:</summary>

```
const { WebClient }               = require('@slack/web-api');
const { decrypt }                 = require('enigma');
const { channel, botTokenCipher } = require('amp/lib/config').slack.dev;

const blocks = [
  {
    'type': 'header',
    'text': {
      'type': 'plain_text',
      'text': 'header 1'
    }
  },
  {
    'type': 'context',
    'elements': [
      {
        'type': 'mrkdwn',
        'text': '*ctx1:* val1'
      },
      {
        'type': 'mrkdwn',
        'text': '*ctx2:* val2'
      }
    ]
  }
];

const main = async() => {
  const token = await decrypt( botTokenCipher );
  const slack = new WebClient( token );

  await slack.chat.postMessage({
    channel,
    text: 'fallback1',
    attachments: [
      {
        fallback: 'fallback2',
        color: '#ff0000',
        blocks
      }
    ]
  });
};

main()
.then( console.log, console.log )
.finally( () => process.exit( 0 ) );
```
</details>

it renders the fallback even though the attachments are included

<img width="316" alt="image" src="https://user-images.githubusercontent.com/20996513/188017230-0e7be584-16d3-49bb-8b07-d828142a25ed.png">

<details>
<summary>and then when i remove the top level `text` opt</summary>

```
  await slack.chat.postMessage({
    channel,
    attachments: [
      {
        fallback: 'fallback2',
        color: '#ff0000',
        blocks
      }
    ]
  });
```
</details>

<details>
<summary>it no longer renders the fallback message, but now i get a warning in my console:</summary>

```
[WARN]  web-api:WebClient:0 The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
```
</details>

### Expected result:

i need some way to post a slack message with attachments and with a fallback without the fallback rendering and without a console warning

### Actual result:

either i get a warning in the console about not providing a fallback or the fallback is incorrectly posted with the message, despite including an attachment

see previous section for more context

### Notes

related https://github.com/slackapi/node-slack-sdk/issues/1476

**Comment by edwmurph** [comment]
those criteria make sense, but i'm still getting a warning despite including a `fallback` in the attachment

<details>
<summary>e.g. here's a more minimal reproducible test case:</summary>

```
  await slack.chat.postMessage({
    channel,
    attachments: [
      {
        fallback: 'fallback2',
        color: '#ff0000',
        blocks: [
          {
            'type': 'header',
            'text': {
              'type': 'plain_text',
              'text': 'header 1'
            }
          }
        ]
      }
    ]
  });
```
</details>

<details>
<summary>the message posts correctly in slack but i still get the following warning:</summary>

```
[WARN]  web-api:WebClient:0 The top-level `text` argument is missing in the request payload for a chat.postMessage call - It's a best practice to always provide a `text` argument when posting a message. The `text` is used in places where the content cannot be rendered such as: system push notifications, assistive technology such as screen readers, etc.
```
</details>

note how i included a `fallback` in the attachment and omitted the `text` field from the top level

**Comment by seratch** [comment]
Yeah, so I meant this SDK needs to be updated in a future release.

**Comment by edwmurph** [comment]
oh ok sure makes sense, thanks for giving this attention

i created a PR for this to help move it forward https://github.com/slackapi/node-slack-sdk/pull/1529
