### ISSUE TITLE
dependencies in wrong place?

### ISSUE THREAD

**Issue by jimmywarting** [slackapi/node-slack-sdk#1531]
Shouldn't this three be installed as a dev dependency?

https://github.com/slackapi/node-slack-sdk/blob/74087934c636a81be8a0076b3aaaa5de41b9339f/packages/web-api/package.json#L50-L52

cuz right now when i install something then it has to download them eg when i'm deploying it to a server

**Comment by seratch** [comment]
Thanks for writing in. If I understand correctly, these ones still need to be in "dependencies" on this library side to enable library users to smoothly use this SDK in TypeScript.
