### ISSUE TITLE
Creating chat client-server

### ISSUE THREAD

**Issue by Billiardist94** [slackapi/node-slack-sdk#1534]
Hi!
I try to create my application - Chat online, to integrate it on my site and chatting with my collaborators in Slack. Only send and receive messages. 
I initialized server but I don't know, how to connect it with html file.
My server js file:
![190194695-4443ce3f-f2da-46d9-ab3a-1e358935ec2e](https://user-images.githubusercontent.com/21328/190212993-bb3b98b5-7317-4e23-a700-b3ed19ecf8b3.png)
My html file:
![Screenshot_362](https://user-images.githubusercontent.com/50998944/190194907-48908754-dde3-462e-903a-7d73e2cc3494.png)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

my package.json: 
![Screenshot_363](https://user-images.githubusercontent.com/50998944/190195326-36983b67-2e66-4f51-be34-78023aafc3fa.png)

#### Node.js runtime version

v14.19.1

#### OS info

Windows 10 Home, 21H1, 27.‎12.‎2021, 19043.1889

#### Steps to reproduce:

1. Create server js file
2. Create html file
3. Start server

### Expected result:
Connect html with server js file to display chat messages

### Actual result:
Connection problem. The question is how to connect them?

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by Billiardist94** [comment]
Dear @mwbrooks,
Thank you for your response!
I'm using server initialization in separate js file. Just add ExpressJS. 
Try to connect with slack to listen events, but so far unsuccessful.
![Screenshot_365](https://user-images.githubusercontent.com/50998944/190266238-2e9e60d4-5b90-4e83-9475-ed67918c0a7d.png)
This is my another js file with client side to render chat in browser:
![Screenshot_366](https://user-images.githubusercontent.com/50998944/190266377-48b8a568-96d1-4040-901e-b4be74fd13c5.png)
In Browser chat looks like this:
![Screenshot_364](https://user-images.githubusercontent.com/50998944/190266500-b19ca10b-1375-48e4-8211-424ecc1b46ba.png)
In assets folder I keep client files js and css.

**Comment by mwbrooks** [comment]
Hey @Billiardist94 👋🏻 Thanks for clarifying that you're running an Express server and the upload those screenshots.

The setup of your socket mode client looks correct. However, you should listen for a `message` event instead of a `chat message` event. [Here is an example of the listening for the message event with socket mode](https://slack.dev/node-slack-sdk/socket-mode#listen-for-an-event):

```javascript
socketModeClient.on('message', async ({ event }) => {
  console.log(event);
});
```

After making that update, I can you can see message events displaying in your server logs!

**Comment by Billiardist94** [comment]
Dear @mwbrooks,
Yes, thank you!
I changed event to message.
![Screenshot_369](https://user-images.githubusercontent.com/50998944/190342308-1564dda9-e76b-4591-9b2f-1daf0699d582.png)
![Screenshot_368](https://user-images.githubusercontent.com/50998944/190342826-fef0699f-b6bf-48e3-8740-8e96974c477c.png)
And I can receive messages coming from Slaсk. For some reason they are duplicated. I sent one message, and they come a few of the same.

Now I'm going to set up sending messages to Slack. Could you tell me, would it be good to send messages through WebHooks?
