### ISSUE TITLE
Angular App will not build after installing @slack/oauth

### ISSUE THREAD

**Issue by mmartinezcasanova20** [slackapi/node-slack-sdk#1539]
Hello good afternoon, I am trying to integrate the @slack/oauth package to an angular project but it does not work for me when creating the installer.

const installer = new InstallProvider({
clientId: process.env.SLACK_CLIENT_ID,
clientSecret: process.env.SLACK_CLIENT_SECRET,
stateSecret: 'my-state-secret'
});

Could you tell me from where the installProvider should be imported correctly to later use it in the angular component?

Some of the errors I receive on the console when trying to compile my angular project are the following:

./node_modules/@slack/oauth/dist/install-provider.js:54:12-26 - Error: Module not found: Error: Can't resolve 'url' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "url": false }

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:42:27-40 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:43:29-44 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:44:11-24 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:43:11-24 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:44:27-40 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:45:29-44 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/web-api/dist/WebClient.js:126:22-44 - Error: Module not found: Error: Can't resolve 'querystring' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "querystring": false }

./node_modules/@slack/web-api/dist/WebClient.js:128:15-30 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/web-api/dist/instrument.js:27:24-37 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/web-api/dist/instrument.js:28:15-30 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/jwa/index.js:3:13-30 - Error: Module not found: Error: Can't resolve 'crypto' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "crypto": false }

./node_modules/jwa/index.js:5:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/data-stream.js:3:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/data-stream.js:4:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/sign-stream.js:5:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/sign-stream.js:7:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/verify-stream.js:5:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/verify-stream.js:7:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

Cheers,
Thank you very much

**Comment by e-zim** [comment]
Going to close this in favor of #1540! 👋
