### ISSUE TITLE
Angular App will not build after installing @slack/oauth

### ISSUE THREAD

**Issue by mmartinezcasanova20** [slackapi/node-slack-sdk#1540]
Hello good afternoon, I am trying to integrate the `@slack/oauth` package to an angular project but it does not work for me when creating the installer.

```javascript
const installer = new InstallProvider({
  clientId: process.env.SLACK_CLIENT_ID,
  clientSecret: process.env.SLACK_CLIENT_SECRET,
  stateSecret: 'my-state-secret'
});
```

Could you tell me from where the installProvider should be imported correctly to later use it in the angular component?

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Reproducible in:

Angular CLI: 13.3.3
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Steps to reproduce:
Install @slack/oauth using steps found here https://slack.dev/node-slack-sdk/oauth
Run npm run build
Build fails with error above
Expected result:
The build to complete and my Angular App to run successfully

Actual result:
The App does not build correctly I am unable to load anything

**Comment by mmartinezcasanova20** [comment]
Some of the errors I receive on the console when trying to compile my angular project are the following:

./node_modules/@slack/oauth/dist/install-provider.js:54:12-26 - Error: Module not found: Error: Can't resolve 'url' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "url": false }

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:42:27-40 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:43:29-44 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/oauth/dist/installation-stores/file-store.js:44:11-24 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\installation-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:43:11-24 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:44:27-40 - Error: Module not found: Error: Can't resolve 'fs' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

./node_modules/@slack/oauth/dist/state-stores/file-state-store.js:45:29-44 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\oauth\dist\state-stores'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/web-api/dist/WebClient.js:126:22-44 - Error: Module not found: Error: Can't resolve 'querystring' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
- install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "querystring": false }

./node_modules/@slack/web-api/dist/WebClient.js:128:15-30 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/@slack/web-api/dist/instrument.js:27:24-37 - Error: Module not found: Error: Can't resolve 'os' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "os": require.resolve("os-browserify/browser") }'
- install 'os-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "os": false }

./node_modules/@slack/web-api/dist/instrument.js:28:15-30 - Error: Module not found: Error: Can't resolve 'path' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules@slack\web-api\dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "path": false }

./node_modules/jwa/index.js:3:13-30 - Error: Module not found: Error: Can't resolve 'crypto' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "crypto": false }

./node_modules/jwa/index.js:5:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/data-stream.js:3:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/data-stream.js:4:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/sign-stream.js:5:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/sign-stream.js:7:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

./node_modules/jws/lib/verify-stream.js:5:13-30 - Error: Module not found: Error: Can't resolve 'stream' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "stream": false }

./node_modules/jws/lib/verify-stream.js:7:11-26 - Error: Module not found: Error: Can't resolve 'util' in 'C:\Users\slice\Documents\Slice Buyers Front\Client\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "util": false }

**Comment by e-zim** [comment]
Hi @mmartinezcasanova20! Running the `@slack/oauth` package in the browser with an Angular app may require installing a few additional packages to mimic the Node.js runtime environment needed by the Slack Node SDK. If you're interested, this mimicking of functionality is [known as a polyfill](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill)!

The following should hopefully list these missing packages:

- [url](https://www.npmjs.com/package/url)
- [path-browserify](https://www.npmjs.com/package/path-browserify)
- [os-browserify](https://www.npmjs.com/package/os-browserify)
- [querystring](https://www.npmjs.com/package/querystring-es3)
- [util](https://www.npmjs.com/package/util)
- [crypto-browserify](https://www.npmjs.com/package/crypto-browserify)
- [stream-browserify](https://www.npmjs.com/package/stream-browserify)

Or, to install these packages with an all-in-one command:

```sh
npm install url path-browserify querystring util crypto-browserify stream-browserify
```

I hope this can clean up some of those errors!

**Comment by keith88kwok** [comment]
> Hi @mmartinezcasanova20! Running the `@slack/oauth` package in the browser with an Angular app may require installing a few additional packages to mimic the Node.js runtime environment needed by the Slack Node SDK. If you're interested, this mimicking of functionality is [known as a polyfill](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill)!
> 
> The following should hopefully list these missing packages:
> 
> * [url](https://www.npmjs.com/package/url)
> * [path-browserify](https://www.npmjs.com/package/path-browserify)
> * [os-browserify](https://www.npmjs.com/package/os-browserify)
> * [querystring](https://www.npmjs.com/package/querystring-es3)
> * [util](https://www.npmjs.com/package/util)
> * [crypto-browserify](https://www.npmjs.com/package/crypto-browserify)
> * [stream-browserify](https://www.npmjs.com/package/stream-browserify)
> 
> Or, to install these packages with an all-in-one command:
> 
> ```shell
> npm install url path-browserify querystring util crypto-browserify stream-browserify
> ```
> 
> I hope this can clean up some of those errors!

I cannot solve this issue after installing these packages. any advice?

**Comment by zimeg** [comment]
Sorry for missing this one @keith88kwok! We don't currently support runtimes other than Node with this package, but perhaps a library created by @seratch can come in handy: https://github.com/slackapi/node-slack-sdk/issues/1603#issuecomment-1606541205
