### ISSUE TITLE
File Upload API succeeds despite 408 Request Timeout

### ISSUE THREAD

**Issue by SusumuKanazawa** [slackapi/node-slack-sdk#1541]
files.upload API successds despite 408 error.

same, 
python: https://github.com/slackapi/python-slack-sdk/issues/1165
java: https://github.com/slackapi/java-slack-sdk/pull/1065 

sample 
```
// fileSize: 8.4MB

  async fileUpload (filePath) {
    try {
      const client = new WebClient(this.TOKEN, {
        retryConfig: { retries: 1 },
        logLevel: LogLevel.DEBUG
      })

      const file = fs.readFileSync(filePath)
      const filename = path.basename(filePath)

      await client.files.upload({
        channels: this.channelId,
        file,
        filename
      })
    } catch (e) {
      throw new Error(`upload error: ${e}`)
    }
  }
```
error:
```
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 408
[WARN]  web-api:WebClient:0 http request failed An HTTP protocol error occurred: statusCode = 408
upload error: Error: An HTTP protocol error occurred: statusCode = 408

// files upload complete 2 files.
```

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Reproducible in:
slack/web-api: 6.7.2
node: v16.14.0
npm: 8.3.1
Mac OS: 11.6.7

**Comment by seratch** [comment]
Hi @SusumuKanazawa, thanks for taking the time to report this issue. 

We are aware of this and are now working on the fix for it. Please refer to the pull requests adding a new way to upload files in a stable manner:
* https://github.com/slackapi/java-slack-sdk/pull/1065
* https://github.com/slackapi/python-slack-sdk/pull/1272

We will add the same to Node SDK sometime soon!

**Comment by SusumuKanazawa** [comment]
@seratch thanks.

**Comment by srajiang** [comment]
@SusumuKanazawa - Heads up that we have just merged support for `files.uploadV2` in node-slack-sdk and its slated for release v6.8.0!

**Comment by SusumuKanazawa** [comment]
@srajiang very thanks!
