### ISSUE TITLE
Find channel by name without list method

### ISSUE THREAD

**Issue by fmPeretti** [slackapi/node-slack-sdk#1543]
I cant find my channel id from name without the conversation.list api method.
Given that the channel name is unique why couldnt we have a method to look the channel up by name?

In this case im trying to create a channel if this one doenst exist and then invite people to my channel with the conversation.invite method. if the channel creation fails because of "name_taken" then i'd want to invite the peope anyways to that channel because thats telling me that the channel exists.
It'd be awesome if the response of the failed Channel creation method (conversations.create), would also give the channel id of the channel that has the name taken. 
Or even if we were provided of a method to simply look the channel up with the Channel name....

Id rather not save the channel Ids on my DB.

#### Steps to reproduce
1. create a channel
2. dont save channel Id
3. try to Invite people to the channel without the ID and without the conversations.list method.

#### Expected result:
Get the Id by the name of the channel...

#### Actual result:
Theres no way to do this in the actual api apart from iterating all my channels til i find the one that matches my name... wich is  a pain in the ass because of the pagination and because i have lots of channels...

#### Packages:
- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by filmaj** [comment]
Hello,

Unfortunately as far as I can tell, this is still a limitation of the Slack API. Paginating through `conversations.list` is indeed the only painful way to try to search for a channel ID based on name at the moment.

In the mean time, I have raised this question internally to see if there are other options.

**Comment by filmaj** [comment]
I did some digging and asking around and unfortunately I do not have a better answer for you 😭 

At this time, there is no simpler, less painful way to find a channel ID by name 😢

**Comment by fmPeretti** [comment]
Ok! thanks a lot anyways.
I work arround this by pinging with a message the desired channle, (given that i do can send a message to a channel by name) and then with the response harvest the channel id from the channel property, I found this way more appealing than iterating through the paginated 900 slack channels from my company 😆.
Its not perfect but it works allright.

I hope a channelLookUpByName functionality gets implemented to the api on the future.
Please close this issue if you want now. 

Best Regards.

**Comment by filmaj** [comment]
Oooo that's a pretty brilliant workaround! Nice idea 🧠

**Comment by michaelhorty** [comment]
@fmPeretti - your response here should be pushed to the top of about 20 different forums I have looked into. My AI robot and I are incredibly grateful for your genius.
