### ISSUE TITLE
SocketModeClient raise TypeError when running Node.js 19

### ISSUE THREAD

**Issue by lukaszlenart** [slackapi/node-slack-sdk#1546]
### Description

After upgrading to NodeJS 19 I get the following error:

```
/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:295
                        this.logger.error(`Failed to send a WebSocket message (error: ${error.message})`);
                                                                                              ^

TypeError: Cannot read properties of null (reading 'message')
    at Object.callback (/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:295:95)
    at callback (node:internal/streams/writable:555:21)
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10)
```

everything is fine while running on NodeJS 18.11

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] example code related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/bolt/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

package version: 3.12.1

node version: 19.0

OS version(s): macOS 12.6

#### Steps to reproduce:

1. Create a BoltJS app
2. Use socket mode
3. Try to start the app

#### Expected result:

App is running

#### Actual result:

An error

**Comment by seratch** [comment]
Hi @lukaszlenart, thanks for reporting this issue. We will resolve it in the next release.
