### ISSUE TITLE
Slash command returns "invalid_url" error against app in Socket Mode

### ISSUE THREAD

**Issue by NNskelly** [slackapi/node-slack-sdk#1553]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

"slack/bolt": "3.12.1",

#### Node.js runtime version

v16.15.0

#### OS info

Microsoft Windows [Version 10.0.19043.2130]

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)
```
"use strict";
var fs = require('fs');
var path = require('path');
var child_process = require('child_process');
const { App } = require('@slack/bolt'); // npm install @slack/bolt

...

const slackApp = new App({
	token: CONFIG.botToken, // generated upon Install to workspace
	appToken: CONFIG.appToken, // generate at the bottom of Basic Information
	socketMode: true,
});

...

// the command I am making is not literally '/command', 
// this is just a minimal repro sample matching the syntax used
slackApp.command('/command', async ({ command, ack, respond }) => {
	Log("Got command "+JSON.stringify(command));

	// Acknowledge command request
	await ack();

	...
});

(async () => {
	await slackApp.start();
	Log('⚡️ Bolt app started');
})();

```

1. create new App
2. add a slash command (URL entry is mandatory)
3. add an App Level Token for connections:write
4. enable Socket Mode, verify Features Affected: Slash Commands reads Enabled: Yes (slash command pane now indicates URL not necessary, but previously required URL is still entered and not editable)
5. install App on a workspace
6. create a bolt app, initializing with socketMode: true
7. add a command handler for, e.g., `/command`
8. start and run app
9. invoke the `/command` 

### Expected result:

- `/command` handler executes
-- see "Got command ...", etc. in console

### Actual result:

- slackbot immediately returns error `/command failed with the error "invalid_url"`
- app apparently never receives command (but is, allegedly, connected)
```
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
⚡️ Bolt app started
[INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
```

**Comment by NNskelly** [comment]
Update: when I completely remove the slash command definition and add it back with Socket Mode already engaged (move repro step 2 down below repro step 4), it does _not_ prompt for a URL, and invoking the command in slack actually hits my app.

So this is likely an order-of-validations issue somewhere in slack's command handling: if the specified URL has issues (in my case, probably the fact that I needed to specify a junk/local http url since I'm unlikely to ever have a live server of this app), that results in a rejection _before_ Socket Mode is checked, even though a completely empty URL does not trigger a URL rejection.

**Comment by filmaj** [comment]
Hey, thanks for filing this issue @NNskelly ! I will report it back to the App Configuration team.
