### ISSUE TITLE
How to remove SlackDataStore is deprecated warning message

### ISSUE THREAD

**Issue by ykcab** [slackapi/node-slack-sdk#1560]
I am getting the follow error when I start Hubot:
```
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
warn: SlackDataStore is deprecated and will be removed in the next major version. See project documentation for a migration guide.
```
Although it is mentioned here  [#410](https://github.com/slackapi/node-slack-sdk/issues/410), I couldn't locable where to implement the fix within the code

Following this guide https://github.com/slackapi/node-slack-sdk/wiki/DataStore-v3.x-Migration-Guide, search for `dataStore` yield the following:

```
module.exports = (robot) ->
  robot.whitelistRooms = (currentRoomId, whitelist) ->
    group = robot.adapter.client.rtm.dataStore.getGroupById(currentRoomId)
    channel = robot.adapter.client.rtm.dataStore.getChannelById(currentRoomId)
    if group
      currentRoom = group.name
    if channel
      currentRoom = channel.name
    _.contains whitelist, currentRoom
```
From here, I'd like to understand how to actually implement this https://github.com/slackapi/node-slack-sdk/wiki/DataStore-v3.x-Migration-Guide#what-should-i-change-in-my-app-to-prepare-for-v4

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [x] I don't know

#### The Slack SDK version

Package.json
```bash
{
  "name": "mybot",
  "version": "0.0.0",
  "private": true,
  "author": "",
  "description": "my hubot app",
  "dependencies": {
    "aws-sdk": "^2.7",
    "bufferutil": "^4.0.6",
    "child_process": "^1.0.2",
    "gulp": "^4.0.2",
    "gulp-awspublish": "^6.0.2",
    "hubot": "^3.3.2",
    "hubot-diagnostics": "^1.0.0",
    "hubot-google-images": "^0.2.7",
    "hubot-google-translate": "^0.2.1",
    "hubot-help": "^1.0.1",
    "hubot-heroku-keepalive": "^1.0.3",
    "hubot-maps": "^0.0.3",
    "hubot-pugme": "^0.1.1",
    "hubot-redis-brain": "^1.0.0",
    "hubot-rules": "^1.0.0",
    "hubot-scripts": "^2.17.2",
    "hubot-shipit": "^0.2.1",
    "hubot-slack": "^4.8.0",
    "mkdirp": "^1.0.4",
    "npm": "^8.19.2",
    "request": "^2.88.2",
    "underscore": "^1.13.4",
    "utf-8-validate": "^5.0.9",
    "util": "^0.12.4"
  },
  "engines": {
    "node": "^19.x.x"
  }
}
```

#### Node.js runtime version

see package.json

#### OS info

ubuntu

### Expected result:

Remove the warning

**Comment by e-zim** [comment]
Hi @ykcab! To remove the `rtm.dataStore` and the error it's causing, the code from the migration guide should work with a few changes to mimic your function. Both `getGroupById` and `getChannelById` can be replaced by a single call to [the `conversations.info` method](https://api.slack.com/methods/conversations.info) and the channel name can be collected from this response object. An implementation of this might look something like so:

```
{ RtmClient, WebClient } = require('@slack/client');
web = new WebClient('your-token-here');

module.exports = (robot) ->
  robot.whitelistRooms = (currentRoomId, whitelist) ->
    channel = await web.conversations.info(currentRoomId)
      .then(resp => resp.channel)
      .catch(error => console.error("Failed to retrieve channel info: " + error));
    _.contains whitelist, channel
```
