### ISSUE TITLE
API error occurred: invalid_arguments when using files.uploadV2 

### ISSUE THREAD

**Issue by kothaluri07** [slackapi/node-slack-sdk#1563]
Running into a new error while uploading a csv file after upgrading files upload version to V2. 

code block:
```
await getReportData();  //generates report.csv file 
await client.files.uploadV2({
     channel_id: <channel_id>,
     file: './report.csv',
     filename: 'report.csv'
});
```

Error:
```
[ERROR]  web-api:WebClient:1 must be greater than 1 [json-pointer:/length]
[ERROR]: Error: An API error occurred: invalid_arguments
```

If I comment out the `await getReportData();` line in the above code block once the `report.csv` file is generated in the previous runs, the csv file gets uploaded successfully without any issues. 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/socket-mode`

### Reproducible in:
slack/web-api: 6.7.2
slacl/socket-mode: 1.3.2
node: v14.15.4
npm: 7.6.3
Mac OS: 12.4

**Comment by WilliamBergamin** [comment]
Hi @kothaluri07 thanks for bringing this up!

From what I know a few reasons could be causing this, for example the generation of the file may not close the file properly preventing it from being read.
Have you tried sending this file without storing it locally, passing it directly as a `Buffer` or `Stream` to [the `file` parameter](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/methods.ts#L1720)?

**Comment by kothaluri07** [comment]
Thanks for your quick response @WilliamBergamin
I checked the file handling and it does close the file after writing data to it. I tried sending the file content without storing it locally and that's working fine.

**Comment by tiagoacastro** [comment]
Hey @kothaluri07 I see you closed the thread, did you ever find a solution to this?
