### ISSUE TITLE
Can a bot kick out a user from channel?

### ISSUE THREAD

**Issue by jcortes** [slackapi/node-slack-sdk#1564]
#### Packages:
- [x] `@slack/web-api`

#### The Slack SDK version
```
  "dependencies": {
    "@slack/web-api": "^5.15.0"
  }
```

#### Node.js runtime version
```
v14.19.0
```

#### Steps to reproduce:
Call [conversations.kick](https://api.slack.com/methods/conversations.kick) using `Bot Token`

### Expected result:
Be able to kick out a user from channel

### Actual result:
```
{
  "ok": false,
  "error": "restricted_action",
  "response_metadata": {
    "scopes": [
      "bookmarks:read",
      "calls:read",
      "calls:write",
      "channels:history",
      "channels:join",
      "channels:read",
      "chat:write",
      "commands",
      "dnd:read",
      "emoji:read",
      "files:read",
      "files:write",
      "groups:history",
      "groups:read",
      "groups:write",
      "im:history",
      "im:read",
      "im:write",
      "mpim:history",
      "mpim:read",
      "mpim:write",
      "pins:read",
      "pins:write",
      "reactions:read",
      "reactions:write",
      "reminders:write",
      "reminders:read",
      "remote_files:read",
      "remote_files:share",
      "team:read",
      "usergroups:read",
      "usergroups:write",
      "users.profile:read",
      "users:read",
      "users:read.email",
      "users:write",
      "channels:manage"
    ],
    "acceptedScopes": [
      "channels:write",
      "groups:write",
      "mpim:write",
      "im:write",
      "post"
    ]
  }
}
```

**Comment by hello-ashleyintech** [comment]
Hi, @jcortes! 👋 It looks like you're getting a `restricted_action` error, which is defined as `A team preference prevents the authenticated user from kicking.`. This likely means that the user that owns the API token you're using does not have the right roles within your workspace to kick a user from a channel. You can update this permission from your workspace via Settings & administration > Workspace settings > Permissions > Channel management and alter the permissions for "People who can remove members from private channels" and "People who can remove members from public channels" to include the user who owns the token, depending on what channels you're testing in! If you do not have access to this setting, you may need to ask the Workspace or Org owner to update it to include yourself.

I hope this helps, let me know if you have further questions!
