### ISSUE TITLE
How to listen to slash command?

### ISSUE THREAD

**Issue by bastoto** [slackapi/node-slack-sdk#1567]
I want to listen & react to slash command, I tested with event subscribed to my app, but not understanding how to do it with slash command.

#### Packages:
- [x] `@slack/web-api`
- [x] `@slack/socket-mode`

Probably I missed it in the doc, could you help me?

Tried the following without success:

const { SocketModeClient } = require('@slack/socket-mode');
const appToken = 'xxx';
const socketModeClient = new SocketModeClient({appToken});

// Attach listeners to events by type. See: https://api.slack.com/events/message
socketModeClient.on('/myslashcommand', (event) => {
  console.log('message');
});

(async () => {
  await socketModeClient.start();
})();

**Comment by filmaj** [comment]
Hello @bastoto !

Check out this package's [documentation on handling interactivity event](https://slack.dev/node-slack-sdk/socket-mode#listen-for-interactivity-events) - specifically, at the end of the section it discusses that one should listen for a  `slack_commands` event.

Hope that helps!

**Comment by bastoto** [comment]
Thanks a lot @filmaj I will test this out :)
