### ISSUE TITLE
Change text in default slack/oauth_redirect

### ISSUE THREAD

**Issue by adelebendayan** [slackapi/node-slack-sdk#1574]
(Describe your issue and goal here) 
Hi,
I'm trying to submit my app to the slack workspace, and I got a rejection, that "Slack App" needs to be changed to "App for Slack", which is a text that is provided by the @slack/oauth package.
As far as I understand I can set my own success callback and set my own text there, but It would be great if by default it comes with the right text  
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @adelebendayan, thanks for writing in!

>I'm trying to submit my app to the slack workspace, and I got a rejection

Could you tell a bit more details on this? 

Are you trying to get an approval from your workspace admins? If yes, we may not change the wording for now.

If you're communicating with the [App Directory](https://my.slack.com/apps) team for listing your app as one of publicly available on the site, we will talk to them to be on the same page early next year. In this case, we may change the default wording as necessary.

**Comment by adelebendayan** [comment]
Hi, yes it's for the App Directory
