### ISSUE TITLE
Is it possible to set Timeout on send()?

### ISSUE THREAD

**Issue by austinp0wers** [slackapi/node-slack-sdk#1576]
(Describe your issue and goal here)

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ O ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
    "@slack/webhook": "^6.0.0",

#### Node.js runtime version
    v16.15.0

#### OS info
mac OS Ventura

I would like to add timeout for this hook
as i am planning on running this onApplicationShutdown
However it seems like there are no such options as timeout in this function.

<img width="435" alt="스크린샷 2022-12-28 오전 10 04 59" src="https://user-images.githubusercontent.com/95058190/209741834-0b925bf6-27ef-4354-bd3d-d9404e670857.png">

**Comment by seratch** [comment]
Hi @austinp0wers, you can pass `timeout` when initializing an `IncomingWebhook` instance: https://github.com/slackapi/node-slack-sdk/blob/%40slack/webhook%406.1.0/packages/webhook/src/IncomingWebhook.ts#L106 

The `timeout` value is a duration in milliseconds.

```javascript
// Setting 1000 milliseconds
const webhook = new IncomingWebhook(token, { timeout: 1000 });
```
