### ISSUE TITLE
Security: `@slack/oauth` depends on vulnerable version of `jsonwebtoken": "^8.5.1"`

### ISSUE THREAD

**Issue by philipp-tailor** [slackapi/node-slack-sdk#1578]
Vulnerabilities of used version of `jsonwebtoken`:
- https://github.com/advisories/GHSA-27h2-hvpr-p74q
- https://github.com/advisories/GHSA-8cf7-32gw-wr33
- https://github.com/advisories/GHSA-hjrf-2m68-5959
- https://github.com/advisories/GHSA-qwph-4952-7xr6

The vulnerable version is specified [here](https://github.com/slackapi/node-slack-sdk/blob/8fc8cc660e4ba6b5b2f9310a78234ae20a3482d7/packages/oauth/package.json#L46). 

All of these would be solved by upgrading `jsonwebtoken` to `9.0.0` upwards.

Upgrading it would be a breaking change requiring a major version bump, due to lifting Node.js minimum version.

**Comment by franciscolourenco** [comment]
Looks like `jsonwebtoken` has been upgraded to `^9.0.0` in `@slack/oauth@2.6.0` https://github.com/slackapi/node-slack-sdk/pull/1575/files#diff-2d22085daddc4de31e33d31b69e107b545e364b486810fcf5d5072a73b7bed47L46
