### ISSUE TITLE
Document types introduced in @slack/types ^2.8.0

### ISSUE THREAD

**Issue by zimeg** [slackapi/node-slack-sdk#1588]
New types are introduced in the @slack/types version bump by #1559 that warrant documentation with information on how to leverage them in the web-api package.

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
@zimeg which types and where do you think we should document this?

**Comment by zimeg** [comment]
@filmaj I think only types from #1512 and #1549 were introduced in [@slack/types@2.8.0](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Ftypes%402.8.0). Happy to follow up on this, but I'm now not sure if these need explicit documentation beyond those release notes 🤔

**Comment by filmaj** [comment]
Yeah I mean, the types themselves are JSdoc'ed up the wazoo, so I'm not sure what kind of web-api-specific docs were meant here?

Can we close this?

**Comment by zimeg** [comment]
Totally agree that JSdoc has this covered 🙌 I forget the exact context around this too... Let's close it!
