### ISSUE TITLE
Different video block unfurl behavior for desktop vs. mobile Slack client

### ISSUE THREAD

**Issue by k1mmm** [slackapi/node-slack-sdk#1592]
Hello, I'm building an slack app that unfurls links and I'm sending back a video block. The problem is I want to show different response whether or not the user is on the mobile app or desktop app.

Youtube shows different blocks depending on if it's on mobile or desktop its unfurling. Can I somehow achieve the same by specifying blocks for desktop and mobile?

**Comment by srajiang** [comment]
Hey @k1mmm - Awesome to hear that you're working with the video block 🎉 .

I don't have the answer to this question at the moment, but I've shot a message over to the team internally to see what they have to say. I'll get back to you when I get more details from them.

**Comment by k1mmm** [comment]
Awesome thanks!

If it's not possible to create specific blocks for mobile/desktop, is it possible to to make an image a clickable web link? Either by using markdown or with your image block/element?

**Comment by k1mmm** [comment]
@srajiang But isn't this what's happening to Loom and YouTube unfurls? They show a video block on desktop, and a section block with a link on mobile, and my guess is this is because on mobile your not getting the native video player from chrome/safari when using embedded videos, and by having it as a section with a link your also checking if the user has the app installed to do a deep linking within the app instead.

I'll post a feature request for clickable images for sure! Thanks =)
