### ISSUE TITLE
Calling chat.postMessage with as_user argument returns deprecated_argument

### ISSUE THREAD

**Issue by jcserv** [slackapi/node-slack-sdk#1593]
Hi there, it looks like a breaking change was made to the `chat.postMessage` API which hasn't been updated in this sdk. 

Calling it with as_user provided returns the deprecated_argument error, however it's defined in ChatPostMessageArguments and listed as a legacy argument in the docs (https://api.slack.com/methods/chat.postMessage#arg_as_user). 

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

`@slack/web-api": "^6.7.1"`
`"@slack/bolt": "^3.12.2"`

``

#### Node.js runtime version

`v18.12.1`

#### OS info

```
ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68
Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
```

#### Steps to reproduce:

1. Call client.chat.postMessage() with as_user: false
```
client.chat.postMessage({
      blocks: this.message.blocks,
      channel: this.message.channel,
      text: this.message.text,
      as_user: false,
    });
```

Feel free to use my project when trying to repro this:

Source code: https://github.com/jcserv/ez-pr-bot/pull/54

Project env:
```
NODE_ENV=development
SLACK_APP_ID=<fill this in>
SLACK_SIGNING_SECRET=<fill this in>
SLACK_CLIENT_ID=<fill this in>
SLACK_CLIENT_SECRET=<fill this in>
STATE_SECRET=<fill this in>

DATABASE_URL="file:./dev.db"
```

### Expected result:

Since it's deprecated, I would expect the postMessage to succeed with a warning - but in lieu of that then this should be removed from ChatPostMessageArguments.

### Actual result:

```
[DEBUG]  web-api:WebClient:2 http request result: {"ok":false,"error":"invalid_arguments","deprecated_argument":"as_user","response_metadata":{"scopes":["app_mentions:read","channels:join","channels:history","chat:write","chat:write.public","commands","emoji:read","im:write","reactions:read","reactions:write","users:read","usergroups:read","workflow.steps:execute"],"acceptedScopes":["chat:write:bot"]}}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @jcserv, thank you for reporting this issue, and we apologize for any confusion regarding the legacy parameter.

As outlined in the API documentation as below, 
>(Legacy) Pass true to post the message as the authed user instead of as a bot. Defaults to false. Can only be used by classic Slack apps. See authorship below.

this parameter is still valid for _"classic"_ permission model apps (if you're not familiar with Slack's old permission model, no need to worry about this!). This is why we still keep the argument in all the SDKs.

The legacy parameter may be removed in the future when our platform ends support for "classic" apps. That being said, we don't have any concrete plans to do so at least in the short term. There are still a lot of customers relying on the legacy feature across the world.

With the latest permission model, there are two ways to post a message on behalf of a user using the latest permission model. The first is to use a user token that begins with `xoxp-`. This will post the message as the user, allowing them to edit and delete the message. The alternative approach is to use the `chat:write.customize` scope along with `username` and `icon_url` parameters. This method will post the message as the app's bot user, but with the user's name and icon. Please refer to https://api.slack.com/methods/chat.postMessage#authorship for more information.

Thanks again for writing in! and I hope this helps if there was anything unclear to you with the latest recommended way.

**Comment by jcserv** [comment]
Gotcha, thank you for the detailed explanation!

**Comment by filmaj** [comment]
Closing this as it seems nothing more to do in this issue.
