### ISSUE TITLE
Minor change is required on official documentation 

### ISSUE THREAD

**Issue by rohit1kumar** [slackapi/node-slack-sdk#1594]
On the official [slack documentation](https://api.slack.com/messaging/sending#publishing) on the website, while publishing a message

`const result = await app.client.chat.postMessage({})`
`app` should be removed, right now It's throwing ReferenceError.

### List any relevant URLs
Correct version https://github.com/slackapi/node-slack-sdk#posting-a-message-with-web-api

**Comment by seratch** [comment]
Hi @rohit1kumar, thanks for taking the time to report this issue. The team is now fixing the problem 🙇
