### ISSUE TITLE
Sending message with files with custom bot username 

### ISSUE THREAD

**Issue by giri-nitesh** [slackapi/node-slack-sdk#1595]
Hello, I am using web-api to [post](https://api.slack.com/methods/chat.postMessage) message with any kind of files, with custom username set for bot.

The way I am doing is: 

- Upload files with files.upload API
- Grab file permalink from uploaded file response
- Send message text along with file permalink. Message would look something like this:
`This is text to be posted. <file_permalink_1| ><file_permalink_2| >`

I have taken this approach from this [stackoverflow post](https://stackoverflow.com/questions/59939261/send-multiple-files-to-slack-via-api)

#### Expected Result 
A message is sent along with the files embedded in message. Slack automatically downloads the files sent in message.

#### Actual Result 
If username is set in chat.postMessage API, files aren't shown in the channel - just message text is shown. If I don't use username, it works as expected.

Wanted to check if I am missing something here, or there could be a better way around this. Thanks in advance.

#### Packages:

- [ ] `@slack/web-api`

**Comment by filmaj** [comment]
Can you share the payload you are invoking `chat.postMessage` with?

**Comment by giri-nitesh** [comment]
This is the payload:

` {"channel":"C04RM9RB75Z","text":"Message with attachment <slack_file_permalink| >","username":"My Bot"}`

**Comment by filmaj** [comment]
Check out the section under "Legacy Concerns" for the `chat.postMessage` API: https://api.slack.com/methods/chat.postMessage#legacy

Essentially: unless you are using a 'classic' app, using the old way of managing bot permissions (i.e. a single, overarching `bot` umbrella token), options like changing the bot username are not available to you. "Modern" Slack apps use fine-grained permissions: different scopes registered by your bot, each scope encapsulating some specifically scoped amount of permissions the bot requires to perform its function. If you are using fine-grained permissions (which is recommended, as it is a better/more secure experience for end-users), then you cannot change the bot's name. Whatever you register the bot's name as under api.slack.com/apps will be what displays in the Slack client as the bot's username.

So, _unless_ you are using legacy permissions with your bot, this behaviour is expected.

**Comment by giri-nitesh** [comment]
@filmaj If I don't use file links in the message text, it would work as expected - I can change the name of bot. When I use file permalink in the message text, slack doesn't show these files.

**Comment by filmaj** [comment]
I see, that does indeed sound weird.

Let me try to reproduce the behaviour and I will see about potentially escalating this to the backend team.

**Comment by giri-nitesh** [comment]
Meanwhile, is there any work around to share files with custom bot name ?
That is, the ability to send a message with files with the custom bot name ?

**Comment by filmaj** [comment]
> If username is set in chat.postMessage API, files aren't shown in the channel - just message text is shown. If I don't use username, it works as expected.

Hmm, I can't reproduce this exact behaviour but I can't change the bot username either - which matches my original response to your question. Here is my (bolt-js) code:

```
app.message('hello', async ({ message, say, client }) => {
  console.log('uploading file...');
  const fileResp = await client.files.upload({
    content: "hello world!",
    filename: "foo.txt",
    title: "My Test File"
  });
  console.log('posting message...');
  await client.chat.postMessage({
    channel: message.channel,
    text: `This is text to be posted. <${fileResp.file.permalink}| >`,
    username: `BotName${Math.random()}`
  });
  console.log('all done!');
});
app.message('no-file', async ({ message, say, client }) => {
  console.log('posting file-less message...');
  await client.chat.postMessage({
    channel: message.channel,
    text: `This is text to be posted without a file, can we change the bot name?`,
    username: `BotName${Math.random()}`
  });
  console.log('job done!');
});
```

My app responds to two message types: 
1. a message containing "hello" will upload a file, then post a message containing a permalink to the file as well as set the `username` on the post to something random
2. a message containing "no-file" will just post a message setting `username` to something random.

Here is the Basic Information section of my app on api.slack.com/apps:

<img width="694" alt="Screenshot 2023-03-16 at 9 06 20 AM" src="https://user-images.githubusercontent.com/52645/225626003-e1344281-ab1e-4e48-81b6-beb30304ce45.png">

And here are the two event interactions with my app:

<img width="351" alt="Screenshot 2023-03-16 at 9 06 45 AM" src="https://user-images.githubusercontent.com/52645/225626106-f6694fcd-4ced-412c-882b-400ff467358c.png">

<img width="537" alt="Screenshot 2023-03-16 at 9 06 59 AM" src="https://user-images.githubusercontent.com/52645/225626145-bec2dec9-8f9a-4a43-95a3-ca9f22b7c810.png">

As you can see, the username is not changed in either case - the bot name as set on api.slack.com/apps is always honoured - which matches my expectation.

**Comment by giri-nitesh** [comment]
That's weird. I have been using `username` field to change bot name for text messages. I could even reproduce that with the [slack test api](https://api.slack.com/methods/chat.postMessage/test) as well, by using token and filling username, channel and text field.

**Comment by filmaj** [comment]
What kind of a token is it? a `xoxb-`?
