### ISSUE TITLE
files.uploadV2 - getFileAsDataStream returns partial file data resulting in partial file uploads

### ISSUE THREAD

**Issue by mwbeckner** [slackapi/node-slack-sdk#1601]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:
file-upload.js
Select all that apply:

- [x ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
6.8.1

#### Node.js runtime version
14.18.3

#### OS info
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112

#### Steps to reproduce:
1. unzip files-uploadV2-issue-test.zip
2. cd ./files-uploadV2-issue-test
3. npm install
4. npm test

### Expected result:
Uploaded file size should be 100000 bytes

### Actual result:
Actual uploaded file size is limited to the size of the first chunk read from the stream.
The test output will show DEBUG logging.

### Requirements
requires mocha and slack-web-api packages

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.
[files-uploadV2-issue-test.zip](https://github.com/slackapi/node-slack-sdk/files/11125327/files-uploadV2-issue-test.zip)

**Comment by mwbeckner** [comment]
I forgot to add that a Slack API token and a channel_id are required for testing.

**Comment by seratch** [comment]
Hi @mwbeckner, thanks for reporting this issue! I've confirmed that I can reproduce the issue with you code snippet (thanks a lot for sharing it). As you pointed out in the title of this issue, the internal [getFileAsDataStream](https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%406.8.1/packages/web-api/src/file-upload.ts#L153-L171) method needs improvements for resolving this issue.

@srajiang if you have the bandwidth to work on it next week, you may want to resolve it as the original author of the method. If you're busy with other things, I can look into it.

**Comment by mwbeckner** [comment]
I think the fix is a simple one ...  the content should be returned on stream.end ...

`export async function getFileDataAsStream(readable: Readable): Promise<Buffer> {
  const chunks: Uint8Array[] = [];

  return new Promise((resolve, reject) => {
    readable.on('readable', () => {
      let chunk: Buffer;
      /* eslint-disable no-cond-assign */
      while ((chunk = readable.read()) !== null) {
        chunks.push(chunk);
      }
    });
    readable.on('end', () => {
      if (chunks.length > 0) {
        const content = Buffer.concat(chunks);
        resolve(content);
      } else {
        reject(Error('No data in supplied file'));
      }
    });
  });
}`

**Comment by seratch** [comment]
Thanks, I was also assuming that some changes like you suggest should be necessary. Our team will resolve the issue and ship a new version next week. Thanks again for flagging this!

**Comment by srajiang** [comment]
@mwbeckner - I've just merged this fix and another release is forthcoming. Thanks again for reporting this!

**Comment by filmaj** [comment]
This is now live in v6.9.0 on npm.
