### ISSUE TITLE
UsergroupsListResponse.d.ts Usergroup interface is missing optional users field

### ISSUE THREAD

**Issue by aneff-figma** [slackapi/node-slack-sdk#1606]
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`

#### The Slack SDK version

(Paste the output of)
6.7.1

#### Node.js runtime version

v16.17.1

#### Steps to reproduce:

1. Write `client.usergroups.list({include_users: true}).usergroups.at(0).users` and typescript will complain that there is no user field.
2. Go view the `/node_modules/@slack/web-api/dist/response/UsergroupsListResponse.d.ts` file. Usergroup is missing the users field.

### Expected result:

It should not be missing the Usergroup field

**Comment by seratch** [comment]
Hi @aneff-figma, thanks for taking the time to report this issue! We will improve this in future releases.

**Comment by aneff-figma** [comment]
🙌

**Comment by filmaj** [comment]
This is now live in v6.9.0 on npm.
