### ISSUE TITLE
How to use views.publish endpoint

### ISSUE THREAD

**Issue by yu1hpa** [slackapi/node-slack-sdk#1607]
This is almost my first issue, so please cut me some slack.

I would like to use /api/views.publish endpoint to send to home tab.
I use `callWebApi` from @seratch's article [web-api-はシンプルなコードを使いましょう](https://qiita.com/seratch/items/2158cb0abed5b8e12809#web-api-%E3%81%AF%E3%82%B7%E3%83%B3%E3%83%97%E3%83%AB%E3%81%AA%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E4%BD%BF%E3%81%84%E3%81%BE%E3%81%97%E3%82%87%E3%81%86)
Also, I would like to use GAS to handle process, so I can't use bolt instead of it.

#### Packages:

Select all that apply:

- [x] I don't know

#### The Slack SDK version
```
"slack/web-api": "^6.8.1"
```
FYI, I use it for just using type.

#### Node.js runtime version
```
v18.14.2
```
#### OS info

```
ProductName:    macOS
ProductVersion: 12.6.2
BuildVersion:   21G320
Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

```js
function callWebApi(apiMethod: string, payload) {
  const response = UrlFetchApp.fetch(`https://slack.com/api/${apiMethod}`, {
    method: "post",
    contentType: "application/x-www-form-urlencoded",
    headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` },
    payload: payload,
  });
  console.log(`Web API (${apiMethod}) response: ${response}`);
  return response;
}
```

```js
          callWebApi("views.publish", {
            "user_id": userId,
            "view": {
              "type": "home",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "This is a plain text section block.",
                    "emoji": true
                  }
                }
              ]
            }
          });
```

### Expected result:

To be sent to home tab.

### Actual result:

```
Web API (views.publish) response: {"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] failed to match all allowed schemas [json-pointer:\/view]","[ERROR] must provide an object [json-pointer:\/view]","[ERROR] must provide an object [json-pointer:\/view]"]}}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hey @yu1hpa, thanks for writing in! Indeed, the example code does not work for views.open API method. I just updated the code snippet as below:
```javascript
function callWebApi(token, apiMethod, payload) {
  const params = {};
  Object.assign(params, payload);
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "object") {
      params[key] = JSON.stringify(value);
    }
  } 
  const response = UrlFetchApp.fetch(
    `https://www.slack.com/api/${apiMethod}`,
    {
      method: "post",
      contentType: "application/x-www-form-urlencoded",
      headers: { "Authorization": `Bearer ${token}` },
      payload: params,
    }
  );
  console.log(`Web API (${apiMethod}) response: ${response}`)
  return response;
}
```
The above code should work for you!

Since this repository does not support Google Apps Script, let us close this issue now. If you have follow-up questions, please let me know by posting comments on Qiita.
