### ISSUE TITLE
re-installing app the permissions don't change

### ISSUE THREAD

**Issue by ksuchitra532** [slackapi/node-slack-sdk#1611]
Select all that apply:

- [ ] `@slack/oauth`

re-installing app the permissions don't change

1. Add scope to oauth bot
2. requested to re-install app
3. tried running the app with modified permissions 
4. no change keeps getting error `missing_scope`
5. requested to re-install
6. still the same

I still keep getting this error even though re-installing app not once but twice 
`You've changed the permission scopes your app uses. Please reinstall your app for these changes to take effect (and if your app is listed in the Slack App Directory, you'll need to resubmit it as well).`

**Comment by srajiang** [comment]
Hi @ksuchitra532 - Thanks for writing in!

Can you please provide your App ID (should start with an A) and which scope is supposed to be there but which you're getting the error for? Are you currently using the App Config > Oauth & Permissions > Reinstall the App config page to reinstall the app? 

![Group 1 (1)](https://user-images.githubusercontent.com/55667998/234355867-f3fff13e-2bf0-44d3-ae8f-b8f021f88bce.png)

**Comment by seratch** [comment]
@ksuchitra532 If you enable the OAuth flow and you're trying to install the app through the process starting at "/slack/install", please double-check the scopes parameter you set: https://slack.dev/node-slack-sdk/oauth#showing-an-installation-page Just adding new ones on the app admin page (meaning api.slack.com/apps/{your app id}) does not change the set of scopes in your code.

**Comment by srajiang** [comment]
Hi @ksuchitra532 - Did this help to resolve the issue you were seeing?

**Comment by ksuchitra532** [comment]
Hi @srajiang no

**Comment by sachinagr1293** [comment]
hi, i created a new app with my desired permissions and then i installed it but it still keeps saying "missing_scope". i keep getting reinstall even though i installed the app for the first time after making changes in oauth scope
 #

<img width="1723" alt="Image" src="https://github.com/user-attachments/assets/2661d26e-62f9-4c58-bd42-c63083d59ae3" />
