### ISSUE TITLE
Incorrect type for `Confirm.text`

### ISSUE THREAD

**Issue by ducminh-phan** [slackapi/node-slack-sdk#1612]
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

`@slack/types@2.8.0`

#### Node.js runtime version

N/A

#### OS info

N/A

#### Steps to reproduce:

N/A

### Actual result:

https://github.com/slackapi/node-slack-sdk/blob/ea0483cb71ae22cf6c94866478df351a90f1db7f/packages/types/src/index.ts#L104-L110

### Expected result:

According to [the doc](https://api.slack.com/reference/block-kit/composition-objects?ref=bk#confirm), the type of `text` should be `PlainTextElement` instead of `PlainTextElement | MrkdwnElement`

**Comment by srajiang** [comment]
@ducminh-phan - I believe the documentation in this case is incorrect. Are you having issues using the type? 

If not, we'll get this fixed on the documentation.

**Comment by ducminh-phan** [comment]
@srajiang I think the documentation is correct in this case. I have tested and even with `text.type` of `mrkdwn`, the text is rendered as plain text. Testing with Block Kit Builder yields the same result.

```json
{
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "This is a section block with an overflow menu."
			},
			"accessory": {
				"type": "overflow",
				"options": [
					{
						"text": {
							"type": "plain_text",
							"text": "*this is plain_text text*",
							"emoji": true
						}
					}
				],
				"confirm": {
					"title": {
						"type": "plain_text",
						"text": "Title"
					},
					"text": {
						"type": "mrkdwn",
						"text": "test `code`"
					}
				}
			}
		}
	]
}
```

<img width="958" alt="image" src="https://user-images.githubusercontent.com/25957952/236260726-5fc348ab-0996-40c6-8e70-d1846b34d3d9.png">

**Comment by ducminh-phan** [comment]
@srajiang Any update?
