### ISSUE TITLE
`files.uploadV2` returns `missing_scope` error but still posts message

### ISSUE THREAD

**Issue by mok0230** [slackapi/node-slack-sdk#1620]
I have a bot token with the scope specified in the [files.upload docs ](https://api.slack.com/methods/files.upload): `files:write`. When I execute `files.uploadV2` it posts successfully but returns an error for `missing_scope`. Part of me is wondering if `files.uploadV2` requires a different scope than `files.upload` but I didn't see a documentation page for `files.uploadV2`. Even so, it is odd to have it post successfully but return an error.

I was able to inspect the error object and says it requires `files.read` scope but unsure why this is the case.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```
@slack/web-api": "^6.8.1"
```

#### Node.js runtime version

```
v16.15.0
```

#### Steps to reproduce:

* Create a bot with `files:write` scope
* Add that bot to channel `channelId` (see below)
* Execute this method:
```
await slack.files.uploadV2({
        initial_comment: message,
        channel_id: channelId,
        file,
      });
```

### Expected result:

The message posts successfully on the specified channel and returns 200 success

### Actual result:

The message **posts successfully** on the specified channel but returns an error for `missing_scope`

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by mwbrooks** [comment]
Hi @mok0230 👋🏻

First off, a sincere apology for my slow response and a thanks a ton for the details that you provided! 🙇🏻

The `files.uploadV2` function can be a little confusing and it's completely understandable that you'd ask yourself why the `files.read` scope is required. I did as well!

The backstory is that `files.uploadV2` is a helper function by the SDK to simplify uploading files. [Here is a nice explanation of why it exists](https://slack.dev/node-slack-sdk/web-api#upload-a-file). Behind the scenes, the method calls 3 APIs: 
1. `files.getUploadURLExternal`
2. `files.completeUploadExternal`
3. `files.info`

The [`files.info` API method](https://api.slack.com/methods/files.info) is the culprit that requires the `files.read` scope. The good news is that this is an optional step and you can [disable it by passing in the option `request_file_info: false`](https://github.com/slackapi/node-slack-sdk/blob/de292304955e7980f96b6593f79c3b8bedcdf6a6/packages/web-api/src/WebClient.ts#L434C17-L436) to the `files.uploadV2` function:

```typescript
await slack.files.uploadV2({
        initial_comment: message,
        channel_id: channelId,
        file,
        request_file_info: false,
      });
```

Let me know how that goes for you and happy weekend! ⚡ 🧑‍💻 ⚡

**Comment by mok0230** [comment]
Thanks for this detailed explanation!
