### ISSUE TITLE
hard to debug 400 status

### ISSUE THREAD

**Issue by sibelius** [slackapi/node-slack-sdk#1627]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Reproducible in:

```javascript
const wh = new IncomingWebhook(config.slackWebhook);
const result = await wh.send({
  blocks,
});
```

#### The Slack SDK version

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`

6.1.0

#### Node.js runtime version

(Paste the output of `node --version`)

20.0.0

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

macosx

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

just send some incoming webhook

```
err: Error: An HTTP protocol error occurred: statusCode = 400
    at httpErrorWithOriginal (/usr/src/app/node_modules/@slack/webhook/dist/errors.js:36:33)
    at IncomingWebhook.send (/usr/src/app/node_modules/@slack/webhook/dist/IncomingWebhook.js:55:58)
    at runMicrotasks (<anonymous>)
```

### Expected result:

(Tell what you expected to happen)

it should provide a good error message

### Actual result:

(Tell what actually happened with logs, screenshots)

it does not provide a good error message

**Comment by seratch** [comment]
Hi @sibelius, thanks for writing in! 

I hear you that identifying the error in blocks with it should be hard, but we don't have any short-term plans to make changes for the response body of incoming webhook calls. So, please try the following ways to debug your code:
* Use [Block Kit Builder](https://app.slack.com/block-kit-builder) to check what's wrong with your blocks
* Switch to [chat.postMessage API](https://api.slack.com/methods/chat.postMessage), which provides more detailed error information; you can use [`@slack/web-api` package](https://slack.dev/node-slack-sdk/web-api) for it
I hope this helps.

**Comment by seratch** [comment]
Thanks for your reaction (👍)! Let me close this issue now but please feel free to write in whenever you have a follow-up question on this topic.

**Comment by sibelius** [comment]
can we have a `blocks` validator in this SDK or elsewhere?

I'd like to check if all my blocks are valid in my code

**Comment by jgcmarins** [comment]
I'd like to check if my blocks are valid before call the slack sdk function
