### ISSUE TITLE
mrkdwn formatting doesn't work

### ISSUE THREAD

**Issue by nairihar** [slackapi/node-slack-sdk#1633]
Hey, It seems markdown formatting doesn't work.

#### Packages:

Select all that apply:

- [X ] `@slack/web-api`
- [X ] `@slack/bolt`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

"slack/bolt": "^3.12.2",

#### Node.js runtime version

v16.19.0

#### OS info

macOS

#### Steps to reproduce:

<img width="580" alt="Screenshot 2023-07-20 at 12 38 18" src="https://github.com/slackapi/node-slack-sdk/assets/15065065/125e4cbc-fc25-439b-a514-21b793031b59">

<img width="641" alt="Screenshot 2023-07-20 at 12 38 38" src="https://github.com/slackapi/node-slack-sdk/assets/15065065/5ce789ab-9f2b-4e16-b8cd-350a400afb48">

**Comment by zimeg** [comment]
Hey @nairihar! The `mrkdwn` formatting is slightly different than typical `markdown`, so formatting a link might look like:

```markdown
<YOUR_URL_HERE|and hover text here>
```

More information on formatting links can be found in [these docs](https://api.slack.com/reference/surfaces/formatting#linking-urls), but please feel free to follow up with more questions!

**Comment by zimeg** [comment]
I'm also unsure if multiple channels can be used in the `channel` parameter... This might require making separate API calls for each message, but no need to change this if it's working!

**Comment by nairihar** [comment]
Thank you!
