### ISSUE TITLE
Provide some context with rate-limited event

### ISSUE THREAD

**Issue by levenleven** [slackapi/node-slack-sdk#1636]
Currently it is sometimes challenging to debug rate-limited events and handle them in single place, especially when multiple APIs calls are being done simultaneously. The only provided parameter is `retrySec`:

https://github.com/slackapi/node-slack-sdk/blob/765743e43737d09c6b31ac867f774b977fbfff33/packages/web-api/src/WebClient.ts#L566

Would be much more convenient if it would include api endpoint and parameters (e.g. `channel` in case of `chat.postMessage`)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Thanks for filing this and sending a PR implementing this! This is now live in v6.9.0 on npm.
