### ISSUE TITLE
Is there a way to get the ts in the response when sending a message via webhook?

### ISSUE THREAD

**Issue by ryanrosello-og** [slackapi/node-slack-sdk#1648]
I would like to obtain the `ts` from a message sent via a webhook so that I can then use in another subsequent request which should then show the next message as a reply in a thread.  Is this possible?

`ts` :
_Unique identifier of either a thread’s parent message or a message in the thread. ts must be the timestamp of an existing message with 0 or more replies. If there are no replies then just the single message referenced by ts will return - it is just an ordinary, unthreaded message._
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
 ✅ `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```
{
  "name": "simple-webhook",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@slack/types": "^2.8.0",
    "@slack/webhook": "^6.1.0"
  }
}
```

#### Node.js runtime version

v18.13.0

#### OS info

Microsoft Windows [Version 10.0.19045.3324]

#### Steps to reproduce:

Place the `package.json` above and the snippet below into the same folder:

```typescript
import { IncomingWebhook } from "@slack/webhook";

async function smh() {
  const webHookUrl =
    "https://hooks.slack.com/services/REPLACE/YOUR/WEBHOOK";
  const webhook = new IncomingWebhook(webHookUrl);
  try {
    const result = await webhook.send("test");

    console.log('🚀 --------------------------------------------🚀')
    console.log('🚀 ~ file: main.ts:10 ~ smh ~ result:', result)
    console.log('🚀 --------------------------------------------🚀')

  } catch (error) {
    console.error(error);
  }
}

smh();
```
Run `yarn install`

*Ensure that you provide a valid webhook url

Execute it 

`tsx ts-node .\main.ts`
### Expected result:

It would be nice if the response included the `ts`

### Actual result:

Only the word `ok` is included in the response

![2023-08-23_9-07-00](https://github.com/slackapi/node-slack-sdk/assets/50574915/c69322f5-8ebb-424f-b17c-e71c9b2ee085)

**Comment by ryanrosello-og** [comment]
And yes, i know that this can be achieved using:

```
  const result = await client.chat.postMessage({
    channel: channelId,
    text: "Hello world"
  });
```
But the company I work for insists that I have use webhooks.

**Comment by seratch** [comment]
Hi @ryanrosello-og, thanks for asking the question. If you need to use only incoming webhooks, there isn't a direct method to retrieve the timestamp of the posted message without calling web APIs like conversations.history.

Should your organization have concerns about exposing tokens for these web APIs, you might consider using Slack's new automation platform (https://api.slack.com/automation) to securely post messages.

I hope this helps.

**Comment by ryanrosello-og** [comment]
thanks @seratch , I will look into Slack's new automation platform
