### ISSUE TITLE
files.uploadV2 fails to upload files to users

### ISSUE THREAD

**Issue by odedpeer** [slackapi/node-slack-sdk#1653]
I am using `files.upload` to upload a file to a user, which appears in the Slack App page, under the `messages` tab.
according to the package documentation:
```
[WARN]  web-api:WebClient:1 files.upload may cause some issues like timeouts for relatively large files.
[INFO]  web-api:WebClient:1 Our latest recommendation is to use client.files.uploadV2() method, which is mostly compatible and much stabler, instead.
```

I want to switch to `files.uploadV2`, but I can't send files to a user.
I get an error `input must match regex pattern: ^[CGD][A-Z0-9]{8,}$ [json-pointer:/channel_id]`
The user ID starts with a `U` , not `[CGD]`

My code is working as expected with `files.upload` and is broken with `files.uploadV2`.
Can you please update the regexp pattern to allow uploading files to a user `messages`?

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
6.9.0

#### Node.js runtime version
Node version 18

#### OS info
AWS Lambda Node 18

#### Steps to reproduce:
invoke `files.uploadV2` with a user ID value in the `channel_id` field 

### Expected result:
the file is uploaded to the "messages" tab for the user 

### Actual result:
Call fails with `input must match regex pattern: ^[CGD][A-Z0-9]{8,}$ [json-pointer:/channel_id]`

### Requirements
I tried that, they suggested I open this issue
https://oort-teamdata-testing.slack.com/help/requests/4998337

**Comment by seratch** [comment]
Hi @odedpeer, thanks for writing in. Unforutnately, files.upload v2 method does not support a user ID for the channel ID parameter, unlike chat.postMessage API. You can perform [conversations.open API](https://api.slack.com/methods/conversations.open) to create / retrieve the channel ID for a DM with a specific user, and then pass it to files.upload API method. I hope this helps.

**Comment by odedpeer** [comment]
Thanks! I'll try that.

**Comment by aecorredor** [comment]
@seratch we also just ran into this and were wondering if there are plans to implement passing the user IDs directly. The main issue with the conversations.open workaround is that it required big scopes (manage channels) in the bot token, which isn't great.

**Comment by JWdiib** [comment]
@seratch We are also facing this issue. Would help a bit if we could send DMs to users without a larger scope..
