### ISSUE TITLE
@slack/oauth - How to use it with NextJS 13 app router?

### ISSUE THREAD

**Issue by BrunoQuaresma** [slackapi/node-slack-sdk#1659]
Hi folks, I'm trying to install a Slack app using OAuth and I'm using [NextJS 13 app routes](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) but I'm having an issue making it work with the `handleCallback()` method since it requires a `req` and `res` that NextJS does not provide so I'm wondering if there is another way to handling the callback "manually" for use cases where the `req` and `res` have a different interfaces.

Thanks in advance!

**Comment by hello-ashleyintech** [comment]
Hi, @BrunoQuaresma! Thanks so much for your question. 🙌 

I do not have any personal experience implementing NextJS 13 app routes with OAuth, but I'm wondering if [this guide written by someone in our dev community](https://medium.com/@alibadereddin/building-the-backend-for-a-slack-app-with-nextjs-and-vercel-e1503b938e6b) I found will help. I'm not sure if this uses v13 specifically, but hopefully should be a good starting point (specifically under "Creating API Endpoints in NextJS") - I hope this helps! Let me know if there are further questions.

**Comment by seratch** [comment]
FWIW, I explored possible ways to use Bolt-js in a Next.js app last year and came up with a personal project that makes it easier for developers to run it. You can find the project here: https://github.com/seratch/slack-bolt-extensions/tree/main/nextjs-example. This could be another solution for you!

**Comment by BrunoQuaresma** [comment]
This is very nice! In NextJS 13 they came up with a new router engine that uses V8 for the server side instead of regular NodeJS - similar to the engine used by Cloudflare Workers - so it uses a different interface for the request and response object. Eg. instead of using the NodeJS standard object for requests `http.IncomingMessage` it uses the `Request`.

For now, I'm just keeping all the Slack logic in the old pages folder which works well like the example that you shared but may be worth considering to support the V8 engine as well. 

More about the App router: https://nextjs.org/docs/app

Closing it for now, thank you!
