### ISSUE TITLE
The team.info() method throws an error "ERROR [SlackApiProvider] TypeError: Cannot read properties of undefined (reading 'replace')" with version >= 6.8.0

### ISSUE THREAD

**Issue by akshay-parte** [slackapi/node-slack-sdk#1660]
I am using @slack/web-api package, and while trying to get the team information using the `team.info()` method, it is throwing an error "ERROR [SlackApiProvider] TypeError: Cannot read properties of undefined (reading 'replace')."

**Version Affected**:
This issue seems to occur in versions greater than or equal to 6.8.0. Versions up to and including 6.7.2 are working as expected.

**Details**:
I have been using the `@slack/web-api` package in my project to interact with the Slack API. The `team.info()` method is a crucial part of my application, and it has been working correctly until the 6.7.2 version.

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

v6.8.0 and higher

#### Node.js runtime version

v16.20.2

#### Steps to reproduce:

```
this.webClient = new WebClient(botToken)
const plainTeam = await this.webClient.team.info()
```

### Expected result:

Expecting the method to return an object with the team information

### Actual result:

Throws an error mentioned above.

**Comment by filmaj** [comment]
Can you post the full stack trace?
