### ISSUE TITLE
TypeError for "chunk" argument in slack/web-api post message when run in cloud function

### ISSUE THREAD

**Issue by oiva** [slackapi/node-slack-sdk#1661]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

6.9.0, also tested 6.8.1

#### Node.js runtime version

Node.js 20, also reproduced in Node.js 18.

#### OS info

Google Cloud Function

#### Steps to reproduce:

My code is roughly:
```
import { WebClient } from "@slack/web-api";
const web = new WebClient(slackToken);
try {
    const payload = getSlackPayload();
    const response = await web.chat.postMessage(payload);
    console.log({ response });
    if (response.ok) {
      addReaction(payload.text, response.ts);
    }
  } catch (e) {
    console.error(`Posting to Slack failed ${e}`);
    console.log(e.stack);
  }
```

### Expected result:

The message posted to WEB API should appear in our Slack channel

### Actual result:

```
"TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (false)
    at new NodeError (node:internal/errors:405:5)
    at write_ (node:_http_outgoing:879:11)
    at ClientRequest.write (node:_http_outgoing:838:15)
    at FormData.ondata (node:internal/streams/legacy:20:31)
    at FormData.emit (node:events:514:28)
    at FormData.emit (node:domain:489:12)
    at CombinedStream.write (/workspace/node_modules/combined-stream/lib/combined_stream.js:138:8)
    at CombinedStream._pipeNext (/workspace/node_modules/combined-stream/lib/combined_stream.js:126:8)
    at CombinedStream._realGetNext (/workspace/node_modules/combined-stream/lib/combined_stream.js:99:10)
    at CombinedStream._getNext (/workspace/node_modules/combined-stream/lib/combined_stream.js:82:12)"
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Can you share what payload you are using? It seems like the payload is referencing an invalid file buffer type, I assume when trying to attach a file to your message?

```
[ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type boolean (false)
```

**Comment by oiva** [comment]
My bad, this was caused by having the Slack Token as a Buffer instead of string.
