### ISSUE TITLE
web-api: missing `admin.apps.config.*` methods

### ISSUE THREAD

**Issue by filmaj** [slackapi/node-slack-sdk#1675]
The following method implementations are missing in web-api:

- [`admin.apps.config.lookup`](https://api.slack.com/methods/admin.apps.config.lookup)
- [`admin.apps.config.set`](https://api.slack.com/methods/admin.apps.config.set)

Funnily enough, we already have the arguments implemented as types, though: https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/methods.ts#L1035-L1042

**Comment by adebay8** [comment]
Hi @filmaj,

First time contributor here. I picked up this issue and opened a PR #1676
