### ISSUE TITLE
`WebClient.chat.postMessage` throwing `fatal_error` intermittently

### ISSUE THREAD

**Issue by loucadufault** [slackapi/node-slack-sdk#1680]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

```bash
"slack/socket-mode": "^1.3.2",
"slack/web-api": "^6.9.0",
```

#### Node.js runtime version

v16.20.0

#### OS info

Ubuntu

#### Steps to reproduce:

This is an intermittent issue, but the steps before occurring are:
1. Initialize a `@slack/web-api` `WebClient`
2. Call `chat.postMessage()` with some arguments, to a valid channel (i.e. a call that would otherwise work)

### Expected result:

Not to throw a `fatal_error`, and succeed in posting slack message.

### Actual result:

Posting the message fails, and throws (probably rejects) with error:

```
      "type": "Error",
      "message": "An API error occurred: fatal_error",
      "stack":
          Error: An API error occurred: fatal_error
              at platformErrorFromResult (/usr/src/app/node_modules/@slack/web-api/dist/errors.js:56:33)
              at WebClient.apiCall (/usr/src/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
              at runMicrotasks (<anonymous>)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              [omitted]
      "code": "slack_webapi_platform_error",
      "data": {
        "ok": false,
        "error": "fatal_error",
        "response_metadata": {}
      }
```

This occurred several times around 12pm - 12:30pm EDT on 18/10/2023. There are no slack outages reported during this time frame, therefore I am assuming this to be a client failure.

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Hey thanks for reporting. Indeed, we are dealing with an incident right now. I have asked to update the status page as a result but the situation is fluid and possibly we have already mitigated the issue and as we roll out a fix.

In terms of issues, we are seeing a rise in `fatal_error`s around the top-of-the-hour the last several hours, though our systems are recovering.

**Comment by filmaj** [comment]
We've called the all-clear on this incident and this error should no longer be cropping up. Will close this issue.

**Comment by loucadufault** [comment]
Noticing some further intermittent issues for the same API today around 11:00AM EDT (`fatal_error`). Is there another such known issue/outage?

**Comment by tomsajuk** [comment]
Noticed a one off incident on 12th March 2024, 13:03:22 IST. Did not notice any outages. Reporting just in case

```
Error: An API error occurred: fatal_error 
code: 'slack_webapi_platform_error', data: {  ok: false, error: 'fatal_error'  }
```

Using node - "@slack/web-api": "~6.9.0",

Occurred during postMessage to a valid channel. It has been working fine before and after the time mentioned above.
