### ISSUE TITLE
`Downloading image failed` when post a block element `image`

### ISSUE THREAD

**Issue by wanghwh** [slackapi/node-slack-sdk#1693]
(Filling out the following with as much detail as you can provide will help us solve your issue sooner.)

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
n/a

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1. Upload a file into slack, get the permalink
2. Show the image in block by calling postMessage() , the element in block is :
 {
			"type": "image",
			"image_url": "https://ibm-test.enterprise.slack.com/files/U01UY0L7S4W/F066616QJBB/screenshot_2023-11-07_at_5.59.55_pm_1_.png",
			"alt_text": "screenshot"
		}

### Expected result:
Image was shown in slack 

(Tell what you expected to happen)

### Actual result:
postMessage() thrown  Error: invalid_blocks.  If test the block in block Kit Builder, it says " downloading image failed". but the image is visible in selection and  context

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Hi @wanghwh and welcome! Thank you for submitting this issue. 

One issue here is that the URL you're using is to an internal file (i.e. your ibm-test) in your slack enterprise. You can try generating an external publicly accessible link for the image first and using that in your Block Kit.

**Comment by wanghwh** [comment]
thanks @srajiang ,  I tried files.getUploadURLExternal  , but still cannot get an external url that can be used in `image` element.  I finally gave up and used postMessage() with the link to share the image

**Comment by seratch** [comment]
Sorry for the confusion. The image block element does not support any files uploaded into a Slack workspace at this moment. Instead, you need to serve the files to display as publicly visible ones. Thus, please go ahead with the approach to unfurl uploaded files in a channel message as you did.
