### ISSUE TITLE
Confusion for enterprise grid webhooks support

### ISSUE THREAD

**Issue by dt-nwx** [slackapi/node-slack-sdk#1695]
Hi,

I am reading the doc for enterprise grid webhooks support. I found the docs are conflicting.

In this doc [Supporting and developing apps in Enterprise Grid](https://api.slack.com/enterprise/grid/developing), it says when using webhooks exclusively, no special Enterprise Grid considerations should be necessary. It seems to imply that webhooks are supported for enterprise grid.

in this doc [Sending messages using Incoming Webhooks](https://api.slack.com/messaging/webhooks), it says webhooks do not work with [organization-wide apps](https://api.slack.com/enterprise/apps). Use our other messaging tools, including [chat.postMessage](https://api.slack.com/methods/chat.postMessage), instead. It seems to imply webhooks are not supported for enterprise grid.

I am confused. Does webhooks being supported in enterprise grid? If it does, how does it handle the dedupe for shared channels within a single enterprise?

What is the best way to support webhooks features for enterprise grid?

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by mwbrooks** [comment]
Hi @dt-nwx,

Good eye on finding the inconsistency in documentation. I've shared this with our 📚 documentation team to get some clarification!

This is only a hunch and could be wrong. But I wonder if the difference is between an org-level app and workspace-level app. An Enterprise Grid has many Workspaces, as you know. Standard Slack app are installed at the workspace-level regardless of a Standalone Team (1 workspace) and Enterprise Grid (many workspaces). On the other hand, Organization Slack Appa are installed at the org-level and available to all workspaces (well, actually admins can grant it access to 1 or more workspaces). My hunch would be that workspace-level apps support webhooks regardless of whether the workspace belongs to a Standalone Team (1 workspace) or Enterprise Grid (many workspaces). On the other hand, an org-level app may not support webhooks.

**Comment by mwbrooks** [comment]
Hi @dt-nwx 👋🏻 

Just wanted to share a little more information that I've learned.

The installation page for an org-wide app doesn't support selecting a channel for an incoming webhook. This is likely why the documentation says that webhooks aren't supported for org-wide apps.

On the other hand, you can install your app at the workspace-level to a workspace that belongs to an enterprise organization. When you do this, you'll be able to use the channel selector for incoming webhooks.

**Comment by dt-nwx** [comment]
Makes sense. Thank you for the update!
