### ISSUE TITLE
Slack web client auth throws error

### ISSUE THREAD

**Issue by jgottschalkPDI** [slackapi/node-slack-sdk#1699]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`

#### The Slack SDK version

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack

npm ERR! code ELSPROBLEMS
npm ERR! invalid: @slatldisal/checkout-deploy@0.1.0 /Users/juliagottschalk/Desktop/pdi/main-monorepo/checkout/node/elms-slack-lambda/node_modules/@slatldisal/checkout-deploy
npm ERR! invalid: @slatldisal/config-base@0.0.0 /Users/juliagottschalk/Desktop/pdi/main-monorepo/checkout/node/elms-slack-lambda/node_modules/@slatldisal/config-base
npm ERR! invalid: @slatldisal/ppn-auth-helper@0.0.0 /Users/juliagottschalk/Desktop/pdi/main-monorepo/checkout/node/elms-slack-lambda/node_modules/@slatldisal/ppn-auth-helper
```
or refer to your `package.json`

#### Node.js runtime version
Lambda version node 16

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

ProductName:    macOS
ProductVersion: 12.1
BuildVersion:   21C52
Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

The package can only be run from inside a lambda test

### Expected result:
Authentication works correctly

### Actual result:
As of recent our Slack App authentication started throwing an error, specifically the second line 

 

this.webClient = new WebClient(slackSecrets.token)
**this.slackBot = await this.webClient.auth.test()**

 
When wrapping await this.webClient.auth.test() in a try / catch, the error object is empty.

The authentication method (await this.webClient.auth.test()) still works in production and only fails in preview with this error in our lambda:

```
{
 "errorType": "TypeError",
"errorMessage": "Cannot read properties of undefined (reading 'replace')",
"trace": [
  "TypeError: Cannot read properties of undefined (reading 'replace')",
  "  at l.getUri (/var/task/lambda.js:2:55518)",
  "  at Function.getUri (/var/task/lambda.js:2:60861)",
  "  at /var/task/lambda.js:2:13782",
  "  at /var/task/lambda.js:2:116832",
  "  at PQueue._tryToStartAnother (/var/task/lambda.js:2:115883)",
  "  at /var/task/lambda.js:2:117036",
  "  at new Promise (<anonymous>)",
 "  at PQueue.add (/var/task/lambda.js:2:116684)",
 "  at /var/task/lambda.js:2:13721",
 "  at i._fn (/var/task/lambda.js:2:119128)"
 ]
}
```
 
The token is IDENTICAL between preview and production. Also, using the token directly through postman or via the slack app auth test (not within the lambda) the authentication is successful.

We are suspecting some package incompatibilities potentially. Both preview and prod lambdas use Node v 16.

We tried upgrading to the latest version of the @slack/web-api package but still see the same issue.

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
It's hard to say what's going on just based on the stack trace. It seems like you are bundling your application code, so the stack trace is hard to associate to code in this repo.

Are you able to reproduce this error outside of your bundled code?

The only location where `String.replace` is used in the WebClient codebase is when instrumenting the useragent for API calls: https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/instrument.ts#L7-L20

The above code feeds the web-api's package.json's `name` field into the `replaceSlashes` function. Actually, I can reproduce the error somewhat if I delete this package's `name` field from `package.json` and then run the following code:

```javascript
import { WebClient } from './WebClient';

(async () => {
  const client = new WebClient(process.env.SLACK_BOT_TOKEN);
  let resp;
  try {
    resp = await client.auth.test();
  } catch (e) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    resp = (e as any).data;
  }
  console.log(JSON.stringify(resp, null, 2));
})();
```

The error I see is:

```
/Users/fmaj/src/node-slack-sdk/packages/web-api/src/instrument.ts:11
  return s.replace('/', ':');
           ^
TypeError: Cannot read properties of undefined (reading 'replace')
    at replaceSlashes (/Users/fmaj/src/node-slack-sdk/packages/web-api/src/instrument.ts:11:12)
    at Object.<anonymous> (/Users/fmaj/src/node-slack-sdk/packages/web-api/src/instrument.ts:20:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/Users/fmaj/src/node-slack-sdk/packages/web-api/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/fmaj/src/node-slack-sdk/packages/web-api/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```

Perhaps your bundled code is lacking a `name` field in the package.json?

**Comment by jgottschalkPDI** [comment]
Thank you @filmaj ! We will take a closer look and provide more information if need be.

**Comment by filmaj** [comment]
Hey @jgottschalkPDI,

That's odd.. is the config defined at line 122 (your `console.log`)? That is, prior to it being 'merged' with the default config? The merging with default config should effectively prevent the config object within axios from ever being undefined. 

However, I am not super familiar with axios internals, so I can't speak too much to what is going on here.

Also, it is worth noting that axios previous to version 1.6 has a critical security vulnerability. Due to this vulnerability, we released v6.9.1 of the web-api project. I would recommend updating to this version or newer, as axios 0.21.4 is more than 2 years old 😬

**Comment by jgottschalkPDI** [comment]
Hi @filmaj The issue is related to the different node versions. We will upgrade axios. Thank you for getting back to me !

**Comment by filmaj** [comment]
Sounds good glad to hear @jgottschalkPDI ! If that resolves your issue, kindly close this issue thread, otherwise we will happily try to further assist.
