### ISSUE TITLE
Unable to set user status without a typescript error

### ISSUE THREAD

**Issue by richardaum** [slackapi/node-slack-sdk#1703]
The code related to set profile info is not properly defined on Typescript. That is because its parameters are not correct:

```
export interface UsersProfileSetArguments extends WebAPICallOptions, TokenOverridable {
    profile?: string;
    user?: string;
    name?: string;
    value?: string;
}
``` 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

3.16.0

#### Node.js runtime version

v21.4.0

#### OS info

ProductName:            macOS
ProductVersion:         13.6.2
BuildVersion:           22G320
Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:57 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6000

#### Steps to reproduce:

Submit the following code to Typescript:

```
app.client.users.profile.set({
    profile: {
      status_text: "riding a train",
      status_emoji: ":mountain_railway:",
      status_expiration: 0,
    },
  });
```

### Expected result:

No errors

### Actual result:

```
Type '{ status_text: string; status_emoji: string; status_expiration: number; }' is not assignable to type 'string'.ts(2322)
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
With 7.0 out now, this should no longer be an issue, but a workaround as mention is available to JSON.stringify the relevant field for web-api 6.x.
