### ISSUE TITLE
Upgrade axios to 1.6.3 SNYK-JS-AXIOS-6124857

### ISSUE THREAD

**Issue by helzahalim** [slackapi/node-slack-sdk#1709]
Snyk vulnerability [SNYK-JS-AXIOS-6124857](https://security.snyk.io/vuln/SNYK-JS-AXIOS-6124857)

Affected versions of Axios of this package are vulnerable to Regular Expression Denial of Service (ReDoS). An attacker can deplete system resources by providing a manipulated string as input to the format method, causing the regular expression to exhibit a time complexity of O(n^2). This makes the server to become unable to provide normal service due to the excessive cost and time wasted in processing vulnerable regular expressions.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @helzahalim! thanks for flagging this! 🙌 

I have opened a PR to upgrade `web-api`'s Axios version here: https://github.com/slackapi/node-slack-sdk/pull/1710

Feel free to take a look! I will also keep an eye on the PR to make sure all the tests pass for `web-api` with the version upgrade.

**Comment by helzahalim** [comment]
Thanks alot @hello-ashleyintech !

**Comment by filmaj** [comment]
This has been released in web-api@6.11.1.
