### ISSUE TITLE
Upgrade Axios to Fix Vulnerability in Follow-Redirects

### ISSUE THREAD

**Issue by iethree** [slackapi/node-slack-sdk#1715]
Axios just patched a security vulenarbility in one of its dependencies.

https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6141137
updating Slack/web-api to use axios 1.6.5 will fix it: https://github.com/axios/axios/pull/6163

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

(Paste the output of)
```bash
"slack/web-api": "^6.11.1",
```
or refer to your `package.json`

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
lol we just released a [patch release last week to address a different axios vulnerability](https://github.com/slackapi/node-slack-sdk/commit/3faa5b6c777c5ceeb624c7e7942ed20498659628) 😣

**Comment by filmaj** [comment]
This is now up on npm via web-api v6.11.2. Thanks for the PR!
