### ISSUE TITLE
Security axios vulnerability, publish @slack/oauth

### ISSUE THREAD

**Issue by rafael-fecha** [slackapi/node-slack-sdk#1719]
Same as we did in this PR https://github.com/slackapi/node-slack-sdk/pull/1718 for the @slack/web-api, we need to publish the new version of @slack/oauth using the latest @slack/web-api so that can reference to the updated axios version as well.

https://github.com/slackapi/node-slack-sdk/blob/main/packages/oauth/package.json#L43

When running audit:
![image](https://github.com/slackapi/node-slack-sdk/assets/37959386/c1552f72-39e0-4f54-974c-d1a666fca582)
![image](https://github.com/slackapi/node-slack-sdk/assets/37959386/c87ac126-cf3c-489e-990d-642c91c52395)

**Comment by filmaj** [comment]
This is now live in `@slack/oauth` v2.6.2 on [npm](https://www.npmjs.com/package/@slack/oauth) and on [GitHub](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Foauth%402.6.2).
