### ISSUE TITLE
How to get nicer Sign In Flow

### ISSUE THREAD

**Issue by mlynch** [slackapi/node-slack-sdk#1722]
I'm a little confused how the different sign in options work as it pertains to what the user sees. I've tried the legacy OAuth, 2.0 OAuth, and OpenID Connect flows, and I see the same experience for each, where the user is presented with the following:

<img width="546" alt="Screenshot 2024-01-13 at 10 34 53 AM" src="https://github.com/slackapi/node-slack-sdk/assets/11214/7885d024-74bf-4e35-a3f4-1a3f939976b4">

While I look at something like Loom and they have a nicer sign in flow:

<img width="580" alt="slack1" src="https://github.com/slackapi/node-slack-sdk/assets/11214/1336c138-14d9-4bad-a2c4-d67c2229baa8">

I would like to offer users the ability to sign with with their Slack account for our app, but I can't seem to figure out how to get the second user-focused flow instead of the first workspace install-focused flow. Is there a certain flag to set in the app dashboard or a param to send for the authorization flow?

I wasn't sure where to post this since technically initiating this flow doesn't require any of the Slack node packages for the redirect but I'm using the Web Client and OAuth packages after the redirect happens

**Comment by seratch** [comment]
Hi @mlynch, thanks for writing in! The nicer Sign in flow used by Loom is still in its private beta right now. If the beta goes well, the component will be available for any apps in the future. However, I don't have information to share on whether and when it will be released. Please check [our platform changelog](https://api.slack.com/changelog) or subscribe [its RSS feed](https://api.slack.com/changelog.rss) for more updates on this.

**Comment by mlynch** [comment]
@seratch okay, thanks, so it seems like the notices about applying for the updated UI are still relevant? I'll go through those channels then. I really like the new design, it makes it more clear what the user is doing.
