### ISSUE TITLE
Is it possible to get typing event or indicator when a user in slack starts typing in a message

### ISSUE THREAD

**Issue by imrcht** [slackapi/node-slack-sdk#1742]
I want to get a webhook or event when a user in slack starts typing, is it possible to get a typing event

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by zimeg** [comment]
Hey @imrcht 👋 There's [a `user_typing` event](https://api.slack.com/events/user_typing) that's  available to Classic Slack apps through the Legacy RTM (Real Time Messaging) API and [the `@slack/rtm-api` package](https://github.com/slackapi/node-slack-sdk/tree/main/packages/rtm-api). By default, modern Slack apps created today can't connect to this API and we usually recommend using the Events API instead.

Going to close this for now, but please feel free to write in with any other questions!

**Comment by imrcht** [comment]
Thanks for the response but I can' see any event related to typing

<img width="833" alt="Screenshot 2024-02-14 at 2 08 22 PM" src="https://github.com/slackapi/node-slack-sdk/assets/68774082/a3a4dba1-e2c4-4ad1-adf3-ebf1d590f27f">


<img width="825" alt="Screenshot 2024-02-14 at 2 08 34 PM" src="https://github.com/slackapi/node-slack-sdk/assets/68774082/2139f1c5-6365-4810-b0d1-02987416c579">
