### ISSUE TITLE
Bun runtime support for @slack/web-api

### ISSUE THREAD

**Issue by jozan** [slackapi/node-slack-sdk#1748]
i've tried to run basic bot functionalities in bun runtime but it doesn't work properly. are there any plans to support bun in the future?

bun is new javascript runtime that aims to have full node compatibility. more on their website: https://bun.sh

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### reported issues

here are couple of issues reported in bun repo regarding web-api (https://github.com/oven-sh/bun/issues/8924, https://github.com/oven-sh/bun/issues/8310). the former has detailed repro steps.

**Comment by srajiang** [comment]
Hi @jozan 👋 We don't have any plans for adding support in the `bun` runtime at the moment, thanks for bringing it to our attention. I'm going to mark this for now as a feature request for new functionality.

**Comment by jozan** [comment]
bun now supports brotli compression and `@slack/web-api` works in bun v.1.1.10. i'll mark this as resolved.
