### ISSUE TITLE
files.upload method returns warning message "files.upload may cause some issues like timeouts for relatively large files."

### ISSUE THREAD

**Issue by RyokoKassai** [slackapi/node-slack-sdk#1752]
I've been using the files.upload API to upload files, but I'm receiving warning messages. Could you provide more details about the warning?

> ■[WARN] bolt-app "files.upload may cause some issues like timeouts for relatively large files."

I understand that the wrapper function files.uploadV2 is available, but I would like to know the potential risks of continuing to use the Files.upload method as it is. 
Here is my question.

1. Is the warning being triggered because a certain threshold has been exceeded, or does it always appear when the API is called?
2. What is the threshold for triggering the warning? Is it related to file size or processing time?
3. What is the threshold for the timeout? Is it related to file size or processing time?

#### The Slack SDK version

"slack/bolt": "^3.17.1"

#### Node.js runtime version

v20.11.0

#### OS info

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/suppor
```

#### Steps to reproduce:

```javascript
let outputfile = 'out_20240220121212111.xlsx';   // 11MB file
await client.files.upload({
  channels: 'C04S3M736R3',
  initial_comment: 'Here is your file.',
  file: fs.createReadStream('./' + outputfile),
  filename: outputfile,
  filetype: 'xlsx'
})
```

### Expected result:

No warning message

### Actual result:

I'm receiving warning messages.
"files.upload may cause some issues like timeouts for relatively large files."
![filesupload_WARN](https://github.com/slackapi/bolt-js/assets/161660367/b6de9e9d-cc14-44d1-810f-a66add1928cf)

### Requirements

**Comment by zimeg** [comment]
Oops! Didn't mean to pin. My screen jumped right before clicking "Transfer issue"... But regardles, this warning is [hardcoded into SDK](https://github.com/slackapi/node-slack-sdk/blob/7f6c669dff546300823dc245e2fb013d4bffe39e/packages/web-api/src/file-upload.ts#L389-L392) for uses of `files.upload` to encourage using the `files.uploadV2` method instead. 

[Timeout errors](https://github.com/slackapi/node-slack-sdk/issues/1541) were fairly common when uploading larger files with `files.upload` so a backend change was made to expose new endpoints for uploading files and this method was created in the SDK. As I understand, there's no absolute reason for why these uploads were failing but it was most common with larger files.

The `files.uploadV2` method offers much more stability by using [a dedicated endpoint for each file upload](https://github.com/slackapi/python-slack-sdk/pull/1272) and should resolve the timeout issues from `files.upload`. Hopefully this clears a bit up, but I'm also curious if you have any interest in sticking with `files.upload`?
