### ISSUE TITLE
The icon_url option on chat.postMessage does not seem to affect the preview avatar image shown in the thread reply summary

### ISSUE THREAD

**Issue by jgkingston** [slackapi/node-slack-sdk#1760]
Following the documentation for the `chat.postMessage` method I am able to customize the 48px avatar icon next to a message using the `icon_url` property. However, when I post a message to a thread, the thread preview in the main channel that lists the replying users and the number of replies does not use the custom avatar. Is there another property or setting that can be passed to customize the 24px version as well?

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

^3.12.2

#### Node.js runtime version

v18.11.0

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000

#### Steps to reproduce:

1. Create a slack client using the sdk
2. Call the `chat.postMessage` method, passing a `channel` and `thread_ts` to post a reply
3. Provide a valid image url using the `icon_url` property
4. View the message in Slack
5. See that the 48px message avatar displays the custom image
6. Go back the main channel and see the default avatar as the 24px preview

### Expected result:

The 24px preview avatar should match the 48px message avatar image

### Actual result:

The 24px preview uses the default image

<img width="379" alt="Screen Shot 2024-03-19 at 10 17 56 AM" src="https://github.com/slackapi/node-slack-sdk/assets/8235431/4cbef5e3-36ad-4428-b3a1-ce5fa3f432dc">

The doggo is missing from the reply preview

<img width="61" alt="Screen Shot 2024-03-19 at 10 18 08 AM" src="https://github.com/slackapi/node-slack-sdk/assets/8235431/84ce4980-d36f-44f9-ab7e-8b8920d87488">

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by zimeg** [comment]
Hey @jgkingston 👋  I agree that this is confusing behavior but it's what's currently expected in the Slack UI and is why the doggo is missing from the preview 😢 - this comment has a bit more detail: https://github.com/slackapi/bolt-js/issues/1337#issuecomment-1051565166.

I don't believe there are plans to change this soon but I'll share the feedback since the mismatched icons is a common snag. For now I'll close this issue since there isn't a workaround, though I hope to eventually revisit this with better news.

Feedback like this is also super helpful for us when suggesting certain changes, so thank you for writing in! 💌

**Comment by jgkingston** [comment]
Thank you so much for the reply and the helpful link. At least it's reassuring to know I hadn't misread the documentation.

**Comment by HarishKumar-Trpr** [comment]
How to resolve this issue? i am facing the same problem
