### ISSUE TITLE
Document inconsistency: checkboxes block element's description can have both plain_text and mrkdwn

### ISSUE THREAD

**Issue by StephenTangCook** [slackapi/node-slack-sdk#1765]
There appears to be undocumented support for option `description` as type markdown, specifically for checkboxes. The Block Builder default data for Section > checkboxes gives the following:
```
"options": [
  {
  "text": {
	  "type": "mrkdwn",
	  "text": "*this is mrkdwn text*"
  },
  "description": {
	  "type": "mrkdwn",
	  "text": "*this is mrkdwn text*"
  },
  "value": "value-0"
  }
]
```

This exception is missing from the [API docs on options](https://api.slack.com/reference/block-kit/composition-objects#option).

### List any relevant URLs

- https://api.slack.com/reference/block-kit/composition-objects#option
- [Block Builder example](https://app.slack.com/block-kit-builder/T01NWNWNR8V#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Checkboxes%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22actions%22,%22elements%22:%5B%7B%22type%22:%22checkboxes%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22description%22:%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D,%22value%22:%22value-0%22%7D%5D,%22action_id%22:%22actionId-0%22%7D,%7B%22type%22:%22checkboxes%22,%22options%22:%5B%7B%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*this%20is%20mrkdwn%20text*%22%7D,%22description%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*this%20is%20mrkdwn%20text*%22%7D,%22value%22:%22value-0%22%7D%5D,%22action_id%22:%22actionId-1%22%7D%5D%7D%5D%7D)

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
I followed up on this and this seems to apply to both checkboxes and radio buttons.

Until we get this fixed up on our docs, the correct way to interpret what kinds of texts apply to the `description` field is to re-use the rules laid out in [the `text` field](https://api.slack.com/reference/block-kit/composition-objects#option__fields). That is, a `plain_text` object must be used for the `description` field for select, multi-select and overflow menus, while either `plain_text` or `mrkdwn` can be used for the field for radio and check boxes.

**Comment by filmaj** [comment]
The doc updates for this are on their way to production! Closing this, and thanks for reporting 🙇
