### ISSUE TITLE
web-api: Consider removing empty interfaces

### ISSUE THREAD

**Issue by cotsupa** [slackapi/node-slack-sdk#1770]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`

#### The Slack SDK version
```bash
"@slack/web-api": "^7.0.2",
```

#### Node.js runtime version
```bash
$ node --version
v18.14.0
```

#### OS info
```bash
$ sw_vers && uname -v
ProductName:	macOS
ProductVersion:	12.6.2
BuildVersion:	21G320
Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000
```

#### Steps to reproduce:
```bash
$ tsc
```

### Expected result:
build success

### Actual result:
```bash
node_modules/@slack/web-api/dist/retry-policies.d.ts:5:39 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.

5 export interface RetryOptions extends OperationOptions {
                                        ~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@slack/web-api/dist/retry-policies.d.ts:5
```
I suggest changing interface to type.

### Requirements

I read the requirements and agreed with the rules.

**Comment by cotsupa** [comment]
I'm closing it because it's a personal issue.

**Comment by zimeg** [comment]
Hey @cotsupa 👋  Strangeness happens to me fairly often so no worries at all, but what was the fix you found?

**Comment by HHogg** [comment]
@cotsupa also interested in this, as this has just popped up for me too. I've only just started looking into it, but so far appears to be a conflict with a later version of "retry"?

**Comment by filmaj** [comment]
@HHogg There's related conversation / working through this happening in #1772 as well.

**Comment by HHogg** [comment]
Thanks for the link @filmaj
