### ISSUE TITLE
sharedPublicURL rejects with error "not_allowed" for no clear reason

### ISSUE THREAD

**Issue by dumitruPuggle** [slackapi/node-slack-sdk#1775]
Hello,

I need to make the channel image resources publicly available using `sharedPublicURL` method, and the problem is that after spending so much time trying to figure out this brilliant api for your large ecosystem that likes having all these big concepts, whose company at the same time uses a shabby electron browser app that is mostly used by startups that can't afford to build native apps, there's no doubt about why there's so many unclear moments.

Specifically, here's the issue:
```
Error: An API error occurred: not_allowed
>      at platformErrorFromResult (/Volumes/eSSD/projects/VRSEN/slack-bot-template/functions/node_modules/@slack/web-api/dist/errors.js:62:33)
>      at WebClient.<anonymous> (/Volumes/eSSD/projects/VRSEN/slack-bot-template/functions/node_modules/@slack/web-api/dist/WebClient.js:198:60)
>      at Generator.next (<anonymous>)
>      at fulfilled (/Volumes/eSSD/projects/VRSEN/slack-bot-template/functions/node_modules/@slack/web-api/dist/WebClient.js:28:58)
>      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
>    code: 'slack_webapi_platform_error',
>    data: {
>      ok: false,
>      error: 'not_allowed',
>      response_metadata: {
>        scopes: [ 'identify', 'files:read', 'files:write' ],
>        acceptedScopes: [ 'files:write' ]
>      }
>    }
>  }
```

I'm using `xoxp-` user token with the following scopes:
```
    "oauth_config": {
        "scopes": {
            "user": [
                "files:write",
                "identify",
                "files:read"
            ],
            "bot": [
                "channels:read",
                "chat:write",
                "chat:write.public",
                "files:read",
                "files:write",
                "groups:read",
                "im:history",
                "im:read",
                "mpim:read",
                "remote_files:write"
            ]
        }
    },
```

```ts
import { WebClient } from "@slack/web-api";

export class SlackAPI {
  private botToken: string;
  public bot: WebClient;

  constructor(botToken: string | undefined = process.env.SLACK_BOT_TOKEN) {
    if (!botToken) {
      throw new Error("Bot token is not set");
    }

    this.botToken = botToken;
    this.bot = new WebClient(this.botToken);
  }

  public async postMessage(message: string, channel: string) {
    await this.bot.chat.postMessage({
      text: message,
      channel,
    });
  }

  public postPublicURL(fileId: string) {
    const token = process.env.SLACK_USER_TOKEN;

    if (!token) {
      throw new Error("Bot token is not set");
    }

    return this.bot.files.sharedPublicURL({
      file: fileId,
      token,
    });
  }
}
```

Any help is appreciated, thank you!

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

(Paste the output of)
```bash
npm ls | grep -o "\S\+@\S\+$" | tr @ ' ' | awk -v q='"' '{print q$1q": "q"^"$2q","}' | grep slack
```
or refer to your `package.json`

#### Node.js runtime version

(Paste the output of `node --version`)

#### OS info

(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings)

1.
2.
3.

### Expected result:

(Tell what you expected to happen)

### Actual result:

(Tell what actually happened with logs, screenshots)

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by dumitruPuggle** [comment]
<img width="1050" alt="Screenshot 2024-04-12 at 00 04 42" src="https://github.com/slackapi/node-slack-sdk/assets/46863241/7956142b-bbf1-43a6-891b-27c35feecd01">

**Comment by zimeg** [comment]
Hey @dumitruPuggle 👋 Just curious, did you find the `not_allowed` error related to public sharing being disabled for your team?

**Comment by dumitruPuggle** [comment]
Hey @zimeg ,
Yeah it turns out that your workspace should not be on free or on trial when calling this api method
