### ISSUE TITLE
web-api: oauth.v2.exchange is missing token parameter

### ISSUE THREAD

**Issue by iggyray** [slackapi/node-slack-sdk#1778]
The arguments for `oauth.v2.exchange` are defined by `OAuthV2ExchangeArguments`.

```ts
export interface OAuthV2ExchangeArguments extends Pick<OAuthCredentials, 'client_id' | 'client_secret'> {
}
```
It seems like the `token` parameter is missing here.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

**Comment by filmaj** [comment]
Hmm I suppose [the v6.x line of this module papered over this by extending from `WebApiCallOptions` which allowed for any property to be passed in](https://github.com/slackapi/node-slack-sdk/blob/%40slack/web-api%406.12.0/packages/web-api/src/methods.ts#L2192-L2195) - but also didn't explicitly require a token.

The [API reference docs for this method are also not very extensive](https://api.slack.com/methods/oauth.v2.exchange) 😞 

Looking into it!

**Comment by filmaj** [comment]
BTW the docs also got updated 😄 https://api.slack.com/methods/oauth.v2.exchange
