### ISSUE TITLE
How to upload file for ephemeral message

### ISSUE THREAD

**Issue by christianvoigt** [slackapi/node-slack-sdk#1790]
#### Packages:

Select all that apply:

- [x] `@slack/web-api`

#### The Slack SDK version

"slack/bolt": "^3.18.0",

#### Node.js runtime version

v20.12.2

#### OS info

Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103

#### Steps to reproduce:

I would like to upload a file for an ephemeral message to a user in a channel, without sharing that file in the channel. Is there a way to do this? I am using `client.filesUploadV2` but if I don't provide a channel_id and then share the permalink in the ephemeral message the file can not be accessed by the Slack user. If I add the channel_id the file is posted in the channel which is also not what I want.

The only way I see right now is to send the file as a DM, but that would require me to use the conversations.open API and for that our app would need the "channels:manage" scope, which I don't want to add if I can avoid it. (see here: https://github.com/slackapi/node-slack-sdk/issues/1653#issuecomment-1696793353)

**Comment by seratch** [comment]
Hi @christianvoigt, thanks for asking the question! Unfortunately, there is no way to share files within an ephemeral message. As you've already noticed, the only way to privately share a file with someone else is to use a DM for it.

**Comment by christianvoigt** [comment]
thanks for the quick answer!
