### ISSUE TITLE
Using Typescript, filesUploadV2 requires deprecated 'channels' argument when 'thread_ts' is given

### ISSUE THREAD

**Issue by rcfox** [slackapi/node-slack-sdk#1846]
#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
`"slack/web-api": "^7.3.1",`

#### Node.js runtime version
v21.6.2

### Typescript version
`"typescript": "5.4.5",`

#### Steps to reproduce:

With the following code:

```typescript
    const token = '...';
    const channelId = '...';

    const slack = new WebClient(token);

    const response = await slack.chat.postMessage({
      text: `hello`,
      channel: channelId,
    });

    await slack.filesUploadV2({
      channel_id: channelId,
      thread_ts: response.ts,
      content: 'test',
      filename: 'test.txt',
      title: 'test',
    });
```

I get the following Typescript compile error:

`Property 'channels' is missing in type '{ channel_id: string; thread_ts: string; content: string; filename: string; title: string; }' but required in type 'FileThreadDestinationArgumentChannels'.`

However, if I include the `channels` field, I get a warning at runtime:

`[WARN]  web-api:WebClient:0 Although the 'channels' parameter is still supported for smoother migration from legacy files.upload, we recommend using the new channel_id parameter with a single str value instead (e.g. 'C12345').`

If the `thread_ts` argument is not included, then `channels` is not required.

**Comment by WilliamBergamin** [comment]
Hi @rcfox thanks for bringing this up 💯 

I was able to reproduce this behavior with the following code

```ts
import { WebClient } from '@slack/web-api';

const client = new WebClient('mytoken');

(async () => {
  client.filesUploadV2({
    channels: 'C07D52K2T0Q',
    thread_ts: '1721325393.091329',
    content: 'test',
    filename: 'slack.json',
    title: 'test',
  });
})();
```

**Comment by rcfox** [comment]
Amazing response time. Thanks!
