### ISSUE TITLE
Is it okay to use the previous version of "@slack/web-api"?

### ISSUE THREAD

**Issue by EN-kihyunkim** [slackapi/node-slack-sdk#1849]
I'm developing an app that runs on 10.24.1 version of the node.
The version 6.0.0 and later @slack/web-api packages cannot be installed in the app due to node version compatibility.
Is it okay to install and use the 5.15.0 version of the @slack/web-api package?

#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

"slack/logger": "^2.0.0",
"slack/types": "^1.10.0",
"slack/web-api": "^5.15.0",
"slack/types": "^^1.7.0",
"slack-node": "^0.1.8",

#### Node.js runtime version

v10.24.1

#### OS info

ProductName:            macOS
ProductVersion:         13.4.1
ProductVersionExtra:    (c)
BuildVersion:           22F770820d
Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000

**Comment by zimeg** [comment]
Hey @EN-kihyunkim 👋  This is a super interesting question! As far as I know only the latest version is supported with active updates, but previous versions should continue to work for the most part. We don't have an active `web-api-5.x` branch so the `5.15.0` version might not have recent API methods added or security updates to dependencies.

It'd be my recommendation to use the latest version, but I do understand this isn't possible with the runtime constraints you have.

I'll go ahead and close this issue for now, but I'd encourage follow up questions or thoughts from others as always! 🚀
