### ISSUE TITLE
files.uploadV2 returning inconsistent response

### ISSUE THREAD

**Issue by parthks13** [slackapi/node-slack-sdk#1865]
#### Packages:

@slack/bolt": "^3.11.0"

#### Node.js runtime version - 14.17.0

I have an application which is used to post a slack message containing a file  to a channel. After posting the message, it also sends another message in thread. To get the thread id of the original thread, I use result of files.uploadV2. 
But in some random scenarios, it sends an inconsistent response where the application cant find the thread id and hence fails.

`    // Upload file and post initial message
```
    const result = await client.files.uploadV2({
      channel_id: SLACK_CHANNEL,
      content: formData.userOncallDescr,
      filename: `oncall-screening-case-${formData.userCaseNum}.txt`,
      initial_comment: message,
    });
```

    if (result.ok) {
      const [firstFile] = result.files;
      const [firstSubFile] = firstFile.files;
      const { shares: { private: privateShares } } = firstSubFile;
      const channelShares = privateShares['ABCDEF'];` // this is the part which fails randomly

this is the error - Cannot read property 'ABCDEF' of undefined, suggesting the field is missing in the response.

Please can someone help me in understanding why it might be happening / how to fix / alternate approach?

**Comment by hello-ashleyintech** [comment]
Hi, @parthks13! Thanks for reaching out 🙌 

Are you able to send both a successful response where you get no error as well as an unsuccessful response where you do get the mentioned error? This will help me compare what might be deviating in the two calls.

**Comment by parthks13** [comment]
Hey @hello-ashleyintech 
Yes in both the cases the I am able to successfully post the slack message along with the file. In other words, result.ok always comes true but after that the issue comes where I cannot access private shares.

Thanks for the response.

**Comment by seratch** [comment]
Hi @parthks13, the files.upload v2 method completes the process asynchronously for resource efficiency and performance reasons. If your app needs to continue doing something else right after the files are shared in a channel, please consider polling the files.info API with the file IDs until the "shares" property appears. See also:

- https://github.com/slackapi/python-slack-sdk/issues/1329#issuecomment-1430589611
- https://github.com/slackapi/python-slack-sdk/issues/1461#issuecomment-1960432170
