### ISSUE TITLE
Update Axios to 1.7.4 to remove high severity vulnerability 

### ISSUE THREAD

**Issue by Saku75** [slackapi/node-slack-sdk#1874]
As of yesterday, Axios fixed [this vulnerability](https://github.com/advisories/GHSA-8hc4-vh64-cxmj). How much work needs to be done to update Axios?

Let me know if i posted this correctly, wasn't sure what to call it.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
The fix for this should be live in `@slack/web-api` v7.3.4.
