### ISSUE TITLE
Timeout option is not working

### ISSUE THREAD

**Issue by yevheniistepanov45** [slackapi/node-slack-sdk#1914]
The timeout option is not working. 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

`"@slack/web-api": "^7.3.4"`

#### Node.js runtime version

`v18.12.1`

#### OS info

Windows/macOS

#### Steps to reproduce:

Run this code:
```
const {WebClient} = require('@slack/web-api');
const client = new WebClient('botToken', {
    timeout: 2
});
client.users.conversations({
    token: 'userToken'
}).then((r) => {
    console.log(r);
}).catch(e => {
    console.log(e);
})
```

### Expected result:
An AxiosError timeout should be thrown (AxiosError: timeout of 2ms exceeded). You can try the same with pure Axios:

```
const axios = require("axios");
const instance = axios.create({
  timeout: 2,
  baseURL: "https://slack.com",
  headers: {
    "content-type": "application/x-www-form-urlencoded",
    authorization: "Bearer " + "userToken",
  },
});
instance
  .get("/api/users.conversations")
  .then((data) => {
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
  });


```

### Actual result:

The Axios error is not thrown; instead, we receive some warnings (with retries).

```
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
[WARN]  web-api:WebClient:0 http request failed timeout of 2ms exceeded
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by filmaj** [comment]
Interesting, [the `timeout` value is passed to the axios instance created](https://github.com/slackapi/node-slack-sdk/blob/8ba12a98591a3986b6bf11e970ebae70bf7263bd/packages/web-api/src/WebClient.ts#L228-L229), pretty much mirroring your axios example.

We also have a test for this here: https://github.com/slackapi/node-slack-sdk/blob/8ba12a98591a3986b6bf11e970ebae70bf7263bd/packages/web-api/src/WebClient.spec.js#L108-L144

Something doesn't seem right 🤔

**Comment by yevheniistepanov45** [comment]
Hey @filmaj
Yes, you are right. The retry configuration (`retryConfig: { retries: 0 }`) works fine in this case.
Thanks.
