### ISSUE TITLE
Return a promise from RtmClient.start

### ISSUE THREAD

**Issue by ekmartin** [slackapi/node-slack-sdk#198]
``` js
const rtm = new RtmClient(token);
rtm.start()
  .then(data => {
    console.log('Authenticated!', data);
  });
```

Could be equivalent to:

``` js
new Promise((resolve, reject) => {
  rtm.on(RTM.AUTHENTICATED, resolve);
  rtm.on(RTM.UNABLE_TO_RTM_START, reject);
  rtm.start();
});
```

or even wait until the websocket connection is started too, not sure.

**Comment by l12s** [comment]
Hey there, sorry for not replying. This seems pretty reasonable to me. I think that it makes most sense to have this return when `RTM_CONNECTION_OPENED` fires, so the socket is ready and has been acked.

Basically, wrap all of the back and forth logic with the socket opening and `hello` events.

**Comment by l12s** [comment]
Hmm, so it's a little more complicated than I thought.

The issue is that with the auto-reconnect logic it's sort of unclear when the failure function should be invoked. Let me think about this a bit more.

**Comment by ekmartin** [comment]
No problem. As for when to resolve/reject, wouldn't it be possible to resolve when `RTM_CONNECTION_OPENED` fires but only reject when all the reconnection attempts have been used?

Unrelated to promises, shouldn't [this](https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L339) nonetheless emit an error instead of throwing? Seeing as an error is emitted here: https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L250

**Comment by l12s** [comment]
Yep - that should definitely emit.

Related to #170 - I think the current retry policies are probably a bit aggressive - 5 minutes feels a little long. Thoughts?

**Comment by l12s** [comment]
https://github.com/slackhq/node-slack-sdk/pull/223 addresses the bad `throw error`

**Comment by aoberoi** [comment]
just stopping by to triage against our new labels
