### ISSUE TITLE
Reg. handling ratelimiting error for chat.update slack api

### ISSUE THREAD

**Issue by FirozaSurveySparrow22** [slackapi/node-slack-sdk#2010]
**Packages**: 
@slack/web-api - 6.11.1 version

Reproducible in: After crossing the ratelimiting

**The Slack SDK version**
"slack/web-api": "^6.11.1",
"slack/logger": "^3.0.0",
"slack/types": "^2.11.0",

**Node.js runtime version** - 14.17.6

I am using chat.update slack api using WebClient of @slack/web-api. The api has ratelimiting of type Web API Tier 3 (50 per minute) and when I have used more that 50 apis per minute, I am getting an info and warning like below but I am not getting any error so that I can catch the error and then I can implement custom backoff strategy to retry the update api after the given retry-after from the rate limit error.

[INFO] web-api:WebClient:1523 API Call failed due to rate limiting. Will retry in 10 seconds.
[WARN] web-api:WebClient:1523 http request failed A rate limit was exceeded (url: chat.update, retry-after: 10)

I wanted to implement custom backoff strategy, so I want an appropriate error with retry-after header when ratelimiting occurs.
Can you please help in this, if we get the error in the catch block or how does it work.
Thank you.

**Comment by filmaj** [comment]
Have you read the documentation about rate limiting, the event available to listen on, and the option to turn off warning and enable rejection (error) instead? https://slack.dev/node-slack-sdk/web-api#rate-limits

Note that the default rate limit handling in `@slack/web-api` is to look at the `Retry-After` information returned by the Slack backend and honour it. The client, therefore, will retry at the soonest possible time.
