### ISSUE TITLE
web-api: expose axios interceptors as `WebClient` constructor option

### ISSUE THREAD

**Issue by mtjandra** [slackapi/node-slack-sdk#2073]
I'd like to transform outgoing requests from the `@slack/web-api` package similar to other SDKs such as
- Github - [@octokit/rest](https://github.com/octokit/rest.js)
    - can transform outgoing requests uses the concept of [hooks](https://octokit.github.io/rest.js/v21/#hooks)
- Datadog - [@datadog/datadog-api-client](https://github.com/DataDog/datadog-api-client-typescript/)
    - can transform outgoing request by [overriding](https://github.com/DataDog/datadog-api-client-typescript?tab=readme-ov-file#configure-proxy) their [default httpClient](https://github.com/DataDog/datadog-api-client-typescript/blob/c6d3465bd0aeb8545facee8892a4a30e534cfc46/packages/datadog-api-client-common/http/isomorphic-fetch.ts#L13)

This Slack SDK allowa adding additional headers but I require more flexibility. Taking a look at the source it seems it is using axios under the hood ([ref](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L242)). Axios seems to support the concept of [interceptors](https://axios-http.com/docs/interceptors) which would support my use case. 

I'd like to transform all outgoing requests into POST requests with a body representing the original request, add custom headers, then re-route that to a proxy. Is this possible to configure with the current version `@slack/web-api`?

If what I'm asking for is not currently possible, is there anything in the works?

----
**Side note:** was also thinking we could override the method making the outgoing request ([makeRequest](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L564)), although I'm confused why all outgoing requests are [post requests](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L611)

**Comment by filmaj** [comment]
It may be possible in JavaScript, though you'd have to reach in to [the private `axios` instance contained within `WebClient`](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L161-L164), which may be tricky - not sure what the state of the art for ignoring class visibility modifiers is in JS 🤷 

Alternatively, this could be a new feature request: expose some option on the `WebClient` constructor to provide the ability to specify interceptors.

> although I'm confused why all outgoing requests are [post requests](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L611)

Because this project is aimed at interacting solely with the Slack HTTP API, and it is designed to accept POST requests for any HTTP API method you wish to interact with, this is a convenient approach for the API client.

**Comment by mtjandra** [comment]
Hi @filmaj thank you for the reply.

> you'd have to reach in to [the private axios instance contained within WebClient](https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/WebClient.ts#L161-L164)

I would like to avoid overriding and/or modifying private methods/variables as it could lead to unexpected behaviour and breaking changes on version updates.


> Alternatively, this could be a new feature request: expose some option on the WebClient constructor to provide the ability to specify interceptors.

Yes it would be amazing if this could be added as a feature. I'm sure other consumers would benefit from this feature as well. It seems fairly common for SDKs to allow consumers to hook into the request life cycle.

**Comment by filmaj** [comment]
OK, I've set it as a feature / enhancement. We cannot promise any delivery timelines for it. However, if this is something you need, we welcome pull requests!

**Comment by mtjandra** [comment]
@filmaj I have created a pr: https://github.com/slackapi/node-slack-sdk/pull/2076

I've sign the contributor license agreement, but CI is still failing, please advise

![image](https://github.com/user-attachments/assets/dae4bcda-e953-498e-b54b-43777e36ee4b)

**Comment by filmaj** [comment]
Closing and re-opening - this sometimes helps reset the CLA robot.

**Comment by filmaj** [comment]
I meant to do on the PR, woopsie. Anyways, the CLA check is now resolved. Will review your PR shortly. Thank you for sending it!

**Comment by mtjandra** [comment]
@filmaj any idea on when a new release will be published with these changes?

would love to start using it!

**Comment by filmaj** [comment]
Just released web-api 7.7.0 on npm and as [a GitHub Release](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fweb-api%407.7.0)!
