### ISSUE TITLE
Modal not closing when a permalink(within the modal) is clicked

### ISSUE THREAD

**Issue by megandsouza03** [slackapi/node-slack-sdk#2075]
Currently clicking on the a slack permalink in a modal doesn't close the slack modal. It was working a month back (~9th September). 

However, when I right click the click and select `Open link` (which opens the browser is works as expected that is the modal closes)

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [X] I don't know

### Reproducible in: 

Slack Desktop App & Website ❌ 
Slack mobile works fine ✅ 

#### The Slack SDK version (I don't know)

Slack Desktop App Version
Version 4.40.128
762ca04eeb794ece8401f92b3da19740682f32a5@1728354454 (Production)

#### Node.js runtime version

v18.20.4

#### OS info

ProductName:		macOS
ProductVersion:		14.5

#### Steps to reproduce:

- Create a modal as follows
```
{
	"title": {
		"type": "plain_text",
		"text": "My App",
		"emoji": true
	},
	"submit": {
		"type": "plain_text",
		"text": "Submit",
		"emoji": true
	},
	"type": "modal",
	"close": {
		"type": "plain_text",
		"text": "Cancel",
		"emoji": true
	},
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "<{INSERT-PERMALINK-1}|Task1>"
			}
		},
		{
			"type": "section",
			"text": {
				"type": "mrkdwn",
				"text": "<{INSERT-PERMALINK-2}|Task2>"
			}
		}
	]
}
```

- Open the modal 
- Now, select Task 1, the back view scrolls to the permalink but doesn't close the modal 
- Now, right click on Task 1 and select "Open link", the browser opens and the modal is closed. 
- Note: It was working a month back approximately, where the modal closed.

### Expected result:

The Modal should close when a permalink within the slack modal is click upon

### Actual result:

The Modal doesn't close when a permalink within the slack modal is click upon

**Comment by filmaj** [comment]
@megandsouza03 what do you mean by 'permalink'? As in, a link to a message within Slack?

**Comment by megandsouza03** [comment]
Yes, I mean links received via `getPermalink` which references other slack messages 

https://api.slack.com/methods/chat.getPermalink

**Comment by seratch** [comment]
Thank you for sharing this. I don't think this behavior was by design. At least, the modal and its Block Kit on the platform side do not guarantee the behavior, so I think it might be due to the desktop app's implementation back then, rather than its design philosophy. 

Unfortunately, there is no workaround to achieve the same user experience at this moment. To request a feature addition for this use case, please contact our customer support team via either /feedback in your Slack workspce or https://my.slack.com/help/requests/new. Thank you again for taking the time to share this.

**Comment by megandsouza03** [comment]
Thanks for the insight on this! I'll get back on creating a feature request on this!
