### ISSUE TITLE
Medium vulnerability : Update Axios to 1.7.8

### ISSUE THREAD

**Issue by s-dupuis** [slackapi/node-slack-sdk#2115]
Axios fixed [this vulnerability](https://cwe.mitre.org/data/definitions/79.html) in https://github.com/axios/axios/pull/6714.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

### Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @s-dupuis! 👋 Thanks for submitting this.

I will come out with a PR to bump the minimum version of Axios in the `webhook` package to `1.7.8` shortly. If the package is ready to release, I will also release it!

**Comment by hello-ashleyintech** [comment]
Also looks like this needs to be updated for `web-api` and `interactive-messages`!

**Comment by zimeg** [comment]
Bumping to `1.7.8` seems good - I'm not sure if the changes in `1.7.9` are needed - but I'm wondering where this was noted as a major vulnerability? 🤔 

@s-dupuis The issues linked in that PR hint at this being a possible warning, but I'm not finding a CVE for it. Do you know if this might've been posted somewhere?

**Comment by hello-ashleyintech** [comment]
@zimeg I'm seeing Snyk listing it as a medium vuln (versions <1.7.8) [here](https://security.snyk.io/package/npm/axios)!

**Comment by s-dupuis** [comment]
@zimeg @hello-ashleyintech I made a mistake when creating this issue, this is indeed a medium vulnerability. Thank you for the quick fix !

**Comment by hello-ashleyintech** [comment]
This has now been released to `@slack/webhook@7.0.4` and `@slack/web-api@7.8.0`, both available on NPM now! ✨ closing this issue since the root of the issue has been resolved- I will be updating these dependency versions in other packages, as well as BoltJS , in separate PRs on Monday!
