### ISSUE TITLE
Alternative token in place of bots in certain API calls

### ISSUE THREAD

**Issue by justin97530** [slackapi/node-slack-sdk#237]
This is helpful for things like message deletion, which cannot be done with a bot token.

**Comment by DEGoodmanWilson** [comment]
(Thanks for this, will help in tracking the issue, will have more to say later today.)

**Comment by DEGoodmanWilson** [comment]
Later that day: apparently not.

So, I've had some time to go through the way tokens are handled in the code, and I'm not convinced that `node-slack-sdk` is the right level to address this issue, as in general I think this SDK should not have strong opinions about how to use your tokens. Please tell me if you disagree, but it seems to me the Thing to Do® would be to create two Slack objects, one with each of the two tokens returned by `oauth.access`, and then decide which object to use depending on the call.

**Comment by aoberoi** [comment]
i think this is a legitimate use case for the slack client, but i'd like to solve for it using the approach in the referencing issue above.
