### ISSUE TITLE
Add event de-duplication

### ISSUE THREAD

**Issue by DEGoodmanWilson** [slackapi/node-slack-sdk#238]
Apparently during the Nov outage, our backend sent out duplicate events. This caused a lot of problems for chat-ops people. Let's add support for event de-duping!

**Comment by aoberoi** [comment]
de-duplication of events is going to require considerations in the DataStore layer. i don't have an answer of how we will accomplish this yet, but i think implementing it will require a very new approach.

there's an open discussion about what the future of that DataStore API will be in #330, and this use case is important for that discussion.

**Comment by aoberoi** [comment]
The data store has officially been deprecated. Closing this issue.
