### ISSUE TITLE
Documentation for usage in a distributed Slack app

### ISSUE THREAD

**Issue by xWee** [slackapi/node-slack-sdk#239]
I'm looking at creating an app for Slack that can be installed across multiple different Slack teams. This SDK works great with one team. As many people add the app to slack via "Add to Slack" button, I get their bot_access_token. Now how should I run the code with so many Slack tokens. How can I do this?
This is solution on [Ruby](https://github.com/dblock/slack-ruby-bot-server).

**Comment by DEGoodmanWilson** [comment]
This is an excellent question. I don't have a good answer for you at the moment, but I'll be researching this and getting back to you—and then sharing the result in our documentation as well! Meanwhile, if others here have solutions they'd like to share, I think hearing a number of different voices might be helpful.

**Comment by andrewpbrett** [comment]
The bot I've been working on is installed across ~100 teams right now and runs on Heroku: https://github.com/beeminder/beebot

It might be terribly, terribly wrong, but I created an endpoint to store the tokens in Redis and then when the app restarts, fetch all those keys and create a Slack RTM client for each one. If people have ideas or suggestions for improvement let me know! Hope it's helpful for you to see.

**Comment by aoberoi** [comment]
i think @andrewpbrett has got the right idea. ideally you are storing your access tokens in some persistent storage, and you read from that storage whenever you need to instantiate a client. i think its valid to keep this issue around as a docs issue, and we potentially need to surface better examples or even a step-by-step guide.

i'm going to take @xWee's mention of the ruby bot framework as a request for a higher level framework take this information to that issue.

**Comment by aoberoi** [comment]
worth noting: there is the [`@aoberoi/passport-slack`](https://github.com/aoberoi/passport-slack) package that is useful for handling the OAuth flow. its likely to become an officially supported package sometime in the future.
