### ISSUE TITLE
Support auto reconnect on websocket errors

### ISSUE THREAD

**Issue by mhahn** [slackapi/node-slack-sdk#240]
I think we should support reconnecting on websocket errors instead of just emitting the error.

https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L576

I'm running this in production and will sporadically get "Socket Hang Up" or other such errors which bypass the current auto reconnection logic.

**Comment by mhahn** [comment]
There is also this comment which I hope doesn't get implemented :) https://github.com/slackhq/node-slack-sdk/blob/3.3.0/lib/clients/rtm/client.js#L343

**Comment by CharlieHess** [comment]
So our reconnect policy is more legit after #349, but I think we've decided we're not gonna try to reconnect on just any ole error (since not all errors will result in a d/c).
