### ISSUE TITLE
File Availability

### ISSUE THREAD

**Issue by jdcauley** [slackapi/node-slack-sdk#242]
I've had several experiences using the RTM apis that result in empty or nonexistent files when requested after message is posted via Real Time.

Is there a best method for dealing with this issue?

**Comment by DEGoodmanWilson** [comment]
Could you say a little more about what you are experiencing? Is it that you receive a (`file_shared`)[https://api.slack.com/events/file_shared] event, and then find that you cannot download the file? This might be an authentication issue, perhaps—I don't know if we properly handle authenticated file downloads. Anyway, more details on the nature of the failure would help!

**Comment by aoberoi** [comment]
@jdcauley ping! can you provide any more details?
