### ISSUE TITLE
Confusing implications of "UNABLE_TO_RTM_START"

### ISSUE THREAD

**Issue by mhahn** [slackapi/node-slack-sdk#245]
I think https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L348 should be some event other than `UNABLE_TO_RTM_START`.

here: https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L258, an `UNABLE_TO_RTM_START` message is published, but that doesn't mean anything definitively. If it happens to be an error it can't recover from, `DISCONNECT` is later published. If `autoReconnect` is enabled, it will attempt to reconnect. Which might publish `UNABLE_TO_RTM_START` because we've exceeded the max connection attempts.

I think in the case of: https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L348, we should raise either a distinct message or call `DISCONNECT` so that at least we're consistent.

My goal is to know when an RTM connection is hosed, ie. `DISCONNECT` but right now `UNABLE_TO_RTM_START` can also sometimes indicate that the connection is lost.

**Comment by mhahn** [comment]
Sure.

**Scenario 1: Connecting with a token that is no longer valid (ie. `account_inactive` is returned)**
- emit `CLIENT_EVENTS.CONNECTING`
- start fails with `account_inactive` which is listed within https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L24
- emit `CLIENT_EVENTS.UNABLE_TO_RTM_START`
- emit `CLIENT_EVENTS.DISCONNECT`

this token is invalid and something should be done (ie. deactivating the team in your system to prevent future connections)

**Scenario 2: Network failure, auto-reconnect not enabled**
- emit `CLIENT_EVENTS.CONNECTING`
- start fails with some error not listed in https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L24
- emit `CLIENT_EVENTS.UNABLE_TO_RTM_START`

you wish you would have enabled auto reconnecting

**Scenario 3: Network failure, auto-reconnect enabled**
- emit `CLIENT_EVENTS.CONNECTING`
- start fails with some error not listed in https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L24
- emit `CLIENT_EVENTS.UNABLE_TO_RTM_START`
- emit `CLIENT_EVENTS.ATTEMPTING_RECONNECT`
- connection attempts exceed MAX_CONNECTION_ATTEMPTS (https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L346)
- emit `CLIENT_EVENTS.UNABLE_TO_RTM_START`

In Scenario 2, `UNABLE_TO_RTM_START` is what i would listen to in order to log an error message about connection issues. In Scenario 3, `UNABLE_TO_RTM_START` doesn't indicate that the connection will never get established, unless I check the string error message of:
https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L349, since reconnection attempts can occur after an `UNABLE_TO_RTM_START`.

If we wanted to be backwards compatible, we could add a `code` that gets emitted with `UNABLE_TO_RTM_START` that indicates no more connection attempts will occur. Alternatively, a slightly less breaking change than raising a new error message would be to set this: https://github.com/slackhq/node-slack-sdk/blob/master/lib/clients/rtm/client.js#L349 to some constant code that could be checked against.

Does that help?

**Comment by DEGoodmanWilson** [comment]
Very helpful! Thank you!
