### ISSUE TITLE
Events API middleware client

### ISSUE THREAD

**Issue by Starfox64** [slackapi/node-slack-sdk#262]
Would it be within the scope of the SDK to provide an express middleware that would handle requests coming from the Events API?

I was thinking about something like this:

``` javascript
const EventsMiddleware = require('@slack/client').EventsMiddleware;
const MemoryDataStore = require('@slack/client').MemoryDataStore;
const API_EVENTS = require('@slack/client').API_EVENTS;

var events = new EventsMiddleware('TOKEN', { // Token used to populate the DataStore.
  slackToken: 'XXYYZZ', // Token to verify that the request is coming from Slack.
  dataStore: new MemoryDataStore()
});

app.use('/eventsapi', events.middleware);

events.on(API_EVENTS.MESSAGE.CHANNEL, (data) => {
  console.log('Message received!');
});
```

I would be willing to work on this but I'd like to have your input first.

**Comment by DEGoodmanWilson** [comment]
I'd like to think a little more about the structure of this, but in general: Hells yes!

It would be cool if we could do something similar with the RTM api, so you could pick which method to use to connect as a bot.

**Comment by Starfox64** [comment]
> It would be cool if we could do something similar with the RTM api, so you could pick which method to use to connect as a bot.

I don't quite understand, would you rather have two distinct clients or just a single one where you can choose how to receive events?

**Comment by mvaragnat** [comment]
This, or a dedicated events API client ?

In any case, it would be great. I want to test the new API :-D

**Comment by DEGoodmanWilson** [comment]
Sorry for the long delay in returning to this. Adding this feature is now in the planning stages, and we hope to start actively working on building it very soon!

**Comment by aoberoi** [comment]
@Starfox64 thanks for taking the time to sketch an API design for us, that is super helpful!

Personally, I think prototyping this as a separate module makes a lot of sense. I hope that it's something that would compose well with this SDK, or even be included in this SDK.

I'll keep this thread updated with any developments, and you should expect something about this topic in the next couple weeks.

**Comment by LaurentVB** [comment]
related ? https://github.com/johnagan/express-slack

**Comment by aoberoi** [comment]
good news! we've just released a new [Slack Event Adapter module for Node](https://github.com/slackapi/node-slack-events-api). you can get it on npm with `npm install @slack/events-api`).

its a pretty basic utility that helps you set up listeners and adhere to some best practices. we look forward to enhancing it with new features (read: you feedback and ideas welcome) and potentially integrating it into this package in the future.

**Comment by aoberoi** [comment]
since the module was released and is being used by many developers, i'm closing this issue.
