### ISSUE TITLE
Adding a reaction to a message with RTM client.

### ISSUE THREAD

**Issue by xori** [slackapi/node-slack-sdk#275]
- [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
- [x] I've searched for any related issues and avoided creating a duplicate issue.
#### Description

Is there an official way of adding reactions with the RTM client? I know it's possible because I'm doing this right now, and it's working. 

``` javascript
rtmClient._chat.makeAPICall('reactions.add', { name: 'hand' }, { 
    channel: 'CHANID',
    timestamp: 'TIMESTAMP' 
})
```

Is there a reason why you don't expose the `.makeAPICall()`? Or do you and is it just named something else? Personally I think adding a reaction to a _message_ should fall under the _real-time-messaging_ api as it's conceptually like adding an attachment.

**Comment by DEGoodmanWilson** [comment]
So, although it looks like you can react to messages with the RTM API, actually this is an illusion. You can only do it with the Web API—`rtmClient.__chat.makeAPICall` just calls out to the Web API. Properly, you should be using an instance of `webclient` to do that, as you are digging around in object internals that are subject to change.

So, try this instead:
```
var web = new WebClient(token);

web.reactions.add("joy_cat", {
    channel: "C1234",
    timestamp: "123.456"
});
```
