### ISSUE TITLE
Slack Web API 'users.profile.get' method question

### ISSUE THREAD

**Issue by DevanB** [slackapi/node-slack-sdk#279]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I'm trying to figure out how to call the `users.profile.get` Slack Web API method from this library. Is it possible? The only thing I can find remotely close is the RTM dataStore method `getUserById`.

**Comment by DEGoodmanWilson** [comment]
Hello, at the moment we don't have an explicit method to call this endpoint. However, you can call any arbitrary endpoint, like `users.profile.get` with the `WebClient.makeAPICall()` method, as such:

```
var WebClient = require('@slack/client').WebClient;
var web = new WebClient(token);

web.makeAPICall('users.profile.get', null /*no required args to this call*/, {
    user: "U123", //optional user param
    include_labels: false //optional include_labels param, defaults to false
}, function(err, info) {
   //err is set if there was an error 
   //otherwise info will be an object that contains the result of the call
   if (!err) {
       console.log(info.howdy);
   }
});

**Comment by e-founders** [comment]
Looks like the `makeAPICall` is actually prefixed by an underscore so use `web._makeAPICall` :)

**Comment by DEGoodmanWilson** [comment]
:facepalm: you are of course absolutely correct on that, thank you. As it happens, a closely related issue was fixed in #289 and released as part of v3.7.0. A similar fix can be made here as well—I'll get on that this morning.

**Comment by DEGoodmanWilson** [comment]
@DevanB @e-founders Please have a look at #297 and tell me if this sorts out your issue! If so, I'll add some tests and merge it in.

**Comment by e-founders** [comment]
Works like a charm, thanks @DEGoodmanWilson !
