### ISSUE TITLE
Internal links inside JSDoc blocks do not lead anywhere

### ISSUE THREAD

**Issue by dempfi** [slackapi/node-slack-sdk#285]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
The information about `authorship` referenced in the code is missing in repo and in the standalone docs.

### Expected result:
Some explanation in docs or anywhere

### Actual result:
no entry in docs or in comments in the code

### Attachments:
https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/web/facets/chat.js#L78

**Comment by DEGoodmanWilson** [comment]
Hello! Questions about how to use the Slack Web API _itself_ are best answered by going to the source, in this case https://api.slack.com/methods/chat.postMessage

That said, we could probably add this fact to the documentation, and I'll put it on the list to do so for our weekly sprint.

**Comment by dempfi** [comment]
@DEGoodmanWilson thank you for pointing out to right docs

**Comment by aoberoi** [comment]
This issue seems to be more broadly part of #294. I'm going to rename it to give it a more precise action step, but please see the linked issue for more context.

**Comment by aoberoi** [comment]
fixed in #439
