### ISSUE TITLE
Cannot access headers (and thus X-OAuth-Scopes)

### ISSUE THREAD

**Issue by benjie** [slackapi/node-slack-sdk#292]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md). (Also this link doesn't work in GitHub issues preview.)
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

When doing an API fetch, headers aren't available and thus we can't determine what OAuth scopes are available to the current access token.

### Workaround

Bypass the SDK and perform a simple HTTPS request with `?token=...`; then read the headers from this response.

```
$ curl https://slack.com/api/files.list?token=abcd -I
HTTP/1.1 200 OK
X-OAuth-Scopes: files:read, chat:write:bot
X-Accepted-OAuth-Scopes: files:read
```

#### Reproducible in:

Node.js 6.8.1
@slack/client version: 3.6.1

#### Steps to reproduce:

1. `const slack = new SlackWebClient(accessToken);`
2. `slack.team.info((err, details) => {...})`
3. No way to determine headers as described in [Working with Scopes](https://api.slack.com/docs/oauth-scopes)

### Expected result:

Response data (JSON) and headers.

### Actual result:

Response data only.

**Comment by DEGoodmanWilson** [comment]
This is quite good, thanks for this! We should look into adding returning that information to the callbacks for sure. Shouldn't be hard, I think!

**Comment by DEGoodmanWilson** [comment]
@benjie Would you have a look at #296 and see if this helps resolve your issue?

**Comment by benjie** [comment]
Looks like it should solve it; I also like the improvements to error handling, the previous behaviour was not idiomatic. Thanks! 👍
