### ISSUE TITLE
Reference documentation for web and RTM clients should contain facets

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#294]
* [X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> Currently the reference documentation for some of the most critical objects ([WebAPIClient](https://slackapi.github.io/node-slack-sdk/reference/WebAPIClient) and [RtmClient](https://slackapi.github.io/node-slack-sdk/reference/RTMClient)) are not very useful because they do not surface the facets.

**Comment by choujar** [comment]
Hi folks, any update on this? I'm struggling with the current docs...
