### ISSUE TITLE
module.exports.repository.replace is not a function

### ISSUE THREAD

**Issue by Rauno56** [slackapi/node-slack-sdk#303]
* [X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

When I do: 
```
npm install @slack/client
node -e 'require("@slack/client")'
```

The output I get is this:
```
TypeError: module.exports.repository.replace is not a function
```

It's because on the installed version the value of repository property in package.json is:
```
{ type: 'git',
  url: 'git+https://github.com/slackapi/node-slack-sdk.git' }
```
Which, I guess, is not expected. 

On linux. Latest version.

**Comment by palmerabollo** [comment]
Same here. The module is broken.

**Comment by DEGoodmanWilson** [comment]
Right. I did not expect that NPM would actually alter the package.json file. TIL. Getting a fix out now.

**Comment by DEGoodmanWilson** [comment]
@Rauno56 @palmerabollo Can you confirm the issue is resolved?

**Comment by palmerabollo** [comment]
It works now. Thank you @DEGoodmanWilson.
