### ISSUE TITLE
Is there a way to get the bot id/profile from memory datastore?

### ISSUE THREAD

**Issue by denouche** [slackapi/node-slack-sdk#306]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Is there a way to get the bot id/profile from memory datastore?
For now I can store it by myself in the "CLIENT_EVENTS.RTM.AUTHENTICATED" event, but as the memory datastore store all the needed informations, maybe the current bot profile could be stored also in the datastore?

The use case is the following:

I want to be able to know if someone is talking to the bot on a channel.
So when the bot receive for example this:
`coucou <@U00123456> ça va ?`
I need to be able to compare the given `U00123456` with the bot id.

By the way maybe there is another way to achieve that?

Thank you in advance

**Comment by aoberoi** [comment]
you should be able to read the bot user ID from the `RtmClient` instance itself: `rtm.activeUserId`.

you can find details about the your bot user's profile in the data store using `rtm.dataStore.getUserById(rtm.activeUserId)`.
