### ISSUE TITLE
Helper function to download a file

### ISSUE THREAD

**Issue by njordhov** [slackapi/node-slack-sdk#308]
I suggest adding a method on the Web API to *download a file from slack*, symmetrical to `files.upload`.

**Comment by Everesty** [comment]
First off, this repository is for handling the client that _uses_ the Web API, which is produced by some lovely engineers at Slack. We have no control over what is and isn't in the API. Nonetheless, such a method (one that downloads files) isn't exactly possible with the Web API (can't _force_ a client to download something, you can only send data).

**But,** there is a way to do what you're looking for: simply use an http client (such as [request](https://npmjs.org/package/request)) to go to the file's url (which you can get using the [`files.list` method](https://api.slack.com/methods/files.list)) and save the file's response to disk.

Further, there's a special little bit of authentication you need to do in your request to get the file (using it's `url_private` field), as specified by [the `file` type documentation](https://api.slack.com/types/file#authentication). Simply, there must be an `Authentication` header present in the request that's set to `Bearer YOUR_TOKEN` (which may be the bot's token or a [OAuth](https://api.slack.com/docs/oauth) token).

Here's an example of what all of that would look like:

```js
const fs = require('fs');
const request = require('request');
const WebClient = require('@slack/client').WebClient;

const web = new WebClient(your token and options);

web.files.list({}, function(err, fileListResp) {
  if (err)
    return console.log(err);

  // Strategically choose a file to download.
  var filePrivateUrl = fileListResp.files[Math.floor(
    Math.random() * fileListResp.files.length)].url_private;

  // If you don't want to write the returned data to a file then just remove the
  // `pipe` call and supply `request` with a callback.
  request({
    url: filePrivateUrl,
    headers: {
      'Authentication': 'Bearer ' + YOUR_TOKEN // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    }
  }).pipe(fs.createWriteStream('./thefile'));
});
```

I didn't test the code, it could error. I'm also unaware of any situation in which a file doesn't have a `url_private` field. You'll have to do your own testing to make sure the above approach is sound (sorry). It should still be a solid basis for what you're attempting to achieve. Good luck!

**Comment by eelkeh** [comment]
Small correction: `Authentication` should be `Authorization`

**Comment by Everesty** [comment]
Thanks for noticing that! I edited my response to help anyone else who looks at it in the future.

**Comment by aoberoi** [comment]
i think the SDK could provide a helper function to download actual files. what i'm imagining is a function `web.helpers.fileDownload(fileId, [opts])` and the opts could allow you to specify if you want the return value to be a readable stream or a Buffer.

**Comment by aoberoi** [comment]
As a reminder, this is an issue where we'd be happy to review and accept a contribution from the community. If you need any guidance or help with that process, let us know.

**Comment by jumanakarwa** [comment]
Im trying to download a file using Python and have similar syntax, however when I download the file along with the Auth token as suggested above, I get the Slack html web page asking me to sign in.

tokenSlackAuth = "Bearer xoxp-<OAuth user token>"
headers={"Authorization": tokenSlack, "content-type" : contentType}
filename = download_file(url, filePath, headers)

def download_file(url, filename, headers):
    f = open(filename, "w") 
    try:
        with requests.get(url, headers) as req:
            with open(filename, 'wb') as f:
                for chunk in req.iter_content(chunk_size=1024):
                    if chunk:
                        print("chunk : ", chunk)
                        f.write(chunk)
            return filename
    except Exception as e:
        print(e)
        return None

**Comment by spullara** [comment]
I am getting this too. A bunch of HTML rather than the file contents.

**Comment by seratch** [comment]
We may want to have something like this in the future for convenience. 

For references, we have been receiving questions about this:

* https://github.com/slackapi/bolt-python/issues/266
* https://github.com/slackapi/java-slack-sdk/issues/453

**Comment by master0v** [comment]
It is worth mentioning that file:read scope is required for this to work!

**Comment by siramNIkhil2000** [comment]
> Im trying to download a file using Python and have similar syntax, however when I download the file along with the Auth token as suggested above, I get the Slack html web page asking me to sign in.
> 
> ```python
> tokenSlackAuth = "Bearer xoxp-<OAuth user token>"
> headers={"Authorization": tokenSlackAuth, "content-type" : contentType}
> filename = download_file(url, filePath, headers)
> 
> def download_file(url, filename, headers):
>     f = open(filename, "w") 
>     try:
>         with requests.get(url, headers) as req:
>             with open(filename, 'wb') as f:
>                 for chunk in req.iter_content(chunk_size=1024):
>                     if chunk:
>                         print("chunk : ", chunk)
>                         f.write(chunk)
>             return filename
>     except Exception as e:
>         print(e)
>         return None          
> ```
please use `requests.get(url, headers=headers)`, else we will be getting a HTML page instead of the attachment even if we have `files:read` scope.
