### ISSUE TITLE
Documentation for Receiving Messages is incorrect

### ISSUE THREAD

**Issue by mydigitalself** [slackapi/node-slack-sdk#315]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Two issues I'm experiencing.

Firstly, https://slackapi.github.io/node-slack-sdk/bots#receiving-messages has the following code snippet and I think your documentation is incorrect.

```
var RtmClient = require('@slack/client').RtmClient;

var bot_token = process.env.SLACK_BOT_TOKEN || '';

var rtm = new RtmClient(bot_token);
rtm.start();

rtm.on(RTM_EVENTS.MESSAGE, function handleRtmMessage(message) {
  console.log('Message:', message); //this is no doubt the lamest possible message handler, but you get the idea
});
```

`RTM_EVENTS` is undefined. Looking at other documents, you need to add 

```
var RTM_EVENTS = require('@slack/client').CLIENT_EVENTS.RTM;
```

Is that correct? Note in other examples it is in fact `RTM_CLIENT_EVENTS`.

If so, perhaps I have a conceptual misunderstanding - can I use this to listen to messages for ME, not a bot? I generated a personal token from here: https://api.slack.com/docs/oauth-test-tokens

I would expect then for that token to work with the following code:

```
var RtmClient = require('@slack/client').RtmClient;
var RTM_CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS.RTM;
var bot_token = process.env.SLACK_BOT_TOKEN || 'XXX MY TOKEN HIDDEN XXXX';

var rtm = new RtmClient(bot_token);
rtm.start();

rtm.on(RTM_CLIENT_EVENTS.MESSAGE, function handleRtmMessage(message) {
  console.log('Message:', message); //this is no doubt the lamest possible message handler, but you get the idea
});
```

All I ever get from that code is the following shortly after launching, which is effectively the previous message I typed. No other messages sent to me seem to come through.

```
info: message received on reconnect with no registered callback:
{"reply_to":21040,"type":"message","channel":"D3V3R53KN","user":"U3NV8A9BK","text":"***my hidden message***","ts":"1485965459.000012"}
```

I'm basically trying to write an app that listens to messages for me and make it control my Phillip Hue lights when I have a notification - like make them flash briefly or change colour.

#### Reproducible in:
{project_name} version: Node API "@slack/client": "^3.8.1"
OS version(s): Mac

#### Steps to reproduce:

1. See code error above, in particular regarding issue in documentation
2. Help a brother out by conceptually explaining if what I'm doing is correct - thanks!
3. Profit

### Expected result:

I expect to get a message for every message my user receives.

### Actual result:

Only some random startup message

### Attachments:

None

**Comment by Roach** [comment]
@mydigitalself thanks for calling this out, I've merged an updated version of the docs. Please let us know if you run into any more issues 👍
