### ISSUE TITLE
Mobile slack doesn't parse <@userids> in the author field of attachments

### ISSUE THREAD

**Issue by roberttod** [slackapi/node-slack-sdk#316]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
When sending an attachment using the web API, user IDs in the author field do not get parsed. This only happens on mobile and works fine on desktop slack.

#### Reproducible in:
Slack version: 3.12
OS version(s): 10.2.1
Device(s): iPhone 6S

#### Steps to reproduce:
Send an attachment from a bot with a user ID in the `author_name` field
```js
web.chat.postMessage(channel.id, 'should say @robert, <@U02898598>', {
  attachments: [
    {
      author_name: 'should also say @robert, <@U02898598>',
      text: 'should also say @robert, <@U02898598>'
    }
  ]
})
```

### Expected result:
The user ID should be parsed and shown as a link. This works fine on desktop slack.

### Actual result:
The username is not parsed on mobile.

### Attachments:
On desktop
<img width="300" alt="screen shot 2017-02-02 at 16 40 17" src="https://cloud.githubusercontent.com/assets/823104/22570056/d977fbd8-e967-11e6-8843-1d3c7525aabd.png">

On mobile
<img width="376" alt="screen shot 2017-02-02 at 16 40 33" src="https://cloud.githubusercontent.com/assets/823104/22570067/e3a76a58-e967-11e6-95ed-c25f0e4e09cf.png">

**Comment by Everesty** [comment]
This is a great thing for us to know, especially if someone asks about it in the future! However, this isn't the place to report this.

You should [send a help request](https://slack.com/help/requests/new) to Slack themselves about this issue, as we have nothing to do with it.

Nice job finding this, though!
