### ISSUE TITLE
Duplicate RTM_CONNECTION_OPENED

### ISSUE THREAD

**Issue by sarabsilveira** [slackapi/node-slack-sdk#320]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

Hi,

I've been experiencing an issue with duplicate connections with Slack. It seems that we are getting the RTM_CONNECTION_OPENED event more than once in a very short time (in the same millisecond).

Is this something that we should expect?

Thanks in advance for any help.

**Comment by aoberoi** [comment]
hi @sarabsilveira, sorry for taking so so long to find this issue. can you supply some sample code that reproduces this issue? i haven't experienced this, and i haven't found any other reports that could be related, so i don't have a starting point to look at.
