### ISSUE TITLE
New web client with users auth token

### ISSUE THREAD

**Issue by optimadesign** [slackapi/node-slack-sdk#324]
I can successfully `web.chat.postMessage` into a Slack channel using a bot token with `new WebClient()`, but what's best practice for using user auth tokens with `var web = new WebClient(token)` as not to keeping writing over the same client instance over and over?

**Comment by aoberoi** [comment]
i'm very sorry for taking so long to respond!

my advice is to initialize the `WebClient()` when you receive the token you wish to use, and to keep it around in memory (so long as its not becoming a bottleneck).

for a distributed (aka App Directory) app, this would be at the end of the OAuth flow. you might get a single token or multiple (with a bot user) so you might actually end up creating two instances.

for an app for a single team, you probably have the token when the program starts up (environment variable or other configuration) so you'd just instantiate the client(s) on startup.
