### ISSUE TITLE
IncomingWebhook does not send attachments

### ISSUE THREAD

**Issue by samosale** [slackapi/node-slack-sdk#331]
When using IncomingWebhook to send message to slack, it does not send attachments object. 
It normally sends text and other properties but attachments are not shown in channel.

**Comment by jyotman** [comment]
I can successfully send attachments @samosale.

**Comment by aoberoi** [comment]
ditto. can you post a code snippet to reproduce the issue?

**Comment by aoberoi** [comment]
The `v3` line of this project is no longer supported, so we're closing all issues that were specific to those releases. If this issue still persists in current releases, please open a new issue.
