### ISSUE TITLE
Better error messages from RtmClient when passing invalid arguments

### ISSUE THREAD

**Issue by KTachibanaM** [slackapi/node-slack-sdk#333]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

Is there a reason to have different argument order in `web.chat.postMessage` and `rtm.sendMessage`?

I once tried to migrate posting message from `web.chat.postMessage` to `rtm.sendMessage`, and since the former accepts `channel id`/`message`, the later accepts `message`/`channel id`, I had a hard time debugging.

**Comment by aoberoi** [comment]
@KTachibanaM to be honest, i couldn't tell you why. i agree its confusing. hopefully the error messages you got back were helpful enough that it didn't waste too much of your time.

out of curiosity, would you mind sharing why you would be moving from using the web API method to the RTM method?

**Comment by KTachibanaM** [comment]
The error message returned back was neither helpful, because in case of passing in the wrong order of parameters in RTM method, the error message doesn't say what channel id is wrong, but merely the channel id is wrong. I couldn't find the source code on the SDK itself, so I believe the error message is concatenated on server-side.
<img width="835" alt="helpful-slack-api-response" src="https://cloud.githubusercontent.com/assets/3515852/24973905/1987d3de-1f86-11e7-8898-9b9c79079b82.png">

Using a bot token to send a message on behalf of a bot via Web API doesn't seem to show the bot's avatar (maybe name as well? Couldn't remember) on the Slack UI, so I switched from web API to RTM method.

**Comment by kubik369** [comment]
@KTachibanaM You don't need to move to RTM method for that, just pass `{as_user: true}` to optional parameters of the `postMessage` method :)

**Comment by KTachibanaM** [comment]
@kubik369 Good to know that thanks

**Comment by aoberoi** [comment]
as a follow up to this issue, i think what we need is better validation of arguments so we can give users better errors.

one idea is to create new Error types with `code` properties that belong to an enumeration so you can deal with them programmatically.

**Comment by aoberoi** [comment]
new error types are in v4! if there's some shortcoming with those, please open a new issue with a specific idea or bug.
