### ISSUE TITLE
No support for username and icon_emoji attributes in sendMessage

### ISSUE THREAD

**Issue by mazerab** [slackapi/node-slack-sdk#335]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Feature request: in Python the send_message function supports more arguments than the sendMessage function in Node.js. It would be nice to have access to username and icon_emoji attributes.

#### Reproducible in:
{project_name} version: All
OS version(s): All
Device(s): All

#### Steps to reproduce:

Send a message to Slack.

### Expected result:
rtm.sendMessage(JSON.stringify(data.msg), channel, username, icon_emoji);

The above call will send message to a channel on behalf of user specified in username with correct slack icon. 

Here is the Python equivalent:
def send_message(channel_id, message):
    slack_client.api_call(
        "chat.postMessage",
        channel=channel,
        text=message,
        username='support_bot',
        icon_emoji=':robot_face:'
    )

### Actual result:
You can post message to a channel but NOT customize the icon or username. 

### Attachments:
None

**Comment by aoberoi** [comment]
hi @mazerab, i understand that appears frustrating not to have the same feature support. it turns out you're actually comparing two different things. the method you're showing in the Python SDK is actually a call to the Web API, which supports more rich message formatting. This Node SDK has that exact same functionality, but as a different method. see: https://slackapi.github.io/node-slack-sdk/basic_usage#posting-a-message-with-web-api

**Comment by mazerab** [comment]
Thank you for the prompt reply and it does make sense. It would be nice to have this logged as a feature request.

**Comment by aoberoi** [comment]
@mazerab im happy to take feature requests. out of curiosity, is there something preventing you from using the Web API method?

**Comment by mazerab** [comment]
@aoberoi There is nothing preventing me from using Web API and it is working fine. I just find it more natural to continue using the RTM API since this is what I'm using in the script throughout. It would be nice not to have to switch to the Web API to accomplish this simple request.
