### ISSUE TITLE
SLACK_WEBHOOK_URL stopped working

### ISSUE THREAD

**Issue by sibelius** [slackapi/node-slack-sdk#340]
I've created a webhook here: https://<team>.slack.com/apps/<id>-incoming-webhooks

it worked for sometime, and then it stopped working

this is my code:

```jsx
const slackWebhook = 'https://hooks.slack.com/services/...";
export const wh = new IncomingWebhook(slackWebhook);

wh.send({
   attachments: [
      { text: error.message },
   ],
    channel: 'error',
  });
```

**Comment by aoberoi** [comment]
i believe your code should look more like this:

```
const slackWebhook = 'https://hooks.slack.com/services/...';
export const wh = new IncomingWebhook(slackWebhook);

wh.send({
   text: '',
   attachments: [
      { text: error.message },
   ],
    channel: '#error',
  }, callback);
```

i might have misunderstood, and if i have, please show me what type of error you are getting in the callback (or the rejected Promise).

i also wanted to add that i highly discourage you from using a channel name in the incoming webhook in this manner. in fact, this could be a reason for your error as well. from the documentation:
> You cannot override the default username, icon, or channel for incoming webhooks attached to Slack apps. Instead, these values will stubbornly inherit from the associated Slack app configuration.
