### ISSUE TITLE
Ping / pong for rtm client is not implemented correctly

### ISSUE THREAD

**Issue by CharlieHess** [slackapi/node-slack-sdk#348]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
The current logic for ping / pong can lead to spurious disconnects. There are a few reasons for this:

1. We save `_lastPong` when we get a pong message response, but don't check it until the _next_ time we `_pingServer`. Since we `_pingServer` on a 5 second interval, this means the gap can never be lower than 5 seconds. Basically we're imposing a 5 second handicap. :joy:
1. We don't let other messages count as pongs. This can cause starvation if the socket is super busy processing other work **cough** IBM **cough**.
1. On some platforms, like [macOS](https://github.com/electron/electron/issues/5101), timers are artificially throttled when the application is backgrounded. This, in combination with 1, can result in a lot of unnecessary reconnects.

#### Steps to reproduce:

1. Set a `debug` `logLevel`
2. Drop `logger` statements in `_pingServer` and `_handlePong`
3. Subtract the intervals

**Comment by aoberoi** [comment]
fixed in #349
