### ISSUE TITLE
RTM: attachments in rtmClient.send doesnt't work

### ISSUE THREAD

**Issue by navratill** [slackapi/node-slack-sdk#359]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> e.g. Description of the bug or feature
I am using RtmClient for bot integration. Goal is to answer on message with attachments included into answer. Slack's documentation says, that it is possible with RTM: http://bit.ly/2qiL06d

"Messages can also include an attachments property, containing a list of attachment objects."

But when I am sending this object:

`{
    type: TYPES.MESSAGE,
    text: "I am a test message",
    attachments: [
        {
            title: 'Hello Word!',
            color: '#36a64f',
            text: "And here’s an attachment message!"
        }
    ]
}`

It is sent without attachments.

#### Reproducible in:
{project_name} version: 3.9.x

#### Steps to reproduce:

1. create message object with attachments attribute
2. send with RtmClient's send method
3. message to slack will be send without attachments

### Expected result:
> e.g. What you expected to happen
Attachments should be added into received message, as is described in slack's documentation: http://bit.ly/2f972yx

### Actual result:
> e.g. What actually happened
Message is received, but missing attachments

**Comment by aoberoi** [comment]
hi @navratill 

the documentation page you linked is for the general use of receiving (not sending) messages over the RTM or the Events API.

if you consult the documentation for sending messages over RTM, [found here](https://api.slack.com/rtm#formatting_messages), it says the following:

>  The RTM API only supports posting simple messages formatted using our default message formatting mode. It **does not support attachments** or other message formatting modes.

I suggest you instead use the `WebClient` to send your message. And I'm just curious, is there a reason you preferred to use the `RtmClient`?
