### ISSUE TITLE
No api for reactions

### ISSUE THREAD

**Issue by Redblueflame** [slackapi/node-slack-sdk#368]
* [√] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [√] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [√] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
> There are no possibility to add in message an reaction ?
i've readed the docs and changelogs, but any addReaction() or anything else are in those.

#### Reproducible in:
This is a feature request, but i'm in the last version.
#### Steps to reproduce:
This is a feature request.
### Expected result:
> Adding a reaction in messages

### Actual result:
> Nothing...

### Attachments:
> Nothing...

**Comment by aoberoi** [comment]
Hi @Redblueflame,

The `WebClient` supports the following methods: `reactions.add`, `reactions.get`, `reactions.list`, `reactions.remove`

Here is an example of it being used:

```javascript
const WebClient = require('@slack/client').WebClient
const slackWeb = new WebClient(SLACK_TOKEN);

slackWeb.reactions.add(':thumbsup:', { channel: channelId, timestamp: messageTs })
  .then(console.log)
  .catch(console.error);
```

**Comment by aoberoi** [comment]
Let us know if you have any problem with that.

**Comment by Redblueflame** [comment]
How to get a ts from a message event ?
I'm trying but i've not found...
