### ISSUE TITLE
RTM client subscribing to message subtypes is awkward

### ISSUE THREAD

**Issue by husnulhamidiah** [slackapi/node-slack-sdk#375]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
Client does not listen to `RTM_MESSAGE_SUBTYPES` event. I want to listen to file_share event instead of message event. I set to listener one for `RTM_EVENTS.MESSAGE` (all message) and `RTM_MESSAGE_SUBTYPES.FILE_SHARE` (only when user upload a file). When I upload a file, triggered as I expected but not for `RTM_MESSAGE_SUBTYPES.FILE_SHARE`.

#### Steps to reproduce:
Run this simple code:

```
import { RtmClient, CLIENT_EVENTS, RTM_EVENTS, RTM_MESSAGE_SUBTYPES } from '@slack/client'

const BOT_TOKEN = process.env.SLACK_BOT_TOKEN
const rtm = new RtmClient(BOT_TOKEN)

rtm.on(CLIENT_EVENTS.RTM.AUTHENTICATED, (rtmStartData) => console.log('slackbot is running..'))
rtm.on(RTM_EVENTS.MESSAGE, (message) => console.log(message))
rtm.on(RTM_MESSAGE_SUBTYPES.FILE_SHARE, (message) => console.log(message))
rtm.start()
```

### Expected result:
When I upload a file (to any channel or DM), it will print out `message` object TWICE. One from `RTM_EVENTS.MESSAGE` and another from `RTM_MESSAGE_SUBTYPES.FILE_SHARE`.

### Actual result:
It ONLY trigger `RTM_EVENTS.MESSAGE` and NOT `RTM_MESSAGE_SUBTYPES.FILE_SHARE`.

**Comment by aoberoi** [comment]
hi @husnulhamidiah, i understand why you expected this to work that way, the documentation isn't clear on how the subtypes work.

if you want to attach a handler for just the subtype of a message, you would actually do it like this:

```
rtm.on(`${RTM_EVENTS.MESSAGE}::${RTM_MESSAGE_SUBTYPES.FILE_SHARE}`, handlerFn);
```

i'm going to leave this issue open because i think we need to at least improve the documentation of this feature, but even perhaps rethink how those constants work.

**Comment by aoberoi** [comment]
we've improved the documentation around subscribing to message subtypes. i haven't heard of any further desire to add another technique, so i'm closing this issue.

docs: https://slackapi.github.io/node-slack-sdk/rtm_api#listening-for-message-subtypes
