### ISSUE TITLE
web.chat.delete has wrong method signature

### ISSUE THREAD

**Issue by rophy** [slackapi/node-slack-sdk#382]
version: node-slack-sdk@3.8.1, using hubot-slack@3.4.0

According to [api docs](https://api.slack.com/methods/chat.delete), expected method signature should be:

```
client.web.chat.delete(channel, ts, opts, callback)
```

But actually in the mentioned version, it is:

```
client.web.chat.delete(ts, channel, opts, callback)
```

Confused me a while to figure out it.

**Comment by aoberoi** [comment]
Hi @rophy, we think of the Web API arguments in that table as a set, without a natural order. Sorry this is confusing to you. We're considering #381 to help solve this kind of confusion. Your feedback is welcome.
