### ISSUE TITLE
Are slash commands supported ? 

### ISSUE THREAD

**Issue by gterras** [slackapi/node-slack-sdk#393]
I am using `WebClient` along with `eventAdapter` and `messageAdapter`. 

I can't find a way to make slash commands respond with other than a 500 error, using both `/slack/events` and `/slack/actions` endpoints. 

Do I need to handle them "manually" or is there a built-in feature for this ? 

Thank you !

**Comment by aoberoi** [comment]
@gterras: unfortunately, none of these packages support slash commands. **but fortunately** slash commands are super easy in node. here is an example from one of our template apps: https://github.com/slackapi/template-slash-command-and-dialogs/blob/9a459e8494b88245eb63e33db3ba298ea5cb701c/src/index.js#L27. let me know if there's anything specific you might need help with.
