### ISSUE TITLE
Incorrect order of parameters in the chat.unfurl facet

### ISSUE THREAD

**Issue by DominikPalo** [slackapi/node-slack-sdk#412]
### Description

In the chat.unfurl facet function required parameters are ordered as: `ts`, `channel`, `unfurls`
```
ChatFacet.prototype.unfurl = function unfurl(ts, channel, unfurls, opts, optCb) {
   //...
};
```

but in the [chat.unfurl method documentation](https://api.slack.com/methods/chat.unfurl) order is: `channel`, `ts`, `unfurls`.

I'm expecting the same order of req. parameters also in the `chat.unfurl` SDK method (actually `channel`, `ts` are switched).

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
closing in favor if #428
