### ISSUE TITLE
[Security Issue] Uninitialized Memory Exposure (Medium)

### ISSUE THREAD

**Issue by lmammino** [slackapi/node-slack-sdk#417]
### Description

[Source (Snyk)](https://snyk.io/test/npm/@slack/client?tab=issues)

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion
- [X] Security issue

### Requirements
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 3.14.1

node version: any

OS version(s): any

#### Steps to reproduce:

1. Visit [Snyk report page](https://snyk.io/test/npm/@slack/client?tab=issues)

**Comment by aoberoi** [comment]
we're not 100% sure that this issue is reproducible in this package, but its better to be safe than sorry, so we're triaging as `bug`.

discussed in the PR above, but the summary is we will solve this in v4 after we can drop support for node v0.12 and update our dependencies.
