### ISSUE TITLE
TypeError: Expected a function thrown from the lodash package.

### ISSUE THREAD

**Issue by jhale0810** [slackapi/node-slack-sdk#419]
### Description

Trying to initialise RtmClient throws TypeError: Expected a function.

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version:
v3.14.1

node version:
v7.10.1

OS version(s):
MacOS Sierra v10.12.6

#### Steps to reproduce:

1.  `const RtmClient = require('@slack/client').RtmClient;`
2.  `const slack_bot_token = process.env.SLACK_BOT_TOKEN || "";`
3.  `const rtm = RtmClient(slack_bot_token);`

#### Expected result:
`rtm` to be initialised with or without a valid token. If invalid then receive unauthorised error on http req to slack api.

#### Actual result:
Error thrown during `const rtm = RtmClient(slack_bot_token);` call from the Lodash package.

#### Attachments:

![image](https://user-images.githubusercontent.com/32717817/31573736-b6cd5460-b0b9-11e7-91a6-3d8223726895.png)

**Comment by aoberoi** [comment]
thanks for the report @jhale0810!

could you tell me which line number the stack trace contains for the `BaseAPIClient` frame? i can't tell what happened from the screenshot.

also, we've updated the docs to remove the code snippet you used. if the value is `undefined` because the environment variable is not set, then the constructor should succeed.

**Comment by aoberoi** [comment]
The `v3` line of this project is no longer supported, so we're closing all issues that were specific to those releases. If this issue still persists in current releases, please open a new issue.
