### ISSUE TITLE
chat.update: wrong order of required parameters

### ISSUE THREAD

**Issue by Finkes** [slackapi/node-slack-sdk#420]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 3.14.1

node version: 8

OS version(s): Mac OS X

#### Steps to reproduce:

the order of the paremters is different to the official documentation (see https://api.slack.com/methods/chat.update).
The correct order would be: **channel, text, ts** and not: **ts, channel, text**

```
this.webClient.chat.update("<ts>", "<channel>", 'updated message',  { as_user: true }, (error) => {
            console.error(error)
        })
```

#### Expected result:
the call works with the order specified in the API description as described in your docs:

> The required parameters will be entered in the same order and name as presented in the documentation on the API webpage. The optional parameters are passed in as an object whose fields are also named as in the documentation. And finally, the info parameter in the callback will contain an object with fields again as named in the documentation.

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

here are the relevant code lines: 

/node_modules/@slack/client/lib/clients/web/facets/chat.js:147

```
/**
 * Updates a message.
 * @see {@link https://api.slack.com/methods/chat.update|chat.update}
 *
 * @param {?} ts - Timestamp of the message to be updated.
 * @param {?} channel - Channel containing the message to be updated.
 * @param {?} text - New text for the message, using the [default formatting
 *   rules](/docs/formatting).
 * @param {Object=} opts
 * @param {?} opts.attachments - Structured message attachments.
 * @param {?} opts.parse - Change how messages are treated. Defaults to `client`, unlike
 *   `chat.postMessage`. See [below](#formatting).
 * @param {?} opts.link_names - Find and link channel names and usernames. Defaults to `none`.
 *   This parameter should be used in conjunction with `parse`. To set `link_names` to `1`, specify
 *   a `parse` mode of `full`.
 * @param {?} opts.as_user - Pass true to update the message as the authed user. [Bot
 *   users](/bot-users) in this context are considered authed users.
 * @param {function=} optCb Optional callback, if not using promises.
 */
ChatFacet.prototype.update = function update(ts, channel, text, opts, optCb) {
  var requiredArgs = {
    ts: ts,
    channel: channel,
    text: text
  };

  return this.makeAPICall('chat.update', requiredArgs, opts, optCb);
};
```

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
thanks for reporting. please see #428 for follow on steps.
