### ISSUE TITLE
RTMClient does not support sending attachments

### ISSUE THREAD

**Issue by t3h2mas** [slackapi/node-slack-sdk#427]
### Description

RTMClient doesn't support sending of message attachments

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (missing feature)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

The functionality of the RTM client is limited. Message attachments [aren't supported](https://github.com/slackapi/node-slack-sdk/blob/03743068caa535f15a636da164953f402d1899c5/lib/clients/rtm/client.js#L507) in either #sendMessage()` or `#send()`. From what I can tell, this leaves users forced to implement the functionality at a very low level (#ws.send()) using the websockets call. 

The other alternative would be not using node-slack-sdk for the message sending which isn't ideal.

**Comment by t3h2mas** [comment]
After further looking, I am not sure this is possible with the websocket API, not specific to the node implementation. While I don't understand the limitation, if that's the case, this issue could be closed as a non issue

**Comment by aoberoi** [comment]
@t3h2mas that's exactly the issue, unfortunately.

most users find the web client's `chat.postMessage` just as simple (if not more simple) to use as a workaround.
