### ISSUE TITLE
Feature request: mute setTopic in channel

### ISSUE THREAD

**Issue by khuezy** [slackapi/node-slack-sdk#430]
### Description

I'd like to set the channel topic frequently (eg days left til Christmas) but don't want the emote to spam the channel every time I change the topic.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 3.11.0

node version: 8.9.0

OS version(s):

#### Steps to reproduce:

1. channels.setTopic
2.
3.

#### Expected result:

Changes the channel topic to the new topic

#### Actual result:

Changed the channel topic to the new topic BUT it includes the emote from the user:
``` 
user [5:54 PM] 
set the channel topic: Hello 
```

#### Request:

Have ability to mute the response

**Comment by aoberoi** [comment]
@khuezy thanks for filing the issue. i'm not sure i completely understand the request. are you asking for the API to give you an option to not send any mentions in the user's Slack app (or web app) when the topic is changed?

if so, that's not a feature request for the SDK, but more of a feature request for the Web API. i'm happy to take feedback to the team. can i ask more about why the notification is an issue for your users?

there's a few other ways i can think of to get a countdown that's less "visible". how about a slash command that responds with an ephemeral message?

**Comment by khuezy** [comment]
@aoberoi Thank you for responding!

Yes, I would like the Web API to allow topic changes w/o sending notifications to all the users and w/o posting a comment in the channel of the topic change

My use case: Display the current price of a cryptocurrency (eg Bitcoin) every minute as the topic. 

Right now, it when I update the topic, it spams the channel with the topic change and it also notifies my users.

Thank you for forwarding to the team!

**Comment by aoberoi** [comment]
@khuezy thanks for the feedback! i've made the folks internally aware, and i'll update this ticket if we make any decisions about this feature request. for now, since this repo is focussed on SDK development, i will close this issue.
