### ISSUE TITLE
Does not work in webpack'ed environments due to a tricky library

### ISSUE THREAD

**Issue by soramichi** [slackapi/node-slack-sdk#445]
### Description

The sdk uses [pkginfo](https://github.com/indexzero/node-pkginfo) to retrieve the version information of itself. This information is sent to the Slack server with the user-agent string (which I guess is to control some backward/forward compatibilities).

However, the pkginfo library does not work in webpack'ed environments due to two reasons:
1. It opens `package.json` using a `require` statement [here](https://github.com/indexzero/node-pkginfo/blob/master/lib/pkginfo.js#L104), which is automatically replaced by webpack into the whole code of the `require`-d file at a **compilation time**. This clearly is not what is intended by the library and does not work.
2. The `module` variable that the sdk passes to pkginfo refers different things in a normal node.js environment and a webpack'ed environment.

Given this, I guess pkginfo should be removed from the dependencies and a different way to retrieve the version information of the sdk is needed in order to make the sdk work with webpack.

We webpack the sdk with a patch that embeds a fixed value for the version information (instead of retrieving it using pkginfo) and it seems working perfectly. So I guess the only hurdle to make the sdk work with webpack is the pkginfo dependency.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
Hi @soramichi! This is an interesting use case that I hadn’t previously considered. Are you using webpack on your server side code? Or are you trying to use this SDK from the client (browser)?

**Comment by soramichi** [comment]
@aoberoi thanks for the comment. We use our webpacked version of the sdk (with the patch I described above) in the client-side on electron. The reason why we use webpack is that Angular is based upon webpack and we cannot really separate them.

**Comment by aoberoi** [comment]
closing as dup (even though this issue came first) of #466. that issue has more information regarding solutions.
