### ISSUE TITLE
Docs: Changing the request concurrency

### ISSUE THREAD

**Issue by gunar** [slackapi/node-slack-sdk#453]
On documentation here https://github.com/slackapi/node-slack-sdk/blob/12595afb91551ed5c8f93798524c1529767da8ca/docs/_pages/web_client.md#changing-the-request-concurrency the key `maxRequestConcurrency` should be a top-level key (not under `retryConfig`).

**Comment by aoberoi** [comment]
you're totally right! thanks for pointing this one out.
