### ISSUE TITLE
Use batch_presence_aware as default option for rtm.start / rtm.connect

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#456]
### Description

There's an efficiency win when using this option, so it should be the default. Unfortunately, this has to be done in a `semver:major` update because it would change the shape of the event object received in the `"presence_change"` events.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
this didn't make it into v4. my understanding is that its totally dependent on the personal preference of the developer. yes, you can gain efficiency, but no its not required. if this is a feature you'd like to see landed, please `+1`.

**Comment by seratch** [comment]
Let me close this issue due to its inactivity
