### ISSUE TITLE
Getting 404 when installing using npm

### ISSUE THREAD

**Issue by gunjpan** [slackapi/node-slack-sdk#459]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

node version: 
`using node v8.9.4 (npm v5.6.0)`

OS version(s):
Mac Sierra@10.12.6

#### Actual result:

What actually happened
Doing `npm i @slack/client` results in following `npm` error:
```console
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@slack/client' ]
2 info using npm@5.4.2
3 info using node@v8.5.0
4 verbose npm-session ae5525794e702e48
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@slack%2fclient 575ms
8 silly fetchPackageMetaData error for @slack/client@latest 404 Not Found: @slack/client@latest
9 verbose stack Error: 404 Not Found: @slack/client@latest
9 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
9 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
9 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
9 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
9 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
9 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
9 verbose stack     at runCallback (timers.js:781:20)
9 verbose stack     at tryOnImmediate (timers.js:743:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
10 verbose cwd /Users/gunjanpandya/novaDev/slack_app/card-manager-api
11 verbose Darwin 16.7.0
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@slack/client"
13 verbose node v8.5.0
14 verbose npm  v5.4.2
15 error code E404
16 error 404 Not Found: @slack/client@latest
17 verbose exit [ 1, true ]
```
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by gunjpan** [comment]
@aoberoi thoughts? FWIW, I updated my `npm` and reinstalled as well.

**Comment by aoberoi** [comment]
@gunjpan, i can't reproduce this problem. can you try running the following command to see if its still a 404: `curl https://registry.npmjs.org/@slack%2fclient`? if it outputs a big JSON blob, you should be good. if not, this might be an issue on your system (firewalls?). to further investigate could you try installing some other package (e.g. `npm i express`)?

**Comment by gunjpan** [comment]
Yup.. that curl gives me a blob. 
>to further investigate could you try installing some other package (e.g. npm i express)?

I did install `rimraf` as a test.

**Comment by aoberoi** [comment]
stupid question: did you try `npm i @slack/client` again after the `rimraf` success?

**Comment by gunjpan** [comment]
It's working now, I had my enterprise creds in global `.npmrc` file. 🙈

**Comment by gunjpan** [comment]
@aoberoi Thanks for a timely response! Appreciate that, have a great day! 👍
