### ISSUE TITLE
4.0.0 removed examples

### ISSUE THREAD

**Issue by BeauBouchard** [slackapi/node-slack-sdk#474]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 4.0.0

As of  #473 all /examples have gone away. 
I am trying to get my IRC based bot to us this SDK instead for our slack channels. 
When can we expect docs and examples for 4.0.0?

**Comment by aoberoi** [comment]
the best place to find information to help you migrate your bot is the dedicated [migration guide](https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4).

the documentation in the README.md file, and on [the website](https://slackapi.github.io/node-slack-sdk/) is updated a handful of examples. if there's anything in particular you find missing, do let us know.

its true that the `examples/` directory was removed. they hadn't been kept up to date in quite some time, and i hadn't seen issues reported, so i figured that people were using the documentation instead. sorry about that!

the `docs/` directory is still in the project tree. can you double check that you see it?

**Comment by dustingraves** [comment]
The markdown is broken on the website https://slackapi.github.io/node-slack-sdk/reference/WebClient

**Comment by aoberoi** [comment]
@dustingraves oh gosh, thanks for letting me know!

**Comment by aoberoi** [comment]
@dustingraves #476 is a crude but effective fix, for now. i'll make a ticket to track getting the method aliases back into the docs.

**Comment by BeauBouchard** [comment]
Thanks ! :D @aoberoi
