### ISSUE TITLE
Can I omit IncomingWebhookDefaultArguments?

### ISSUE THREAD

**Issue by shamofu** [slackapi/node-slack-sdk#479]
### Description

After https://github.com/slackapi/node-slack-sdk/commit/fa70a8d5794401bf5e86e57b24c1a3fc907096c6, I cannot omit `defaults` value in this line.
https://github.com/slackapi/node-slack-sdk/blob/fa70a8d5794401bf5e86e57b24c1a3fc907096c6/src/IncomingWebhook.ts#L38

Is this expected behavior? Or can I do like this?
https://github.com/shamofu/node-slack-sdk/commit/9206686cf20b8dda1e27b751f6167e3ac52d69be

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: v4.0.0

node version: v8.9.4

OS version(s): Ubuntu 17.10 (GNU/Linux 4.13.0-36-generic x86_64)

#### Steps to reproduce:

1. `const slackWebhook = process.env.SLACK_WEBHOOK_URL || '';`
2. `const webhook = new incomingWebhook(slackWebhook);`
3. `webhook.send('some messages', (err) => { console.log(err); });`

#### Expected result:

No error.

#### Actual result:

```
TypeError: Cannot set property 'text' of undefined
  at IncomingWebhook.send (/home/shamofu/repo/node_modules/@slack/client/dist/IncomingWebhook.js:26:26)
```

**Comment by aoberoi** [comment]
thanks for reporting! this is indeed an issue. let me know if you'd like to submit a PR. if not, i'd like to get this fixed within the next day.
