### ISSUE TITLE
WebClient constructor should allow no token

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#482]
### Description

In the cases of using the object to call methods like `oauth.access`, we shouldn't require a token.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by bilby91** [comment]
Any ETA for a new release ?

**Comment by aoberoi** [comment]
today!

**Comment by bilby91** [comment]
🎉
