### ISSUE TITLE
IncomingWebhook.send throws due to undefined payload object

### ISSUE THREAD

**Issue by SpencerKaiser** [slackapi/node-slack-sdk#488]
### Description
`IncomingWebhook.send` appears to be broken in `v4.0.0`

### What type of issue is this?
- [x] bug

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: `v4.0.0`

node version: `v9.1.0`

OS version(s): `macOS 10.13.3`

#### Steps to reproduce:

1. Create a js file with the following code (directly from the README)
```
// incomingWebhookDemo.js
require('dotenv').config();
const { IncomingWebhook } = require('@slack/client');
const url = process.env.SLACK_WEBHOOK;
const webhook = new IncomingWebhook(url);

// Send simple text to the webhook channel
webhook.send('Hello there', function(err, res) {
    if (err) {
        console.log('Error:', err);
    } else {
        console.log('Message sent: ', res);
    }
});
```
2. Run the script with `node incomingWebhookDemo.js`

#### Expected result:
Text will be sent to the corresponding channel in Slack.

#### Actual result:
Error thrown:
```
payload.text = message;
             ^

TypeError: Cannot set property 'text' of undefined
    at IncomingWebhook.send (/.../@slack/client/dist/IncomingWebhook.js:26:26)
```

**Comment by clavin** [comment]
This has technically [already been reported](https://github.com/slackapi/node-slack-sdk/issues/479) and [already been fixed](https://github.com/slackapi/node-slack-sdk/commit/409ed5e94e93815dc2fe5cb8d45d3e4030084ef5#diff-62a319cb536c6129eccd04a831c16705R38). I can confirm the latest version of the code currently in the repository (not on npm) works using the configuration mentioned in this issue as I was able to get the demo code to work using node v9.1.0 on macOS 10.13.3, as per the environment in this issue.

To get the code in the docs to work, either **wait until the next release**, or (for now) supply an empty object as the second argument to the `IncomingWebhook` constructor:

```js
const web hook = new IncomingWebhook(url, {}); // Verbose second argument needed until >4.0.0
```

**Comment by SpencerKaiser** [comment]
@clavin sorry I missed that issue! Thanks for the feedback, I’ll definitely go with the empty object param until y’all publicly update. Thank you!
