### ISSUE TITLE
MemoryDataStore is not a constructor

### ISSUE THREAD

**Issue by htilly** [slackapi/node-slack-sdk#489]
### Description

After upgrade to 4.0 Im getting:
TypeError: MemoryDataStore is not a constructor

/opt/zenmusic/index.js:70
    dataStore: new MemoryDataStore(),
               ^
In the code I use:
const RtmClient = require('@slack/client').RtmClient;
const RTM_EVENTS = require('@slack/client').RTM_EVENTS;
const MemoryDataStore = require('@slack/client').MemoryDataStore;

let slack = new RtmClient(token, {
    logLevel: 'error',
    dataStore: new MemoryDataStore(),
    autoReconnect: true,
    autoMark: true
});

What am I missing?
This is the project Im trying to update:
https://github.com/htilly/zenmusic

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version:
4.0.0

node version:
v7.5.0

OS version(s):
Raspbian GNU/Linux 8 (jessie)

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
Hello there! This error is expected if you're running the same code from the v3.x series. This package has had a few big changes in v4 that we described in the [Migration Guide](https://github.com/slackapi/node-slack-sdk/wiki/Migration-Guide-for-v4). The DataStore has been removed, so if your code depends on it, there's [a more specific migration guide](https://github.com/slackapi/node-slack-sdk/wiki/DataStore-v3.x-Migration-Guide) that should also be helpful.

PS. That's a pretty cool app you got there. We might even want to use it here at the Slack office.

**Comment by htilly** [comment]
Aha, that explains a few things! Thanks for pointing that out.
Glad that you like the app. It sure bring some music discussions around the office =)

I would more than love some PLs! Maybe a pull request with some optimazation of the node/slack implementation and uplift to 4.0 ;)

BR
Tilly

**Comment by aoberoi** [comment]
Cool! I'm not sure anyone here will have to time to contribute a migration PR, but I've let the team know in case someone is interested.
