### ISSUE TITLE
client.groups.info doesn't accept channel option parameter

### ISSUE THREAD

**Issue by bilby91** [slackapi/node-slack-sdk#490]
### Description

client.groups.info doesn't seem to accept `{ channel: "XX" }` as an argument. Previously to get information about a group you would pass the channel as the first argument. With the new refactor in how arguments are used in v4, groups seem to be behaving incorrectly.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 4

node version: 8.9

OS version(s): OS X 10.13

**Comment by aoberoi** [comment]
What kind of error are you getting? Is this in a TypeScript project, and is the complaint from the compiler?

**Comment by bilby91** [comment]
I'm getting the following error that based on the interfaces is seems accurate.

```
Argument of type '{ channel: string; }' is not assignable to parameter of type 'TokenOverridable'.
  Object literal may only specify known properties, and 'channel' does not exist in type 'TokenOverridable'.
```

On the other side, `client.channels.info` accepts the `channel` option.

**Comment by aoberoi** [comment]
thanks for the details! this is the same issue as #484, so lets use that to track the fix.

**Comment by bilby91** [comment]
@aoberoi Great! So, if #484 is a generic issue, a lot of method arguments will probably be wrong right ?

**Comment by aoberoi** [comment]
@bilby91 yep! and lucky for us there's an existing PR that i quite like. so we should have a fix out pretty soon!
