### ISSUE TITLE
WebClient should accept an optional token ?

### ISSUE THREAD

**Issue by bilby91** [slackapi/node-slack-sdk#491]
### Description

When using the WebClient for calling oauth methods a token is not required. WebClient `token` argument shouldn't be optional ? 

Example: https://github.com/suttna/botbuilder-slack/blob/master/src/interactors/oauth_interactor.ts#L16

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [X] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by aoberoi** [comment]
Thanks for reporting. We're aware of the issue and are tracking it in #482. I hope to have a fix available in the next couple days.

**Comment by bilby91** [comment]
@aoberoi Awesome, let me know if I can help!
