### ISSUE TITLE
Improve Web API method argument types

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#505]
## We're looking for your help!

In TypeScript, its really helpful to get code completion hints that are smart enough to know which arguments are possible to use with which Web API method (and which type that argument value should be). It can save you time jumping between your editor and the documentation on api.slack.com.

Here's an example:

![code completion](https://user-images.githubusercontent.com/494795/37432077-6c398e94-2794-11e8-838d-7af5ac81f76a.gif)

But this only works for methods where the arguments are typed in `src/methods.ts`. If we get all the Web API methods completed, we can even offer error highlighting when you misspell an argument name or pass an additional argument that isn't actually accepted.

There's over 130 Web API methods, so it's not fun for one person to do all the work. This is a call for our community to come help get all the method's arguments typed.

If you're willing to help, pick a family of methods from the list below and comment on this ticket.

- [ ] `conversations.*`
- [ ] `dialog.*`
- [ ] `dnd.*`
- [ ] `emoji.*`
- [ ] `files.*`
- [ ] `groups.*`
- [ ] `im.*`
- [ ] `migration.*`
- [ ] `mpim.*`
- [ ] `pins.*`
- [ ] `reactions.*`
- [ ] `reminders.*`
- [ ] `rtm.*`
- [ ] `search.*`
- [ ] `stars.*`
- [ ] `team.*`
- [ ] `usergroups.*`

You'll find many method families that are already complete, which can be a guide on how we expect the definitions to look. If you're not sure, that's okay, just ask!

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by clavin** [comment]
I have a few spare hours that I *could* spend twiddling my thumbs, so I figure I can do *all* of these instead.

👏 Productivity \o/ 📈
