### ISSUE TITLE
RTMClient spec tests

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#507]
### Description

`RTMClient` has no spec tests currently. Part of the challenge is being able to mock the stateful WebSocket bits. Also, `KeepAlive` has no tests, and since its strictly an implementation detail of `RTMClient`, its worth including in this issue.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
As this is no longer our priority, let me close it.
