### ISSUE TITLE
Is there a way to listen the event when the cancel button is hit on a dialog box?

### ISSUE THREAD

**Issue by benjamin-hil** [slackapi/node-slack-sdk#524]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---
Hello,

I am using WebClient along with eventAdapter and messageAdapter.

I need to listen the event triggered when a user hit the cancel button on a dialog box for workflow purpose.

Is there a trick to do this? It doesn't seem to have an event on this cancel button.

Thank you!

**Comment by aoberoi** [comment]
Hi @benjamin-hil 👋 

Unfortunately, there's no event dispatched for the user canceling submission of a dialog at this time. We've seen this feedback and agree that this is something we should provide. Keep an eye on our [blog](https://medium.com/slack-developer-blog) and [changelog](https://api.slack.com/changelog) to find out when updates are made to the Dialogs API.
