### ISSUE TITLE
Links are not working?

### ISSUE THREAD

**Issue by kioksy** [slackapi/node-slack-sdk#526]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.1.0

node version: 9

OS version(s): os x el capitan 10.11.6

#### Steps to reproduce:

1. Have a link in your attachment such as < https://example.com|example >
2. type to your bot
3. Get response

#### Expected result:

I was expecting to get a link and not the plain text

#### Actual result:

The text was just written as above

#### Attachments:

Everything enabled (mrkdwn, mrkdwn_in with all fields, parse full, unfurl_links, unfurl media) in webclient request when posting chat.postMessage

This error occured when we updated from sdk version 3 to 4. Why isn't the links working anymore?

**Comment by aoberoi** [comment]
hey @kioksy,

i wasn't able to reproduce this issue. could you provide an example of code that shows this problem?

here is what i used:

```javascript
const { WebClient, RTMClient } = require('@slack/client');

const token = process.env.SLACK_BOT_TOKEN;

const web = new WebClient(token);
const rtm = new RTMClient(token);

rtm.on('message', (event) => {
  if (event.text === 'hello') {
    web.chat.postMessage({
      channel: event.channel,
      text: 'hello to you too!',
      attachments: [
        {
          text: 'This is powered by <https://slack.com|Slack>'
        }
      ]
    })
  }
});

rtm.start();
```

and here is what it looked like in Slack:

<img width="253" alt="screen shot 2018-04-05 at 11 14 52 pm" src="https://user-images.githubusercontent.com/494795/38405946-6d73b510-3927-11e8-9368-3b489cacbe55.png">

**Comment by kioksy** [comment]
Hi again!

It seems to be working now. It seems that the key parse: 'full' was causing this for us
