### ISSUE TITLE
npm ERR! 404 Not Found: @slack/client@4.2.0

### ISSUE THREAD

**Issue by alcmontejo** [slackapi/node-slack-sdk#546]
### Description

Thrown logs below upon install.

17 http fetch GET 404 https://registry.npmjs.org/@slack%2fclient 760ms
18 silly fetchPackageMetaData error for @slack/client@4.2.0 404 Not Found: @slack/client@4.2.0
19 http fetch GET 404 https://registry.npmjs.org/@slack%2fclient 309ms
20 silly fetchPackageMetaData error for @slack/client@4.2.0 404 Not Found: @slack/client@4.2.0

Describe your issue here.

Unable to install slack client.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.2.0

node version: v8.7.0

OS version(s): MacOS 10.13.3

#### Steps to reproduce:

1. issue command in the terminal
`npm install  @slack/client`

#### Actual result:
Exception thrown below 
`
npm ERR! code E404
npm ERR! 404 Not Found: @slack/client@latest
`
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by alcmontejo** [comment]
Hello, Just found workaround. Please withdraw found this thread -> https://github.com/npm/npm/issues/5239

**Comment by aoberoi** [comment]
@alcmontejo: thanks for updating us! So was the fix just to upgrade from an old `npm`? Or, was it something related to the escaped `/`?

**Comment by alcmontejo** [comment]
@aoberoi for workaround, I created .npmrc config file define our company artifactory registry. And yes it sort of related to escaped /

- thanks.
