### ISSUE TITLE
RTMClient handle transition for explicit disconnect from connecting

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#576]
### Description

As alluded to in [the linked comment](https://github.com/slackapi/node-slack-sdk/issues/550#issuecomment-394445291), it seems that a call to `rtm.start(); rtm.disconnect();` without waiting for the connected state in between results in a crash.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by bmajz** [comment]
Is there a guard we can place around our disconnect calls to prevent this from happening?

**Comment by aoberoi** [comment]
@bmajz that's a good question. the only state that can handle an explicitly disconnect is `connected`, so the following should work in place of `rtm.disconnect()`:

```javascript
if (rtm.connected) {
  rtm.disconnect();
} else {
  // if it eventually succeeds, immediately disconnect
  rtm.once('ready', () => rtm.disconnect());
  // if it eventually fails, don't try to reconnect
  rtm.autoReconnect = false;
}
```

i haven't tested this, but logically, as long as this is exception is only being thrown while in the `connecting` state in your code, this should work.
