### ISSUE TITLE
Add note that logLevel: 'debug' should not be used in production

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#577]
### Description

The debug log level is useful for diagnosing issues, but it also logs the content of messages in the RTMClient. There should probably be a mention [here](https://slackapi.github.io/node-slack-sdk/rtm_api#customizing-the-logger) about how its a bad idea to do enable this log level in production for privacy reasons.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by jd0920** [comment]
Sorry about that, accidentally created a pr in my own fork. :stuck_out_tongue:
