### ISSUE TITLE
Adjust Slack app settings programatically 

### ISSUE THREAD

**Issue by keksipurkki** [slackapi/node-slack-sdk#580]
### Description

I am wondering if you are planning to expand the `apps` path (e.g. `apps.permissions`) to include methods that would allow me to create new Slack app features programatically (i.e. not manually through the Slack API Admin)?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by aoberoi** [comment]
hey @keksipurkki, thanks for your feedback. this is a request we've heard from a good number of developers, so you're in good company. there's a few issues around programmatically provisioning app features that we haven't solved yet. we don't have any new features to address this issue to share with you now. if and when we do, it would not necessarily be communicated through this repository. the best way to follow along would be to subscribe to our [roadmap](https://trello.com/b/ZnTQyumQ/slack-platform-roadmap-for-developers) and [changelog](https://api.slack.com/changelog). please continue to give us your valuable feedback!
