### ISSUE TITLE
Access response on rtm.start

### ISSUE THREAD

**Issue by arjun27** [slackapi/node-slack-sdk#585]
### Description

I'm not able to access the response on the rtm.start method on `RTMClient`. See API docs for [rtm.start](https://api.slack.com/methods/rtm.start).

I believe this is because the `start` method returns void. Any plans of changing that to read the response?

https://github.com/slackapi/node-slack-sdk/blob/426c8f81f248894ddecb551f43f4047734c44267/src/RTMClient.ts#L359

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.3.1
node version: 9.11.1
OS version(s): mac OS 10.12.3

**Comment by clavin** [comment]
You can retrieve the result of `rtm.start` (or `rtm.connect`) from the [`authenticated`](https://slackapi.github.io/node-slack-sdk/rtm_api#lifecycle-events) event [(source)](https://github.com/slackapi/node-slack-sdk/blob/426c8f81f248894ddecb551f43f4047734c44267/src/RTMClient.ts#L143)

```ts
const rtm = new RTMClient(token);

rtm.once('authenticated', result => {
  // do stuff with result of `rtm.start` method
});
rtm.start();
```

> Beware that `authenticated` will be called every time the client reconnects, hence the use of `once`.

**Comment by arjun27** [comment]
Thanks @clavin, that works for me. This returns the response of `rtm.connect` [1], and not `rtm.start` [2] - perhaps that is something to clarify in the documentation. Closing this one for now in lieu of #198 

[1] https://api.slack.com/methods/rtm.connect
[2] https://api.slack.com/methods/rtm.start

**Comment by arjun27** [comment]
Actually I take that back. It is possible to use `rtm.start` by passing `useRtmConnect` as true in the constructor.

```
const rtm = new RTMClient(..., { useRtmConnect: false });
```
