### ISSUE TITLE
Undefined token gives unrelated error message during files.upload

### ISSUE THREAD

**Issue by iamtmrobinson** [slackapi/node-slack-sdk#587]
### Description

When running the `files.upload` API method after the WebClient has been initialised with an undefined token I get an error message and stack trace that are seemingly unrelated to the actual issue (see below for full error).

Because the token is undefined, the first element in the array of arrays (`WebClient.js:419`) is an empty array and therefore the `append` function in `form_data` fails.

It would be ideal to have an explicit error message for when the calling code has not provided a token string and one is required.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.3.1

node version: 8.9.4

OS version(s): Mac OSX

#### Steps to reproduce:

1. Initialise a WebClient with an undefined token
2. Make an otherwise valid call to files.upload

i.e.
```
const { WebClient } = require('@slack/client');

const client = new WebClient(undefined);

return client.files
    .upload({
      file: fs.createReadStream(imageLocation),
      channels: "CHANNEL_ID"
    });
```

#### Expected result:

An API response similar to that when an invalid or empty token is provided i.e.
```
{ ok: false,
     error: 'not_authed',
     acceptedScopes: [ 'files:write:user' ] } }
```

#### Actual result:

```
TypeError: Cannot read property 'name' of undefined 
  at FormData._getContentDisposition (/app/node_modules/form-data/lib/form_data.js:226:40) 
  at FormData._multiPartHeader (/app/node_modules/form-data/lib/form_data.js:177:33) 
  at FormData.append (/app/node_modules/form-data/lib/form_data.js:70:21) 
  at flattened.reduce (/app/node_modules/@slack/client/dist/WebClient.js:459:26) 
  at Array.reduce (<anonymous>) 
  at WebClient.serializeApiCallOptions (/app/node_modules/@slack/client/dist/WebClient.js:438:30) 
  at WebClient.<anonymous> (/app/node_modules/@slack/client/dist/WebClient.js:342:38) 
  at Generator.next (<anonymous>) 
  at /app/node_modules/@slack/client/dist/WebClient.js:7:71
  at new Promise (<anonymous>)
```

**Comment by aoberoi** [comment]
@iamtmrobinson thanks for reporting and especially for leaving the important clues about how this occurred (`.append()`). i've got a fix i'm working on and i should be able to have it out shortly.
