### ISSUE TITLE
One RTMClient per bot_access_token?

### ISSUE THREAD

**Issue by Ahlid** [slackapi/node-slack-sdk#598]
### Description

Do I have to create an `const rtm = new RTMClient(token);` for every bot_access_token(xoxb) I receive when someone adds my App to an workspace?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by aoberoi** [comment]
@Ahlid Yes, that is correct.

In my experience, for apps connecting to more than one workspace, its been a worthwhile transition to move away from the RTM API and start to use the Events API in combination with the Web API. The benefit is that you won't have to maintain those connections, the events from all workspaces (all bot tokens) will arrive as HTTP requests to your Request URL.

**Comment by aoberoi** [comment]
Closing since the initial question was pretty straight forward to answer, but if you have any more questions, feel free to ask!
