### ISSUE TITLE
Working on behalf of users in workspace apps

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#608]
### Description

Slack's workspace apps [now support invoking methods on behalf of a specified user](https://api.slack.com/docs/working-for-users).

The `WebClient` class needs to implement support for this new style of calling methods. The following is a proposal for changes to the API for that purpose.

1. Define a new `ActorEnabled` interface which defines an optional property `actor?: string`.
2. Intersect all method argument types for methods that support this feature with `ActorEnabled`.
3. In the implementation of `WebClient#apiCall()`, detect the presence of an `options.actor` property, and when present use the value in request header `X-Slack-User`.

### Open questions:

*  Can we think of a better name than `actor`? One constraint is that we don't want to use a name that might otherwise be used, or used in the future, as a method argument name. It also should communicate that the app is acting on behalf of this user. `actor` is mostly okay, but it isn't perfect because truly the app is the actor, and its acting **as** the user. So perhaps `actingAs`?

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
thanks for the feedback @jd0920 

I've got an implementation in #609 that uses `actor`. I'll hold out on merging to leave time for additional feedback for regarding the name.

**Comment by shanedewael** [comment]
Though it's a little bit of a longer name, maybe `impersonate` could be an alternative? I think it more clearly connotes what is taking place inside of the app.

**Comment by Roach** [comment]
I vote for `on_behalf_of` 😎

**Comment by aoberoi** [comment]
I think `impersonate` isn't going to work for us. It has a potentially negative connotation, and its often in reference to how apps can masquerade as a user when calling `chat.postMessage`. notably, `chat.postMessage` is not one of the methods that supports this feature. I don't think @shanedewael is as strongly in favor of this choice anymore either.

at this point, i'm also leaning towards `on_behalf_of` because it would be most closely aligned to the terminology in the api.slack.com documentation.

i know this is a short timeline, but i'd like to get this feature (and many more sitting on `master`) released today. so i'll wait a few more hours before moving forward.
