### ISSUE TITLE
RTM State Machine never emits `failure` event

### ISSUE THREAD

**Issue by clavin** [slackapi/node-slack-sdk#610]
### Description

Due to some [fuzzy Finity logic](https://github.com/slackapi/node-slack-sdk/blob/842c7a78ebcfc230b341f81719181f80f5817926/src/RTMClient.ts#L134), the `failure` event is never emitted within the RTM state machine when failing to reconnect.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: `v4.3.1`

node version: `v10.7.0`

OS version(s): macOS 10.14 Beta

#### Steps to reproduce:

```js
const { RTMClient, LogLevel } = require('@slack/client');
const rtm = new RTMClient('fake token', {
  logLevel: LogLevel.DEBUG
});

rtm.connect();
// !!! debug logs never show a transition to "disconnected"
```

#### Expected result:

The RTM client should transition to the `disconnected` state on failure to connect.

#### Actual result:

The `failure` event is never emitted from the submachine to the parent state machine, and thus the state never reaches `disconnected`

#### Attachments:

["Failure is not an option" -Gene Kranz](https://www.museumofflightstore.org/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/S/T/STAT206247.jpg)

**Comment by aoberoi** [comment]
Thanks. I was able to reproduce this one (I don't see the `transitioning...` log statement as we would expect).
