### ISSUE TITLE
Methods with no options do not call callback

### ISSUE THREAD

**Issue by gabegorelick** [slackapi/node-slack-sdk#618]
### Description

https://slackapi.github.io/node-slack-sdk/web_api#using-a-callback-instead-of-a-promise lists the following example:

```js
web.channels.list((err, res) => {
  if (err) {
    return console.error(err);
  }

  // `res` contains information about the channels
  res.channels.forEach(c => console.log(c.name));
});
```

While, `web.channels.list({}, callback)` does work, when omitting the options parameter the callback will not be called due to https://github.com/slackapi/node-slack-sdk/blob/b207d885cae73aef97301de8b1b65f7b1195ffb7/src/WebClient.ts#L302-L307

When compiled to JS, `apiCall` has a signature of `function (method, options, callback) {}`. If `options` is not passed, `callback` will be undefined and a promise will be returned instead. 

A potential solution would be to check `typeof options === 'function'` to see if `options` is actually the callback.

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 4.4.0, also verified in 4.0.0

node version: 8.11.4

OS version(s): macOS High Sierra

#### Steps to reproduce:

1. Run example in https://slackapi.github.io/node-slack-sdk/web_api#using-a-callback-instead-of-a-promise

#### Expected result:

Channels should be logged

#### Actual result:

No channels logged due to callback not being called.

**Comment by aoberoi** [comment]
ah, you're right! i overlooked the fact that methods with no arguments still require that parameter when writing the example in the documentation.

the intention of the API is to still require the options parameter as seen in the overload signature below:

https://github.com/slackapi/node-slack-sdk/blob/master/src/WebClient.ts#L133

so i'd describe this as a documentation issue. if you'd like us to consider making `options` optional, then let's open a separate feature request issue for that.
