### ISSUE TITLE
Help do retrive message

### ISSUE THREAD

**Issue by ran-j** [slackapi/node-slack-sdk#627]
### Description

How in WebClient I responde a input from user to bot?

Like one event listener to income personal message.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by aoberoi** [comment]
Hello @ran-j 👋 

To receive incoming events, you have two options: the Events API and the RTM API. **The recommended approach is to use the Events API, and for that there's another package here: https://github.com/slackapi/node-slack-events-api**. If you chose the RTM API, you can use the `RTMClient` class from this package, see those docs here: https://slackapi.github.io/node-slack-sdk/rtm_api#receiving-messages. 

If you need help deciding or understanding the differences, take a look [at this helpful blog post](https://medium.com/slack-developer-blog/getting-started-with-slacks-apis-f930c73fc889).

**Comment by ran-j** [comment]
Hello @aoberoi thanks for help.

So I traing to use RTM, the demo code, but when I trai this:

```
// Log all incoming messages
rtm.on('message', (event) => { 
  rtm.sendMessage('hi',event.user)
  console.log(`Message from ${event.user}: ${event.text}`);
})
```

I got this error 

```
Message from UAQ8WKYV8: oi
(node:4980) UnhandledPromiseRejectionWarning: Error: An API error occurred: invalid channel id
    at RTMClient.eventHandler (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\@slack\client\dist\RTMClient.js:334:66)
    at RTMClient.emit (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\eventemitter3\index.js:182:35)
    at RTMClient.onWebsocketMessage (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\@slack\client\dist\RTMClient.js:474:14)
    at WebSocket.onMessage (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\ws\lib\websocket.js:720:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (C:\Users\Ranieri\Documents\Projetos\Node Js\slackbotnode\node_modules\ws\lib\receiver.js:414:14)
(node:4980) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4980) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by aoberoi** [comment]
Okay, no problem. I can help you understand why you're seeing this error.

First, the error is saying `invalid channel id`. When you called the `rtm.sendMessage()` function, the second parameter is supposed to be a conversation (channel) ID, and you are passing, `event.user`, a user ID. This will not work. You have two options: you can send a message back in the same conversation where the incoming message event happened, or you can create a new DM with the user based on the user ID to get a conversation ID. The first option is easier, and you can do that by replacing `event.user` with `event.channel`. The second option would require using the `WebClient` to call the `im.open` method, and in the result you'll find the conversation ID. It's up to you.

Second, calling `rtm.sendMessage()` returns a Promise. You should never allow a Promise to get created without some kind of error handler. The simplest way to do this is to add a catch: `rtm.sendMessage('hi', event.channel).catch(console.error)`. This will log any error that occurs back to the console.

**Comment by ran-j** [comment]
Yes, worked, thanks :)
