### ISSUE TITLE
`npm install` now gets v3.16.1-sec.2 instead of v4.6.0

### ISSUE THREAD

**Issue by nicgordon** [slackapi/node-slack-sdk#638]
### Description

Since the last security release running `npm install @slack/client` to install this library actually installs v3.16.1-sec.2 instead of v4.6.0.

Unfortunately I'm not familiar enough with the process of creating releases for npm to be much use in the solution here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug - sort of?
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: N/A

node version: 8.11.3 (npm 6.4.1)

OS version(s): MacOS 10.13.6

#### Steps to reproduce:

1. Run `npm install @slack/client` on a new project

#### Expected result:

4.6.0 to be installed

#### Actual result:

v3.16.1-sec.2

**Comment by aoberoi** [comment]
Hi @nicgordon, I'm having trouble reproducing this issue. There was a short period of time where we accidentally left the `v3.x` released tagged as `latest`, but we resolved that fairly quickly. I just tried to create a new project and I got `v4.6.0`.

```
ankur:play/ $ mkdir blaah                                            [12:08:38]
ankur:play/ $ cd blaah                                               [12:08:41]
ankur:blaah/ $ npm install @slack/client                             [12:08:47]
npm WARN saveError ENOENT: no such file or directory, open '/Users/ankur/Developer/play/blaah/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/ankur/Developer/play/blaah/package.json'
npm WARN blaah No description
npm WARN blaah No repository field.
npm WARN blaah No README data
npm WARN blaah No license field.

+ @slack/client@4.6.0
added 46 packages from 75 contributors and audited 91 packages in 2.654s
found 0 vulnerabilities
```

what version of npm do you have? can you try deleting the `node_modules` directory in your project and try again?

**Comment by nicgordon** [comment]
Thanks for the response @aoberoi. I can confirm that this issue is no longer needed as running `npm install @slack/client@latest` installed v4.8.0.
