### ISSUE TITLE
Proxy usage is broken since v4.5.0 (switch to axios)

### ISSUE THREAD

**Issue by jbsil** [slackapi/node-slack-sdk#642]
### Description

I am unable to get WebClient to connect using any proxy on versions 4.5.0 or 4.6.0. Proxies work correctly on v4.4.0. I believe this is due to the change from `got` to `axios` https://github.com/slackapi/node-slack-sdk/pull/620
Also, since RTMClient internally uses a WebClient (for initial authentication?), that also does not work. This is reliably reproducible with multiple proxies.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.5.0, 4.6.0

node version: 6.11.4

OS version(s): docker hub's node 6-alpine image

#### Steps to reproduce:

1. Set up an `https-proxy-agent`
2. Use `{agent: proxyAgent}` when creating an RTMClient
3. list to `.on('hello')` and `.start()` the client

#### Expected result:

Receive a `hello` event from Slack

#### Actual result:

```
[DEBUG] @slack/client:WebClient0 will perform http request
[DEBUG] @slack/client:WebClient0 http request failed
[DEBUG] @slack/client:WebClient0 will perform http request
[DEBUG] @slack/client:WebClient0 http request failed
[DEBUG] @slack/client:WebClient0 will perform http request
[DEBUG] @slack/client:WebClient0 http request failed
```

**Comment by aoberoi** [comment]
I just heard from another user experiencing this issue. they were able to workaround without downgrading by setting the `agent` option to an object with key(s) `http` and/or `https`.

for example, change `{agent: proxyAgent}` to `{agent: { http: proxyAgent, https: proxyAgent } }`.

**Comment by aoberoi** [comment]
@DornieDortsch i'm not able to reproduce this one, but let me describe what i'm doing and maybe you can help me see where your set up is different.

i'm using [Charles Proxy](https://www.charlesproxy.com/) on my mac, which is using the default proxy configuration (post 8888). i clone your repo, and created a new `.env` file. i put the following contents in that file:

```
TOKEN=xoxb-REDACTED
PROXY_URL=http://localhost:8888
```

then i did an `npm install` and started the application with `node index.js`. everything worked.

next, i downgraded to `@slack/client@4.4.0` by updating the entry in `package.json`, wiped out the `package-lock.json` and the `node_modules` directory, did another `npm install` and ran once again using `node index.js`. everything worked again.

one random thought: if your proxy has its own self-signed certificate, you might need to use the `tls` options in the SDK to get the code talking to that proxy properly. however, that shouldn't have changed between v4.4.0 and v4.8.0.

**Comment by DornieDortsch** [comment]
@aoberoi the steps you take to reproduce the error are correct.

I think it's a special problem with my proxy setup. We have to use http proxy for http and https requests. Looks like axios didn't play well with this setup.

I added print to get the error message at WebClient `makeRequest` function. Here is the message:
```
http request failed Error: An HTTP protocol error occurred: statusCode = 403
```

I take som time to get the right axios setup.

**Comment by aoberoi** [comment]
@DornieDortsch yay! thanks for digging deeper and sharing your findings back with the rest of us. this is super helpful and it makes sense.

i'm going to make another issue to discuss your suggestion of disabling the automatic proxy detection using the environment variable.

in terms of logging, i'm not sure if its wise to output that level of detail, but i can be convinced. in theory, the promise would be rejected with an error that contains that detail, so you should be able to log it yourself. i think the only reason that wasn't apparent here is because automatic retries were going to occur for the next ~30 minutes before you saw the final rejected error, but this is the expected behavior. i think a good debugging step should have been to turn retries off to see what the underlying error was, but neither of us thought of that. 🤔
