### ISSUE TITLE
Remove mentions of es2018.asynciterable from TypeScript docs

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#649]
### Description

#644 merged a docs change that mentioned for typescript 3.1 or later, you should use `"es2018.asynciterable"` in the `lib` configuration. that change was scheduled for typescript 3.1, but was later moved to 3.2, so this information is no longer accurate. we should remove that section until the change lands.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by melisdogan** [comment]
I'll do this.
