### ISSUE TITLE
Add ability to upload file to threads

### ISSUE THREAD

**Issue by tcd156** [slackapi/node-slack-sdk#659]
### Description

Slack documentation for [files.upload](https://api.slack.com/methods/files.upload) states that you can supply `thread_ts` to upload a file to a thread. Currently, this value is not exposed in the SDK.

I attemped to fork the repo and expose the `thread_ts` but failed to get it working. Ex:
```
export type FilesUploadArguments = TokenOverridable & {
  channels?: string; // comma-separated list of channels
  content?: string; // if absent, must provide `file`
  file?: Buffer | Stream; // if absent, must provide `content`
  filename?: string;
  filetype?: string;
  initial_comment?: string;
  title?: string;
  thread_ts?: string;
};
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.8.0

node version: 10.6.0

OS version(s): macOS Mojave 10.14

#### Steps to reproduce:

1. Add `thread_ts` to options when calling `files.upload`. Ex:
```
const opts = {
    filetype: ...,
    filename: ...,
    initial_comment: ...,
    thread_ts: ...
}
```

#### Expected result:

Files should be uploaded to a thread of the parent message.

#### Actual result:

Nothing happens - the call to the API succeeds, but the file is not posted to the thread.

**Comment by tcd156** [comment]
Uploading a file to a thread works - I had to specify the `channels` as well as the `thread_ts` in order to get it to work. I was only specifying the `thread_ts` previously.

In the documentation, this is not instantly obvious, as they are all considered Optional, and nowhere does it state you need both values.

**Comment by aoberoi** [comment]
@tcd156 thanks for pointing out the lack of info in the documentation. I’d still be open a PR for the `thread_ts` being added to the arguments type definition. It would be nice to leave a comment next to it indicating that the `channels` argument is required when using it, as you stated here.

**Comment by tcd156** [comment]
Great, opened #661
