### ISSUE TITLE
RTM connection losing presence status -- still connected

### ISSUE THREAD

**Issue by jayjanssen** [slackapi/node-slack-sdk#673]
### Description

I have a bot connecting to Slack via the rtm `start` method.  The bot connects normally and works fine, but after some time the bot's online status (green dot) goes empty and makes the bot look offline.  However, as far as I can tell, the bot is working perfectly fine and is receiving RTM message events as usual.  

I'm aware I can set my app to show the bot's presence as always connected, but I like to use that status as a quick indicator that my bot is offline.  Upon restarting my bot, I've found sometimes I have to restart my slack client too to get the bot's status refreshed, so there may be more going on here beyond just this SDK.  

Unfortunately, this isn't something I can reproduce.  It happens intermittently.  I just want to know if there is something else I should be doing beyond the code snippet below to managed my RTM connection

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.8.0

node version: 10.13

OS version(s): Linux 446460a6df3b 4.14.72-68.55.amzn1.x86_64 #1 SMP Fri Sep 28 21:14:54 UTC 2018 x86_64 Linux

#### Steps to reproduce (kind of):

1.  Startup bot with below framework for starting RTM and getting messages
2. Wait an indeterminate amount of time (overnight?)
3. Bot's online status will be grey

#### Expected result:

Bot to happily show online as long as my bot process is running and I'm not getting RTM connection errors.

#### Actual result:

Bot appears offline, but does appear to be functioning perfectly fine.  Note, I do NOT get any log messages about disconnections, either from my code below or from the logger I pass to the RTMClient object (log level is set to info).  

#### Attachments:

```coffeescript
slack_client = require '@slack/client'
slack_rtm = new slack_client.RTMClient slack_secrets.data.token, {useRtmConnect:false, logger}

log.info "Starting RTM"
{self} = await slack_rtm.start()
log.info "RTM connected as #{self.name}"

slack_rtm.on 'message', (message) ->
   # handle messages

slack_rtm.once 'disconnecting', () ->
  log.info "RTM disconnecting, cleanup..."
  slack_rtm.removeAllListeners 'message'
  # rtm_connected = rtm_fresh_connect()
```

**Comment by aoberoi** [comment]
Ah, sorry that you're having this difficulty. Let's try to track this down. If it ends up being in the Slack client (browser/desktop), then I can also bring this issue to that team.

First thing's first: I'd set the log level to DEBUG in order to see all the intermediate states that the client is transitioning through. The next time you notice an offline presence, you can then consult the logs.

Questions: If you message the bot while it appears offline, will it become online? Will it respond in a way you expect (if you programmed it to respond)?

**Comment by jayjanssen** [comment]
@aoberoi just a quick update on this -- there is one possibility that may be in play -- I am now running multiple bots connected to the same RTM for HA purposes.  (before they react to a message, the bots essentially do a NX set in a common redis instance on the <channel>_<ts> of the message -- the winner who can set that handles the message).

What I'm wondering is how well supported simultaneous connections are here or not.  Just an idea.  I've seen one instance of the offline status on my testing bot and it was when I was running a few instances including one locally on my laptop that would have been connecting/disconnecting.  FTR there was nothing interesting in the debug log on the remaining instance when that happened.

Apart from that, I'll wait until I see it again and report in here with more data.

**Comment by jayjanssen** [comment]
I didn't have any repeat of the issue over the holidays.  I'll close this now and re-open/submit new if needed.
