### ISSUE TITLE
Message sent but no server acknowledgement was recieved

### ISSUE THREAD

**Issue by CoreyCole** [slackapi/node-slack-sdk#680]
### Description
I'm getting this error message when sending messages using `rtm.sendMessage()` and I'm having trouble finding out why:
```
Error: Message sent but no server acknowledgement was recieved. This may be caused by the client changing connection state rather than any issue with the specific message. Check before resending.
```
I'm able to read messages sent in slack channels through the node api just fine, but I'm unable to send messages. It looks like the error message is in the code [here](https://github.com/slackapi/node-slack-sdk/blob/fc6371cea6ef882a05dcd7beaeea0f64f9c649bf/src/RTMClient.ts#L491). The message never arrives in the slack channel I'm sending to.

### What type of issue is this?
- [x] question

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

`@slack/client` version: 4.8.0

node version: 8.12.0

OS version(s): OSX 10.13.6

#### Steps to reproduce:

1. Connect RTM web socket client
2. call `sendMessage()` function

#### Expected result:

A message is sent to slack

#### Actual result:

No message is sent and I'm given the error message.

**Comment by aoberoi** [comment]
@CoreyCole could you enable debug logging in your code to see if the client recently transitioned to `disconnected` or some other unexpected state before this error occurs?

you only need to set the `logLevel` option to `LogLevel.DEBUG`. there's an example here: https://slackapi.github.io/node-slack-sdk/rtm_api#customizing-the-logger (don't worry about the `logger` option/function).

**Comment by CoreyCole** [comment]
So it all looks normal in the debug logs, pings and pongs, until I try sending a message. After sending a message, it looks like it does disconnect:
```
[DEBUG] @slack/client:KeepAlive1 stop monitoring
[DEBUG] @slack/client:RTMClient2 transitioning to state: reconnecting
[SlackService][constructor]: reconnecting to slack API...
[DEBUG] @slack/client:KeepAlive1 stop monitoring
[DEBUG] @slack/client:RTMClient2 transitioning to state: connecting
[SlackService][constructor]: connecting to slack API...
[DEBUG] @slack/client:RTMClient2 transitioning to state: connecting:authenticating
[DEBUG] @slack/client:WebClient0 apiCall() start
[DEBUG] @slack/client:WebClient0 shouldAutoPaginate: false
[DEBUG] @slack/client:WebClient0 will perform http request
[DEBUG] @slack/client:WebClient0 http response received
[DEBUG] @slack/client:RTMClient2 transitioning to state: connecting:authenticated
[DEBUG] @slack/client:RTMClient2 transitioning to state: connecting:handshaking
[DEBUG] @slack/client:RTMClient2 received message on websocket: {"type": "hello"}
[DEBUG] @slack/client:RTMClient2 transitioning to state: connected
[DEBUG] @slack/client:RTMClient2 transitioning to state: connected:resuming
[DEBUG] @slack/client:RTMClient2 transitioning to state: connected:ready
[DEBUG] @slack/client:KeepAlive1 start monitoring
[DEBUG] @slack/client:KeepAlive1 setting ping timer
```

**Comment by CoreyCole** [comment]
! Just tested something and it looks like the content of the message is causing the error. I replaced my long message string with `"test"` and it sent it.

**Comment by CoreyCole** [comment]
This is the content of the message that was causing the error. It was JSON.stringify(obj, null, 2) of the following object:
```json
{
  deviceEventId: '58',
  deviceId: 'n/a',
  creationDate: 2019-01-17T21:09:15.931Z,
  event: 'ERROR',
  userId: 'n/a',
  userName: 'n/a',
  client: 'google',
  type: 'Error',
  message: 'test error',
  metadata:
   { conv:
      { id: 'ABwppHFIge30FG7aJhhj2a-ZQjT5h5r-cJF9yT-fWCvC7xHOJr_n7mK2Nywi0PmTAeI7PWXmm_0',
        body: [Object],
        data: {},
        type: 'NEW',
        user: [Object],
        _init: {},
        input: [Object],
        query: 'GOOGLE_ASSISTANT_WELCOME',
        action: 'input.welcome',
        device: {},
        intent: 'LaunchIntent',
        screen: true,
        headers: {},
        request: [Object],
        sandbox: true,
        surface: [Object],
        version: 2,
        contexts: [Object],
        digested: false,
        incoming: [Object],
        noInputs: [],
        arguments: [Object],
        available: [Object],
        responses: [],
        _responded: false,
        parameters: {},
        speechBiasing: [],
        expectUserResponse: true },
     stack:
      [ 'Error: test error',
        '    at MapSubscriber.conv$.sessionService.get.pipe.operators_1.map [as project] (/Users/corey/Halloo/src/clients/google/src/dialogflow-intents/launch.intent.ts:42:31)',
        '    at MapSubscriber._next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/operators/map.ts:81:29)',
        '    at MapSubscriber.Subscriber.next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/Subscriber.ts:101:12)',
        '    at TapSubscriber._next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/operators/tap.ts:116:22)',
        '    at TapSubscriber.Subscriber.next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/Subscriber.ts:101:12)',
        '    at MapSubscriber._next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/operators/map.ts:86:22)',
        '    at MapSubscriber.Subscriber.next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/Subscriber.ts:101:12)',
        '    at CatchSubscriber.Subscriber._next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/Subscriber.ts:141:22)',
        '    at CatchSubscriber.Subscriber.next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/Subscriber.ts:101:12)',
        '    at MapSubscriber._next (/Users/corey/Halloo/src/clients/google/node_modules/rxjs/src/internal/operators/map.ts:86:22)' ],
     requestData:
      { conv: [Object],
        client: 'google',
        reqDate: '2019-01-17T21:09:15.918Z',
        reqSession: {} },
     creationDate: '2019-01-17T21:09:15.924Z' } }
```

**Comment by CoreyCole** [comment]
Yeah, it looks like it had to do with message length. I deleted off some of the larger sub-objects before calling JSON.stringify() and the message sent to slack. Maybe a new issue should be opened about a better error message for this?

**Comment by aoberoi** [comment]
Glad you figured this out!

Just a bit of advice, if you're going to be posting messages with structured content like that, I think using attachments would be really helpful. It would make it so that the content is collapsible in Slack (a "Show More" link appears at the bottom). You can do this with the `WebClient`.

If preserving the monospace code block would also be nice, you can use [`files.upload`](https://api.slack.com/methods/files.upload) using the `content` argument. Slack can detect that this is JSON content and make it look nice and pretty.

I'm opening a separate issue, because I think its a bug that posting content that is too long can cause the RTM client to disconnect. Thanks for spotting this!
