### ISSUE TITLE
Sending large message causes misleading error message

### ISSUE THREAD

**Issue by CoreyCole** [slackapi/node-slack-sdk#681]
### Description
I opened #680 because I was getting a weird error message and I couldn't figure out why. I was sending a message to one of my slack channels with a large stringified JSON object. When I tried to send it, no message arrived in the slack channel, and my node server got the error from the `rtm.sendMessage()` promise rejection:
```
Error: Message sent but no server acknowledgement was recieved. This may be caused by the client changing connection state rather than any issue with the specific message. Check before resending.
```
After some debugging, I found out the message wasn't sent because the stringified JSON object was too large. Once I deleted off some of the larger sub-objects, the message sent. I'm wondering if we could get a better error message when this is happening.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] enhancement (feature request)

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.8.0

node version: 8.12.0

OS version(s): 10.13.6

#### Steps to reproduce:

1. create a large JSON object
2. `rtm.sendMessage(JSON.stringify(obj, null, 2))`
3. see above error message and no message sent to the slack channel

#### Expected result:

An error message stating the provided message to `rtm.sendMessage()` is too large to be sent.

#### Actual result:

An error message implying a disconnection from the server.

**Comment by aoberoi** [comment]
Wow, you already made the issue I was thinking of making. Thanks so much!

**Comment by misscoded** [comment]
This issue needs to be reverified to decide if it's still relevant in the current version.
