### ISSUE TITLE
Mention bot channel membership as a requirement for posting messages with bot tokens

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#682]
### Description

Throughout the documentation, its important to note that bot user membership is necessary to post a message (or do other actions) when using a bot token (or `bot` scope).

This might have prevented issues like #679.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
Here is one place this needs to be mentioned: https://slackapi.github.io/node-slack-sdk/web_api#posting-a-message

**Comment by misscoded** [comment]
This issue is likely invalid now because bots can post to public channels, assuming they have the right scope permissions: https://api.slack.com/scopes/chat:write.public

If anyone thinks this issue should be reopened, please feel free to comment!
