### ISSUE TITLE
Navigation (hamburger button) non-responsive on touch devices

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#707]
### Description

I tried to browse the documentation on an iPhone in Safari. I clicked on the hamburger icon and nothing happened. 

Cc @shanedewael 

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by sean-brydon** [comment]
Hey could this be assigned to me - I want to take a look
