### ISSUE TITLE
Set limits on cursor pagination

### ISSUE THREAD

**Issue by Lemmmy** [slackapi/node-slack-sdk#709]
### Description

I'd like to set a limit on an automatically paginated request. For example, I'd like to receive all conversation history up to a specific `ts`. I tried to do this with `web.conversations.history({ oldest: ts })`, but I received a spam of this warning:

```
[WARN] @slack/client:WebClient3 Method supports cursor-based pagination and a different technique is used in options. Always prefer cursor-based pagination when available
[WARN] @slack/client:WebClient3 Method supports cursor-based pagination and a different technique is used in options. Always prefer cursor-based pagination when available
[WARN] @slack/client:WebClient3 Method supports cursor-based pagination and a different technique is used in options. Always prefer cursor-based pagination when available
[WARN] @slack/client:WebClient3 Method supports cursor-based pagination and a different technique is used in options. Always prefer cursor-based pagination when available
[WARN] @slack/client:WebClient3 Method supports cursor-based pagination and a different technique is used in options. Always prefer cursor-based pagination when available
```

Looking further into it, it seems that the `oldest` parameter is part of the classic pagination API, and the preferred method is to use the cursor API. However, it does not seem like the cursor API supports anything similar to the `oldest` parameter natively. So, it seems like node-slack-sdk is just going to paginate as many requests as it likes, possibly hitting the rate limits. Is there any way to stop `node-slack-sdk` from paginating fully when a specified limit is reached? Is there something I've missed?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by Lemmmy** [comment]
For what it's worth, I managed to get the desired result with `_.takeWhile(history.messages, m => m.ts !== oldest.ts)`, however this still fetches as many pages as it can, so it's still running more API requests than ultimately necessary.

**Comment by aoberoi** [comment]
@Lemmmy would the feature described in https://github.com/slackapi/node-slack-sdk/issues/701 help? any feedback you have for that would be gladly accepted.

**Comment by Lemmmy** [comment]
Yes, that seems to be what I'm looking for. I'll direct feedback there, thanks!

**Comment by aoberoi** [comment]
No prob! Closing as duplicate to keep things tidy then 😄
