### ISSUE TITLE
Slack API does not linkify user ids in context 'plain_text'

### ISSUE THREAD

**Issue by janniks** [slackapi/node-slack-sdk#712]
### Description

The new blocks protocol of the Slack API does not linkify/parse `<@user.id>` into a correct link. This does currently work when sending `<@user.name>` (name instead of id). However, on Slack's side these are converted to ids again anyway and the next time these are sent out via the API (e.g. via a button click) they only are sent as `<@user.id>`. This should be fixed, as the information is lost once an interactive component tries to use linked usernames.

#### Scenario
- Dialog is triggered and sends information to a third party Slack app
- The third party wants to use linked usernames and uses `<@user.name>`, as `user.id` does not parse in text blocks (e.g. context)
- The third party send a blocks message with a button attached
- When the button is clicked Slack triggers a request to the third party
- The third party now only receives the post-parse text (containing `<@user.id>`)
- When the third party responds (e.g. with `.respond()` of the interactive SDK) Slack fails to parse the user ids

_A simple scenario recording is attached below..._

![mar-01-2019 13-13-16](https://user-images.githubusercontent.com/6362150/53637582-d7968a80-3c23-11e9-8f27-33f8b0ed5e0a.gif)

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: _Technically a Slack API backend issue on Slacks side_

~node version:~

~OS version(s):~

#### Steps to reproduce:

_see **Scenario**_

#### Expected result:

Slack should be able to parse `<@user.id>` (e.g. `<@UGEPZKTLK>`) into a link

#### Actual result:

Slack does not parse `<@user.id>` but only `<@user.name>` correctly

#### Attachments:

_see **Scenario**_

**Comment by shanedewael** [comment]
@janniks Thanks for raising this 🙇This is in fact a bug on the platform and I've reported it to the team. The bug is that _no_ user mentions should be rendering inside of a `plain_text` object (rather than both).

To render user mentions with blocks, you'll have to use the `mrkdwn` text object instead of the `plain_text` one. `mrkdwn` is supported within the context block so this should be a fairly simple fix but let me know if you run into any issues 🙂

There's some relevant documentation and examples for mentioning users with blocks [on the API site](https://api.slack.com/messaging/composing/formatting#mentioning-users).

**Comment by janniks** [comment]
Hi Shane,

I understand - that makes more sense! Thanks for the quick response 🤘🏻

Keep up the great work 🎉
