### ISSUE TITLE
Discussion: investigate using isomorphic-ws to allow updating ws to v6

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#723]
### Description

The `ws` dependency is currently one major version behind the latest (v5.x -> v6.x). There's no expectation that v5.x will continue to receive bug fixes or features. So its a risk for this project (and all apps that depend on it) to not update to the latest version.

However, the v6 release of `ws` drops support for browser environments. While this project doesn't explicitly aim to support browser environments, there are many interesting and valuable apps that we know use the project in this way, and are successful. It would be better if we didn't lose those projects as we adopted v6.

There is another project, [`isomorphic-ws`](https://github.com/heineiuo/isomorphic-ws), which is designed to compliment `ws` with browser support. When put through a bundler, the `ws` project essentially gets compiled away, and what remains is a thin polyfill for websocket support: https://github.com/heineiuo/isomorphic-ws/blob/master/browser.js

This seems to me to be a pretty great approach that would allow us not to lose some good apps while also eliminating the risk. But, how well does this work? In theory, as long as the `RTMClient` only uses web standard API for a `WebSocket` object, it should all be fine. However, there are likely small and hard to identify differences. I guess we won't know until we try.

This issue is a space to discuss anything related to this problem that we identify.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
@arjun27 I know that Team Chat for VSCode uses this package. Do you have any thoughts to add?

**Comment by arjun27** [comment]
Thanks for tagging me, @aoberoi. I'm not 100% sure if this applies to Team Chat, because the RTMClient is only used in the node extension host process. The web view (which is the browser environment) renders the UI and communicates with the node extension host process over VS Code's messaging passing. It seems to me that Team Chat will be unaffected with the upgrade to v6.x. Am I missing something?

**Comment by aoberoi** [comment]
@arjun27 nope, i just didn't know whether the extension used the node context or the browser context when creating an RTM connection. thanks for pointing that out! i agree that the extension should also remain unaffected in that case.

**Comment by eamodio** [comment]
Sounds reasonable to me. In theory it shouldn't affect us at CodeStream either, since we do all our slack communication from within a node process.

**Comment by misscoded** [comment]
It seems that browser compatibility is no longer a concern for the RTM Client. If anyone is facing an issue with this, please feel free to comment and we'll revisit.
