### ISSUE TITLE
Outdated documentation for Slack Incoming Webhooks

### ISSUE THREAD

**Issue by ehannes** [slackapi/node-slack-sdk#765]
### Description

On https://slack.dev/node-slack-sdk/webhook, the following line:
```
const IncomingWebhook = require('@slack/webhook');
```
throws `TypeError: IncomingWebhook is not a constructor`.

It should instead be one of these:
```
// old syntax
const IncomingWebhook = require('@slack/webhook').IncomingWebhook;

// or with the new syntax
const { IncomingWebhook } = require('./IncomingWebhook');
```

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] I don't know

**Comment by MorpheusZero** [comment]
Thanks for this. I have spent hours trying to figure this out....

**Comment by aoberoi** [comment]
@ehannes @MorpheusZero thanks for reporting and following on! we'll get a fix out ASAP.

**Comment by ivan-oliveira** [comment]
Now all it needs is to be updated on NPM as well.
