### ISSUE TITLE
ts compile error: Module eventemitter3 has no default export

### ISSUE THREAD

**Issue by ducbaovn** [slackapi/node-slack-sdk#769]
### Description
ts compile error: Module eventemitter3 has no default export
my tsconfig.json:
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "build",
        "allowJs": true,
        "moduleResolution": "node",
         "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.0

node version: 8.12.0

OS version(s):

**Comment by sashaaro** [comment]
Probably already fixed in https://github.com/slackapi/node-slack-sdk/pull/760 but not release yet

**Comment by aoberoi** [comment]
Yep, this is a duplicate. We're hoping to make a release today. Sorry for the delay and thanks for your patience.
