### ISSUE TITLE
Document ability to pass custom `logger` option

### ISSUE THREAD

**Issue by niftylettuce** [slackapi/node-slack-sdk#783]
The docs at <https://slack.dev/node-slack-sdk/web-api#logging> are missing information about passing a custom logger `logger` option to the instance created.

**Comment by aoberoi** [comment]
Have you tried opening the details pane under the title "Sending log output somewhere besides the console". Maybe that title is not clear enough, but there is information in that section about using a custom `logger`.

**Comment by niftylettuce** [comment]
ty
