### ISSUE TITLE
Disable signature verification for local development and testing with Steno

### ISSUE THREAD

**Issue by jdsmith575** [slackapi/node-slack-sdk#784]
### Description

Please add the ability to disable signature verification in the events-api adapter. We have two use cases for this:

1. Our dev environment is isolated from the internet we cannot route events from Slack to it. I would like to use Postman and Steno to send mocked events to my dev environment, but neither works very well. Using Postman I need to very carefully craft the event so it passes verification. Scenarios recorded by Steno seem to be good for only five minutes because of the replay prevention. It would be very helpful if I could disable the verification in this environment to make mocked events easier to write for development purposes.

2. We handle signature verification at the edge of our network. Performing the verification a second time in the events adapter is unnecessary.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Attachments:

https://gph.is/1pLMT45

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
