### ISSUE TITLE
Interactive-messages usage example doesn't work

### ISSUE THREAD

**Issue by Moglum** [slackapi/node-slack-sdk#785]
### Description

The instructions for using the interactive-messages package here https://slack.dev/node-slack-sdk/interactive-messages or here https://github.com/slackapi/node-slack-sdk/tree/master/packages/interactive-messages don't produce a working example.
Instead, it throws `TypeError: SlackMessageAdapter needs a signing secret`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 1.1.1

node version: v10.15.2

OS version(s): Win 10 Pro

#### Steps to reproduce:

1. Install `@slack/interactive-messages` package
2. Try to run the following code:
```const { createMessageAdapter } = require('@slack/interactive-messages');
const slackSigningSecret = process.env.SLACK_SIGNING_SECRET;
const slackInteractions = createMessageAdapter(slackSigningSecret);

// Read the port from the environment variables, fallback to 3000 default.
const port = process.env.PORT || 3000;

(async () => {
  // Start the built-in server
  const server = await slackInteractions.start(port);

  // Log a message when the server is ready
  console.log(`Listening for events on ${server.address().port}`);
})();
```
3. 

#### Expected result:

Have a running server

#### Actual result:

```
<path_to_my_app>\node_modules\@slack\interactive-messages\dist\adapter.js:143
      throw new TypeError('SlackMessageAdapter needs a signing secret');
```
`TypeError: SlackMessageAdapter needs a signing secret`

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by Moglum** [comment]
🤦‍♂ my bad of course - I've misspelled the name of the env variable. It does work as expected. 
I apologize.

**Comment by aoberoi** [comment]
It happens to the best of us!
