### ISSUE TITLE
@slack/events-api is failing yarn/npm audit

### ISSUE THREAD

**Issue by donhcd** [slackapi/node-slack-sdk#786]
### Description

something to do with `finalhandler`, which is used by `express`. Any way you guys can finagle the package imports or something so that developers don't hit this?

```
yarn audit v1.13.0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ low           │ Insecure Default Configuration                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ finalhandler                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @slack/events-api                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @slack/events-api > express > finalhandler                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/836                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 2.2.0

node version: 8.14.1

OS version(s):

#### Steps to reproduce:

1. run `yarn audit`
2.
3.

#### Expected result:

pass

#### Actual result:

fail

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
