### ISSUE TITLE
Using the built-in HTTP server for interactive messages and events on the same port

### ISSUE THREAD

**Issue by j0h** [slackapi/node-slack-sdk#789]
### Description

1. Is it possible to use interactive messages and events using the built-in HTTP server on the same port (e.g. sharing the existing HTTP server for both)?
2. Is it possible to use slash commands using the built-in HTTP server without the need to bring in express? All examples I've come across use express, wondering if there is a way we can hook in the slash commands to the existing HTTP server.

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:
- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:
package version:
`@slack/interactive-messages`: 1.1.1
`@slack/events-api`: 2.2.0

node version: 10.15.1

OS version(s): OS X 10.14.5

**Comment by seratch** [comment]
Sorry for our very late response here.

>Is it possible to use interactive messages and events using the built-in HTTP server on the same port (e.g. sharing the existing HTTP server for both)?

No, it isn't. These packages are supposed to listen to different ports if you run them in the same host.

>Is it possible to use slash commands using the built-in HTTP server without the need to bring in express? All examples I've come across use express, wondering if there is a way we can hook in the slash commands to the existing HTTP server.

No, unfortunately, this SDK doesn't support slash commands out-of-the-box.

To address above two easily, we recommend using the Bolt framework, which is a newer and well-maintained SDK. https://slack.dev/bolt-js/tutorial/getting-started

I know my answer may be too late but I hope this is helpful for you and other people that arrive here when searching for information.

**Comment by j0h** [comment]
Thanks for the update @seratch. I'll migrate over to using the Bolt framework as suggested.
