### ISSUE TITLE
Parsing slack message as form-urlencoded

### ISSUE THREAD

**Issue by kurumpa** [slackapi/node-slack-sdk#790]
### Description 
Hello. I might be doing something wrong, but i can't get events-api working because here https://github.com/slackapi/node-slack-sdk/blob/8d3b2fdef099306732b344c7e030dd09c82dd91b/packages/events-api/src/http-handler.js#L187 request body is supposed to be JSON, while https://api.slack.com/slash-commands#app_command_handling says it's x-www-form-urlencoded. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
2.2.0
node version:
v11.3.0
OS version(s):
unrelated

**Comment by clavin** [comment]
Slash commands are separate from the Events API and are handled by the `@slack/interactive-messages` package 😄

Check [this example](https://github.com/slackapi/node-slack-sdk/blob/8d3b2fdef099306732b344c7e030dd09c82dd91b/examples/express-all-interactions/server.js#L29) to see how it's done using that package.

**Comment by kurumpa** [comment]
I am sorry then, just guessed slash message is a message event. Guessed wrong, closing, thanks :)
