### ISSUE TITLE
Clean up links at slack.dev and label deprecated repos

### ISSUE THREAD

**Issue by NReilingh** [slackapi/node-slack-sdk#794]
### Description

Hi there! I just spent about 2 hours debugging an "as designed" behavior because I was looking at documentation in the wrong (outdated) GitHub repo. This is because the links at https://slack.dev don't fully reflect the merging of Node.js repos into the SDK, and if you happen to arrive at one of these repos in GitHub (https://github.com/slackapi/node-slack-interactive-messages for example), the repo isn't archived and only reflects "deprecation" in a pinned issue; nowhere on the front README.md page.

I think my unfortunate debugging experience probably could have been improved. ;-)

I had a somewhat roundabout way of finding out about these packages, so here's how I got here and what could be improved along the way:

1. I started from the generic [Slack API docs](https://api.slack.com), but actually never saw a single reference to the Node SDK packages until I went looking for them just now. On [Building a Slack app](https://api.slack.com/start/building#sdks) there's a link to the Node SDK [Getting Started](https://slack.dev/node-slack-sdk/getting-started) page, but what I'm really looking for is the list of `@slack/<package>` npm packages on [this page](https://slack.dev/node-slack-sdk/), which isn't even conspicuously linked in the sidebar. All that's to say these packages could have been made a lot more conspicuous throughout the documentation generic API and "getting started" documentation.

2. I started building a node app against the generic API docs, but eventually started searching npm, where I found `@slack/web-api`. Searching on NPM can't be used (as far as I can tell) to get an exhaustive list of packages from a publisher, but I eventually found my way to the [legacy client package](https://www.npmjs.com/package/@slack/client) page, which lists three of the five current packages (and not `@slack/interactive-messages`, which is what I was really looking for). I get that this legacy page is only trying to show existing users how to migrate to the new SDK at this point so you can't really point it to the current Node SDK homepage, but be aware the package homepage currently 404s at https://slack.dev/node-slack-sdk/tutorials/migrating-to-v5/ due to the trailing slash (#793).

3. At some point I made my way to https://slack.dev out of curiosity for what was at the root of that domain, and had also managed to find the `@slack/interactive-messages` package and add it to my project. But while trying to figure out an issue, I found my way from https://slack.dev to the [old github repo](https://github.com/slackapi/node-slack-interactive-messages) and started digging through it. The issue here is that the listing of projects at https://slack.dev appears to still reflect the "v4" clients, prior to unification into this SDK. So, the description for the SDK still points to `npm install @slack/client`, and the links for the Events API and Interactive Messages clients point to the deprecated GitHub repos (but do list the current `npm install` commands.

4. As I mentioned, there's nothing in the readmes of the deprecated https://github.com/slackapi/node-slack-interactive-messages and https://github.com/slackapi/node-slack-events-api repos to indicate that everything has gone to https://github.com/slackapi/node-slack-sdk. I believe GitHub provides an "archive this repository" feature that will display a conspicuous banner on all pages within the repo. The root readme page could be updated with a conspicuous message as well.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by NReilingh** [comment]
Also just found that the content at https://slack.dev also appears at https://api.slack.com/tools.

**Comment by shaydewael** [comment]
Hey @NReilingh — thanks for all of your considerate feedback on the documentation. It's been helpful as we've been incrementally working to improve them. We've done some work to slack.dev to try and make it easier to navigate packages, and be more explicit about deprecations in the Github repositories.

I'm going to close this issue, but if you have any more documentation feedback, we'd love to hear it 😄
