### ISSUE TITLE
Adding .d.ts to @slack/interactive-messages?

### ISSUE THREAD

**Issue by ryota-ka** [slackapi/node-slack-sdk#798]
### Description

I've made a very first version of type declaration of `@slack/interactive-messages` for my personal use.

- Would it be nice if we had ambient type declaration file for `@slack/interactive-messages`?
- If so,
  - Where should we put `index.d.ts`?
  - With which script should we put `index.d.ts` into `dist/` directory?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by clavin** [comment]
Sorry for taking so long to respond response!

I was actually working on #799 (which converts the source of `@slack/interactive-messages` to TypeScript) when you created this issue, and I believe it should end up fixing this issue :).

I'm interested to see the `index.d.ts` typings you created, and I'm happy to add any types you came up with that enhance the package.

**Comment by clavin** [comment]
#799 has since been merged, and version [`1.2.0` of `@slack/interactive-messages`](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Finteractive-messages%401.2.0) should include typings.

I'm closing this since there's now typings for this package. 🙂
