### ISSUE TITLE
messages contain different source_team value in different channel types

### ISSUE THREAD

**Issue by KharitonOff** [slackapi/node-slack-sdk#801]
### Description

we are facing some strange Slack API behaviour: our Bot uses node-slack-sdk. On new message it receives different values (specifically for the attribute `source_team`)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/client` (RTMClient)
- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 4.8.0-patch

node version: 11

OS version(s): 

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

Consistent values (team ids) for all types of messages 

#### Actual result:

On new message we receive different values (specifically for the attribute `source_team`)

For ‘directMessage’ or ‘groupMessage’ (shared Channel) as expected we get following data, where the ‘source_team’ has the same format as ‘team’:
```channel:"G8CPCNUJV"
client_msg_id:"72a438ca-e4b8-4d1f-95a2-9fd8ebd57679"
event_ts:"1560935384.001600"
source_team:"T81UJGDD1"
suppress_notification:false
team:"T81UJGDD1"
text:"<@W8N3YT2JH> hi"
ts:"1560935384.001600"
type:"message"
user:"W4UR1U4FR"
```

But for ‘channelMessage’ or ‘groupMessage’ (private Channel) we receive data with different team id in the ‘source_team’:

```channel:"CDGS6R81H"
client_msg_id:"491b90f5-d03e-4f19-8c92-d0ec415a6d97"
event_ts:"1560936814.001700"
source_team:"E7RBBBXHB"
suppress_notification:false
team:"T81UJGDD1"
text:"<@W8N3YT2JH> hi"
ts:"1560936814.001700"
type:"message"
user:"W4UR1U4FR"
user_team:"E7RBBBXHB"
```

Why does the source team contain our enterprise id here? Are there any further plans on your side to change values of the attributes?

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by aoberoi** [comment]
Sorry for the delay in our response on this.

We don't recommend using RTM within shared channels. The RTM API is designed for single workspace use cases first and foremost. For apps in Enterprise Grid organizations, our advice is to migrate your app to the [Events API](https://api.slack.com/events-api).

If you have any further questions, feel free to open a new issue.
