### ISSUE TITLE
Remove unnecessary build before testing

### ISSUE THREAD

**Issue by clavin** [slackapi/node-slack-sdk#802]
### Description

Each package runs `npm run build` before running tests. This is unnecessary as each package's tests import directly from source. It's safe to remove the `npm run build &&` at the start of each `"test"` script.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [x] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.1

node version: --

OS version(s): --

**Comment by aoberoi** [comment]
Thanks for the idea @clavin! Although it might be safe to remove `npm run build &&` from our `test` script in many cases, it is comforting to know that we're testing against code that has built correctly, passed the typechecker, and is not stale. In term of benefits, we might be able to save a few milliseconds, but there are much larger fixes we need to address that will reduce our testing time much further (such as #851).
