### ISSUE TITLE
Responding to Dialog submissions with errors

### ISSUE THREAD

**Issue by ghost** [slackapi/node-slack-sdk#806]
### Description

Describe your issue here.

With a dialog, the [documentation](https://api.slack.com/dialogs#evaluating_submission_responses) states that you can respond with errors.

I can't seem to find any examples (or prior issue questions) showing an example of how this can be achieved. Take the following example:

```
slackInteractions.action(<callbackID>, (payload, respond) => {
    /// Perform business logic validation
    if (validation_success) {

    } else {
        respond({
                "errors" : [ ... ]
    });
} 
```

Any attempts I try (including JSON stringifying the payload) result in a 500 error without any specific error message. Can anyone guide me on the correct way to achieve what I'm trying to do?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] I don't know

**Comment by mwbrooks** [comment]
Looks like our user been removed from GitHub, but I'll throw an answer in here for anyone who comes across this issue.

While it's not as obvious as we'd like, the correct approach is to return the `errors` object rather than passing it into the `respond` param. I[n the documentation, the example is](https://slack.dev/node-slack-sdk/interactive-messages#handle-an-action):

```javascript
// Example of handling all dialog submissions
slackInteractions.action({ type: 'dialog_submission' }, (payload, respond) => {
  // Validate the submission (errors is of the shape in https://api.slack.com/dialogs#input_validation)
  const errors = validate(payload.submission);

  // Only return a value if there were errors
  if (errors) {
    return errors;
  }
```

Hope that helps some people! If you are tripped up by this, please feel free to leave and comment and we can try to clarify our documentation.
