### ISSUE TITLE
createServer()'s path option is unused, deprecate?

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#814]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/94

### Description

It seems that we've introduced an issue where the `path` argument to `SlackEventAdapter#createServer()` is unused (besides the log messages). This was likely the result of the refactor which made Express no longer required (https://github.com/slackapi/node-slack-events-api/pull/59).

It doesn't seem to have created any issues since the behavior is that all incoming requests are valid, regardless of which URL they are sent to. The only point of using `path` would be to block incoming requests that had a URL that didn't match, and possibly throw some kind of error (or pass it forward in the case of Express middleware - but we don't do this for any existing error).

Given that nobody seems to have complained, and this issue has existed for over 7 months, I don't think there's any demand for new path matching and error handling functionality like this.

Instead, **I propose that we deprecate the `path` argument, and while we're at it, deprecate the `expressMiddleware()` method**. For the latter, it doesn't add any value since it does the exact same thing as `requestListener()`, but just returns a function with a different arity. Express would be fine with a handler that has no `next` (an arity of 2), and the only thing we'd lose is the opportunity to forward errors through the middleware chain, something we're not doing at all today.

Deprecation would simply look like logging warnings when those options are used.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by mwbrooks** [comment]
_Triage with the team:_

We're labelling this a semver major and leaving it open. At the moment, we're discussing what a major would look like for the events package.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
