### ISSUE TITLE
Move as much functionality as possible into the adapter class

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#815]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/39

### Description

try to bring token verification, error creation, and/or emit argument building into the adapter class. one day this may become shared among multiple web framework outlets.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
This functionality is already available in [Bolt for JS](https://slack.dev/bolt-js). We don't have plans to implement this in the `@slack/events-api` package.
