### ISSUE TITLE
Add TypeScript definitions for events

### ISSUE THREAD

**Issue by shanedewael** [slackapi/node-slack-sdk#816]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/35

### Description

Get some typing built into this package.

My 2c is that we should steer away from over-typing the actual events, but we could document at least a couple of "baseline" properties that all events have.

It shouldn't be too hard to describe the actual API of the module though. We should figure out how much JSDoc will do for us since the typescript language service can read JSDoc comments for types now. At this point I don't think there's any need to port to code to .ts, but open to hear feedback on this.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
#799 converts the package to TypeScript but doesn't add type definitions for events

**Comment by montasaurus** [comment]
It doesn't look like #799 actually resolved this issue. Are there any typescript definitions for the event payloads? Could we reopen this issue if not?

**Comment by alfaproject** [comment]
Just stumbled upon this issue trying to look for the event payload definitions. Can this be reopened?

**Comment by seratch** [comment]
@alfaproject `@slack/events-api` package is deprecated. 
https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6#deprecating-slackevents-api--slackinteractive-messages

`@slack/bolt` provides the complete set of Events API payloads. Check the project instead:
https://github.com/slackapi/bolt-js/tree/main/src/types/events

**Comment by alfaproject** [comment]
Oh that makes sense. I think I saw bolt before but ignored it because it creates a long running server and we only use lambda in our organization. We can use the types tho, ofc. Thanks!
