### ISSUE TITLE
Proxy connection through a gateway

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#817]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/38

### Description

What if we could remove the need for a development proxy (ngrok/localtunnel) by allowing a developer to stand up a gateway service very easily. Then a config flag could be introduced in this module that transparently (without needing any additional code changes) would connect to that gateway using a long-lived connection (such as websocket or HTTP SSE) and receive individual HTTP requests from the gateway. This may ease the use of the Events API substantially by not having to have a sidecar process running while developing. This could be as simple as creating a Heroku Button for deploying the gateway service to Heroku (or other cloud providers).

On the flip side, it introduces some level of non-parity between development and production, which is notoriously a source of bugs in general.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
Since this issue was opened, there have been several important developments for how we can solve this kind of problem. The solution we're currently pursuing is not part of our open source set of tools, but instead a part of the Slack Platform as a whole, which will make it available to a much bigger audience! Stay tuned for more updates as they happen [`@SlackAPI`](https://twitter.com/slackapi).
