### ISSUE TITLE
Listen for any event

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#819]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/76

### Description

You might want to structure an application such that all incoming events are handled by the same function. Maybe you want to use the signature verification facilities of this package, but want to dispatch to your own routing system. Or maybe your application forwards all events on to another micro-service or system. Maybe your application wants to log all events it sees, or implement some other form of "middleware" on event processing.

It would be useful to design a solution where all the mentioned use cases can be addressed. At this point, I'm not proposing a specific API, but the maintainers are interested in hearing proposals for APIs from the community.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by shanedewael** [comment]
https://github.com/slackapi/node-slack-events-api/issues/76

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
