### ISSUE TITLE
Synthetic event types -- event types that are deduced from combinations of event properties

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#820]
Reopened from https://github.com/slackapi/node-slack-events-api/issues/51 where there is more context and discussion

### Description

We can infer some missing event types by looking at `event.type` + `event.subtype` , e.g.
```js
if (type === 'message') {
  if (subtype === 'message_changed') // message_changed
  else if (! subtype) // message_created
}
```

Backwards works too -- going from specific to generic, e.g.
```js
if (type === 'reaction_added' || type === 'reaction_removed') // reaction_changed
```

Would you be willing to add such event types this to this library?

Thanks in advance.
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
