### ISSUE TITLE
Make respond() function wait until next tick before sending request

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#826]
Reopened from https://github.com/slackapi/node-slack-interactive-messages/issues/69

### Description

Inspired by https://github.com/slackapi/node-slack-interactive-messages/issues/68.

Users of this package have the ability to call `respond()` inside a handler before the handler function has returned. That means that someone may accidentally try updating an interactive message before the interactive message has even been acknowledged (because the handler returning is the signal that we can respond with `200 OK`). If the `respond()` function waited until the next tick to do any work, then the handler function's return would always be before the request to the `response_url`, and it would prevent these types of issues.

Disclaimer: we're still not sure this was the actual problem with the issue mentioned above.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
