### ISSUE TITLE
Improve Express All Interactions Glitch instructions

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#827]
Reopened from https://github.com/slackapi/node-slack-interactive-messages/issues/46

### Description

1. The `SLACK_ACCESS_TOKEN` variable is only available after install, but if you try to install the app in the order the instructions are presented, it will fail and say you need to add at least one scope.

2. In enabling interactive components, where do I get the "Glitch URL"? Its in the "Share" menu, but it would be nice to be explicit. Maybe give an example.

3. Where do I put the environment variables? If you know Glitch, you'll know its in `🗝.env`, but many users don't know Glitch. Also, if you're running locally, its not clear that you can put this in `.env`.

4. You need a description for the slash command.

5. `PORT` needs to be commented out in `.env`

6. In `package.json`, `@slack/interactive-messages` dependency version specifier should be set to `"^0.3.0"`

Maybe there should be 2 completely different sets of instructions for setup locally and on Glitch.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
