### ISSUE TITLE
Export a function to verify request signatures

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#829]
Reopened from https://github.com/slackapi/node-slack-interactive-messages/issues/82

### Description

It would be useful to expose a function that verifies request signatures, even when not using the request handler. This functionality would duplicate the work in 
https://github.com/slackapi/node-slack-events-api/issues/70. We could implement this by extracting that into a shared dependency of both of these packages, but that’s not required. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by misscoded** [comment]
It might be better to expose this functionality from its own package.

**Comment by seratch** [comment]
This is not yet implemented. We have similar code in bolt-js project: https://github.com/slackapi/bolt-js/tree/main/src/receivers Once we release a new package, we can remove duplicated code from bolt-js too.

**Comment by seratch** [comment]
We'll use https://github.com/slackapi/node-slack-sdk/issues/1135 for tracking the progress of this.
