### ISSUE TITLE
Finding specific message without knowing if its a channel or group

### ISSUE THREAD

**Issue by doughlass** [slackapi/node-slack-sdk#837]
### Description

I found in the documentation Channels and Groups, with the latter being private.

Currently I have the ID of the channel / group and the timestamp and trying to figure out the best approach to checking if the ID and TS is a channel or a group in order to get the message.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.1

node version: 10.13.0

OS version(s): macOS 10.14.5

#### Steps to reproduce:

This is my script I've written so far. If I take the groups.history out of catch() then channels.history throws an error to the parent function.

      const message = await this.slack.channels.history({
        channel: item.channel,
        latest: item.ts,
        count: 1
      })
        .then(data => data)
        .catch(async (data) => {
          return await this.slack.groups.history({
            channel: item.channel,
            latest: item.ts,
            count: 1
          });
        });

#### Expected result:

What I'm trying to do is simple, check whether the ID is a channel or a group and retrieve the message

#### Actual result:

This code works but I don't feel like it's as good as it can be and would welcome input from other developers into this - looking across the internet there doesn't seem to be an alternative to what I've written.

**Comment by clavin** [comment]
For anyone finding this in the future that's trying to target channel-like "conversations", the solution is to use the [`conversations.*` API methods](https://api.slack.com/methods#conversations). For example, the use of `channels.history` and `groups.history` above ☝️ could be squashed into a call to `conversations.history`:

```js
const message = await this.slack.channels.history({
  channel: item.channel,
  latest: item.ts,
  count: 1
});
```
