### ISSUE TITLE
Pull interactive message info instead of let slack server push

### ISSUE THREAD

**Issue by Terry93** [slackapi/node-slack-sdk#845]
### Description

I have a question about writing a slack bot supporting interactive message. After going through the doc, I think the only way to support it is to register a public URL in the app management page and let slack API server push the action message (which contains callback_id/block_id) to my server right? Is there a way to “pull”, instead of “push” (something like RTM api)? The reason is that my company security team does not recommend using ngrok.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by clavin** [comment]
Sadly, there's currently no API that lets you 'pull' interactive message events 😞. On the upside, on Slack's [Platform Roadmap] there's a card showing that support for [receiving platform data behind a firewall] is a known request. (I personally don't know if the Interactive Messages API falls under this roadmapped feature 🤔.)

As an aside, ngrok isn't the only way to use `@slack/interactive-messages`. As long as the adapter receives the HTTP request it's happy! That means other tunneling services, [external hosting]<sup>1</sup>, or old-fashioned in-house HTTP routing are all acceptable.

I hope that answers your question 🙂

[receiving platform data behind a firewall]: https://trello.com/c/YMq4fN75/70-support-for-apps-to-receive-platform-data-behind-a-firewall
[Platform Roadmap]: https://trello.com/b/ZnTQyumQ/slack-platform-roadmap-for-developers
[external hosting]: https://api.slack.com/docs/hosting

#### Notes

<sup>1</sup> For an internal integration, hosting on a cloud provider is probably overkill.

**Comment by aoberoi** [comment]
It seems like this conversation is done, so I'm going to close the issue. If anyone has any related thoughts, feel free to comment again and we may re-open.
