### ISSUE TITLE
cant_update_message error when updating successfully message

### ISSUE THREAD

**Issue by oprogramador** [slackapi/node-slack-sdk#848]
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] I don't know

#### Reproducible in:

package version: @slack/client@5.0.2

node version: 10.16.0

OS version(s): Linux, kernel: 4.15.0-54-generic, distribution: 18.04.1 LTS (Bionic Beaver)

#### Steps to reproduce:

```js
const { WebClient } = require('@slack/client');

const web = new WebClient(token);

web.chat.update({
    token,
    ts,
    channel,
    text,
});
```

I get an error though the Slack message is in fact updated

#### Expected result:

Either updating message should be rejected or there should be no error thrown.

#### Actual result:

I get the following error: `{"code":"slack_webapi_platform_error","data":{"ok":false,"error":"cant_update_message","response_metadata":{"scopes":["identify","bot:basic"],"acceptedScopes":["chat:write:bot","post"]}}}`.

**Comment by aoberoi** [comment]
Thanks for filing this issue. I haven't been able to reproduce it given the information you provided.

Was the message you're trying to update (represented by that `ts` and `channel`) posted by your bot? I'm assuming you're using a bot token based on the `response_metadata.scopes` in your error example. The `cant_update_message` error is supposed to occur if that message wasn't created by the bot.

Does this happen consistently (100% of the time)? Does it always happen on a particular message, but not on others? Is there any other information you can provide?

**Comment by oprogramador** [comment]
@aoberoi 
As I remember, it was occurring on each message update.
However, I cannot find any related error in the last logs so maybe it's already fixed.

**Comment by aoberoi** [comment]
Awesome, I’m glad you got past the issue!
