### ISSUE TITLE
Routing behaviour when using both @slack/interactive-messages and @slack/events-api

### ISSUE THREAD

**Issue by tantra-anthony** [slackapi/node-slack-sdk#849]
### Description

Using both @slack/interactive-messages and @slack/events-api in the same route in an express app causes some weird routing behaviour.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
```
"@slack/events-api": "^2.3.0",
"@slack/interactive-messages": "^1.3.0"
```
node version: 
`v10.16.10`
OS version(s): 
`Linux 16.04`
#### Steps to reproduce:

Using express and using the same route for these two packages:
```
router.use('/', slackEvents.expressMiddleware());
// some other code
router.use('/', slackInteractions.expressMiddleware());
// some other code
```

#### Expected result:

Initially thought it would filter the messages based on the type of message (whether it's an event/interaction) and it will correctly go into the correct listeners for both cases.

#### Actual result:

Only the first one will be processed, second one will produce a `500` error. This also applies if the second one in the list is the child route of the first, for example:

```
router.use('/', slackEvents.expressMiddleware());
// some other code
router.use('/actions', slackInteractions.expressMiddleware());
// some other code
```

The code above will only work for the events part and will throw a `500` error for every action detected.

#### Suggestion

Would be great to put this in the documentation. At least mention the part where the endpoints must be completely separate. I have no issues with the implementation. Spent quite a while trying to look for the problem why it was giving me a `500` error.

**Comment by aoberoi** [comment]
@tantra-anthony thanks for pointing this out! you're totally right that we could do a better job demonstrating how these packages are meant to be used together in an app. i'm glad you did eventually get to a solution, but let's make sure the next person doesn't have to go through as much confusion as you did.

**Comment by aoberoi** [comment]
a light recommendation: we've released [`@slack/bolt`](https://slack.dev/bolt) which handles messages from the Events API, Interactive Messages, and Slash Commands all in one package. if you haven't already wrote much code to use these packages, its worth considering porting to Bolt.
