### ISSUE TITLE
Implement build stages on Travis CI

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#851]
### Description

Currently, the Travis CI build process takes close to 30 minutes to complete (depending on the change).

One of the inefficiencies is that many jobs duplicate the same work all over again. Travis CI provides a feature called [build stages](https://docs.travis-ci.com/user/build-stages/) which may help eliminate this inefficiency.

Speeding up our CI build time will make it much more feasible to iterate on changes, and ultimately make the process of contributing to this project moroe pleasant.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
it would be rad if we were able to test `@slack/interactive-messages` and `@slack/events-api` on the supported node versions (`>= 4.2.0`) instead of using the same node versions that all the other packages use.

**Comment by seratch** [comment]
We no longer use TravisCI.
