### ISSUE TITLE
How can I record interactive messages made by respond function of @slack/interactive-messages with steno

### ISSUE THREAD

**Issue by eltNEG** [slackapi/node-slack-sdk#854]
### Description

I am trying to record an interactive message using steno. But it appears that the messages responded to using the `respond` function passed to my handler by `createMessageAdapter` isn't recorded by steno. Please, how can I configure the response URL used by `respond` to pass through steno? 

`Sample code`
```
const slackInteractionsRouter = createMessageAdapter(process.env.SLACK_SIGNING_SECRET);

slackInteractionsRouter.action({ callbackId: 'back_to_launch' },
  SlackInteractions.launch);
```

`launch` function takes in `payload` and `respond`. How can I make respond call pass through steno so that it gets recorded?

I would like to know if respond also make use of the response_url in the payload from slack

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by eltNEG** [comment]
A workaround that I am currently using is to replace the respond function with another built with `axios` using a middleware placed between the interactive router and my handlers.

**Comment by aoberoi** [comment]
Sorry for the long delay in getting back to you @eltNEG!

The `respond()` function does use the `response_url` that's sent in the payload from Slack.

This sounds like a feature request to me, and one that is worthwhile. It seems like what we need is a way to get the adapter in `@slack/interactive-messages` to rewrite the host in the `response_url`, in the same way that the client in `@slack/web-api` can be initialized to use a different `slackApiUrl`.

I think this would make sense as a new adapter option, possibly also called `slackApiUrl`.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
