### ISSUE TITLE
chat.postMessage with blocks using Web API, the text of root attribute is not reflected for Slack post.

### ISSUE THREAD

**Issue by kenchan0130** [slackapi/node-slack-sdk#860]
### Description

When I use the `chat.postMessage` with blocks in web-api, the `text` of parent is not reflected for Slack post.
I don't know if there are bugs in slack's api or client.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.1.0

node version: 12.0.0

typescript version: 3.6.2

OS version(s): macOS 10.14.6

#### Steps to reproduce:

Execute
```typescript
import { WebClient } from '@slack/web-api';
const webClient = new WebClient('dummy-access-token');

(async (): Promise<void> => {
  await webClient.chat.postMessage({
    channel: 'XXXXXX',
    text: 'text',
    blocks: [
      {
        type: "section",
        fields: [
          {
            type: "mrkdwn",
	    text: "filed1"
          },
          {
            type: "mrkdwn",
            text: "filed2"
          }
      ]
    }]
  });
})();
```

#### Expected result:

```
text
filed1 filed2
```
will be posted to slack.

#### Actual result:

```
filed1 filed2
```

was posted to slack.

#### Workaround:

Use text of section block with empty string.

```typescript
import { WebClient } from '@slack/web-api';
const webClient = new WebClient('dummy-access-token');

(async (): Promise<void> => {
  await webClient.chat.postMessage({
    channel: 'XXXXXX',
    text: '',
    blocks: [
      {
        type: "section",
        text: {
          text: "text",
          type: "mrkdwn"
        },
        fields: [
          {
            type: "mrkdwn",
	    text: "filed1"
          },
          {
            type: "mrkdwn",
            text: "filed2"
          }
      ]
    }]
  });
})();
```

**Comment by shanedewael** [comment]
This is the intended behavior. If blocks are present in your request, the text won't render in a message. However, the `text` property is still important because it what will render inside of the notification when your message is posted. We could definitely make this more clear in the documentation.

**Comment by shanedewael** [comment]
It's talked a little about here https://api.slack.com/reference/messaging/payload and we'll update https://api.slack.com/methods/chat.postMessage in the future.
