### ISSUE TITLE
How about to set false 'esModuleInterop' on tsconfig.json?

### ISSUE THREAD

**Issue by Ikanny** [slackapi/node-slack-sdk#872]
### Description

The "node slack sdk" uses "esModuleInterop" for all projects. It makes me fail to compile my own projects. Especially, "event-api" package imports "EventEmitter" from "events" module as default. In this case, projects which set "esModuleInterop" false get compile error like `Module '"events"' has no default export.`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

**Comment by aoberoi** [comment]
Hi @Ikanny, thanks for making us aware of this issue! This sounds like the same issue as in #759, except its in the `@slack/events-api` package instead of `@slack/web-api`.

My next steps here are to try and reproduce the issue as you described, but also make sure the other packages in this repo work correctly with `esModuleInterop` turned off. I hope to put these in the integration tests, as we did in #760, so that we don't regress on this in the future.

**Comment by aoberoi** [comment]
I was able to reproduce the failure in a scrap project. Then I made a failing test in the integration tests. I'll open a draft PR for this, but if anyone else would like to pick that PR up and implement the fix, please feel free!

**Comment by saeedseyfi** [comment]
Hi @aoberoi, I opened a PR, please have a look.

**Comment by AmazingTurtle** [comment]
@saeedseyfi your PR seems to fix one particular use case but does not prevent build failures with external projects where `esModuleInterop` is set to false.

As for me, when trying to set `esModuleInterop` to true, I get 

```
node_modules/@slack/events-api/dist/adapter.d.ts:8:48 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.

8 export declare class SlackEventAdapter extends EventEmitter {
```

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
