### ISSUE TITLE
@slack/interactive-messages: view_submission action never routes to action handler

### ISSUE THREAD

**Issue by jmshal** [slackapi/node-slack-sdk#873]
### Description

You cannot currently register an `ActionHandler` for the `view_submission` action type.

I've pinpointed the line that causes the routing to fail.

https://github.com/slackapi/node-slack-sdk/blob/8a3f777519718ffb87cbde712f75b8d594255f84/packages/interactive-messages/src/adapter.ts#L391

The `view_submission` payload does not contain any of the fields checked for on that line (actions, submission, message). But it does contain a `view` field, which I suspect should be enough to fix the bug.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 1.3.0

node version: 12.10.0

OS version(s): macOS Mojave (10.14.6)

#### Steps to reproduce:

```js
// ...

slackInteractions.action({ type: 'view_submission' }, async (event) => {
  console.log(event);
});
```

#### Expected result:

The console log will fire with the event object.

Eg.

```
{
  type: 'view_submission',
  team: { id: '[REDACTED]', domain: '[REDACTED]' },
  user: {
    id: '[REDACTED]',
    username: 'jacob',
    name: 'jacob',
    team_id: '[REDACTED]'
  },
  api_app_id: '[REDACTED]',
  token: '[REDACTED]',
  trigger_id: '[REDACTED]',
  view: {
    id: '[REDACTED]',
    team_id: '[REDACTED]',
    type: 'modal',
    title: { type: 'plain_text', text: '[REDACTED]', emoji: true },
    close: { type: 'plain_text', text: '[REDACTED]', emoji: true },
    submit: { type: 'plain_text', text: '[REDACTED]', emoji: true },
    blocks: [ [Object] ],
    private_metadata: '[REDACTED]',
    callback_id: '',
    state: { values: [Object] },
    hash: '[REDACTED]',
    clear_on_close: false,
    notify_on_close: false,
    root_view_id: '[REDACTED]',
    previous_view_id: null,
    app_id: '[REDACTED]',
    external_id: '',
    bot_id: '[REDACTED]'
  }
}
```

#### Actual result:

The Request URL sends back a 404 (Not Found) to Slack - which displays the following message within the modal.

<img width="495" alt="Screenshot 2019-09-27 13 10 33" src="https://user-images.githubusercontent.com/4710291/65734683-3c698300-e128-11e9-8313-ad4db295f767.png">

**Comment by Startouf** [comment]
Hey, I have been struggling with the same thing and even opened a StackOverflow thinking the problem was coming from me https://stackoverflow.com/questions/58125649/api-error-occurred-invalid-arguments-when-opening-a-modal-in-slack

**Comment by Startouf** [comment]
As I showed in my above StackOverflow question, the `callback_id` when submitting a view is nested under the `views` and this make it very unintuitive when you want to implement an action handler for a given Callback ID (for all other actions, callback_ids are handled via a simple 
`slackInteractions.action({ callbackId: "my_callback_id" })` but here I'm not sure this would even work

**Comment by Startouf** [comment]
Another problem with view_submission : we are expected to return directly a custom response to trigger some view updates like adding live errors or refreshing the modal. By default, if our callback terminates without returning anything, the modal simply closes (the default response is `return Promise.resolve({ status: 200 });`).

It turns out the current implementation does not allow customizing this either. Modal view submissions have a new type `payload.type === 'view_submission'` (different than `'dialog_submission'`) which are not handled by the adapter. I'm having troubles finding more detailed information in the slack api documentation and how we're supposed to respond to this to trigger alternate behaviors (the documentations mentions things like returning an object with `"response_action": "errors"`, but it's not clear how this should be wrapped in the response).

I'm trying some monkeypatches on the adapter on my side, but it seems like replacing the following line in the adapter is not enough. 

```javascript
if (!_this.lateResponseFallbackEnabled || respond === undefined || payload.type === 'dialog_submission' || payload.type === 'view_submission') {
```

**Comment by janniks** [comment]
Also have the same problem - @slack APIs should not be deprecated before the new API/SDK isn't finished...

**Comment by janniks** [comment]
Even the described method of matching all actions does not work:
```
// Example of constraints for all actions.
slackInteractions.action({}, (payload, respond) => { /* ... */ });
```
from https://slack.dev/node-slack-sdk/interactive-messages

**Comment by aoberoi** [comment]
Thanks for bringing this issue to our attention, folks. I agree that handling view submission is desirable feature for the `@slack/interactive-messages` module. Let's start an issue to describe what we need to reach that goal.

PS. I don't mean to dismiss this as "not an actual bug" but view submission support is more than just fixing that conditional.

**Comment by aoberoi** [comment]
I created the issue above, but I also wanted to point out that if this is a blocker for something you are building, you might want to consider using Bolt. We've added support for the majority of use cases already in that project.

slack.dev/bolt
