### ISSUE TITLE
User-Agent header causing IncomingWebhook.send to result in 400 error

### ISSUE THREAD

**Issue by Glen-Moonpig** [slackapi/node-slack-sdk#876]
### Description

Sending a slack message using IncomingWebhook.send is resulting in the following error:

```
Error: Error: Response for preflight has invalid HTTP status code 400
        at Object.dispatchError (C:\Development\Moonpig\moonpig-ops-monitoring-slack\source\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:65:19)
        at EventEmitter.client.on.err (C:\Development\Moonpig\moonpig-ops-monitoring-slack\source\node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:676:20)
        at EventEmitter.emit (events.js:194:15)
        at Request.preflightClient.on.resp (C:\Development\Moonpig\moonpig-ops-monitoring-slack\source\node_modules\jsdom\lib\jsdom\living\xhr-utils.js:376:16)
        at Request.emit (events.js:189:13)
        at Request.onRequestResponse (C:\Development\Moonpig\moonpig-ops-monitoring-slack\source\node_modules\request\request.js:1066:10)
        at ClientRequest.emit (events.js:189:13)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
        at TLSSocket.socketOnData (_http_client.js:442:20) undefined
```

After much trail and error modifying the @slack/webhook internal code I have discovered that the **User-Agent** header is causing the request to be rejected.

The user agent header value being created is `@slack:webhook/5.0.2 node/10.15.1 win32/10.0.17134`

Removing the User-Agent header configuration from the below code in @slack\webhook\dist\IncomingWebhook.js, which initializes the axios client fixes the problem:

```javascript
this.axios = axios_1.default.create({
	baseURL: url,
	httpAgent: defaults.agent,
	httpsAgent: defaults.agent,
	maxRedirects: 0,
	proxy: false,
	headers: {
		'User-Agent': instrument_1.getUserAgent(),
	},
});
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [X] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.2

node version: 10.15.1

OS version(s): Windows 10

#### Steps to reproduce:

1. Use following code
```javascript
const webhook = new IncomingWebhook(slackUrl);
const message = {
  text: "Hello"
};
await webhook.send(message);
```

#### Expected result:

The message sends to Slack without error

#### Actual result:

Error: Response for preflight has invalid HTTP status code 400

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by Glen-Moonpig** [comment]
This can also be resolved by adding `testEnvironment: "node"` to jest configuration

**Comment by aoberoi** [comment]
Hi @Glen-Moonpig,

I'm going to go out on a limb here and guess (based on your use of jest and jsdom) that you're running some sort of test in Node, but using jsdom to emulate running within a browser. Perhaps you're testing a front-end application and trying to send results to Slack.

This package doesn't support running in a browser environment, only node. If my previous assumption is right, it seems that jsdom is so good at emulating the browser environment that its fooled this package. This is causing the failure. Even though this is an unsupported target, I want to help you get this working.

The first step here is for you to help me reproduce the actual issue. Can you confirm if any of my assumptions are right? It might also help if you could provide a sample project where this issue occurs.

**Comment by aoberoi** [comment]
It turns out that even if you're just testing server (node) code, jest will load jsdom (it assumes you're testing browser code).

The recommended fix for this is what you already found: setting `testEnvironment: 'node'`.

That likely won't work if you actually were trying to test client (browser) code. In that case, I found the following two workarounds:
* https://github.com/axios/axios/issues/1180#issuecomment-477920274
* https://stackoverflow.com/a/51054658

Let us know if you're happy with these solutions.

**Comment by Glen-Moonpig** [comment]
I think setting jest environment to jsdom is the right solution. It would be great if there was some kind of clue as to why the request was being rejected but I'm not sure what to suggest for that.
