### ISSUE TITLE
Running `npm run test` does not work properly

### ISSUE THREAD

**Issue by shaydewael** [slackapi/node-slack-sdk#886]
### Description

When you run `npm run test` in the root directory (which is an alias for `lerna run test`) the tests hang. The workaround right now is to go into the individual files and test, but we should be able to test all of the packages at once.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
I haven't been able to reproduce this issue. Have you tried cleaning out your repo (`rm -rf node_modules/ && npx lerna clean && npx lerna bootstrap`) and trying again.
