### ISSUE TITLE
BlockFactory Class Request

### ISSUE THREAD

**Issue by roeintense** [slackapi/node-slack-sdk#889]
### Description

Whereas botbuilder presents MessageFactory and CardFactory classes for crafting certain kinds of messages for presentation, Slack may benefit from presenting a BlockFactory class for use in generating some of the more basic templates. Submitting per @shanedewael  here https://dev4slack.slack.com/archives/C1EJWEW6Q/p1570628349000700

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

None. 

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [X] I don't know

**Comment by raycharius** [comment]
Hi! You might want to check out [slack-block-builder](https://github.com/raycharius/slack-blockbuilder). It's works similarly, for Slack Block Kit

**Comment by seratch** [comment]
As we are not planning to make this addition, let us close this issue. @raycharius's https://github.com/raycharius/slack-block-builder looks pretty cool 👍
