### ISSUE TITLE
[Question] Why Handle Message doesn't work in Events API

### ISSUE THREAD

**Issue by a007mr** [slackapi/node-slack-sdk#890]
I am creating my first Slack bot and have struggle with Events API. Please help me to figure out why Message Handler doesn't work... I've created simple bot:

```
// Start a basic HTTP server
slackEvents.start().then(() => {
  console.log(`Slack bot was started`);
  greeting();     // it works
});

// Error Handler
slackEvents.on('error', console.error);

// Message Handler    // doesn't work :(
slackEvents.on('message', event => {
  console.log(event);  // shows nothing in console
  handleMessage(event);   // doesn't run
});
```
Message handler doesn't work. He doesn't show event in console and doesn't run 'handleMessage(event)'. I don't have errors and can't understand what's wrong. 

When I'm using RTM API instead of Events with the same pattern, everything works with RTM, but I want to use event api as there are more opportunities.

How to understand what's wrong?

**Comment by seratch** [comment]
Let me check just in case. Have you already configured the Events API settings at `https://api.slack.com/apps/{your app id}/event-subscriptions` ?

**Comment by a007mr** [comment]
Nope, I haven't it. I don't know why, but I missed this part in documentation. Thank you so much.

**Comment by seratch** [comment]
Thanks for your response. Glad to be of help!
