### ISSUE TITLE
Validating request using AWS API Gate

### ISSUE THREAD

**Issue by danny-waite** [slackapi/node-slack-sdk#891]
### Description

I'm trying to setup an AWS API Gateway together with an Authorizer lambda function to verify requests made via the events-api.  The issus is verifyRequestSignature requires access to the request body which is not passed to the lambda function and thus I'm unable verify.  Is there a way around this?  It seems strange that `X-Slack-Signature` and `X-Slack-Request-Timestamp` are passed via the header but the body is also needed.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

**Comment by seratch** [comment]
As you mentioned, Authorizer doesn't provide a request body value in the function. So, it's not possible to verify Slack requests in the function. The only way we can do is to verify requests in backend Lambda functions.

**Comment by danny-waite** [comment]
ok thanks for the clarification @seratch
