### ISSUE TITLE
Unable to receive payload from block kit modal

### ISSUE THREAD

**Issue by itsgracian** [slackapi/node-slack-sdk#892]
### Description
I was able to open modal by sending request URL on **https://slack.com/api/views.open** which also contain input and date picker. 
I tried to receive payload by using **@slack/interactive-messages** package but I can't receive a payload.  I would like to ask how should I receive a payload. 

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
^1.3.0
node version:
v10.15.1
OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen
I was expected to receive payload which contains information and store them into my database.
#### Actual result:

What actually happened

#### Attachments:
this is the opening modal from my APP but when i try to send data back to my server i can't receive payload while i setup callback id and so. 

<img width="1150" alt="Screen Shot 2019-10-21 at 16 04 54" src="https://user-images.githubusercontent.com/27460888/67212351-8f2f1580-f41c-11e9-8f36-41d6f74aca1a.png">

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by tholmes-rms** [comment]
I'm having the same problem.

Opening a modal using `web.views.open` opens just fine.
I have an action handler that should be handling all actions:
```js
slackInteractions.actions({}, (payload, response) => {
  console.log('got an action')
}
```
This works for other actions, but for the view submission the debug output is:
```
  express:router dispatching POST /slack/actions +4s
  express:router query  : /slack/actions +0ms
  express:router expressInit  : /slack/actions +1ms
  express:router trim prefix (/slack/actions) from url /slack/actions +0ms
  express:router <anonymous> /slack/actions : /slack/actions +0ms
  @slack/interactive-messages:http-handler request received - method: POST, path: / +4s
  @slack/interactive-messages:http-handler Parsing raw request +0ms
  @slack/interactive-messages:http-handler request signing verification success +1ms
  @slack/interactive-messages:adapter dispatch could not find a handler +4s
  @slack/interactive-messages:http-handler no callback was matched +0ms
```

Is `interactive-messages` not ready for Modals, do I need to use the outdated dialogs?

**Comment by itsgracian** [comment]
@tholmes-rms I found the other way we can use  was to integrate slack app using **bolt framework**  [https://slack.dev/bolt/concepts](https://slack.dev/bolt/concepts)

**Comment by seratch** [comment]
ref #883

**Comment by aoberoi** [comment]
Thanks all for your interest. As @seratch helpfully pointed out, the feature you're asking about hasn't yet been implemented. This was first pointed out in #873. 

@itsgracian, it seems like your question is answered since you figured out that Bolt is capable of handling these requests already.

We still acknowledge that we need to add this feature to `@slack/interactive-messages` and are tracking progress towards it in #883. We're likely going to implement the feature and make a release this week.

**Comment by jacklein** [comment]
@aoberoi Is there any way to use bolt to send a response action back to the modal? I'm having a difficult time figuring out how to send an error message back to my modal. Any help would be greatly appreciated.

**Comment by stevengill** [comment]
@jacklein looks like your question was answered in https://github.com/slackapi/bolt/issues/333
