### ISSUE TITLE
Open modal: invalid_argument

### ISSUE THREAD

**Issue by erperejildo** [slackapi/node-slack-sdk#893]
### Description

I cannot open a modal

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I run my Slack command using `/direct-bot`. It displays a couple of button and pressing one I should be able to display a modal.

This is my code:
```
const { WebClient } = require("@slack/web-api");
const web = new WebClient("xxxx-...");

web.views.open({
    trigger_id: actionJSONPayload.trigger,  // trigger I get from my button
    view: { // object from example here: https://slack.dev/node-slack-sdk/web-api#opening-modals
      type: 'modal',
      callback_id: 'view_identifier',
      title: {
        type: 'plain_text',
        text: 'Modal title'
      },
      submit: {
        type: 'plain_text',
        text: 'Submit'
      },
      blocks: [
        {
          type: 'input',
          label: {
            type: 'plain_text',
            text: 'Input label'
          },
          element: {
            type: 'plain_text_input',
            action_id: 'value_indentifier'
          }
        }
      ]
    }
  }).catch((err: any) => {
    console.log(`ERROR ${err}`);
  });
```
`ERROR Error: An API error occurred: invalid_arguments`

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.2.1

node version: v10.15.3

OS version(s): Windows 10

#### Steps to reproduce:

1. Try to open a modal from button or command

#### Expected result:

I should display a modal

#### Actual result:

I don't display a modal

**Comment by seratch** [comment]
Your view object seems to be [valid](https://api.slack.com/tools/block-kit-builder?mode=modal&view=%7B%22type%22%3A%22modal%22%2C%22callback_id%22%3A%22view_identifier%22%2C%22title%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Modal%20title%22%7D%2C%22submit%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Submit%22%7D%2C%22blocks%22%3A%5B%7B%22type%22%3A%22input%22%2C%22label%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22Input%20label%22%7D%2C%22element%22%3A%7B%22type%22%3A%22plain_text_input%22%2C%22action_id%22%3A%22value_indentifier%22%7D%7D%5D%7D). Can you make sure if `actionJSONPayload.trigger` surely exists? In the `block_actions` payload, the field for trigger id should be `trigger_id` not `trigger`.

**Comment by erperejildo** [comment]
It worked like this at the end:
```
axios
      .post("https://slack.com/api/views.open", modalInfo, headers)
      .then(response => {
        if (response.data.ok) {
          return response.data.error;
        }
      })
      .catch(error => {
        console.log("Error displaying modal: ", error);
      });
```
