### ISSUE TITLE
@slack/rtm-api on('message') is only sent for channels a bot is part of

### ISSUE THREAD

**Issue by midzelis** [slackapi/node-slack-sdk#901]
### Description

First part: 

When authenticating to `RTMClient` with a bot token, on('message') is only sent for channels a bot is part of. 

When authenticating to `RTMClient` with a user token, on('message') causes a `rtm:stream` scope permissions error. 

How can you listen to all incoming messages that a user is a member of? 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

**Comment by aoberoi** [comment]
Hi @midzelis 👋 

Slack's RTM API isn't intended to be used to listen for messages as a user's logged in client. It's meant to be used to implement behavior of a bot.

That being said, there is a way to do this, but it's strictly speaking not supported. It might continue to work, or it might change in a way that breaks your code. You'll find some information about this usage [in this previous issue](https://github.com/slackapi/node-slack-sdk/issues/663#issuecomment-448021501).

**Comment by seratch** [comment]
As the previous comment by @aoberoi already answered this question, please allow me to close this issue now. If you have anything further to ask/confirm or have related questions, please feel free to write in or reopen this.
