### ISSUE TITLE
viewSubmission callbackId constraint causes error

### ISSUE THREAD

**Issue by mstduff** [slackapi/node-slack-sdk#910]
### Description

If you register a constraint that matches callbackId in a view but the current payload does not contain a view it throws an error.

Example constraints:
```
controller.viewSubmission('myCallback', async (payload) => {});
controller.action({ type: 'static_select', blockId: 'myselect'}, async (payload) => {});
```

If you then get a payload that doesn't contain a view you get an error.

`Cannot read property 'callback_id' of undefined`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [X] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 1.4.0

node version: 10.13.0

OS version(s): OSX

#### Steps to reproduce:

1. Register viewSubmission constraint
2. Perform interactive action in slack not related to a view

#### Expected result:

No constraint matched

#### Actual result:

500 Error

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by enochcheung** [comment]
I am encountering this issue as well. One way to temporarily circumvent this issue is registering viewSubmission handlers last, after registering all other handlers.

**Comment by davidalpert** [comment]
I also recently discovered that if you happen to misunderstand the intention of the workflow and use the same callback_id in your view and your message_handler (thinking perhaps that this identifies the workflow and not each individual call) that the dispatch logic appears to evaluate the constraints in the sequence they are registered, such that the first handler you register has it's constraints evaluated first, the second handler registered has it's constraints evaluated second, and so on, with the first matching handler getting fired.

so register more specific constraints before general ones which may match the same requests.
