### ISSUE TITLE
`expressMiddleware()` or `requestListener()` in Express middleware?

### ISSUE THREAD

**Issue by kanadgupta** [slackapi/node-slack-sdk#911]
### Description

Hello! I'm a newbie with this SDK and I'm looking at the documentation for `@slack/interactive-messages` and noticed that there is a slight discrepancy with the documentation on how to attach this to an existing Express app (and I noticed this also applies in `@slack/events-api` as well).

It looks like these two commits ([here](https://github.com/slackapi/node-slack-sdk/commit/57f3ad7853592e8232c0d6f987ac75a2c5ff3e1e#diff-3e994560d34484fefa9c534dba55bfe5L125) and [here](https://github.com/slackapi/node-slack-sdk/commit/8d92d8cc906f0f3b493ee14ba4e0797ba566c153#diff-c0acfd863ef01503499400d34089d9a6L154)) in March indicate that `requestListener()` should be used over `expressMiddleware()`:
https://github.com/slackapi/node-slack-sdk/blob/1503609d79abf035e9e21bad7360e124e4211594/packages/interactive-messages/README.md#L140

However the top-level README.md for the repo still seems to indicate that `expressMiddleware()` should be used:
https://github.com/slackapi/node-slack-sdk/blob/1503609d79abf035e9e21bad7360e124e4211594/README.md#L203

I'm assuming `requestListener()` should be used and I'm seeing the same results for my purposes in either case so it's not a huge deal, but could you update the documentation to reflect what the recommended approach should be for Express middleware? As I mentioned above, this discrepancy applies to the Express middleware docs for both `@slack/interactive-messages` and `@slack/events-api`.

Thanks so much for working on this SDK - please let me know if you have any questions!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: N/A

node version: N/A

OS version(s): N/A

#### Steps to reproduce:

1. N/A
2.
3.

#### Expected result:

N/A

#### Actual result:

N/A

#### Attachments:

N/A

**Comment by stevengill** [comment]
Hey @kanadgupta!

Thanks for filing the issue! You are correct in assuming `requestListener()` is the recommended approach. I'm going to push a fix for this shortly.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
