### ISSUE TITLE
Invalid form data error with electron JS

### ISSUE THREAD

**Issue by farhatnawaz** [slackapi/node-slack-sdk#920]
### Description

I'm trying to upload a file to slack but constantly getting an error saying `invalid_form_data`. I'm building an electronJS app and using the following code to upload the file:

```
const filee = fs.createReadStream(file);
  (async () => {

    const result = await web.files.upload({
      channels: '#general',
      file: filee
    })

  })()
```

I have even tried to post using axios but ran into the same problem. The code is:
```
const upload_url = 'https://slack.com/api/files.upload'
  let file = null
  fs.readFile(file_path, 'utf-8', function (err, data) {
    file = data
  });
  const post = {
    channels: "#general",
    file: file
  }

  axios.post(upload_url, post, {
    headers: {
      'Content-Type': 'multipart/form-data',
      "Authorization": `Bearer ${token}`
    }
  }).then(function (response) {
    console.log(response['data']['ok'])
  }).then(function (err) {
    console.log(err)
  })
```
What am I doing wrong?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

I expected it to upload the file

#### Actual result:

Throws an error saying `invalid_form_data`

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
I haven't figured out what the problem you're having is yet. Can you confirm if you still see the same problem with the following minimum working example? It works by just running `npm test`. If the problem is Electron-specific, it would be appreciated if you could provide a sample app that reproduces the issue.

## package.json

```json
{
  "name": "file-upload",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "node index.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@slack/web-api": "^5.6.0"
  }
}
```

## index.js

```js
const token = 'xoxb-***';
const channelIds = 'C12345678';
const filepath = 'full path to the file';

// @slack/web-api 5.6.0
const { WebClient } = require('@slack/web-api');
const web = new WebClient(token);

const fs = require('fs');
const filee = fs.createReadStream(filepath);

(async () => {
    const result = await web.files.upload({
        channels: channelIds,
        file: filee,
    })
    console.log(result);
})();
```

**Comment by farhatnawaz** [comment]
@seratch well, it was really weird. I got to use the slack npm package instead and it worked like a charm in just a couple of lines of code, like so:
```
const Slack = require('slack')
const web = new Slack({token: 'xoxp-00000000-AAAAAAAAA-BBBBBBB'})
(async () => {
        const result = await web.files.upload({
            channels: '#general',
            file: fs.createReadStream(file_path)
        })
    })()
```

That's all what was required with the npm package. With `@slack/web-api`, I tried all the code I mentioned and even with the formData module but nothing worked.

**Comment by farhatnawaz** [comment]
Just ran the code you shared. It works fine. :/

**Comment by seratch** [comment]
@farhatnawaz Good to know you managed to run the code successfully! If my code helped you achieve what you wanted to do, could you close this issue? Otherwise, let me know if there is anything else I can help you out here.

**Comment by farhatnawaz** [comment]
@seratch  Uh, your code is more or less the same as what I was trying earlier and it wasn't working inside the electron app. It worked when I ran it separately though and I'm not sure why. I had shifted to to using the slack npm package before you replied, so I didn't get into further debugging the problem. Anyways, I'm closing the issue.
