### ISSUE TITLE
Conflicting definitions for 'node'

### ISSUE THREAD

**Issue by bargald** [slackapi/node-slack-sdk#922]
### Description

when installing the library in a typescript project and building it I am getting an error:

Conflicting definitions for 'node' found at '/home/ubuntu/<PROJECT>/node_modules/@slack/webhook/node_modules/@types/node/ts3.2/index.d.ts' and '/home/ubuntu/<PROJECT>/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ X] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.2

node version: latest

OS version(s): ubunutu + mac OS-X

#### Steps to reproduce:

1. create a node project
2. npm i @slack/webhook
3. run tsc

#### Expected result:

The project should run

#### Actual result:

The build failed.

#### Attachments:

`Conflicting definitions for 'node' found at '/home/ubuntu/<PROJECT>/node_modules/@slack/webhook/node_modules/@types/node/ts3.2/index.d.ts' and '/home/ubuntu/<PROJECT>/node_modules/@types/node/index.d.ts'. Consider installing a specific version of this library to resolve the conflict.`

When looking into package-lock file or yarn.lock, the requirements for node for the webhooks package are:
```
 "requires": {
        "@types/node": ">=8.9.0"
      }
```

while on most libraries it's:
```
 "requires": {
        "@types/node": "*"
      }
```

**Comment by stevengill** [comment]
Hey @bargald,

Appreciate you opening up this issue and the PR!

All of our libraries actually explicitly define a minimum version required of the `@types/node`. Setting it to `*` is not a solution that would work as `@slack/web-api` requires a minimum version of `8.9.0`. Setting it to `*` would allow older versions of `@types/node` to be installed. 

For context, checkout https://github.com/slackapi/node-slack-sdk/issues/514 for the original discussion around why we had to set a minimum version in the first place. 

A quick question about your project so I can attempt to reproduce it:
1) do you have `@types/node` as a dependency in your node project? If yes, what version?

**Comment by bargald** [comment]
Hi @stevengill thank you for your reply,

1. I don't have @types/node explicitly installed.
2. My current node version is v12.9.0.

**Comment by stevengill** [comment]
Hmm, any chance you could provide some steps to reproduce? A quick repo possibly?

**Comment by seratch** [comment]
Let us close this issue due to its inactivity.
