### ISSUE TITLE
views.open with a type of home doesn't open the Home tab

### ISSUE THREAD

**Issue by gleb-rudenko** [slackapi/node-slack-sdk#925]
### Description

According to the [docs](https://api.slack.com/reference/surfaces/views) I have the ability to open(?) the home tab by using views.open() with the type of `home`. I assume that it is possible when a user interacts with an interactive message e.g. click a button.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
When I try to trigger `views.open` with View object as `{type: "home", blocks: []}`
I get the following response error:
```
"code": "slack_webapi_platform_error",
      "data": {
        "ok": false,
        "error": "invalid_arguments",
        "response_metadata": {
          "messages": [
            "[ERROR] must be a valid enum value [json-pointer:/view/type]"
          ],
          "scopes": [
            "identify",
            "bot:basic"
          ]
        }
      }
```

I also noticed, that when we omit the `title` property we get another error that says the `title` is required. But when looking into [slack/types view interface](https://github.com/slackapi/node-slack-sdk/blob/master/packages/types/src/index.ts#L35) the title is optional.
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
@slack/bolt: 1.4.1
@slack/types: 1.3.0
@slack/web-api: 5.6.0

node version:
v10.16.3

OS version(s):
macOS High Sierra v10.13.6

#### Steps to reproduce:

1. create an interactive message with a button that will trigger

```
views.open({
  trigger_id: <id>,
  view: { type: "home", blocks: [] } 
})
```

2. click the button

#### Expected result:
should open/redirect the user to the Home tab

#### Actual result:
throws invalid_arguments error

### Attachements:

**Comment by shaydewael** [comment]
The home tab uses [`views.publish`](https://api.slack.com/methods/views.publish) rather than `views.open` (which is used to open modals).

Also, unfortunately, at the moment there is no way to redirect to the home tab from an action like a button click. You can call `views.publish`, but the user still has to navigate to your app's home tab before the view appears for them.

**Comment by gleb-rudenko** [comment]
@shaydewael , Thank you for the information, I'll close this ticket then. 👍
