### ISSUE TITLE
Not receiving events for member_left_channel

### ISSUE THREAD

**Issue by jeffreyliim** [slackapi/node-slack-sdk#931]
I am creating a service to add and remove bots in slack channels but I'm not receiving any events for member_left_channel.

```
function registerListeners(rtm, slackService) {
    rtm.on('member_joined_channel', async (event) => {
        return await botJoinedChannel(slackService, event)
    });
    rtm.on('member_left_channel', async (event) => {
        console.log(event)
        return await botLeftChannel(slackService, event)
    });
}
```

**Comment by shlasouski** [comment]
+1

**Comment by omarvelous** [comment]
@jeffreyliim I was coming to also notify on this issue (although I am not using this SDK) and I think I understand why. I'm assuming only members of the channel would receive `member_left_channel`? I was able to use `channel_left` to know when a bot was removed from a channel.
