### ISSUE TITLE
TypeScript: createMessageAdapter() Documentation

### ISSUE THREAD

**Issue by egdelgadillo** [slackapi/node-slack-sdk#932]
### Disclaimer
I know this is TypeScript-related, while the documentation is Node.JS-related.

### Description

node-slack-sdk **documentation** references the createMessageAdapter() should be imported and initialized as a const variable: 
`
const { createMessageAdapter } = require('@slack/interactive-messages');
const slackInteractions = createMessageAdapter(process.env.SLACK_SIGNING_SECRET);
`
This does not provide TypeScript the necessary information to be able to use Type Inference on the newly created variable

![image](https://user-images.githubusercontent.com/16352338/70714021-0a4ad480-1cc6-11ea-9714-788a157912fc.png)

Wouldn't it be better if the documentation referenced how to import the createMessageAdapter function using the ES6 `import {foo} from 'bar'` syntax? This way Typescript has all the necessary info to perform the desired **type inference** in the new instance:

![image](https://user-images.githubusercontent.com/16352338/70714211-6d3c6b80-1cc6-11ea-9560-408b6b14831c.png)

The problem with this is that some of us are forced to use this syntax due to it being on the official documentation, although it does not provide the complete usefulness it would if we used the newer syntax.

**This does also happen with other instances, for example the createEventAdapter function, etc**
Maybe there's a reason this is made this way. I would also like to know the reason.

In exchange, **I offer myself to update the documentation or create a new TypeScript-related documentation, whether this could be improved or whether this is done this way for a particular reason, provided that this reason is explained to me**

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [x] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

**package version:** All

**node version:** TypeScript-only

**OS version(s):** All

#### Steps to reproduce:

1.  Open your TypeScript editor and import all necessary packages
2. Write  the import statements and create a new instance of **createMessageAdapter** as written in the documentation:
`
const { createMessageAdapter } = require('@slack/interactive-messages');
export const slackInteractions = new createMessageAdapter(SLACK_CLIENT_SIGNING_SECRET);
`
3. Watch the `SlackMessageAdapter` type not being inferenced on the variable

#### Expected result:

![image](https://user-images.githubusercontent.com/16352338/70714211-6d3c6b80-1cc6-11ea-9560-408b6b14831c.png)

#### Actual result:

![image](https://user-images.githubusercontent.com/16352338/70714021-0a4ad480-1cc6-11ea-9714-788a157912fc.png)

**Comment by stevengill** [comment]
Hey @egdelgadillo,

Thanks for filing the issue! You bring up an interesting point about the Type Interface not working.

The problem with using `import {foo} from 'bar'` syntax is that it doesn't work without a build step in `node.js`. That means we would have to get users to introduce a tool like `babel` before they even get started. For this reason, I don't think we can switch our default documentation to use `import` vs `require`.

I'm not sure sure creating a new set of documentation for Typescript makes sense. It would just mean that we are duplicating content and having to update both when we make changes. We could also run into discoverability issues. 

Let me check with others on my team to get their thoughts. Maybe we can come up with an inline solution? Maybe we add a note near the install instructions for typescript users?

**Comment by stevengill** [comment]
Quick update @egdelgadillo,

We definitely don't want to change `requires` to `imports` for the documentation as a vast majority of folks using this SDK are using vanilla `node.js`. 

We do have a page in our docs dedicated to typescript over at https://slack.dev/node-slack-sdk/typescript. Take a look at it and perhaps you could send a PR against it clarifying the `imports` vs `require` for type interfaces.

**Comment by egdelgadillo** [comment]
Excellent, I found the cited information. Thanks. I will now close the issue.
