### ISSUE TITLE
How to authorize users in order to utilize user token?

### ISSUE THREAD

**Issue by jacklein** [slackapi/node-slack-sdk#939]
My app needs access to the workspace's user token in order to be able to post to user's DMs _without a direct invitation._  I'm assuming when the app first gets installed to a workspace through the bolt OAuth flow, my app gets authorization to use the user token only for the user who installed the app (I still haven't implemented the OAuth flow so I'm not quite sure). However, how do I authorize other users in the workspace in order to be able to use the user token on their behalf?

**My main goal** is to get my app configured so that it can post in the DMs for multiple users in the same workspace. Right now if I use the user token provided in the app dashboard, I can only post in the DMs of the user who downloaded the app, but when I post in the DMs of other users I get the error `An API error occurred: channel_not_found`, which makes me think that the other users in the workspace haven't authorized the app yet. If this is the case, how do I authorize other users in the workspace? **Can I authorize other users when they hit my slash command?**

My main reference to what I want to achieve is the app `quick-maps`. How are they able to access all users' DMs in my workspace even if just one user downloaded the app? (are they authorizing follow-up users once they hit the slash command?)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hello @jacklein 
I've answered your question at https://github.com/slackapi/bolt/issues/366#issuecomment-571020988

Let me close this one.
