### ISSUE TITLE
Max length for plain text input in view throws an error when the value is greater than 3000.

### ISSUE THREAD

**Issue by andrewyalung** [slackapi/node-slack-sdk#940]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I'm attempting to open up a view with a block that contains a `plain_text_input` that has a `max_length` of `16000`. I receive an error stating that the max length can not be longer than 3000, however if I remove the `max_length` parameter I can enter in significantly more than 3000 characters. 

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.5.0

node version: 8.10.0

OS version(s): Mac

#### Steps to reproduce:

1. Attempt to open up a view with a block that contains a `plain_text_input`.
2. Set the `max_length` to a value greater than 3000.
3. See the error above.

#### Expected result:

I would expect the view to open up with an `plain_text_input` that has a max_length.

#### Actual result:

Slack Api throws an error stating the `max_length` can not be greater than 3000.

#### Attachments:

<img width="642" alt="Screen Shot 2020-01-06 at 10 18 56 AM" src="https://user-images.githubusercontent.com/50601399/71835186-2ac04180-306e-11ea-91df-91c22a5a03a1.png">

**Comment by shaydewael** [comment]
Hey @andrewyalung, I was able to reproduce this and I believe you've run into a platform bug which I've reported to the development team. The `plain_text_input` should throw an error if more than 3000 characters are entered by default (without a `max_length` property).

Just out of curiosity - what use case are you building for where 16000 characters in a `plain_text_element` would be helpful?

**Comment by andrewyalung** [comment]
I'm working with an issue tracking software where the description length of an issue can be up to 16000 characters long.

**Comment by shaydewael** [comment]
@andrewyalung Oof, yeah I can't think of a great work-around for that besides only allowing 3000 inside of Slack. I'll pass the use case onto the team. They confirmed it was a known bug, so I'd suspect any input with greater than 3000 characters will start erroring by default in the near future.

**Comment by stevengill** [comment]
@andrewyalung going to close this issue. Feel free to re-open if you have more to add. Thanks again for reporting this!
