### ISSUE TITLE
chat.update() remove previous `icon_emoji` and `username` information

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [slackapi/node-slack-sdk#944]
### Description
When I use `web.chat.update()` like below code, the `icon_emoji` and `username` information used in `web.chat.postMessage()` are disappear.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
```
    "@slack/web-api": "^5.7.0",
```

node version:
```
v10.18.1
```

OS version(s):
```
macOS Mojave 10.14.6
```

#### Expected result:
The icon_emoji and username information used in postMessage () should be maintained.

#### Actual result:
When I use `web.chat.update()` like below code, the `icon_emoji` and `username` information used in `web.chat.postMessage()` are disappear.

```javascript
import { WebClient } from '@slack/web-api'

const web = new WebClient(group.accessToken)
// object contains the same icon_emoji, username information used in `web.chat.postMessage()`
const arg = { ... }
web.chat.update(arg)
```

On the other hand, if I use `axios` with `response_url` like:

```
axios.post(response_url, arg)
```

It works well.

#### Attachments:
![2020-01-19 21 26 28](https://user-images.githubusercontent.com/15520015/72681799-7fea6180-3b0a-11ea-8bb2-27d697a167e9.gif)

👍 button is handled by `axios`,
🚨 button is handled by `web.chat.update()`

**Comment by seratch** [comment]
Thanks for taking the time to report this issue! Unfortunately, chat.update does not support the icon-related parameters and there is no work around for it. As you figured out yourself, please consider using response_url instead.
