### ISSUE TITLE
TypeScript build failure related to EventEmitter types

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#951]
### Description

New builds on Travis are currently failing (since 8 days ago) with the following errors:

```
src/adapter.ts:16:40 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.
16 export class SlackEventAdapter extends EventEmitter {
                                          ~~~~~~~~~~~~
src/http-handler.ts:115:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
115         adapter.emit('error', error, respond);
                    ~~~~
src/http-handler.ts:117:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
117         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:121:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
121         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:202:19 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
202           adapter.emit(body.event.type, ...emitArguments);
                      ~~~~
Found 5 errors.
```

There seems to be an issue with the type definitions for `eventemitter3`.

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment]
It looks like there were a pretty significant refactor of `events.d.ts` in the release of `@types/node@13.5.2`:

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/19826ba267c2203e61d28b87f56ca28eac23a994#diff-7d7d86e4d89d5a8d8e623c8873828549

**Comment by http417** [comment]
will this update be pushed to the npm registry anytime soon?

**Comment by aoberoi** [comment]
@http417 this update is out now! it is part of [`@slack/events-api@2.3.2`](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Fevents-api%402.3.2). sorry for the delay.

**Comment by pacjin79** [comment]
still an issue after I updated to events-api 2.3.2


<img width="1089" alt="screenshot_207" src="https://user-images.githubusercontent.com/6507793/77468735-62749500-6de4-11ea-9bc3-ff68dd2c09f2.png">

**Comment by seratch** [comment]
@pacjin79 The reason for that is that you're using `@types/node` 13.x. `@types/node` 13 has applied a breaking change to the `EventEmitter` type definition. Our package is compatible with the latest LTS release (=12). 

If you're not intentionally relying on Node 13, consider specifying 12 in package.json as we do. https://github.com/slackapi/node-slack-sdk/pull/958/files

**Comment by seratch** [comment]
We may revisit this issue when we start supporting Node 14 in the future. That said, I think we should close this issue for now as we don't have any further actions to take until then.

**Comment by m0ar** [comment]
@seratch Maybe it's time now then :) The repo README clearly says you do, so I was confused by this for quite a while.

https://github.com/slackapi/node-slack-sdk#requirements
