### ISSUE TITLE
Recommended way of calling API on behalf of a user

### ISSUE THREAD

**Issue by guyfedwards** [slackapi/node-slack-sdk#952]
### Description

What is the new recommended way for acting on a users behalf as `on_behalf_of` was removed in [this](https://github.com/slackapi/node-slack-sdk/commit/2c085e0c866eae06d84624c8b233f383ea2b5f8c) commit with little information on replacement. I have tried adding headers for `X-Slack-User` but no luck.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

**Comment by shaydewael** [comment]
Hey @guyfedwards 👋Based on your usage of `on_behalf_of` and `X-Slack-User`, I'm guessing your app is a workspace token app? The [commit you linked](https://github.com/slackapi/node-slack-sdk/commit/2c085e0c866eae06d84624c8b233f383ea2b5f8c) was in response to the workspace token app developer preview ending (talked about at the top of the page here: https://api.slack.com/legacy/workspace-apps/working-with-workspace-tokens).

- Unfortunately, workspace token apps don't have a great migration path. The recommended way forward is to create a new app (which uses [granular bot permissions](https://api.slack.com/authentication/quickstart)). This is the app model going forward with the platform and has additive functionality like [channel management](https://api.slack.com/authentication/quickstart#channels) and [Home tabs](https://api.slack.com/surfaces). For this new app model, user impersonation would be done by utilizing user tokens, where each user would would need to authenticate the app and you could use that token to act on behalf of the user (no need for `on_behalf_of` or the header). There's a bit more information on the new role of user tokens [in the documentation](https://api.slack.com/authentication/basics).

- If that route isn't viable for you for any reason, you can use a package from before that commit (which was deployed with `@slack/client@5.0.0` I believe, so `@slack/client@4.12.0`.

I know I just threw a lot at you, so let me know if I can clarify any of that or answer any other concerns around that.

**Comment by stevengill** [comment]
@guyfedwards hopefully the answer by @shaydewael cleared up your questions. I'm going to close this issue but feel free to comment or reopen if you require more assistance 😄

**Comment by guyfedwards** [comment]
Yea all good cheers.
