### ISSUE TITLE
Integrating events and messages with HapiJS

### ISSUE THREAD

**Issue by danielgreane** [slackapi/node-slack-sdk#954]
### Description

I've been searching for an integration guide for listening to events and interactive messages with an existing HapiJS server, but could only find examples for express or a vanilla node server in the official docs

I managed to get it working using HapiJS server.ext middleware with the following solution:

```
import * as Hapi from "hapi";
import { createMessageAdapter } from "@slack/interactive-messages";
import { createHTTPHandler as HTTPHandlerInteractive } from "@slack/interactive-messages/dist/http-handler";

const interactiveMessages = createMessageAdapter("YOUR_SIGNING_SECRET");
const interactiveHandle = HTTPHandlerInteractive(interactiveMessages);
const server = new Hapi.Server({ port: 3000 })

server.ext("onRequest", async (req, res) => {
    if (req.path === "/slackApp/messages" && req.method === "post") {
        return new Promise(resolve => {
            req.raw.req.on("close", () => resolve(res.close));
            interactiveHandle(req.raw.req, req.raw.res);
        });
    }
    return res.continue;
});
```

The same pattern can be applied with an events adaptor for the events API

I'm hoping this will help someone struggling with the same issue, but it would be great to include a helper function similar to `expressMiddleware` to support those with an existing HapiJS implementation. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
Thanks for sharing this @danielgreane.

**Comment by misscoded** [comment]
Hi @danielgreane! Thanks again for sharing this in an effort to help others. Community contributions are important to us and our tools benefit from continued input/suggestions like that of which you've provided us here. 🙂 

That said, we are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time (and for anyone stumbling upon this issue at a later date), we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
