### ISSUE TITLE
CI build failures with the master branch

### ISSUE THREAD

**Issue by seratch** [slackapi/node-slack-sdk#957]
### Description

It seems affecting all the packages. We need to fix this as soon as possible for smoothly accepting forthcoming PRs.

https://travis-ci.org/slackapi/node-slack-sdk/builds/643608052

<img width="600" src="https://user-images.githubusercontent.com/19658/73983957-f09ed400-497a-11ea-869f-52c2e4f0cfba.png">

```
> @slack/events-api@2.3.1 build:clean /home/travis/build/slackapi/node-slack-sdk/packages/events-api
> shx rm -rf ./dist ./coverage ./.nyc_output
src/adapter.ts:16:40 - error TS2507: Type 'typeof EventEmitter' is not a constructor function type.
16 export class SlackEventAdapter extends EventEmitter {
                                          ~~~~~~~~~~~~
src/http-handler.ts:115:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
115         adapter.emit('error', error, respond);
                    ~~~~
src/http-handler.ts:117:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
117         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:121:17 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
121         adapter.emit('error', error);
                    ~~~~
src/http-handler.ts:202:19 - error TS2339: Property 'emit' does not exist on type 'SlackEventAdapter'.
202           adapter.emit(body.event.type, ...emitArguments);
                      ~~~~
Found 5 errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @slack/events-api@2.3.1 build: `npm run build:clean && tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @slack/events-api@2.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-01-29T22_33_26_415Z-debug.log
lerna info lifecycle @slack/events-api@2.3.1~prepare: Failed to exec prepare script
> @slack/interactive-messages@1.4.1 prepare /home/travis/build/slackapi/node-slack-sdk/packages/interactive-messages
> npm run build
The command "lerna bootstrap --no-ci --hoist" failed and exited with 2 during .
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by stevengill** [comment]
@seratch I believe this is a duplicate of https://github.com/slackapi/node-slack-sdk/issues/951

**Comment by seratch** [comment]
Oops, I overlooked it. Thanks! Anyway, we should fix this now.
