### ISSUE TITLE
Slack bot Messaging

### ISSUE THREAD

**Issue by vcardamone** [slackapi/node-slack-sdk#962]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x ] question
- [x ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ x] I don't know

#### Reproducible in:

package version:

node version:

OS version(s):

#### Steps to reproduce:

1. I created an app/bot to send a message like the tutorial says here: https://slack.dev/python-slackclient/basic_usage.html#sending-a-message
2. When I run the code in jupyter labs or the python interpreter I get an error message

3. I have registered all the tokens and the app but I don't fully understand environment variables. How can I make this code work? Please let me know if I need to clarify.

#### Expected result:

What you expected to happen
I expected the code to run without an error message since I got all tokens and went through all steps to deploy the app.

#### Actual result:

What actually happened
I got an error message
KeyError                                  Traceback (most recent call last)
<ipython-input-42-2e6aea63ebe8> in <module>
      5 os.chdir('C:/Users/vince.cardamone/AppData/Local/Programs/Python/Python37/Scripts/starterbot')
      6 print(os.environ.get('SLACK_API_TOKEN'))
----> 7 slack_token = os.environ["SLACK_API_TOKEN"]
      8 client = slack.WebClient(token=slack_token)
      9 

C:\ProgramData\Anaconda3\lib\os.py in __getitem__(self, key)
    676         except KeyError:
    677             # raise KeyError with the original key value
--> 678             raise KeyError(key) from None
    679         return self.decodevalue(value)
    680 

KeyError: 'SLACK_API_TOKEN'
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
👋 Your question looks about slack-pythonclient, not node-slack-sdk. Putting that aside, I’m afraid you haven’t set the environment variable SLACK_API_TOKEN yet. Run set command with your bot token (xoxb-***) before run your code.

**Comment by vcardamone** [comment]
Sorry for putting this in the wrong spot. When you say run set command to set the environment variable with the bot token do I do this in python or command shell?

**Comment by seratch** [comment]
I mean doing that on your command prompt, not in your python code.

**Comment by vcardamone** [comment]
Thank you. I will give that a try now.

**Comment by vcardamone** [comment]
It worked! Thanks for your help and sorry I am new to this.

**Comment by seratch** [comment]
@vcardamone Awesome! Enjoy working with Slack APIs 👍
