### ISSUE TITLE
Express middleware circular structure to json uncaught exception

### ISSUE THREAD

**Issue by battlecow** [slackapi/node-slack-sdk#965]
### Description

Stacktrace thrown from attempting to stringify circular JSON when using `interactive-messages` packaage as Express middleware.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

`(node:1) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'socket' -> object with constructor 'TLSSocket'
    --- property '_httpMessage' closes the circle
    at JSON.stringify (<anonymous>)
    at /home/node/node_modules/@slack/interactive-messages/dist/http-handler.js:39:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)`

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 1.4.1

node versions: 12.15.x , 12.16.x

OS version(s): Official Docker Node image (Debian GNU/Linux 9 (stretch))

#### Steps to reproduce:

1. Create a bot user integration with interactive components enabled and path set to `/slack/actions`
2. Use this Gist to reproduce https://gist.github.com/battlecow/67238cc9ae922792c93d475a28fe66e2

#### Expected result:

No circular reference throwing an exception.

#### Actual result:

Exception thrown as stated above.

**Comment by misscoded** [comment]
We are going to close this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
