### ISSUE TITLE
Missing type `RadioButton` on SectionBlock.accessory type

### ISSUE THREAD

**Issue by Elrendio** [slackapi/node-slack-sdk#968]
### Description

In the [official documentation](https://api.slack.com/reference/block-kit/block-elements) for Slack API, one of the possible accessory for section block is a [RadioButton](https://api.slack.com/reference/block-kit/block-elements#radio). However the package `@types/slack` types the section block as below:
```ts
export interface Block {
    type: string;
    block_id?: string;
}

export interface SectionBlock extends Block {
    type: 'section';
    text?: PlainTextElement | MrkdwnElement;
    fields?: (PlainTextElement | MrkdwnElement)[];
    accessory?: Button | Overflow | Datepicker | Select | MultiSelect | Action | ImageElement;
}
```

There seems to be missing the follow types:
 - Checkboxes
 - Plain-text input
 - Radio button group

Sorry if this is not the right place to submit the bug.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

Select all that apply:

- [x] `@types/slack`
- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: "@types" = "1.3.0", "@slack/web-api": "^5.0.1",

node version: v13.8.0

OS version(s): Linux scylla 5.5.2-arch2-2 #1 SMP PREEMPT Wed, 05 Feb 2020 22:01:13 +0000 x86_64 GNU/Linux

#### Steps to reproduce:

1. Start as typescript project
2. Try to create a modal with a radio_button:
```ts
await new WebClient(process.env.SlackToken).views.open({
	trigger_id: "my-trigger-id",
	view: {
		type: 'modal',
		callback_id: "my-callback-id",
		title: {
			type: 'plain_text',
			text: "My Modal",
		},
		submit: {
			type: 'plain_text',
			text: 'Go !',
		},
		blocks: [{
			type: 'section' as 'section',
			text: {
				type: 'mrkdwn' as 'mrkdwn',
				text: 'My Radio button title',
			},
			block_id: 'my-block-id',
			accessory: {
				type: 'radio_buttons' as 'radio_buttons',
				options: [{
					text: {
						type: 'plain_text',
						text: 'Radio button 1'
					},
					// Value has a max of 75 characters
					value: "my-value",
					description: {
						type: 'plain_text',
						text: "This is the first radio button",
					}
				}, {
						text: {
							type: 'plain_text',
							text: 'Radio button 2'
						},
						// Value has a max of 75 characters
						value: "my-value-2",
						description: {
							type: 'plain_text',
							text: "This is the second radio button",
						}
					}],
				initial_option: {
					text: {
						type: 'plain_text',
						text: 'Radio button 1'
					},
					// Value has a max of 75 characters
					value: "my-value",
					description: {
						type: 'plain_text',
						text: "This is the first radio button",
					}
				},
			},
		}],
	}
})
```

#### Expected result:

The code should compile.

#### Actual result:

The code doesn't compile.

#### Attachments:

Thanks a lot !

**Comment by stevengill** [comment]
This was released in [`@slack/types@1.6.0`](https://github.com/slackapi/node-slack-sdk/releases/tag/%40slack%2Ftypes%401.6.0)! Thanks for reporting it!
