### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by leifwells** [slackapi/node-slack-sdk#969]
I realize this isn't the purpose of issues in GitHub, but I wanted to thank you for providing the Greet and React example and the instructions that appear in the README.

After days of frustration, your example taught me everything I hadn't figured out. Now I am on my way to creating the application I have designed.

Quality code comes with quality documentation. Thanks to everyone responsible for taking the extra steps to make it easier for the rest of us.

**Comment by stevengill** [comment]
Appreciate the kind words @leifwells! So glad you found the example useful!
