### ISSUE TITLE
What is the usage of `response_urls` when action type is `view_submission`  ?

### ISSUE THREAD

**Issue by zhang699** [slackapi/node-slack-sdk#970]
### Description

Since I need close my modal when submit in asynchronous way, I have inspect the payload of `view_submission` if contains `response_url` property. Unfortunately it doesn't, but I have found the empty `response_urls` array,  curious about what usage it is ?  my `view_submission` payload shape as following

```
{
  "type": "view_submission",
  "team": { ...ignore },
  "user": {
    ...ignore
  },
  "api_app_id": "AR8RMK537",
  "token": "lZhvV74fyJf5qlNqv2TuzvZE",
  "trigger_id": "966730317457.852304361845.1f200a111962b825664eb6e2d21aeee4",
  "view": {
    "id": "VUQR15H4M",
    "team_id": "TR28YAMQV",
    "type": "modal",
    "blocks": [
      ...ignore
    ],
    "private_metadata": "",
    "callback_id": "1582524048.002200",
    "state": {
      "values": {
        ...ignore
      }
    },
    "hash": "1583138631.9b412ab1",
    "title": {
      "type": "plain_text",
      "text": "\u586b\u5beb\u8655\u7406\u65b9\u5f0f\u8207\u539f\u56e0",
      "emoji": true
    },
    "clear_on_close": false,
    "notify_on_close": false,
    "close": { "type": "plain_text", "text": "Cancel", "emoji": true },
    "submit": { "type": "plain_text", "text": "Submit", "emoji": true },
    "previous_view_id": null,
    "root_view_id": "VUQR15H4M",
    "app_id": "AR8RMK537",
    "external_id": "",
    "app_installed_team_id": "TR28YAMQV",
    "bot_id": "BR8RLBN00"
  },
  "response_urls": []
}


```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by gajus** [comment]
Same question here.

**Comment by seratch** [comment]
I'm sorry for our belated reply here.

The attribute has been added recently to support the use case you mentioned. Your app can ask your users where to post a message by having `conversations_select` or `channels_select` input blocks with an additional option `response_url_enabled: true`.  Refer to the parts mentioning `response_url_enabled` in https://api.slack.com/surfaces/modals/using for details.

Allow me to close this question issue now. Please feel free to reopen if you have further related questions.
