### ISSUE TITLE
Slack Interactions order seems cause a 500 Internal server error

### ISSUE THREAD

**Issue by DanielPe05** [slackapi/node-slack-sdk#971]
### Description

I'm working on a simple slack app that will fetch a list of options and upon selection I want it to fire an action handler. The app also has another view which is a modal and there is a `viewSumbission` handler for that as well. What is happening is that if I place the `.action({actionId})` handler before the `.viewSubmission(callbackId)` handler it all seems to work fine but if I place it after it then the app returns an internal server error (500) response. I tried looking in the docs to see if there was some sort of action matching happening that would depend on the order but I could not find anything. See example below:

**This works as expected:**
```
slackInteractions.action(
  { actionId: 'uniqueActionId' },
  (payload, respond) => {
    // Logs the contents of the action to the console
    console.log(payload.actions)
    respond({ text: 'Thanks for your submission.', response_type: 'ephemeral' })
  }
)

slackInteractions.viewSubmission('uniqueCallbackId`,
  async ({ user, view: { state } }) => {
    await someAsyncOperation(user)

    return {
      response_action: 'update',
      view: {
        type: 'modal',
        title: {
          type: 'plain_text',
          text: 'User Created!'
        },
        blocks: [
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: 'success, you have created a user'
            }
          }
        ]
      }
    }
  }
)
```

**Simply changing the order makes it fail:**
```
slackInteractions.viewSubmission('uniqueCallbackId`,
  async ({ user, view: { state } }) => {
    await someAsyncOperation(user)

    return {
      response_action: 'update',
      view: {
        type: 'modal',
        title: {
          type: 'plain_text',
          text: 'User Created!'
        },
        blocks: [
          {
            type: 'section',
            text: {
              type: 'mrkdwn',
              text: 'success, you have created a user'
            }
          }
        ]
      }
    }
  }
)

slackInteractions.action(
  { actionId: 'uniqueActionId' },
  (payload, respond) => {
    // Logs the contents of the action to the console
    console.log(payload.actions)
    respond({ text: 'Thanks for your submission.', response_type: 'ephemeral' })
  }
)

```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version:
^1.4.1

node version:
10.16.3

OS version(s):
MacOs Catalina

#### Steps to reproduce:

1. 
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by misscoded** [comment]
We are closing this issue as `@slack/interactive-messages` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
