### ISSUE TITLE
Option should allow for MarkdwnElement type for text field

### ISSUE THREAD

**Issue by tteltrab** [slackapi/node-slack-sdk#973]
### Description

Option should have MrkdwnElement as an option for text field in types, to match docs/behavior to enable mrkdwn for checkboxes and radio buttons.

https://api.slack.com/reference/block-kit/composition-objects#option 

> Overflow, select, and multi-select menus can only use plain_text objects, while radio buttons and checkboxes can use mrkdwn text objects.

https://github.com/slackapi/node-slack-sdk/blob/master/packages/types/src/index.ts#L69

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

`@slack/types`

#### Reproducible in:

package version: 1.4.0

**Comment by stevengill** [comment]
Thanks for sending the fix!
