### ISSUE TITLE
Global Shortcuts

### ISSUE THREAD

**Issue by cjdenio** [slackapi/node-slack-sdk#984]
### Description
Hello,

It looks like the Interactive Messages SDK doesn't support global shortcuts yet. I've tried setting a constraint like so: `{type: 'shortcut'}`, but alas, `no callback was matched`. This is sort of a question, too; does the SDK support global shortcuts?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

Here's a funny GIF.

![image](https://i.giphy.com/media/wpoLqr5FT1sY0/giphy.webp)

**Comment by stevengill** [comment]
Thanks for reporting this! You are correct. Looking at fixing it now

**Comment by stevengill** [comment]
@cjdenio Sent a PR adding support for this. https://github.com/slackapi/node-slack-sdk/pull/985

I'd also recommend checking out bolt for javascript which already has support for shortcuts https://slack.dev/bolt/concepts#shortcuts

**Comment by gbartlett** [comment]
Hi @stevengill,

It looks like the Interactive Messages SDK still doesn't support global shortcuts. I just ran an `npm update @slack/interactive-messages` and it's still giving me this error: `.shortcut is not a function`. It looks like the last publish date for the NPM package was a month ago.

**Comment by stevengill** [comment]
Hey @gbartlett,

You are correct that we haven't done an npm release for it yet. Will aim to get it out early next week! 

If you are need access now, you could temporarily clone this repo down and run `npm install path/to/cloned/repo/packages/interactive-messages` from your project.

**Comment by gbartlett** [comment]
@stevengill awesome thank you so much! 😄

**Comment by mahir-shaikh** [comment]
Still receiving the same error .shortcut() is not a function.
