### ISSUE TITLE
Missing code sample in interactive-messages docs

### ISSUE THREAD

**Issue by EddieCameron** [slackapi/node-slack-sdk#986]
### Description

In the docs for the interactive-messages sdk, the last section "Synchronous response timeout" has the same code sample as the previous section "Late response fallback".
It was easy to figure out how to actually change the timeout, but hopefully a simple fix

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Packages:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [x] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

**Comment by seratch** [comment]
@EddieCameron Thanks for taking the time to report this! You're right. I'll come up a quick fix soon.
