### ISSUE TITLE
Add team property to message event with files

### ISSUE THREAD

**Issue by http417** [slackapi/node-slack-sdk#988]
### Description

Normally message events contain the team id.  However if a message has at least one file, then the team property is not provided directly in the event.  

As a workaround, I can extract the team ID from one of the file url's, but I'm not sure how reliable this solution will be -- if the url structure of a file ever changes.

`https://files.slack.com/files-pri/TXXXXXX-FXXXXX/some_attachment.txt`

### What type of issue is this? (place an `x` in one of the `[ ]`)
-  [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 2.3.2 (latest)

node version: 13.8.0

OS version(s): OSX Catalina

#### Steps to reproduce:

1. send message with at least one file attachment
2.
3.

#### Expected result:

```
{
  type: 'message',
  text: 'yo',
  files: [
    {
// ...file info block
    }
  ],
  upload: true,
  blocks: [ { type: 'rich_text', block_id: 'AhtJF', elements: [Array] } ],
  user: 'UU1J60FSB',
  display_as_bot: false,
  ts: 'xxxx.xxxx',
  team: 'Txxxxxxxx' // <============== this is missing!
  client_msg_id: 'xxxxxxxx,
  channel: 'Cxxxxxxx',
  subtype: 'file_share',
  event_ts: 'xxxxx.xxxxxx',
  channel_type: 'channel'
}
```

#### Actual result:

```
{
  type: 'message',
  text: 'yo',
  files: [
    {
   // ...file info block
    }
  ],
  upload: true,
  blocks: [ { type: 'rich_text', block_id: 'AhtJF', elements: [Array] } ],
  user: 'UU1J60FSB',
  display_as_bot: false,
  ts: 'xxxx.xxxx',

  client_msg_id: 'xxxxxxxx,
  channel: 'Cxxxxxxx',
  subtype: 'file_share',
  event_ts: 'xxxxx.xxxxxx',
  channel_type: 'channel'
}
```

What actually happened

any received message event that contains a 'files' array key does not contain a 'team' key/value pair

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by seratch** [comment]
@http417 Thank you for taking the time to report this. We've got this feedback a few weeks ago and I escalated it to the server-side team. https://github.com/slackapi/bolt/issues/435#issuecomment-604794119

Sorry for the inconvenience but please go with the workaround you mentioned for a while.

**Comment by garrett-rethink-contract** [comment]
Still a thing! Any link to the server-side ticket for this?

**Comment by macegr** [comment]
This is still happening, any link to the server-side ticket for this? Would like to get a notification when it's working

**Comment by misscoded** [comment]
We are closing this issue as `@slack/events-api` officially reached its EOL on May 31st, 2021. As of that date, development has fully stopped for this package and all remaining open issues and pull requests are being closed. 

At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in this package (and more!). To help with that process, we've also provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps.
