### ISSUE TITLE
Cannot read property `split` of undefined

### ISSUE THREAD

**Issue by IsAmrish** [slackapi/node-slack-sdk#991]
### Description

Describe your issue here.
I am getting `Cannot read property `split` of undefined` when I am trying to use a simple express app. I tried that simple express app from here - [https://slack.dev/node-slack-sdk/events-api](https://slack.dev/node-slack-sdk/events-api)

More details about the error

```
/Users/isamrish/Desktop/workspace/slack-api/node_modules/@slack/events-api/dist/http-handler.js:132
            process.nextTick(function () { throw userError; });
                                           ^

TypeError: Cannot read property 'split' of undefined
    at verifyRequestSignature (/Users/isamrish/Desktop/workspace/slack-api/node_modules/@slack/events-api/dist/http-handler.js:41:31)
    at /Users/isamrish/Desktop/workspace/slack-api/node_modules/@slack/events-api/dist/http-handler.js:168:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at handleError (/Users/isamrish/Desktop/workspace/slack-api/node_modules/@slack/events-api/dist/http-handler.js:127:25)
    at /Users/isamrish/Desktop/workspace/slack-api/node_modules/@slack/events-api/dist/http-handler.js:200:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 2.3.2

node version: v10.15.3

OS version(s): macOS catalina - version 10.15.1

#### Steps to reproduce:

1. Create a simple express app using [https://slack.dev/node-slack-sdk/events-api](https://slack.dev/node-slack-sdk/events-api)
2. Once the app is running, open http://localhost:3000/my/path on your browser
3. You will get above error on your terminal

**Comment by IsAmrish** [comment]
Actually figured out that I need to use request URL for using API. I was looking for one thing and mistakenly did wrong thing. :man_facepalming:

closing it!! :smile:

**Comment by seratch** [comment]
@IsAmrish I'm also glad to know you've figured out the cause! 👍
