### ISSUE TITLE
Why is payload undefined?

### ISSUE THREAD

**Issue by ChezCoder** [slackapi/node-slack-sdk#996]
When I tried to get the event, it gave me an error saying that `payload` was undefined... here is my code:
```javascript
const express = require('express');
const fs = require("fs");
const app = express();
const path = require("path");

app.post("/", (req, res) => {
    let payload = res.body;
    res.send("pong!");
    console.log(payload);
});

app.get("/",(req,res) => {
    res.send("")
});

app.listen(3000, () => {
  console.log('server started');
});
```

When I run it, payload is `undefined`. Please help!!!

**Comment by seratch** [comment]
@ChezCoder 👋 If you're building a Slack app using Express, checking this sample project is helpful. https://glitch.com/edit/#!/slash-blockkit?path=index.js:1:0

**Comment by seratch** [comment]
@ChezCoder Was my previous reply helpful for you? If so, could you close this issue now?

**Comment by ChezCoder** [comment]
Yes, it was helpful, thank you :D
